Update patch set 2
Patch Set 2:

Gitlab Orange 2: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98436-2/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 210
 * Nb Failed Pods: 48
 * List of Failed Pods: [
   - onap-aai-aai-data-router-7cd8669b68-lt9w4
   - onap-aai-aai-graphgraph-5875c7ffdb-669kp
   - onap-aai-aai-resources-59b7c66784-mg7sm
   - onap-cds-cds-blueprints-processor-76cf8d7b77-hfww6
   - onap-cds-cds-command-executor-58b446997d-9qprw
   - onap-cds-cds-sdc-listener-75c5fd5ffb-btt2x
   - onap-clamp-clamp-dash-logstash-56bb7678c-lzrgr
   - onap-clamp-clamp-dash-logstash-56bb7678c-qsjbh
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-2wlx5
   - onap-log-log-kibana-6cb786cc47-9qf9z
   - onap-log-log-kibana-6cb786cc47-qktvp
   - onap-log-log-kibana-6cb786cc47-skmgh
   - onap-multicloud-multicloud-k8s-fd756f9c7-4l4kq
   - onap-multicloud-multicloud-k8s-fd756f9c7-mxcgm
   - onap-oof-oof-86c448d5c7-2gcww
   - onap-oof-oof-86c448d5c7-wbfjw
   - onap-oof-oof-cmso-ticketmgt-5f8b89b4c4-wp277
   - onap-oof-oof-cmso-topology-7b458f47bd-46hrp
   - onap-oof-oof-cmso-topology-7b458f47bd-phzlg
   - onap-oof-oof-has-api-5bb7b84888-74gft
   - onap-oof-oof-has-api-5bb7b84888-7jh95
   - onap-oof-oof-has-data-d575ff6df-r9gw5
   - onap-oof-oof-has-reservation-547c8f4d7f-xp4zq
   - onap-oof-oof-has-solver-746bff67d8-gdjrk
   - onap-pomba-pomba-contextaggregator-77bd58448d-p7252
   - onap-pomba-pomba-elasticsearch-59d5774bbb-hh6xz
   - onap-pomba-pomba-sdncctxbuilder-69b65c7c94-m86d5
   - onap-portal-portal-zookeeper-bd88545cf-8jzbw
   - onap-portal-portal-zookeeper-bd88545cf-n7p7q
   - onap-sdc-sdc-es-846948b858-52nk6
   - onap-sdc-sdc-es-846948b858-bs8d8
   - onap-sdc-sdc-kb-574c577d77-zr2sv
   - onap-sdc-sdc-kb-574c577d77-zt5zj
   - onap-sdc-sdc-wfd-be-5c8747d55d-kwtf4
   - onap-sdc-sdc-wfd-fe-fbccb85d-tjt8j
   - onap-sdnc-network-name-gen-85ff6b896c-t8wvf
   - onap-sdnc-network-name-gen-85ff6b896c-wdj7d
   - onap-sdnc-network-name-gen-85ff6b896c-zvrc9
   - onap-sdnc-sdnc-dmaap-listener-7df88fddcb-wwzxb
   - onap-sdnc-sdnc-ueb-listener-5f57ff6d5f-ggscg
   - onap-so-so-bpmn-infra-846c54746c-45r8f
   - onap-so-so-bpmn-infra-846c54746c-ktd4j
   - onap-so-so-monitoring-7d8cd59bf6-js9mr
   - onap-uui-uui-server-676957854d-zdm6d
   - onap-vfc-vfc-ems-driver-86bdb477f4-b4lt5
   - onap-vfc-vfc-ems-driver-86bdb477f4-fb5wq
   - onap-vfc-vfc-multivim-proxy-7fd79cc558-h6n4z
   - onap-vfc-vfc-multivim-proxy-7fd79cc558-t8s8t]
*********** Helm Results ***********
 * Nb Helm Charts: 35
 * Nb Failed Helm Charts: 0
 * List of Failed Helm Charts: []
******** Healthcheck Results *******
2019-12-03 16:24:21,317 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe792a01810>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7926f8050>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe7926f8710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-contextaggregator.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe79291eb10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe792c75050>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 50 passed, 11 failed
61 tests total, 50 passed, 11 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-12-03 16:21:28,472 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
500 != 200

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 2
Label: Code-Review=0