Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 204
 * Nb Failed Pods: 40
 * List of Failed Pods: [
   - onap-aai-aai-champ-7f97f98976-ld5np
   - onap-aai-aai-d6df6d67d-xx275
   - onap-aai-aai-graphadmin-c79fb7fcf-wk6mh
   - onap-aai-aai-graphadmin-create-db-schema-kwl7x
   - onap-aai-aai-resources-557c6f9d78-bfnxn
   - onap-aai-aai-sparky-be-5ff8689c54-5j9c9
   - onap-aai-aai-spike-77ccc5bf78-xzkz5
   - onap-aai-aai-traversal-7fb5558d98-c4pqt
   - onap-aai-aai-traversal-update-query-data-7j59h
   - onap-contrib-netbox-app-695fd89fd-t7tqn
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-5qvql
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-vx24q
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-9p4kr
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-fq4sj
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-j5qw6
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-r5gh8
   - onap-dmaap-dmaap-bc-post-install-lh5rr
   - onap-policy-policy-api-6db49d977f-6wnt6
   - onap-policy-policy-pap-85845569c5-g8595
   - onap-policy-policy-xacml-pdp-7df865f5cc-qxv7g
   - onap-sdc-sdc-be-5d69fd8d6-9f559
   - onap-sdc-sdc-be-config-backend-6rk86
   - onap-sdc-sdc-dcae-be-6466bf5fc-bzl8k
   - onap-sdc-sdc-dcae-dt-7c76c788fb-p9qnl
   - onap-sdc-sdc-dcae-fe-5579cb67bd-p8kx4
   - onap-sdc-sdc-dcae-tosca-lab-68dd59dbd4-jjc58
   - onap-sdc-sdc-fe-6968588c6b-6kns2
   - onap-sdc-sdc-onboarding-be-cassandra-init-656xf
   - onap-sdc-sdc-onboarding-be-f949f77cc-cpctl
   - onap-sdc-sdc-wfd-be-6ddb89dcc6-vst95
   - onap-sdc-sdc-wfd-be-workflow-init-rrdq8
   - onap-sdc-sdc-wfd-fe-8dc658b6d-6smj4
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-sm7lc
   - onap-so-so-bpmn-infra-7b4cf7dbf4-g6bq2
   - onap-so-so-catalog-db-adapter-684f7f7f57-r8sk8
   - onap-so-so-f57fb6c78-7q2zt
   - onap-so-so-openstack-adapter-6c75fcdd89-r7rt8
   - onap-so-so-request-db-adapter-6797d64c57-nn27x
   - onap-so-so-sdc-controller-849949db55-sr5vd
   - onap-so-so-vfc-adapter-6df5476d68-6h6k6]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-05 07:04:54,532 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff54179b990>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff541603710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5415ff890>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff54151d850>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 48 passed, 10 failed
58 tests total, 48 passed, 10 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2