Update patch set 6
Patch Set 6: Code-Review-1

gating (see https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/210055233/artifacts/download for details)

Chart onap-dmaap
STATUS: FAILED
Chart problem
info:
  Description: 'Release "onap-dmaap" failed post-install: timed out waiting for the
    condition'
  first_deployed:
    nanos: 274200730
    seconds: 1557427892
  last_deployed:
    nanos: 274200730
    seconds: 1557427892
  status:
    code: 4
name: onap-dmaap
namespace: onap

Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba0d28790>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 6
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1