Update patch set 8
Patch Set 8: Code-Review-1

OOF healthchecks are failing

Basic OOF-Homing Health Check                                         | FAIL |
SSLError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by SSLError(SSLError(1, u'[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)'),))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
----------------------------------------------------------------------

--------
Basic OOF-CMSO Health Check                                           | FAIL |
SSLError: HTTPSConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=true (Caused by SSLError(S

Patch-set: 8
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1