Update patch set 1
Patch Set 1:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 257
 * Nb Failed Pods: 21
 * List of Failed Pods: [
   - dep-dcae-dashboard-6b568595b7-76qzt
   - dep-dcae-ves-collector-d879f5466-6vp4m
   - dep-holmes-rule-mgmt-6b98ff6875-cgx94
   - onap-aaf-aaf-cs-8df4b9646-xcqf5
   - onap-aaf-aaf-sms-5d7667b5b7-xnbbs
   - onap-aai-aai-traversal-7d4dcb764d-pwm9f
   - onap-contrib-netbox-nginx-75fbcf6fb5-24k66
   - onap-dcaegen2-dcae-redis-4
   - onap-dmaap-message-router-kafka-1
   - onap-dmaap-message-router-mirrormaker-78cb664858-tdq27
   - onap-esr-esr-gui-6cfc9689dd-gkrhm
   - onap-esr-esr-server-f6cdd9b57-5r2br
   - onap-multicloud-multicloud-pike-79fbc64846-v7vvh
   - onap-policy-nexus-7bd779b5c6-kjg5f
   - onap-sdc-sdc-fe-86df7b5f7b-4m7vc
   - onap-so-so-vnfm-adapter-6486b77447-pb9lz
   - onap-uui-uui-55ccd4b9d5-rrx9t
   - onap-vfc-vfc-catalog-6bc765ddb9-w8klc
   - onap-vfc-vfc-db-5d69c78c74-xfst7
   - onap-vfc-vfc-ems-driver-ddf998d5f-5hpnf
   - onap-vfc-vfc-juju-vnfm-driver-7d696f588-fjpfs]
 * Deployment Duration Estimation (s): 60
*********** Helm Results ***********
 * Nb Helm Charts: 30
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-dmaap]
******** Healthcheck Results *******
2019-04-25 18:47:16,325 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
No keyword with name 'dev-aaf' found.
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
503 != 200
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic MUSIC Health Check                                              | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52d149e790>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic MUSIC Cassa Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/service/musicHealthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52d1469550>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
61 critical tests, 53 passed, 8 failed
61 tests total, 53 passed, 8 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1
Label: Verified=0