Update patch set 4
Patch Set 4: Code-Review-1

Hi,
since the update to version 1.12.2 (https://gerrit.onap.org/r/c/oom/+/133432) we see in the logs of sdc-be decoding errors:
```
2023-03-24T16:32:59.028Z	[qtp1472465-15]	ERROR	o.onap.logging.filter.base.MDCSetup	RequestID=08baac7d-881b-4266-b316-640c2d503221	ServerIPAddress=10.244.2.158	ServiceName=v1/setup/ui	EntryTimestamp=2023-03-24T16:32:47.744Z	InvocationID=4c3d26db-ea32-43ba-9d14-2f554074ee9c	PartnerName=Apache-HttpClient/4.5.13 (Java/11.0.11)	auditOn=true	ServerFQDN=onap-sdc-be-6756d6cfb5-qf8cm	could not decode basic auth value YWFpOktwOGJKNFNYc3pNMFdYbGhhazNlSGxjc2UyZ0F3ODR2YW9HR21KdlV5MlU=,Basic dGVzdE5hbWU6dGVzdFBhc3M=
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 64
```
The same errors are visible in the current gating logs:
https://logs.onap.org/onap-integration/gating//133806-4/k8s-teardown/k8s-teardown/kubernetes-status/pod-onap-sdc-be-6756d6cfb5-qf8cm-sdc-be.log
As we are not sure, if the functionality is impacted, I give this patch a -1.
Best regards
Andreas

Patch-set: 4
Reviewer: Gerrit User 2679 <2679@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1