Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Gitlab Orange 3: 
> Full results can be seen here: https://logs.onap.org/onap-integration/gating//119053-1/index.html
> ______________ Results ______________________
> 
> ************************************************************
> ************************************************************
> ************ Infrastructure-healthcheck Results ************
> ************************************************************
> ************************************************************
> --------> onap-k8s
>  * Nb Jobs: 28
>  * Nb Failed Jobs: 0
>  * Nb Deployments: 151
>  * Nb Failed Deployments: 0
>  * Nb StatefulSets: 27
>  * Nb Failed StatefulSets: 0
>  * Nb Persistent Volume Claims: 75
>  * Nb Failed Persistent Volume Claims: 0
> --------> onap-helm
>  * Nb Helms: 34
>  * Nb Failed Helms: 0
> 
> ************************************************************
> ************************************************************
> ********************* Healthcheck Results ******************
> ************************************************************
> ************************************************************
> --------> robot full healthcheck tests
> 2021-03-10 23:17:04,878 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Basic A&AI Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced A&AI Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic AAF Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic AAF SMS Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic APPC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic CLI Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic CLAMP Health Check                                              | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Data Router Health Check                                  | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Message Router Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> ------------------------------------------------------------------------------
> Basic External API NBI Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Microservice Bus Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-pike API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-starlingx API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-vio API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-k8s API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-Homing Health Check                                         | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-OSDF Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-CMSO Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic Policy Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Enhanced Policy New Healthcheck                                       | PASS |
> ------------------------------------------------------------------------------
> Basic Portal Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDC Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDC Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDNC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDNC Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic SO Health Check                                                 | PASS |
> ------------------------------------------------------------------------------
> Basic UseCaseUI API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC gvnfmdriver API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic VFC nslcm API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnflcm API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfmgr API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfres API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC ztevnfmdriver API Health Check                              | PASS |
> ------------------------------------------------------------------------------
> Basic VID Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic VNFSDK Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-fcaps API Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic Modeling genericparser API Health Check                         | PASS |
> ------------------------------------------------------------------------------
> Enhanced CDS Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | PASS |
> 43 critical tests, 43 passed, 0 failed
> 43 tests total, 43 passed, 0 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/full/output.xml
> 
> ************************************************************
> ************************************************************
> ********************* Basic tests Results ******************
> ************************************************************
> ************************************************************
> --------> healthdist (vFW onboarding and distribution)
> Health-Check :: Test that ONAP components are available via basic ... | PASS |
> --------> postinstall tests (dmaap and A&AI)
> Post-Install-Tests :: Testing Installation                            | PASS |
> --------> CMPv2 tests
> Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
> Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
> Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
> Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
> Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
> Send registration request to VES without CMPv2 certificate :: This... | PASS |
> Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
> --------> HV-VES tests
> Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
> --------> VES collector tests
> Ves :: Suite for checking handling events by VES Collector            | PASS |
> --------> Basic Onboard tests (SDC)
> basic_onboard: PASS (03:28)
> --------> CDS tests
> basic_cds: PASS (00:20)
> 
> ************************************************************
> ************************************************************
> ******************** End to End usecases *******************
> ************************************************************
> ************************************************************
> --------> pnf-registrate tests
> PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
> Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
> --------> 5gbulkpm tests
> Setting Global Variables :: This test case checks suite if it is w... | PASS |
> 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> --------> basic_vm tests NOT executed
> --------> basic_network tests
> basic_network: PASS (12:42)
> --------> basic_cnf tests NOT executed
> 
> ************************************************************
> ************************************************************
> ********************** Security tests **********************
> ************************************************************
> ************************************************************
> --------> cis_kubernetes tests
> cis_kubernetes: PASS (00:00)
> --------> nonssl_endpoints tests
> nonssl_endpoints: FAIL (01:16)
> --------> jdpw_ports tests
> jdpw_ports: PASS (08:31)
> --------> kube_hunter tests
> kube_hunter: PASS (00:08)
> --------> root_pods tests
> root_pods: FAIL (03:08)
> --------> unlimitted_pods tests
> unlimitted_pods: FAIL (01:25)
> 
> ____________________________________________________________

Be careful...the link is dangerously misleading...

in both cases basic_vm and basic_cnf were executed but we do not have the logs..
we can see that in the 
> 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> --------> basic_vm tests NOT executed

NOT executed means that we were not able to collect the logs

on AKS4: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/pipelines/268496164
on Orange 3: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/pipelines/268591591

as we pushed to the backend with the gerrit-id/patch-id, in case of redeploy we may collect old logs for the dashboard, we do not have the id of redeploy attempts.

but here for basic_cnf and basic_vm, on the 2 last attempts, we do not have the results of the run - logs show that results are earlier results -

when we look at the logs, we can see that the dockers started but reached the test timeout (45m)(e.g. basic_vm => https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/1088387021
unfortunately we do not have the logs as we rsync at the end of the test

I had a look at the master of the day because it seems that we have the same behavior...but we can access to the logs

in the master, as here, the basic_vm docker seems to be stuck
the test starts at 2021-03-11 06:41:55
the model is properly distributed by SDC at 06:48:10
the test is running but seems to be stuck in SO at service instantiation

still trying at 07:42:00
....
still trying at 08:00:00

so in case of gating or daily results, the test timeout (45) would have expired and results reported as FAIL

in so logs 
it seems we are stuck at 36%
2021-03-11T07:46:53.674Z|593ed7cc-0738-440a-aa6d-ec4d09905a8a|http-nio-8080-exec-7|onap/so/infra/orchestrationRequests/v7/a2af4d94-73cd-430d-b615-bf559e4a8d21|InfraPortalClient|Unknown-Target-Entity|http://so-request-db-adapter.onap:8083/infraActiveRequests/a2af4d94-73cd-430d-b615-bf559e4a8d21|DEBUG|500||Response body: {
  "requestId" : "a2af4d94-73cd-430d-b615-bf559e4a8d21",
  "requestStatus" : "IN_PROGRESS",
  "flowStatus" : "Execution of AssignVfModuleBB has completed successfully, next invoking CreateVfModuleBB (Execution Path progress: BBs completed = 1; BBs remaining = 2).",
  "progress" : 36,

If I look into SDNC logs (tests done at the end of the tests so I assume basic_vm and basic_cnf are were stuck when this test has been performed)
https://logs.onap.org/onap-integration/gating//119053-1/infrastructure-healthcheck/k8s-teardown/kubernetes-status/pod-onap-sdnc-0-sdnc.log

we keep on having an exception

2021-03-11T00:12:44,243 | WARN  | qtp25668424-2648 | AbstractAuthenticator            | 147 - org.apache.shiro.core - 1.3.2 |  -   | Authentication failed for token submission [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=false].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
org.opendaylight.aaa.api.AuthenticationException: UserName / Password not found
	at org.opendaylight.aaa.shiro.idm.IdmLightProxy.dbAuthenticate(IdmLightProxy.java:106) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at org.opendaylight.aaa.shiro.idm.IdmLightProxy.authenticate(IdmLightProxy.java:67) ~[?:?]
	at org.opendaylight.aaa.shiro.idm.IdmLightProxy.authenticate(IdmLightProxy.java:40) ~[?:?]
	at org.opendaylight.aaa.shiro.tokenauthrealm.auth.HttpBasicAuth.generateAuthentication(HttpBasicAuth.java:102) ~[?:?]
	at org.opendaylight.aaa.shiro.tokenauthrealm.auth.HttpBasicAuth.validate(HttpBasicAuth.java:122) ~[?:?]


it is a bit strange than the SO never reaches a timeout
I have no idea if SO is stuck because of the exception seen in SDNC...
I think Seshu shall have access to the Orange Daily, he can have a look

Patch-set: 1
Reviewer: Gerrit User 897 <897@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 937 <937@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>