Update patch set 3
Patch Set 3: Code-Review+1

> Patch Set 3: Code-Review+1
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > @konrad, @Bartek, do we have your +1?
> > 
> > Looks good to me, but to verify it in field, I need few more hours as I need to also provide checks for other bug. You can consider +0.5 from my side now. I think it's safe to be merged, I'll report if I'll catch any issues with this change in place.
> 
> We can wait the other 0.5 part of the +1 today ;)

So, I've tried to test as much as possible without redeploying environment (that I wanted to save for tomorrow) and I came across some by-standing issue in SO
> 2020-04-29T18:12:43.813Z|b4aa7ad6-090a-4a76-9083-b2989b821c21|camundaTaskExecutor-2|CreateVfModuleBB||||ERROR|500||Exception occurred if bb object not found in VnfAdapterCreateTasks createVfModule
> org.onap.so.client.exception.BBObjectNotFoundException: BBObjectVOLUME_GROUP_ID was not found in gBBInput using reference value: null

But that's most likely due to local hacky update attempt. I've checked certificate of https MSB service now and it looks fine. Just one related patch from SO side to make it work (I'll drop WIP once I'll test fully) - https://gerrit.onap.org/r/c/oom/+/106826.

LGTM

Patch-set: 3
Reviewer: Gerrit User 5550 <5550@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1