Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> > Patch Set 12:
> > 
> > I found this when deploying locally :
> > [tiller] 2020/03/27 14:00:43 warning: Release dev-dmaap post-install dmaap/charts/dmaap-bc/templates/post-install-job.yaml could not complete: timed out waiting for the condition
> > [tiller] 2020/03/27 14:00:43 warning: Release "dev-dmaap" failed post-install: timed out waiting for the condition
> > [storage] 2020/03/27 14:00:43 updating release "dev-dmaap.v1"
> > [tiller] 2020/03/27 14:00:43 failed install perform step: timed out waiting for the condition
> > 
> > Is there a way to see the tiller pod logs from the gating ?
> 
> here Christophe the issue is dmaap-bc post install jobs waits for dmaap-bc to be up and running
> So you have to look at the logs of dmaap-bc (and its aaf init container maybe) to figure out why it's not OK

Ok I ran this locally and traced down the error to the dmaap dr prov pod

the dmaap dr prov container fails to start :

I looked at the aaf init and they look fine (they are mounted by the container with proper permissions) from the dmaap dr prov container it looks like this :

 /opt/app/osaaf/local $ ls -lhrt
 total 176
 -rw-r--r--    1 dradmin  onap          16 Mar 27 17:48 VERSION
 -rw-r--r--    1 dradmin  onap      115.2K Mar 27 17:48 truststoreONAPall.jks
 -r--------    1 dradmin  onap        2.0K Mar 27 17:48 org.onap.dmaap-dr.keyfile
 -rw-r--r--    1 dradmin  onap        1.1K Mar 27 17:48 org.onap.dmaap-dr.props
 -rw-r--r--    1 dradmin  onap         278 Mar 27 17:48 org.onap.dmaap-dr.location.props
 -rw-r--r--    1 dradmin  onap         548 Mar 27 17:48 org.onap.dmaap- dr.cred.props.5842541777143763733.backup
 -rw-r--r--    1 dradmin  onap        1.4K Mar 27 17:48 org.onap.dmaap-dr.trust.jks.6348686222350239249.backup
 -r--------    1 dradmin  onap        1.7K Mar 27 17:48 org.onap.dmaap-dr.key
 -rw-r--r--    1 dradmin  onap        3.6K Mar 27 17:48 org.onap.dmaap-dr.jks
 -rw-r--r--    1 dradmin  onap        1.6K Mar 27 17:48 org.onap.dmaap-dr.crt
 -rw-r--r--    1 dradmin  onap        1.4K Mar 27 17:48 org.onap.dmaap-dr.trust.jks
 -rw-r--r--    1 dradmin  onap        4.1K Mar 27 17:48 org.onap.dmaap-dr.p12
 -rw-r--r--    1 dradmin  onap         751 Mar 27 17:48 org.onap.dmaap-dr.crontab.sh
 -rw-r--r--    1 dradmin  onap        1.1K Mar 27 17:48 org.onap.dmaap-dr.cred.props
 -rw-r--r--    1 dradmin  onap        1.8K Mar 27 17:48 org.onap.dmaap-dr.check.sh

then looked into why the java process crash, I see the following exception in the logs :

03/27-16:52:18.891|InternalLog||||main|||ERROR||||||PROV9000: The database credentials are not working: Cannot create PoolableConnectionFactory (Could not connect to address=(host=dmaap-dr-db-svc)(port=3306)(type=master) : Access denied for user 'datarouter'@'10-1-1-74.dmaap-dr-prov.onap.svc.cluster.local' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding')
java.sql.SQLException: Cannot create PoolableConnectionFactory (Could not connect to address=(host=dmaap-dr-db-svc)(port=3306)(type=master) : Access denied for user 'datarouter'@'10-1-1-74.dmaap-dr-prov.onap.svc.cluster.local' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding')
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at org.onap.dmaap.datarouter.provisioning.utils.ProvDbUtils.getConnection(ProvDbUtils.java:86)
	at org.onap.dmaap.datarouter.provisioning.utils.ProvDbUtils.initProvDB(ProvDbUtils.java:95)
	at org.onap.dmaap.datarouter.provisioning.ProvRunner.main(ProvRunner.java:90)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=dmaap-dr-db-svc)(port=3306)(type=master) : Access denied for user 'datarouter'@'10-1-1-74.dmaap-dr-prov.onap.svc.cluster.local' (using password: YES)

not sure where to go from here, does not look like aaf related but I don't know how dmaap works so...

Note i see this in the container's environment :

DB_PASSWORD=Diwy2'HezaGase

looks like a generated password,maybe password mismatch somewhere ?

Patch-set: 12
Reviewer: Gerrit User 5 <5@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0