Update patch set 9
Patch Set 9:

> Patch Set 9:
> 
> Look at the logs of the SDNC-0 (https://logs.onap.org/onap-integration/gating//134393-9/k8s-teardown/k8s-teardown/kubernetes-status/pod-onap-sdnc-0-sdnc-logs.html)
> It seems the 
> ```
> 2023-05-26T22:41:40,339 | WARN  | qtp322984832-273 | Providers                        | 187 - org.glassfish.jersey.core.jersey-common - 2.37.0 |  -   | A provider org.opendaylight.restconf.nb.rfc8040.rests.services.impl.RestconfSchemaServiceImpl registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.opendaylight.restconf.nb.rfc8040.rests.services.impl.RestconfSchemaServiceImpl will be ignored. 
> ...
> ```
> This seems to lead to the failing SO call (https://logs.onap.org/onap-integration/gating//134393-9/k8s-teardown/k8s-teardown/kubernetes-status/pod-onap-so-bpmn-infra-b6fd99dc4-dspx8-so-bpmn-infra-logs.html)
> ```
> 2023-05-26T22:41:40.617Z|c618879b-f5dd-4ecd-9780-af3ad7bb1875|camundaTaskExecutor-1|SDNC||Unknown-Target-Entity|http://sdnc-oam.onap:8282/rests/operations/GENERIC-RESOURCE-API:service-topology-operation/|DEBUG|500||Response body: {
>   "errors": {
>     "error": [
>       {
>         "error-tag": "malformed-message",
>         "error-info": "Identifier may not be empty",
>         "error-message": "Invalid path 'GENERIC-RESOURCE-API:service-topology-operation/' at offset 48",
>         "error-type": "protocol"
>       }
>     ]
>   }
> }
> 
> ```
> In my opinion the GENERIC-RESOURCE-API is not accepted in the SDNC

I could reproduce this issue: Rest path with tailing '/' causes the error. 
'http://sdnc-oam.onap:8282/rests/operations/GENERIC-RESOURCE-API:service-topology-operation/'
should be
'http://sdnc-oam.onap:8282/rests/operations/GENERIC-RESOURCE-API:service-topology-operation'
Most likely all other requests might be changed as well.

Patch-set: 9