Update patch set 1
Patch Set 1: Code-Review+1

APPC startup became longish...
"Total Appc install took 930 seconds"

All bundles started successfully:
opendaylight-user@root>list | grep -v Active
START LEVEL 100 , List Threshold: 50
 ID | State    | Lvl | Version                             | Name
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 31 | Resolved |  80 | 4.0.10                              | Apache Karaf :: Diagnostic :: Boot
190 | Resolved |  80 | 0.7.1                               | config-persister-directory-xml-adapter, Hosts: 192
191 | Resolved |  80 | 0.7.1                               | config-persister-file-xml-adapter, Hosts: 192

I see some feature not installed:
opendaylight-user@root>feature:list  | grep appc | grep -v "\| x"
appc-event-listener                              | 1.3.0.SNAPSHOT   |          | Uninstalled | appc-event-listener-1.3.0-SNAPSHOT               | event listener
appc-ssh-adapter                                 | 1.3.0.SNAPSHOT   |          | Started     | appc-ssh-adapter-1.3.0-SNAPSHOT                  | appc-ssh-adapter
appc-dispatcher                                  | 1.3.0.SNAPSHOT   |          | Uninstalled | appc-dispatcher-1.3.0-SNAPSHOT                   | appc-dispatcher


Manually starting appc-dispatcher and appc-event-listener succeeded.
appc-ssh-adapter stays "Started", but without "x".
Does it look OK?



There is still this error during start:
 88% [===============================================================>        ]17:35:15.384 [Start Level: Equinox Container: d0233aa9-6542-0018-165e-978c3d441146] ERROR o.o.a.dao.util.dbcp.DBConnectionPool - Get connection failure
java.sql.SQLException: Cannot create JDBC driver of class '' for connect URL ''
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2023) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        at org.onap.appc.dao.util.dbcp.DBConnectionPool.getConnection(DBConnectionPool.java:84) ~[bundleFile:na]
        at org.onap.appc.dao.util.AppcDatabaseConnectionPool.init(AppcDatabaseConnectionPool.java:89) [bundleFile:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
        at org.apache.aries.blueprint.utils.ReflectionUtils.invoke(ReflectionUtils.java:299) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BeanRecipe.invoke(BeanRecipe.java:980) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BeanRecipe.runBeanProcInit(BeanRecipe.java:736) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:848) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:811) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79) [bundleFile:1.7.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_162]
        at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:255) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:186) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:724) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:411) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:276) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:300) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:269) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintExtender.createContainer(BlueprintExtender.java:265) [bundleFile:1.7.1]
        at org.apache.aries.blueprint.container.BlueprintExtender.modifiedBundle(BlueprintExtender.java:255) [bundleFile:1.7.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:500) [bundleFile:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.customizerModified(BundleHookBundleTracker.java:433) [bundleFile:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$AbstractTracked.track(BundleHookBundleTracker.java:725) [bundleFile:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$Tracked.bundleChanged(BundleHookBundleTracker.java:463) [bundleFile:1.1.1]
        at org.apache.aries.util.tracker.hook.BundleHookBundleTracker$BundleEventHook.event(BundleHookBundleTracker.java:422) [bundleFile:1.1.1]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$2.call(EquinoxEventPublisher.java:189) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.notifyEventHooksPrivileged(EquinoxEventPublisher.java:186) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:146) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:466) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.Module.start(Module.java:457) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi-3.10.101.v20150820-1432.jar:na]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:315) ~[na:1.8.0_162]
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2007) ~[commons-dbcp2-2.0.1.jar:2.0.1]
        ... 47 common frames omitted
17:35:15.384 [Start Level: Equinox Container: d0233aa9-6542-0018-165e-978c3d441146] ERROR o.o.a.d.u.AppcDatabaseConnectionPool - DB connection pool is created failed.Please make sure the provided information is correct.

Would be nice if you could take care of it at some later date.

Patch-set: 1