Update patch set 1
Patch Set 1: Code-Review-1

problem reproducible
onap-portal-portal-app not running
+ robot healthcheck issue

Basic Portal Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='portal-app.onap', port=8989): Max retries exceeded with url: /ONAPPORTAL/portalApi/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f044dfe6950>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1