Update patch set 4
Patch Set 4: Code-Review-1

Release "onap-aai" does not exist. Installing it now.
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8446},{"nam|..., bigger context ...|value":"1000"},{"name":"INTERNAL_PORT_1","value":8446},{"name":"INTERNAL_PORT_2","value":5005}],"ima|...

Patch-set: 4
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1