Update patch set 3
Patch Set 3:

Hi Chris,  

/service/logs/catalina.out shows:  
06-Sep-2018 20:08:44.037 SEVERE [http-nio-8702-exec-2] org.postgresql.Driver.connect Connection error:
 org.postgresql.util.PSQLException: FATAL: database "marketplaceDB" does not exist

The DB initialization script is missing when using common DB chart. Would you provide initialization script? 

Thanks, 
Jasmine

Patch-set: 3