Update patch set 5
Patch Set 5:

Pods and Healthcheck are below

root@linux-r4ap:~/oom/kubernetes/robot# kubectl get pods -n onap 
NAME READY STATUS RESTARTS AGE
demo-dmaap-dbc-pg-0 1/1 Running 0 11m
demo-dmaap-dbc-pg-1 1/1 Running 0 10m
demo-dmaap-dbc-pgpool-7796f4cd76-862nj 1/1 Running 0 11m
demo-dmaap-dbc-pgpool-7796f4cd76-qgkb5 1/1 Running 0 11m
demo-dmaap-dmaap-bus-controller-b86544cdc-7t4tx 1/1 Running 0 11m
demo-dmaap-dmaap-dr-db-7756fccdb4-5lz5s 1/1 Running 0 11m
demo-dmaap-dmaap-dr-node-b67b9fdd9-nvxf2 2/2 Running 0 11m
demo-dmaap-dmaap-dr-prov-7f5c689f6d-wgwxn 2/2 Running 0 11m
demo-dmaap-message-router-0 1/1 Running 0 11m
demo-dmaap-message-router-kafka-0 1/1 Running 2 11m
demo-dmaap-message-router-kafka-1 1/1 Running 2 11m
demo-dmaap-message-router-kafka-2 1/1 Running 2 11m
demo-dmaap-message-router-zookeeper-0 1/1 Running 0 11m
demo-dmaap-message-router-zookeeper-1 1/1 Running 0 11m
demo-dmaap-message-router-zookeeper-2 1/1 Running 0 11m
demo-log-log-elasticsearch-6c7879c84c-sgxmn 1/1 Running 0 11m
demo-log-log-kibana-5c6866fcc6-s4lmw 1/1 Running 0 11m
demo-log-log-logstash-58b98f5f99-f2w4n 1/1 Running 0 11m
demo-log-log-logstash-58b98f5f99-stznx 1/1 Running 0 11m
demo-log-log-logstash-58b98f5f99-znf4m 1/1 Running 0 11m
demo-robot-robot-9b77fb45-v9mmz 1/1 Running 0 11m


------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdd4595d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdd4597d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdd4599d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
| FAIL |
ConnectionError: HTTPConnectionPool(host='nbi.onap', port=8080): Max retries exceeded with url: /nbi/api/v3/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdd4ca550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------

Patch-set: 5