Update patch set 5
Patch Set 5:

There's an issue with port assignment:

Release "dev-policy" does not exist. Installing it now.
Error: release dev-policy failed: Service "policy-xacml-pdp" is invalid: spec.ports[0].port: Invalid value: 0: must be between 1 and 65535, inclusive

will look at it.

Patch-set: 5