Update patch set 10
Patch Set 10:

results of  gating (deployment + tests on Orange OOM gating based on OOM repo (no integration manifest + code of the patchset)) for information

deployment OK

tests:
https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/pipelines/49305458
k8s status after deployment
8 pods (on 213) are not in Running state
--------------------------------------------------------------------------------------
NAME                                                           READY     STATUS             RESTARTS   AGE
onap-appc-appc-ansible-server-598558f644-fskzb                 0/1       CrashLoopBackOff   15         1h
onap-dcaegen2-dcae-bootstrap-595d9f9594-9spz9                  0/1       Init:0/1           4          1h
onap-dcaegen2-dcae-cloudify-manager-6dfd7f945f-fw5gz           0/1       ImagePullBackOff   0          1h
onap-dcaegen2-dcae-healthcheck-6ffbc5fdc9-wknd7                0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-bus-controller-577d694c69-8wrpx               0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-5c498cd687-wcvtf                      0/1       CrashLoopBackOff   21         1h
onap-sdnc-controller-blueprints-64b8cf4c7c-496dd               0/1       CrashLoopBackOff   16         1h
onap-sdnc-sdnc-ueb-listener-7587fb798c-hxtj7                   0/1       CrashLoopBackOff   16         1h

healthcheck (medium)
note vnf E2E tests not triggered because core healthcheck FAIL (dmap healtcheck is FAIL)

===================================================================
Health-Check :: Testing ecomp components are available via calls.             
===================================================================
Basic A&AI Health Check                                    | PASS |
----------------------------------------------------------------------
Basic AAF Health Check                                     | PASS |
----------------------------------------------------------------------
Basic AAF SMS Health Check                                 | PASS |
----------------------------------------------------------------------
Basic APPC Health Check                                    | FAIL |
401 != 200
----------------------------------------------------------------------
Basic CLI Health Check                                     | PASS |
----------------------------------------------------------------------
Basic CLAMP Health Check                                   | PASS |
----------------------------------------------------------------------
Basic DCAE Health Check                                    | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                       | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc70cdb9ad0>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                    | PASS |
----------------------------------------------------------------------
Basic External API NBI Health Check                        | PASS |
----------------------------------------------------------------------
Basic Log Elasticsearch Health Check                       | PASS |
----------------------------------------------------------------------
Basic Log Kibana Health Check                              | PASS |
----------------------------------------------------------------------
Basic Log Logstash Health Check                            | PASS |
----------------------------------------------------------------------
Basic Microservice Bus Health Check                        | PASS |
----------------------------------------------------------------------
Basic Multicloud API Health Check                          | PASS |
----------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                    | PASS |
----------------------------------------------------------------------
Basic Multicloud-pike API Health Check                     | PASS |
----------------------------------------------------------------------
Basic OOF-Homing Health Check                              | PASS |
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                               | PASS |
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                                | PASS |
----------------------------------------------------------------------
Basic Policy Health Check                                  | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                  | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                     | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                    | PASS |
----------------------------------------------------------------------
Basic SO Health Check                                      | PASS |
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VID Health Check                                     | PASS |
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check              | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check            | FAIL |
502 != 200
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.| FAIL |
29 critical tests, 24 passed, 5 failed
29 tests total, 24 passed, 5 failed
======================================================================
Output:  /var/lib/xtesting/results/medium/output.xml

src: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/167851607

Patch-set: 10
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0