Update patch set 20
Patch Set 20:

Gitlab Azure AKS 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//124842-20/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 24
 * Nb Failed Jobs: 0
 * Nb Deployments: 137
 * Nb Failed Deployments: 6
 * List of Failed Deployments: [
   - onap-cps-core
   - onap-dcae-dashboard
   - onap-holmes-engine-mgmt
   - onap-holmes-rule-mgmt
   - onap-modeling-etsicatalog
   - onap-ncmp-dmi-plugin]
 * Nb StatefulSets: 22
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 62
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 35
 * Nb Failed Helms: 2
 * List of Failed Helms: [
   - onap-msb
   - onap-oof]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-12-01 18:28:29,106 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /iui/microservices/default.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e831a7410>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8321bfd0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-pike/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8316c450>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-k8s/v1/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8316cd90>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8321d290>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e83190890>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /iui/usecaseui/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e830ab1d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/gvnfmdriver/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e830a66d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/huaweivnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8312b250>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/nslcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e835721d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnflcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e83146610>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnfmgr/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8316c790>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/vnfres/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e8311aa50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/ztevnfmdriver/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e831754d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/holmes-rule-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e83072550>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/holmes-engine-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e830dced0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/multicloud-fcaps/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e83082a50>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='msb-iag.onap', port=443): Max retries exceeded with url: /api/parser/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0e830991d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
40 critical tests, 21 passed, 19 failed
40 tests total, 21 passed, 19 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | PASS |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests NOT executed
--------> DCAEMOD tests NOT executed
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (01:28)
--------> CDS tests
basic_cds: PASS (00:12)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | PASS |
--------> 5gbulkpm tests NOT executed
--------> basic_vm tests
basic_vm: PASS (07:08)
--------> basic_network tests
basic_network: PASS (04:03)
--------> basic_cnf tests
basic_cnf: FAIL (04:34)
--------> basic_vm_macro tests
basic_vm_macro: PASS (07:20)
--------> basic_clamp tests NOT executed
--------> pnf_macro tests
pnf_macro: FAIL (04:33)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests
nonssl_endpoints: PASS (00:45)
--------> jdpw_ports tests
jdpw_ports: PASS (04:23)
--------> kube_hunter tests
kube_hunter: FAIL (00:00)
--------> root_pods tests
root_pods: PASS (02:30)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (00:37)

____________________________________________________________

Patch-set: 20