Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 208
 * Nb Failed Pods: 20
 * List of Failed Pods: [
   - onap-aai-aai-788c4d9c94-4pzkz
   - onap-aai-aai-champ-7f97f98976-jpcgj
   - onap-aai-aai-graphadmin-c79fb7fcf-2rc4t
   - onap-aai-aai-graphadmin-create-db-schema-w2fwx
   - onap-aai-aai-resources-557c6f9d78-rh4cx
   - onap-aai-aai-sparky-be-5ff8689c54-pl8vx
   - onap-aai-aai-spike-77ccc5bf78-9shgk
   - onap-aai-aai-traversal-7fb5558d98-5rg8k
   - onap-aai-aai-traversal-update-query-data-sws6v
   - onap-cassandra-cassandra-2
   - onap-contrib-netbox-app-695fd89fd-mh924
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-cbls7
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-n7zsd
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-zdchd
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-ctkj9
   - onap-dcaegen2-dcae-policy-handler-6fcc6477d-qlmnr
   - onap-dmaap-dmaap-bc-post-install-x5qwj
   - onap-policy-policy-api-6db49d977f-z4kgx
   - onap-policy-policy-pap-85845569c5-bkfhf
   - onap-policy-policy-xacml-pdp-7df865f5cc-527n5]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-05 14:30:22,866 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06a0c31e50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06a0a73090>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06a0a737d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f06a0935990>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 49 passed, 9 failed
58 tests total, 49 passed, 9 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0