Update patch set 4
Patch Set 4:

Gatign results (second pipeline)
Installation OK
Results: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/172998936/artifacts/download

results ~ in line with 1st pipeline except that the pod so-bpmn was OK when running the kubectl command, however it had been also already restarted several times

helm
*****
Chart onap-so
STATUS: DEPLOYED

(vnfsdk and policy FAILED)

healthcheck
***********
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-bpmn-infra.onap', port=8081): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff1d7d8f590>: Failed to establish a new connection: [Errno 111] Connection refused',))

End to End
**********
not triggered
k8s
****
onap-so-so-bpmn-infra-7b4cf7dbf4-nnbbr         1/1 Running 3 15m
onap-so-so-catalog-db-adapter-684f7f7f57-f6pgd 1/1 Running 0 15m
onap-so-so-f57fb6c78-7tl9m                     1/1 Running 0 15m
onap-so-so-mariadb-5dfdc49646-v2cbj            1/1 Running 0 15m
onap-so-so-monitoring-594bd744b6-bxzjz         1/1 Running 0 15m
onap-so-so-openstack-adapter-6c75fcdd89-2n7cs  1/1 Running 1 15m
onap-so-so-request-db-adapter-6797d64c57-64trq 1/1 Running 0 15m
onap-so-so-sdc-controller-849949db55-r7dtr     1/1 Running 0 15m
onap-so-so-sdnc-adapter-64b78944c6-b4zv9       1/1 Running 0 15m
onap-so-so-vfc-adapter-6df5476d68-mml86        1/1 Running 0 15m

even if we can see that the so-bpmn has been restarted 3 times
Name:		onap-so-so-bpmn-infra-7b4cf7dbf4-nnbbr
Namespace:	onap
Node:		compute08-onap-master.novalocal/10.253.0.9
Start Time:	Wed, 06 Mar 2019 21:25:57 +0000
Labels:		app=so-bpmn-infra
		pod-template-hash=3607938690
		release=onap-so
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"onap","name":"onap-so-so-bpmn-infra-7b4cf7dbf4","uid":"6df6c8a8-4056-11e9-9d79-02...
Status:		Running
IP:		10.42.73.146
Controllers:	ReplicaSet/onap-so-so-bpmn-infra-7b4cf7dbf4
Init Containers:
  so-bpmn-infra-readiness:
    Container ID:	docker://c100e50f74f0df24f297f8b3e86787706ff75cd76acd765ee42b550e0f83cc64
    Image:		oomk8s/readiness-check:2.0.0
    Image ID:		docker-pullable://oomk8s/readiness-check@sha256:7daa08b81954360a1111d03364febcb3dcfeb723bcc12ce3eb3ed3e53f2323ed
    Port:		
    Command:
      /root/ready.py
    Args:
      --container-name
      so-mariadb
    State:		Terminated
      Reason:		Completed
      Exit Code:	0
      Started:		Wed, 06 Mar 2019 21:37:36 +0000
      Finished:		Wed, 06 Mar 2019 21:39:15 +0000
    Ready:		True
    Restart Count:	1
    Environment:
      NAMESPACE:	onap (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xcwlg (ro)
Containers:
  so-bpmn-infra:
    Container ID:	docker://95a3dce36507b60eaa0abdf0a125ba30241337c04c19020b8ded17848ad59375
    Image:		nexus3.onap.org:10001/onap/so/bpmn-infra:1.3.3
    Image ID:		docker-pullable://nexus3.onap.org:10001/onap/so/bpmn-infra@sha256:1da40f00639469a4ae95994aec3a66ca70a8f2468a816256c435a7ba64913df7
    Port:		8081/TCP
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Wed, 06 Mar 2019 21:41:16 +0000
      Finished:		Wed, 06 Mar 2019 21:41:40 +0000
    Ready:		False
    Restart Count:	3
    Liveness:		http-get http://:8081/manage/health delay=600s timeout=10s period=60s #success=1 #failure=3
    Environment Variables from:
      onap-so-so-bpmn-infra-configmap	ConfigMap	Optional: false
    Environment:
      DB_HOST:			<set to the key 'mariadb.readwrite.host' in secret 'onap-so-so-db-secrets'>	Optional: false
      DB_PORT:			<set to the key 'mariadb.readwrite.port' in secret 'onap-so-so-db-secrets'>	Optional: false
      DB_USERNAME:		<set to the key 'mariadb.readwrite.rolename' in secret 'onap-so-so-db-secrets'>	Optional: false
      DB_PASSWORD:		<set to the key 'mariadb.readwrite.password' in secret 'onap-so-so-db-secrets'>	Optional: false
      DB_ADMIN_USERNAME:	<set to the key 'mariadb.admin.rolename' in secret 'onap-so-so-db-secrets'>	Optional: false
      DB_ADMIN_PASSWORD:	<set to the key 'mariadb.admin.password' in secret 'onap-so-so-db-secrets'>	Optional: false
    Mounts:
      /app/config from config (ro)
      /app/logs from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xcwlg (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  logs:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  config:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	onap-so-so-bpmn-infra-app-configmap
    Optional:	false
  default-token-xcwlg:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-xcwlg
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From						SubObjectPath					Type		Reason			Message
  ---------	--------	-----	----						-------------					--------	------			-------
  16m		16m		1	default-scheduler										Normal		Scheduled		Successfully assigned onap-so-so-bpmn-infra-7b4cf7dbf4-nnbbr to compute08-onap-master.novalocal
  16m		16m		1	kubelet, compute08-onap-master.novalocal							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "logs" 
  16m		16m		1	kubelet, compute08-onap-master.novalocal							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "config" 
  16m		16m		1	kubelet, compute08-onap-master.novalocal							Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-xcwlg" 
  14m		4m		2	kubelet, compute08-onap-master.novalocal	spec.initContainers{so-bpmn-infra-readiness}	Normal		Pulling			pulling image "oomk8s/readiness-check:2.0.0"
  14m		4m		2	kubelet, compute08-onap-master.novalocal	spec.initContainers{so-bpmn-infra-readiness}	Normal		Pulled			Successfully pulled image "oomk8s/readiness-check:2.0.0"
  14m		4m		2	kubelet, compute08-onap-master.novalocal	spec.initContainers{so-bpmn-infra-readiness}	Normal		Created			Created container
  14m		4m		2	kubelet, compute08-onap-master.novalocal	spec.initContainers{so-bpmn-infra-readiness}	Normal		Started			Started container
  2m		1m		3	kubelet, compute08-onap-master.novalocal	spec.containers{so-bpmn-infra}			Normal		Pulling			pulling image "nexus3.onap.org:10001/onap/so/bpmn-infra:1.3.3"
  2m		1m		3	kubelet, compute08-onap-master.novalocal	spec.containers{so-bpmn-infra}			Normal		Pulled			Successfully pulled image "nexus3.onap.org:10001/onap/so/bpmn-infra:1.3.3"
  2m		1m		3	kubelet, compute08-onap-master.novalocal	spec.containers{so-bpmn-infra}			Normal		Created			Created container
  2m		1m		3	kubelet, compute08-onap-master.novalocal	spec.containers{so-bpmn-infra}			Normal		Started			Started container
  1m		1m		2	kubelet, compute08-onap-master.novalocal							Warning		FailedSync		Error syncing pod
  1m		1m		3	kubelet, compute08-onap-master.novalocal	spec.containers{so-bpmn-infra}			Warning		BackOff			Back-off restarting failed container

Patch-set: 4
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0