Update patch set 4
Patch Set 4:

(1 comment)

I'm getting the following error trying to build cps chart by running `make cps`:

  [WARNING] templates/: directory not found
  [ERROR] /oom/kubernetes/cps: chart metadata is missing these dependencies: postgres,readinessCheck,repositoryGenerator,serviceAccount,certInitializer

  Error: 1 chart(s) linted, 1 chart(s) failed
  make[1]: *** [lint-cps] Error 1
  make: *** [cps] Error 2

Do you have the same ?

Patch-set: 4
Reviewer: Gerrit User 5658 <5658@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>