Update patch set 16
Patch Set 16:

Robot health check passes successfully except usecaseui-gui (which failed even before):
root@borislav-oom-rancher:~/master/oom/kubernetes/robot# date
Wed Feb 28 15:08:10 UTC 2018
root@borislav-oom-rancher:~/master/oom/kubernetes/robot# ./ete-k8s.sh onap health
Starting Xvfb on display :88 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
OpenECOMP ETE
==============================================================================
OpenECOMP ETE.Robot
==============================================================================
OpenECOMP ETE.Robot.Testsuites
==============================================================================
OpenECOMP ETE.Robot.Testsuites.Health-Check :: Testing ecomp components are...
==============================================================================
Basic DCAE Health Check                                               [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9748acc810>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9748ae4890>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9746d2c550>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-controller.onap', port=8080): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9746d2c810>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SDNGC Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic MSO Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic ASDC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Message Router Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
catalog API Health Check                                              | PASS |
------------------------------------------------------------------------------
emsdriver API Health Check                                            | PASS |
------------------------------------------------------------------------------
gvnfmdriver API Health Check                                          | PASS |
------------------------------------------------------------------------------
huaweivnfmdriver API Health Check                                     | PASS |
------------------------------------------------------------------------------
multicloud API Health Check                                           | PASS |
------------------------------------------------------------------------------
multicloud-ocata API Health Check                                     | PASS |
------------------------------------------------------------------------------
multicloud-titanium_cloud API Health Check                            | PASS |
------------------------------------------------------------------------------
multicloud-vio API Health Check                                       | PASS |
------------------------------------------------------------------------------
nokiavnfmdriver API Health Check                                      | PASS |
------------------------------------------------------------------------------
nslcm API Health Check                                                | PASS |
------------------------------------------------------------------------------
resmgr API Health Check                                               | PASS |
------------------------------------------------------------------------------
usecaseui-gui API Health Check                                        | FAIL |
502 != 200
------------------------------------------------------------------------------
vnflcm API Health Check                                               | PASS |
------------------------------------------------------------------------------
vnfmgr API Health Check                                               | PASS |
------------------------------------------------------------------------------
vnfres API Health Check                                               | PASS |
------------------------------------------------------------------------------
workflow API Health Check                                             | PASS |
------------------------------------------------------------------------------
ztesdncdriver API Health Check                                        | PASS |
------------------------------------------------------------------------------
ztevmanagerdriver API Health Check                                    | PASS |
------------------------------------------------------------------------------
OpenECOMP ETE.Robot.Testsuites.Health-Check :: Testing ecomp compo... | FAIL |
30 critical tests, 28 passed, 2 failed
30 tests total, 28 passed, 2 failed
==============================================================================
OpenECOMP ETE.Robot.Testsuites                                        | FAIL |
30 critical tests, 28 passed, 2 failed
30 tests total, 28 passed, 2 failed
==============================================================================
OpenECOMP ETE.Robot                                                   | FAIL |
30 critical tests, 28 passed, 2 failed
30 tests total, 28 passed, 2 failed
==============================================================================
OpenECOMP ETE                                                         | FAIL |
30 critical tests, 28 passed, 2 failed
30 tests total, 28 passed, 2 failed
==============================================================================
Output:  /share/logs/ETE_32399/output.xml
Log:     /share/logs/ETE_32399/log.html
Report:  /share/logs/ETE_32399/report.html
command terminated with exit code 2

Patch-set: 16
Label: Code-Review=0