Update patch set 6
Patch Set 6:

####################################################################################

Below I attached hv-ves blueprint (updated in Bootstrap) & log from HV-VES component tested on our lab yesterday. 
(use_tls: true ; hv-ves 1.4.0 )

HV-VES Worked.

-------------------------------------------------------------------------------------

imports:
  - https://www.getcloudify.org/spec/cloudify/4.5.5/types.yaml
  - https://nexus.onap.org/service/local/repositories/raw/content/org.onap.dcaegen2.platform.plugins/R6/k8splugin/1.7.2/k8splugin_types.yaml

 

inputs:
  tag_version:
type: string
default: 'nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.hv-ves.hv-collector-main:1.4.0'
  hv_ves_name:
type: string
default: 'dcae-hv-ves-collector'
  replicas:
type: integer
description: number of instances
default: 1
  host_port:
type: integer
description: Network port that the platform service is expecting to expose on the host
default: 30222
  container_port:
type: integer
description: Network port that the platform service exposes in the container
default: 6061
  kafka_bootstrap_servers:
type: string
default: 'message-router-kafka:9092'
  kafka_username:
type: string
default: 'admin'
  kafka_password:
type: string
default: 'admin_secret'
  perf3gpp_kafka_topic:
type: string
default: 'HV_VES_PERF3GPP'
  log_level:
type: string
default: 'INFO'
  server_idle_timeout_sec:
type: integer
default: 300
  cbs_request_interval_sec:
type: integer
default: 5
  security_ssl_disable:
type: boolean
default: true
  security_keys_key_store_file:
type: string
default: '/etc/ves-hv/ssl/cert.jks'
  security_keys_key_store_password_file:
type: string
default: '/etc/ves-hv/ssl/jks.pass'
  security_keys_trust_store_file:
type: string
default: '/etc/ves-hv/ssl/trust.jks'
  security_keys_trust_store_password_file:
type: string
default: '/etc/ves-hv/ssl/trust.pass'
node_templates:
  hv-ves:
interfaces:
  cloudify.interfaces.lifecycle:
start:
  inputs:
envs:
  JAVA_OPTS: { concat: [ '-Dlogback.configurationFile=/etc/ONAP/', { get_input: hv_ves_name }, '/logback.xml' ] }
properties:
  application_config:
logLevel: { get_input: log_level }
server.idleTimeoutSec: { get_input: server_idle_timeout_sec }
server.listenPort: { get_input: container_port }
cbs.requestIntervalSec: { get_input: cbs_request_interval_sec}
security.sslDisable: { get_input: security_ssl_disable }
security.keys.keyStoreFile: { get_input: security_keys_key_store_file }
security.keys.keyStorePasswordFile: { get_input: security_keys_key_store_password_file }
security.keys.trustStoreFile: { get_input: security_keys_trust_store_file }
security.keys.trustStorePasswordFile: { get_input: security_keys_trust_store_password_file }
streams_publishes:
  perf3gpp:
type: kafka
aaf_credentials:
  username: { get_input: kafka_username }
  password: { get_input: kafka_password }
kafka_info:
  bootstrap_servers: { get_input: kafka_bootstrap_servers }
  topic_name: { get_input: perf3gpp_kafka_topic }
  docker_config:
healthcheck:
  type: script
  script: "/opt/ves-hv-collector/healthcheck.sh"
  interval: 15s
  timeout: 2s
  image: { get_input: tag_version }
  replicas: { get_input: replicas }
  name: { get_input: hv_ves_name }
  dns_name: { get_input: hv_ves_name }
  container_port: { get_input: container_port }
  host_port: { get_input: host_port }
  log_info:
log_directory: { concat: [ '/var/log/ONAP/', { get_input: hv_ves_name } ] }
  tls_info:
cert_directory: '/etc/ves-hv/ssl'
use_tls: true
type: dcae.nodes.ContainerizedPlatformComponent

 

 

_____________________________________________________________________________________________________________-

 

ubuntu@onap-5418-rke-node:~$ kubectl get pods -n onap | grep hv-ves
dep-dcae-hv-ves-collector-5c46899857-gwdp2              2/2     Running      0          100s
ubuntu@onap-5418-rke-node:~$ kubectl edit pod dep-dcae-hv-ves-collector-5c46899857-gwdp2 -n onap
pod/dep-dcae-hv-ves-collector-5c46899857-gwdp2 edited
ubuntu@onap-5418-rke-node:~$ kubectl get pods -n onap | grep hv-ves
dep-dcae-hv-ves-collector-5c46899857-gwdp2              1/2     Running      1          3m5s
ubuntu@onap-5418-rke-node:~$ docker logs dep-dcae-hv-ves-collector-5c46899857-gwdp2
Error: No such container: dep-dcae-hv-ves-collector-5c46899857-gwdp2
ubuntu@onap-5418-rke-node:~$ docker logs dep-dcae-hv-ves-collector-5c46899857-gwdp2 -n onap
unknown shorthand flag: 'n' in -n
See 'docker logs --help'.
ubuntu@onap-5418-rke-node:~$ kubectl logs dep-dcae-hv-ves-collector-5c46899857-gwdp2
Error from server (NotFound): pods "dep-dcae-hv-ves-collector-5c46899857-gwdp2" not found
ubuntu@onap-5418-rke-node:~$ kubectl logs dep-dcae-hv-ves-collector-5c46899857-gwdp2 -n onap
Error from server (BadRequest): a container name must be specified for pod dep-dcae-hv-ves-collector-5c46899857-gwdp2, choose one of: [dcae-hv-ves-collector filebeat] or one of the init containers: [init-tls]
ubuntu@onap-5418-rke-node:~$ kubectl logs dep-dcae-hv-ves-collector-5c46899857-gwdp2 dcae-hv-ves-collector -n onap 
Service started with pid=6
 | 2020-03-03T09:43:42.801Z     |                 reactor.util.Loggers$LoggerFactory     | DEBUG     | Using Slf4j logging framework     |      |      |      | main
 | 2020-03-03T09:43:42.836Z     | t.services.cbs.client.model.CbsClientConfiguration     | INFO     | CBS client will use http over TLS.     |      |      |      | main
 | 2020-03-03T09:43:42.844Z     | t.services.cbs.client.model.CbsClientConfiguration     | INFO     | Path to cert files: /etc/ves-hv/ssl/     |      |      |      | main
 | 2020-03-03T09:43:43.043Z     | ollectors.veshv.config.impl.HvVesCommandLineParser     | INFO     | Healthcheck port missing on command line, using default: 6060     |      |      |      | main
 | 2020-03-03T09:43:43.907Z     | ae.collectors.veshv.main.servers.HealthCheckServer     | INFO     | Health check server is up and listening on 0.0.0.0:6060     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | reactor-http-epoll-1
 | 2020-03-03T09:43:43.944Z     | ae.collectors.veshv.config.api.ConfigurationModule     | INFO     | Using base configuration file: /etc/ves-hv/configuration/base.json     |      |      |      | main
 | 2020-03-03T09:43:43.965Z     | ae.collectors.veshv.config.api.ConfigurationModule     | INFO     | Successfully parsed configuration file to: PartialConfiguration(listenPort=Some(6061), idleTimeoutSec=Some(60), firstRequestDelaySec=Some(10), requestIntervalSec=Some(5), sslDisable=Some(true), keyStoreFile=None, keyStorePasswordFile=None, trustStoreFile=None, trustStorePasswordFile=None, logLevel=Some(INFO), streamPublishers=None)     |      |      |      | main
 | 2020-03-03T09:43:44.498Z     | rvices.sdk.rest.services.cbs.client.impl.CbsLookup     | INFO     | Config Binding Service address: config-binding-service:10443     |      |      |      | main
 | 2020-03-03T09:43:44.499Z     | dcae.collectors.veshv.config.impl.CbsClientAdapter     | INFO     | CBS client successfully created, first request will be sent in 10 s     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | main
 | 2020-03-03T09:43:53.296Z     | ors.veshv.healthcheck.factory.HealthCheckApiServer     | DEBUG     | Component status: OUT_OF_SERVICE, Component is starting     |      |      |      | reactor-http-epoll-2
 | 2020-03-03T09:43:54.973Z     | lectors.veshv.config.impl.CbsConfigurationProvider     | INFO     | Received new configuration:
{"security.sslDisable":true,"logLevel":"INFO","security.keys.trustStoreFile":"/etc/ves-hv/ssl/trust.jks","server.listenPort":6061,"server.idleTimeoutSec":300,"cbs.requestIntervalSec":5,"streams_publishes":{"perf3gpp":{"type":"kafka","aaf_credentials":{"username":"admin","password":"admin_secret"},"kafka_info":{"bootstrap_servers":"message-router-kafka:9092","topic_name":"HV_VES_PERF3GPP"}}},"security.keys.keyStoreFile":"/etc/ves-hv/ssl/cert.jks","security.keys.trustStorePasswordFile":"/etc/ves-hv/ssl/trust.pass","security.keys.keyStorePasswordFile":"/etc/ves-hv/ssl/jks.pass"}     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | reactor-http-epoll-3
 | 2020-03-03T09:43:55.029Z     | lectors.veshv.config.impl.CbsConfigurationProvider     | INFO     | Successfully parsed configuration json to:
PartialConfiguration(listenPort=Some(6061), idleTimeoutSec=Some(300), firstRequestDelaySec=None, requestIntervalSec=Some(5), sslDisable=Some(true), keyStoreFile=Some(/etc/ves-hv/ssl/cert.jks), keyStorePasswordFile=Some(/etc/ves-hv/ssl/jks.pass), trustStoreFile=Some(/etc/ves-hv/ssl/trust.jks), trustStorePasswordFile=Some(/etc/ves-hv/ssl/trust.pass), logLevel=Some(INFO), streamPublishers=Some([GsonKafka{name='perf3gpp', kafkaInfo=KafkaInfo{bootstrapServers=message-router-kafka:9092, topicName=HV_VES_PERF3GPP, consumerGroupId=null, clientRole=null, clientId=null, maxPayloadSizeBytes=1048576}, aafCredentials=AafCredentials{username=*, password=*}}]))     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | reactor-http-epoll-3
 | 2020-03-03T09:43:55.030Z     | ollectors.veshv.config.impl.ConfigurationValidator     | INFO     | About to validate configuration: PartialConfiguration(listenPort=Some(6061), idleTimeoutSec=Some(300), firstRequestDelaySec=Some(10), requestIntervalSec=Some(5), sslDisable=Some(true), keyStoreFile=Some(/etc/ves-hv/ssl/cert.jks), keyStorePasswordFile=Some(/etc/ves-hv/ssl/jks.pass), trustStoreFile=Some(/etc/ves-hv/ssl/trust.jks), trustStorePasswordFile=Some(/etc/ves-hv/ssl/trust.pass), logLevel=Some(INFO), streamPublishers=Some([GsonKafka{name='perf3gpp', kafkaInfo=KafkaInfo{bootstrapServers=message-router-kafka:9092, topicName=HV_VES_PERF3GPP, consumerGroupId=null, clientRole=null, clientId=null, maxPayloadSizeBytes=1048576}, aafCredentials=AafCredentials{username=*, password=*}}]))     |      |      |      | reactor-http-epoll-3
 | 2020-03-03T09:43:55.038Z     | dcae.collectors.veshv.config.impl.CbsClientAdapter     | DEBUG     | CBS request interval changed to: 5 s     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | reactor-http-epoll-3
 | 2020-03-03T09:43:55.040Z     |                org.onap.dcae.collectors.veshv.main     | INFO     | Using updated configuration for new connections     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | elastic-2
 | 2020-03-03T09:43:55.059Z     | org.onap.dcae.collectors.veshv.impl.NettyTcpServer     | INFO     | Collector configured with SSL disabled     |      |      |      | elastic-2
 | 2020-03-03T09:43:55.066Z     |    org.onap.dcae.collectors.veshv.impl.HvVesServer     | INFO     | HighVolume VES Collector is up and listening on 0.0.0.0:6061     |      |      | InstanceID=ba7d6d65-7fc8-408f-8b29-c32526449e8b, ServerFQDN=dcae-hv-ves-collector     | reactor-tcp-epoll-1

 

ubuntu@onap-5418-rke-node:~$ kubectl get pods -n onap | grep hv-ves
dep-dcae-hv-ves-collector-5c46899857-gwdp2              2/2     Running      1          10m

 

WORKED

Patch-set: 6
Reviewer: Gerrit User 2807 <2807@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0