Update patch set 12
Patch Set 12:

Gitlab Orange 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//114236-12/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 24
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
   - onap-aai-graphadmin-create-db-schema
   - onap-aai-traversal-update-query-data
   - onap-awx
   - onap-cmso-db-config-config-job
   - onap-dmaap-bc-dmaap-provisioning
   - onap-ejbca-config-config-job
   - onap-modeling-etsicatalog-config-job
   - onap-nbi-config-config-job
   - onap-nengdb-init-config-job
   - onap-netbox-app-provisioning
   - onap-oof-has-healthcheck
   - onap-oof-has-onboard
   - onap-policy-galera-config
   - onap-portal-db-config
   - onap-sdc-be-config-backend
   - onap-sdc-cs-config-cassandra
   - onap-sdc-onboarding-be-cassandra-init
   - onap-sdc-wfd-be-workflow-init
   - onap-sdnc-dbinit-job
   - onap-sdnc-sdnrdb-init-job
   - onap-so-mariadb-config-job
   - onap-vid-mariadb-init-config-job
   - onap-vnfsdk-init-postgres]
 * Nb Deployments: 148
 * Nb Failed Deployments: 133
 * List of Failed Deployments: [
   - onap-a1policymanagement
   - onap-aaf-cass
   - onap-aaf-cm
   - onap-aaf-fs
   - onap-aaf-gui
   - onap-aaf-locate
   - onap-aaf-oauth
   - onap-aaf-service
   - onap-aaf-sms
   - onap-aai
   - onap-aai-babel
   - onap-aai-data-router
   - onap-aai-elasticsearch
   - onap-aai-graphadmin
   - onap-aai-modelloader
   - onap-aai-resources
   - onap-aai-schema-service
   - onap-aai-search-data
   - onap-aai-sparky-be
   - onap-aai-traversal
   - onap-appc-dgbuilder
   - onap-awx-postgres
   - onap-cds-blueprints-processor
   - onap-cds-command-executor
   - onap-cds-sdc-listener
   - onap-clamp
   - onap-clamp-backend
   - onap-clamp-dash-es
   - onap-clamp-dash-kibana
   - onap-clamp-dash-logstash
   - onap-clamp-mariadb
   - onap-dbc-pg-primary
   - onap-dbc-pg-replica
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-config-binding-service
   - onap-dcae-dashboard
   - onap-dcae-dashboard-pg-primary
   - onap-dcae-dashboard-pg-replica
   - onap-dcae-db-primary
   - onap-dcae-db-replica
   - onap-dcae-deployment-handler
   - onap-dcae-inv-pg-primary
   - onap-dcae-inv-pg-replica
   - onap-dcae-inventory-api
   - onap-dcae-policy-handler
   - onap-dcae-servicechange-handler
   - onap-dcaemod-db-primary
   - onap-dcaemod-db-replica
   - onap-dcaemod-designtool
   - onap-dcaemod-distributor-api
   - onap-dcaemod-genprocessor
   - onap-dcaemod-nifi-registry
   - onap-dcaemod-onboarding-api
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-ejbca
   - onap-esr-server
   - onap-kube2msb
   - onap-modeling-etsicatalog
   - onap-msb-consul
   - onap-msb-discovery
   - onap-msb-eag
   - onap-msb-iag
   - onap-multicloud
   - onap-multicloud-azure
   - onap-multicloud-fcaps
   - onap-multicloud-k8s
   - onap-multicloud-pike
   - onap-multicloud-starlingx
   - onap-multicloud-vio
   - onap-multicloud-windriver
   - onap-music
   - onap-nbi
   - onap-netbox-app
   - onap-netbox-nginx
   - onap-netbox-postgres
   - onap-network-name-gen
   - onap-oof
   - onap-oof-cmso-optimizer
   - onap-oof-cmso-service
   - onap-oof-cmso-ticketmgt
   - onap-oof-cmso-topology
   - onap-oof-has-api
   - onap-oof-has-controller
   - onap-oof-has-data
   - onap-oof-has-reservation
   - onap-oof-has-solver
   - onap-oom-cert-service
   - onap-policy-api
   - onap-policy-distribution
   - onap-policy-pap
   - onap-policy-xacml-pdp
   - onap-portal-app
   - onap-portal-cassandra
   - onap-portal-sdk
   - onap-portal-widget
   - onap-sdc-be
   - onap-sdc-fe
   - onap-sdc-onboarding-be
   - onap-sdc-wfd-be
   - onap-sdc-wfd-fe
   - onap-sdnc-ansible-server
   - onap-sdnc-dgbuilder
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-sdnc-web
   - onap-sdnrdb-coordinating-only
   - onap-so
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-cnf-adapter
   - onap-so-etsi-nfvo-ns-lcm
   - onap-so-monitoring
   - onap-so-nssmf-adapter
   - onap-so-oof-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-sdnc-adapter
   - onap-so-vfc-adapter
   - onap-so-vnfm-adapter
   - onap-vfc-generic-vnfm-driver
   - onap-vfc-huawei-vnfm-driver
   - onap-vfc-nslcm
   - onap-vfc-vnflcm
   - onap-vfc-vnfmgr
   - onap-vfc-vnfres
   - onap-vfc-zte-vnfm-driver
   - onap-vid
   - onap-vnfsdk
   - onap-vnfsdk-postgres-primary
   - onap-vnfsdk-postgres-replica]
 * Nb StatefulSets: 27
 * Nb Failed StatefulSets: 24
 * List of Failed StatefulSets: [
   - onap-aaf-sms-quorumclient
   - onap-aaf-sms-vault
   - onap-appc
   - onap-appc-db
   - onap-awx
   - onap-cassandra
   - onap-cds-db
   - onap-cmso-db
   - onap-dcae-mongo
   - onap-dmaap-dr-db
   - onap-dmaap-dr-node
   - onap-mariadb-galera
   - onap-message-router
   - onap-message-router-kafka
   - onap-message-router-zookeeper
   - onap-multicloud-k8s-etcd
   - onap-multicloud-k8s-mongo
   - onap-nbi-mongo
   - onap-policy-apex-pdp
   - onap-policy-drools-pdp
   - onap-policy-mariadb
   - onap-sdnc
   - onap-sdnrdb-master
   - onap-vfc-mariadb]
 * Nb Persistent Volume Claims: 62
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 3
 * List of Failed Helms: [
   - onap-so
   - onap-aai
   - onap-oof]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2021-01-20 20:54:46,069 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9f7ac67910>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2021-01-20 20:54:36,055 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f45f1c71d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v16/service-design-and-creation/models/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f45f1be6550>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
20:58:42,559: Loading (INFO)
20:58:43,507: Running (INFO)
cat: ./public/114236-12/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (00:35)
hv-ves: FAIL (00:24)
5gbulkpm: FAIL (00:15)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:01)
cat: ./public/114236-12/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (00:43)
kube_hunter: PASS (00:07)
root_pods: FAIL (00:12)
unlimitted_pods: FAIL (00:04)

--------> FOCUS on CIS errors
cat: ./public/114236-12/security/cis_kubernetes/cis_kubernetes.log: No such file or directory

____________________________________________________________

Patch-set: 12