Update patch set 2
Patch Set 2:

Gitlab Azure 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//115983-2/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 25
 * Nb Failed Jobs: 0
 * Nb Deployments: 140
 * Nb Failed Deployments: 0
 * Nb StatefulSets: 27
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 71
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 5
 * List of Failed Helms: [
   - onap-uui
   - onap-vfc
   - onap-vid
   - onap-vnfsdk
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-12-02 09:44:43,678 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='vid.onap', port=8443): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc72c57f7d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='refrepo.onap', port=8703): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc72c5488d0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 33 passed, 10 failed
43 tests total, 33 passed, 10 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-12-02 09:50:28,801 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-12-02 09:43:32,889 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
09:54:34,645: Running (INFO)
basic_network: PASS (07:56)
basic_cnf: PASS (10:03)
pnf-registrate: FAIL (06:16)
hv-ves: PASS (00:36)
5gbulkpm: PASS (07:24)

************************************************************
************************************************************
********************** Security tests **********************
Security tests not executed

____________________________________________________________

Patch-set: 2