Update patch set 2
Patch Set 2: Code-Review+1

Healthcheck full report is empty but healthcheck small has been run

SDC healthcheck PASS

------------------------------------------------------------------------

Basic A&AI Health Check                                  | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff5658fc1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
-----------------------------------------------------------------
Basic AAF Health Check                                   | PASS |
-----------------------------------------------------------------
Basic AAF SMS Health Check                               | PASS |
-----------------------------------------------------------------
Basic APPC Health Check                                  | PASS |
-----------------------------------------------------------------
Basic CLI Health Check                                   | PASS |
-----------------------------------------------------------------
Basic DMAAP Message Router Health Check                  | PASS |
-----------------------------------------------------------------
Basic External API NBI Health Check                      | PASS |
-----------------------------------------------------------------
Basic Log Elasticsearch Health Check                     | PASS |
-----------------------------------------------------------------
Basic Log Kibana Health Check                            | PASS |
-----------------------------------------------------------------
Basic Log Logstash Health Check                          | PASS |
-----------------------------------------------------------------
Basic Microservice Bus Health Check                      | PASS |
-----------------------------------------------------------------
Basic Multicloud API Health Check                        | FAIL |
502 != 200
-----------------------------------------------------------------
Basic Multicloud-ocata API Health Check                  | FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic Multicloud-pike API Health Check                   | PASS |
-----------------------------------------------------------------
Basic Multicloud-thinkcloud API Health Check             | FAIL |
502 != 200
-----------------------------------------------------------------
Basic Portal Health Check                                | FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic SDC Health Check                                   | PASS |
-----------------------------------------------------------------
Basic SDNC Health Check                                  | FAIL |
Resolving variable '${resp.json()['output']['response-code']}' failed: ValueError: No JSON object could be decoded
-----------------------------------------------------------------
Basic SO Health Check                                    | FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic VID Health Check                                   | PASS |
-----------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
20 critical tests, 13 passed, 7 failed

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1