Update patch set 2
Patch Set 2: Code-Review-1

We are trying to use new charts and we are not able to run new images, I tried to run aaf_cm manually and found below errors (I had to create the log file manually otherwise default image fails by saying log file does not exist):

root@dev1-aaf-cm-5658c7d6fc-mrx5s:/# mkdir -p  /opt/app/osaaf/logs/cm/
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/# /opt/app/aaf/cm/bin/cm >> /opt/app/osaaf/logs/cm/stdout`date -I` 2>> /opt/app/osaaf/logs/cm/stderr`date -I`
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/#
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/# /opt/app/aaf/cm/bin/cm
org.onap.aaf.misc.env.APIException: java.io.IOException: Neither File: /opt/app/osaaf/etc/org.osaaf.log4j.props nor resource on Classpath org.osaaf.log4j.props exist
        at org.onap.aaf.auth.server.Log4JLogIt.<init>(Log4JLogIt.java:79)
        at org.onap.aaf.auth.cm.AAF_CM.main(AAF_CM.java:231)
Caused by: java.io.IOException: Neither File: /opt/app/osaaf/etc/org.osaaf.log4j.props nor resource on Classpath org.osaaf.log4j.props exist
        at org.onap.aaf.misc.env.log4j.LogFileNamer.configure(LogFileNamer.java:82)
        at org.onap.aaf.auth.server.Log4JLogIt.<init>(Log4JLogIt.java:77)
        ... 1 more
root@dev1-aaf-cm-5658c7d6fc-mrx5s:/# ls -ltr /opt/app/osaaf/etc/org.osaaf.log4j.props
ls: cannot access '/opt/app/osaaf/etc/org.osaaf.log4j.props': No such file or directory

Patch-set: 2