Update patch set 34
Patch Set 34:

Gitlab Orange 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//115482-34/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 9
 * List of Failed Jobs: [
   - onap-dmaap-bc-dmaap-provisioning
   - onap-ejbca-config-config-job
   - onap-modeling-etsicatalog-config-job
   - onap-nbi-config-config-job
   - onap-nengdb-init-config-job
   - onap-netbox-app-provisioning
   - onap-sdnc-dbinit-job
   - onap-so-mariadb-config-job
   - onap-vid-mariadb-init-config-job]
 * Nb Deployments: 154
 * Nb Failed Deployments: 23
 * List of Failed Deployments: [
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-ejbca
   - onap-modeling-etsicatalog
   - onap-nbi
   - onap-netbox-app
   - onap-network-name-gen
   - onap-oom-cert-service
   - onap-sdnc-ansible-server
   - onap-sdnc-dgbuilder
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-sdnc-web
   - onap-so
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-cnf-adapter
   - onap-so-nssmf-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-vfc-adapter
   - onap-vid]
 * Nb StatefulSets: 27
 * Nb Failed StatefulSets: 4
 * List of Failed StatefulSets: [
   - onap-dmaap-dr-db
   - onap-dmaap-dr-node
   - onap-mariadb-galera
   - onap-sdnc]
 * Nb Persistent Volume Claims: 73
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 3
 * List of Failed Helms: [
   - onap-sdnc
   - onap-so
   - onap-aai]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-12-13 20:14:16,103 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-dr-node.onap', port=8443): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac9a1790>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac90e510>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | FAIL |
ConnectionError: HTTPSConnectionPool(host='nbi.onap', port=8443): Max retries exceeded with url: /nbi/api/v4/status?fullStatus=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac9230d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | FAIL |
No keyword with name 'Run Undeploy Policy' found. Did you mean:
    policy_interface.Undeploy Policy
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac92cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/config/GENERIC-RESOURCE-API:services/service/GRSIdummy123 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac8b2c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08ac8b2710>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='vid.onap', port=8443): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f08ac80a810>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 34 passed, 9 failed
43 tests total, 34 passed, 9 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-12-13 20:21:47,691 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
FAIL != PASS

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-12-13 20:12:47,703 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
basic_vm: FAIL (16:56)
basic_network: FAIL (15:23)
cat: ./public/115482-34/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (08:13)
hv-ves: PASS (00:50)
5gbulkpm: FAIL (13:29)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/115482-34/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (08:11)
kube_hunter: PASS (00:20)
root_pods: PASS (03:45)
unlimitted_pods: PASS (00:56)

--------> FOCUS on CIS errors
cat: ./public/115482-34/security/cis_kubernetes/cis_kubernetes.log: No such file or directory

____________________________________________________________

Patch-set: 34