Update patch set 14
Patch Set 14:

Gitlab Azure AKS 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//135759-14/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s NOT executed
--------> onap-helm
 * Nb Helms: 29
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2023-08-29 21:33:26,288 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='aai.onap', port=80): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfb53610>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
ConnectionError: HTTPConnectionPool(host='aai.onap', port=80): Max retries exceeded with url: /aai/v19/service-design-and-creation/models/model/AAI-HealthCheck-Dummy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfb81d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa9c850>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='nbi.onap', port=8080): Max retries exceeded with url: /nbi/api/v4/status?fullStatus=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfab2cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa45a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='policy-pap.onap', port=6969): Max retries exceeded with url: /policy/pap/v1/components/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfab2190>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | FAIL |
ConnectionError: HTTPConnectionPool(host='policy-api.onap', port=6969): Max retries exceeded with url: /policy/api/v1/policytypes/onap.policies.controlloop.operational.common.Drools/versions/1.0.0/policies/operational.modifyconfig/versions/1.0.0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfc24790>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfb3b250>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-onboarding-be.onap', port=8081): Max retries exceeded with url: /onboarding-api/v1.0/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfba1d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa71910>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/config/GENERIC-RESOURCE-API:services/service/GRSIdummy123 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa06490>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa2b710>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='vfc-nslcm.onap', port=8403): Max retries exceeded with url: /api/nslcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bf9cfd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='vfc-vnflcm.onap', port=8801): Max retries exceeded with url: /api/vnflcm/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bf9c36d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='vfc-vnfmgr.onap', port=8803): Max retries exceeded with url: /api/vnfmgr/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bf9e45d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='vfc-vnfres.onap', port=8802): Max retries exceeded with url: /api/vnfres/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bf9eac90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Modeling Parser API Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='modeling-etsicatalog.onap', port=8806): Max retries exceeded with url: /api/parser/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa12b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4bfa01650>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
33 critical tests, 14 passed, 19 failed
33 tests total, 14 passed, 19 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | FAIL |
--------> CMPv2 tests NOT executed
--------> DCAEMOD tests NOT executed
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: FAIL (00:05)
--------> CDS tests NOT executed

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | FAIL |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | FAIL |
--------> basic_vm tests
basic_vm: FAIL (00:10)
--------> basic_network tests
basic_network: FAIL (00:10)
--------> basic_cnf tests NOT executed
--------> basic_vm_macro tests
basic_vm_macro: FAIL (00:05)
--------> basic_clamp tests NOT executed
--------> pnf_macro tests
pnf_macro: FAIL (00:05)
--------> cds_resource_resolution tests
cds_resource_resolution: FAIL (00:05)
--------> basic_cnf_macro tests
basic_cnf_macro: FAIL (00:05)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests
nonssl_endpoints: PASS (00:00)
--------> jdpw_ports tests NOT executed
--------> kube_hunter tests
kube_hunter: FAIL (00:00)
--------> root_pods tests
root_pods: PASS (01:30)
--------> unlimitted_pods tests
unlimitted_pods: PASS (00:24)

____________________________________________________________

Patch-set: 14