Update patch set 27
Patch Set 27:

Gitlab Azure 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//118295-27/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 1
 * List of Failed Jobs: [
   - onap-aai-traversal-update-query-data]
 * Nb Deployments: 147
 * Nb Failed Deployments: 4
 * List of Failed Deployments: [
   - onap-aai
   - onap-aai-graphadmin
   - onap-aai-sparky-be
   - onap-dcae-dashboard]
 * Nb StatefulSets: 23
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 62
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 36
 * Nb Failed Helms: 0

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-11-11 23:11:26,106 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56cd24e410>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v19/service-design-and-creation/models/model/AAI-HealthCheck-Dummy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56ccd663d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
40 critical tests, 37 passed, 3 failed
40 tests total, 37 passed, 3 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | FAIL |
--------> CMPv2 tests
Deploying VES Client :: This test case deploys VES Client with "en... | PASS |
Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
Send registration request to CMPv2 VES :: This test case triggers ... | FAIL |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
Send registration request to VES without CMPv2 certificate :: This... | PASS |
Cmpv2 :: CMPv2 Usecase functionality                                  | FAIL |
--------> DCAEMOD tests
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (01:38)
--------> CDS tests
basic_cds: PASS (00:10)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | FAIL |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
--------> basic_vm tests
basic_vm: FAIL (04:36)
--------> basic_network tests
basic_network: FAIL (04:34)
--------> basic_cnf tests
basic_cnf: FAIL (04:37)
--------> basic_vm_macro tests
basic_vm_macro: FAIL (04:45)
--------> basic_clamp tests
basic_clamp: PASS (09:12)
--------> pnf_macro tests
pnf_macro: FAIL (04:33)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (00:43)
--------> jdpw_ports tests
jdpw_ports: PASS (04:37)
--------> kube_hunter tests
kube_hunter: FAIL (00:00)
--------> root_pods tests
root_pods: FAIL (02:04)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (00:49)

____________________________________________________________

Patch-set: 27