Update patch set 18
Patch Set 18:

git merge
<resolve review comments>
git add .
git commit --amend --no-edit
git push origin HEAD:refs/for/master

I get an error by git push. Error message is referencing to another commit.
Do you have an idea how t reolve this?

Thx!

Details:
~/workspace/oom_SDNC-1165$ git push origin HEAD:refs/for/master
Counting objects: 303, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (247/247), done.
Writing objects: 100% (303/303), 98.20 KiB | 9.82 MiB/s, done.
Total 303 (delta 217), reused 105 (delta 50)
remote: Resolving deltas: 100% (217/217)
remote: Processing changes: refs: 1, done    
remote: commit efbbb30: warning: subject >50 characters; use shorter first paragraph
remote: commit f2de82a: warning: subject >50 characters; use shorter first paragraph
To ssh://gerrit.onap.org:29418/oom
 ! [remote rejected]   HEAD -> refs/for/master (commit dec08be: not Signed-off-by author/committer/uploader in message footer)
error: failed to push some refs to 'ssh://demskeq8@gerrit.onap.org:29418/oom'

commit dec08be:
commit dec08be74ae954dabff5ab97a84e9fb163b30728
Author: mrichomme <morgan.richomme@orange.com>
Date:   Fri Jul 10 11:04:10 2020 +0200

    Update git submodules
    
    * Update kubernetes/robot from branch 'master'
      to 44a38a594677ca38c4eea288908ebf503ad91b4e
      - Bump 1.6.4 version for Frankfurt maintenance release
    
        This new version includes minor fixes for ue case support
    
        Issue-ID: INT-1652
    
        Signed-off-by: mrichomme <morgan.richomme@orange.com>
        Change-Id: I773d78906c5b32678e58eafe825ba12059ff52cf

Patch-set: 18