Update patch set 15
Patch Set 15:

There is a conflict now on port 30258 (see https://gerrit.onap.org/r/#/c/64545/ - 
give clamp port 58 from log - fix conflict)

Release "aaa" does not exist. Installing it now.
Error: release aaa failed: Service "so" is invalid: spec.ports[0].nodePort: Invalid value: 30258: provided port is already allocated

# grep -r 58 | grep nodePort
so/values.yaml:    nodePort: 58
clamp/values.yaml:  nodePort2: 58

Patch-set: 15
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0