Update patch set 1
Patch Set 1: Verified-1

[multicloud]
make[1]: Entering directory '/root/onap/master/oom/kubernetes'
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ?Happy Helming!?
Saving 1 charts
Downloading common from repo http://127.0.0.1:8879
Deleting outdated charts
==> Linting multicloud
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "multicloud/charts/multicloud-windriver/templates/NOTES.txt": template: multicloud/charts/multicloud-windriver/templates/NOTES.txt:2:14: executing "multicloud/charts/multicloud-windriver/templates/NOTES.txt" at <.Values.ingress.enab...>: can't evaluate field enabled in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed
Makefile:45: recipe for target 'lint-multicloud' failed
make[1]: *** [lint-multicloud] Error 1
make[1]: Leaving directory '/root/onap/master/oom/kubernetes'
Makefile:35: recipe for target 'multicloud' failed
make: *** [multicloud] Error 2

Patch-set: 1
Label: Verified=-1