Update patch set 1
Patch Set 1:

Gitlab Orange 2: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 218
 * Nb Failed Pods: 37
 * List of Failed Pods: [
   - onap-clamp-clamp-dash-logstash-564978f944-g26n2
   - onap-contrib-netbox-app-64ddd5494d-vwsg8
   - onap-dcaegen2-dcae-deployment-handler-68744f9448-mhvp9
   - onap-dcaegen2-dcae-policy-handler-d5f8d8cb9-m85fn
   - onap-dcaegen2-dcae-redis-5
   - onap-dcaegen2-dcae-servicechange-handler-65d6d9dc99-ts6tf
   - onap-dmaap-message-router-mirrormaker-5d4c9fc84c-mn4hd
   - onap-policy-policy-api-794fc87f89-jz7vx
   - onap-policy-policy-pap-578c574d77-5mbwd
   - onap-policy-policy-xacml-pdp-688dbbdbc9-j8dqv
   - onap-pomba-pomba-kibana-55c4cd5799-x5nx7
   - onap-sdc-sdc-be-95fcb5584-gpxff
   - onap-sdc-sdc-be-config-backend-qk89p
   - onap-sdc-sdc-cs-config-cassandra-4xg6r
   - onap-sdc-sdc-dcae-be-69846c79-gmxz9
   - onap-sdc-sdc-dcae-be-tools-7n5ml
   - onap-sdc-sdc-dcae-dt-565c85b48d-59j67
   - onap-sdc-sdc-dcae-fe-756fccc7b-xdrp2
   - onap-sdc-sdc-dcae-tosca-lab-7dbcbbc8cd-6c8sl
   - onap-sdc-sdc-fe-86df7b5f7b-k7dc2
   - onap-sdc-sdc-onboarding-be-6fb769dff9-tbbnq
   - onap-sdc-sdc-onboarding-be-cassandra-init-7mv79
   - onap-sdc-sdc-wfd-be-7fb7995699-x92f4
   - onap-sdc-sdc-wfd-be-workflow-init-97fkl
   - onap-sdc-sdc-wfd-fe-5658698dc8-qprqb
   - onap-sdnc-blueprints-processor-76495445f6-bhxtm
   - onap-sdnc-controller-blueprints-74d657954b-c6cdw
   - onap-sdnc-sdnc-db-0
   - onap-sdnc-sdnc-portal-7df5d44f56-t85kv
   - onap-sdnc-sdnc-ueb-listener-75d98567df-pc7zf
   - onap-so-so-catalog-db-adapter-5bd69d4ddc-nvcq7
   - onap-so-so-openstack-adapter-555d64d4b7-6qk79
   - onap-so-so-request-db-adapter-56fd489f4f-cn8f5
   - onap-so-so-vfc-adapter-594868bdd4-259sw
   - onap-so-so-vnfm-adapter-6486b77447-q7j7m
   - onap-vfc-vfc-catalog-5df4dcffd6-z6nlm
   - onap-vfc-vfc-ems-driver-6cd4b7975c-sfvww
   - onap-vfc-vfc-vnflcm-65c6b8995b-p5mbc]
 * Deployment Duration Estimation (s): 60
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-10 20:05:39,775 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='appc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f897195d610>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8972990450>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f89718b2c10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8971725f50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8971736910>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | FAIL |
ConnectionError: HTTPSConnectionPool(host='pomba-kibana.onap', port=5601): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f89716fec50>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f897170a2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8971756890>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f897164c6d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 20 passed, 38 failed
58 tests total, 20 passed, 38 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1