Update patch set 2
Patch Set 2: Code-Review+1

Gating results

******** Kubernetes Results ********
 * Nb Pods: 194
 * Nb Failed Pods: 8
 * List of Failed Pods: [
   - onap-appc-appc-ansible-server-598558f644-kznhs
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-7mx76
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-7mdfw
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-bpvld
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-fghtk
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-nr76g
   - onap-sdnc-blueprints-processor-6d8c669cb-5c6st
   - onap-sdnc-controller-blueprints-64b8cf4c7c-54k5p]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-robot
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-03-14 13:24:07,332 - xtesting.core.robotframework - INFO - 
======================================================================
Health-Check :: Testing ecomp components are available via calls.             
======================================================================
Basic A&AI Health Check                                    | PASS |
----------------------------------------------------------------------
Basic AAF Health Check                                     | PASS |
----------------------------------------------------------------------
Basic AAF SMS Health Check                                 | PASS |
----------------------------------------------------------------------
Basic APPC Health Check                                    | PASS |
----------------------------------------------------------------------
Basic CLI Health Check                                     | PASS |
----------------------------------------------------------------------
Basic CLAMP Health Check                                   | PASS |
----------------------------------------------------------------------
Basic DCAE Health Check                                    | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                       | PASS |
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                    | PASS |
----------------------------------------------------------------------
Basic External API NBI Health Check                        | PASS |
----------------------------------------------------------------------
Basic Log Elasticsearch Health Check                       | PASS |
----------------------------------------------------------------------
Basic Log Kibana Health Check                              | PASS |
----------------------------------------------------------------------
Basic Log Logstash Health Check                            | PASS |
----------------------------------------------------------------------
Basic Microservice Bus Health Check                        | PASS |
----------------------------------------------------------------------
Basic Multicloud API Health Check                          | PASS |
----------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                    | PASS |
----------------------------------------------------------------------
Basic Multicloud-pike API Health Check                     | PASS |
----------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check           | PASS |
----------------------------------------------------------------------
Basic Multicloud-vio API Health Check                      | PASS |
----------------------------------------------------------------------
Basic OOF-Homing Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b85d8a210>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                            | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b85d3e5d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b85d3ee50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Policy Health Check                                | PASS |
----------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check             | PASS |
----------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check             | PASS |
----------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                  | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                     | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                    | PASS |
----------------------------------------------------------------------
Basic SO Health Check                                      | PASS |
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC catalog API Health Check                         | PASS |
----------------------------------------------------------------------
Basic VFC emsdriver API Health Check                       | PASS |
----------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                     | PASS |
----------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                | PASS |
----------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                  | PASS |
----------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                   | PASS |
----------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                 | PASS |
----------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                   | PASS |
----------------------------------------------------------------------
Basic VFC nslcm API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC resmgr API Health Check                          | PASS |
----------------------------------------------------------------------
Basic VFC vnflcm API Health Check                          | PASS |
----------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                          | PASS |
----------------------------------------------------------------------
Basic VFC vnfres API Health Check                          | PASS |
----------------------------------------------------------------------
Basic VFC workflow API Health Check                        | PASS |
----------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                   | PASS |
----------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                   | PASS |
----------------------------------------------------------------------
Basic VID Health Check                                     | FAIL |
Resolving variable '${resp.json()['detailedMsg']}' failed: KeyError: 'detailedMsg'
----------------------------------------------------------------------
Basic VNFSDK Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b85bb8a10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check               | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check             | FAIL |
502 != 200
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 43 passed, 9 failed
52 tests total, 43 passed, 9 failed
======================================================================

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1