Update patch set 1
Patch Set 1:

Robot healthcheck failed on gating:

Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='appc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe78b62d4d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

traces available: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/238088463/artifacts/download

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0