Update patch set 9
Patch Set 9:

> Patch Set 9: Code-Review-1
> 
> Looks like we have a concrete problem comming from AAI image change
> 
> 2022-04-11T03:04:23.387Z|b959d48c-eff8-4860-a7b9-e4e847d9a5bb|TopicSubscriptionManager|InventoryDelete|SO.OPENSTACK_ADAPTER|AAI|https://aai.onap:8443/aai/v24/cloud-infrastructure/cloud-regions/cloud-region/basicvm-cloud-owner/RegionOne/tenants/tenant/ada7f5c9de4e4c4c96b72dd357af72de/vservers/vserver/e956d3fa-d10c-491f-b6e2-b3b0df410fc1?depth=2|INFO|400|Bad Request|InvokeReturn
> 2022-04-11T03:04:23.388Z|b959d48c-eff8-4860-a7b9-e4e847d9a5bb|TopicSubscriptionManager|InventoryDelete|SO.OPENSTACK_ADAPTER|||DEBUG|500||Failed to commit delete heatbridge data transaction with error: javax.ws.rs.BadRequestException: Error calling A&AI. Request-Id=b959d48c-eff8-4860-a7b9-e4e847d9a5bb Invalid input performing GET on cloud-infrastructure/cloud-regions/cloud-region/basicvm-cloud-owner/RegionOne/tenants/tenant/ada7f5c9de4e4c4c96b72dd357af72de/vservers/vserver/e956d3fa-d10c-491f-b6e2-b3b0df410fc1 (msg=Required Edge-property not found in input data:org.onap.aai.edges.exceptions.EdgeRuleNotFoundException: No rule found for EdgeRuleQuery with filter params node type: l-interface, node type: lcmp-unreachable, type: TREE, isPrivate: false.) (ec=ERR.5.4.6107)
> 2022-04-11T03:04:23.388Z|b959d48c-eff8-4860-a7b9-e4e847d9a5bb|TopicSubscriptionManager|InventoryDelete|SO.OPENSTACK_ADAPTER|||ERROR|500||Error during inventory of stack
> org.onap.so.heatbridge.HeatBridgeException: Failed to commit delete heatbridge data transaction
> 	at org.onap.so.heatbridge.HeatBridgeImpl.deleteVfModuleData(HeatBridgeImpl.java:816)
> 	at org.onap.so.adapters.tasks.inventory.DeleteAAIInventory.heatbridge(DeleteAAIInventory.java:64)
> 	at org.onap.so.adapters.tasks.inventory.DeleteInventoryTask.executeExternalTask(DeleteInventoryTask.java:68)
> 	at org.camunda.bpm.client.topic.impl.TopicSubscriptionManager.handleExternalTask(TopicSubscriptionManager.java:152)
> 	at org.camunda.bpm.client.topic.impl.TopicSubscriptionManager.lambda$acquire$0(TopicSubscriptionManager.java:108)
> 	at java.base/java.util.Arrays$ArrayList.forEach(Unknown Source)
> 	at org.camunda.bpm.client.topic.impl.TopicSubscriptionManager.acquire(TopicSubscriptionManager.java:103)
> 	at org.camunda.bpm.client.topic.impl.TopicSubscriptionManager.run(TopicSubscriptionManager.java:87)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: javax.ws.rs.BadRequestException: Error calling A&AI. Request-Id=b959d48c-eff8-4860-a7b9-e4e847d9a5bb Invalid input performing GET on cloud-infrastructure/cloud-regions/cloud-region/basicvm-cloud-owner/RegionOne/tenants/tenant/ada7f5c9de4e4c4c96b72dd357af72de/vservers/vserver/e956d3fa-d10c-491f-b6e2-b3b0df410fc1 (msg=Required Edge-property not found in input data:org.onap.aai.edges.exceptions.EdgeRuleNotFoundException: No rule found for EdgeRuleQuery with filter params node type: l-interface, node type: lcmp-unreachable, type: TREE, isPrivate: false.) (ec=ERR.5.4.6107)
> 	at org.onap.so.client.ResponseExceptionMapper.map(ResponseExceptionMapper.java:65)
> 	at org.onap.so.client.RestRequest.get(RestRequest.java:77)
> 	at org.onap.so.client.RestClient.buildRequest(RestClient.java:326)
> 	at org.onap.so.client.RestClient.lambda$method$4(RestClient.java:322)
> 	at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:283)
> 	at net.jodah.failsafe.internal.executor.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:67)
> 	at net.jodah.failsafe.Execution.executeSync(Execution.java:117)
> 	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:319)
> 	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:71)
> 	at org.onap.so.client.RestClient.method(RestClient.java:322)
> 	at org.onap.so.client.RestClient.get(RestClient.java:281)
> 	at org.onap.aaiclient.client.graphinventory.GraphInventoryResourcesClient.get(GraphInventoryResourcesClient.java:334)
> 	at org.onap.so.heatbridge.HeatBridgeImpl.getPserverToPciIdMap(HeatBridgeImpl.java:870)
> 	at org.onap.so.heatbridge.HeatBridgeImpl.createTransactionToDeleteSriovPfFromPserver(HeatBridgeImpl.java:836)
> 	at org.onap.so.heatbridge.HeatBridgeImpl.deleteVfModuleData(HeatBridgeImpl.java:796)
> 	... 8 common frames omitted

Are all the calls being made being done to v24? I would expect they would still work but if there is a mix of v26 and v24 calls it may be why you are getting this issue. I would suggest if needing to interact with this object SO should modify it to use icmp-unreachable instead of lcmp-unreachable

Patch-set: 9