Update patch set 1
Patch Set 1: Code-Review-1

Release "onap-contrib" does not exist. Installing it now.
Error: release onap-contrib failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|y":"750mi"}},"volume|..., bigger context ...|:"1.5Gi"},"requests":{"cpu":"10m","memory":"750mi"}},"volumeMounts":[{"mountPath":"/opt/primekey/scr|...

Patch-set: 1
Reviewer: Gerrit User 4965 <4965@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1