Update patch set 1
Patch Set 1: Code-Review+1

Gating results

MSB tests OK

******** Kubernetes Results ********
 * Nb Pods: 183
 * Nb Failed Pods: 29
 * List of Failed Pods: [
   - onap-aai-aai-6d9d76f6bd-cvlmw
   - onap-aai-aai-champ-7f97f98976-xpxnz
   - onap-aai-aai-graphadmin-c79fb7fcf-jg7ls
   - onap-aai-aai-graphadmin-create-db-schema-swkzp
   - onap-aai-aai-resources-557c6f9d78-4d5fr
   - onap-aai-aai-sparky-be-5ff8689c54-hvtwv
   - onap-aai-aai-spike-77ccc5bf78-zn8f2
   - onap-aai-aai-traversal-7fb5558d98-97h2m
   - onap-aai-aai-traversal-update-query-data-znm5t
   - onap-contrib-netbox-app-695fd89fd-sqxjv
   - onap-contrib-netbox-app-provisioning-ggtsp
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-2ghwn
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-9jqlc
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-6qvtx
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-j42kh
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-p7zxg
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-2kcb2
   - onap-nbi-nbi-6d6ccb4cb5-wpxc5
   - onap-pomba-pomba-contextaggregator-865fd64646-gv6jw
   - onap-sdc-sdc-dcae-be-tools-lnnt6
   - onap-sdc-sdc-dcae-dt-7f49b64bd8-pxlg2
   - onap-sdc-sdc-dcae-fe-5b7fdcdc68-7l72j
   - onap-sdc-sdc-dcae-tosca-lab-74d894f9c4-r6c2f
   - onap-sdnc-blueprints-processor-6d8c669cb-flzhd
   - onap-sdnc-controller-blueprints-64b8cf4c7c-zgnkb
   - onap-sdnc-sdnc-ansible-server-64f864fd54-6qhkp
   - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-9vzsp
   - onap-sdnc-sdnc-portal-848d54f7c4-f7s8t
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-l6ksd]
 * Deployment Duration Estimation (s): 1320
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]

healthcheck
************
Basic A&AI Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic AAF Health Check                                        | PASS |
----------------------------------------------------------------------
Basic AAF SMS Health Check                                    | PASS |
----------------------------------------------------------------------
Basic APPC Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic CLI Health Check                                        | PASS |
----------------------------------------------------------------------
Basic CLAMP Health Check                                      | PASS |
----------------------------------------------------------------------
Basic DCAE Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                          | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf779650>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                       | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfe0e617d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic External API NBI Health Check                           | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic Log Elasticsearch Health Check                          | PASS |
----------------------------------------------------------------------
Basic Log Kibana Health Check                                 | PASS |
----------------------------------------------------------------------
Basic Log Logstash Health Check                               | PASS |
----------------------------------------------------------------------
Basic Microservice Bus Health Check                           | PASS |
----------------------------------------------------------------------
Basic Multicloud API Health Check                             | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                       | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-pike API Health Check                        | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                   | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check              | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-vio API Health Check                         | FAIL |
502 != 200
----------------------------------------------------------------------
Basic OOF-Homing Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf6d1b50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf8117d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf76d2d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Policy Health Check                                     | PASS |
----------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                  | PASS |
----------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                  | PASS |
----------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check    | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                     | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                        | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic SO Health Check                                         | PASS |
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                              | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC catalog API Health Check                            | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC emsdriver API Health Check                          | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                        | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                   | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                     | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                      | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                    | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                      | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC nslcm API Health Check                              | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC resmgr API Health Check                             | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC vnflcm API Health Check                             | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                             | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC vnfres API Health Check                             | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC workflow API Health Check                           | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                      | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                      | FAIL |
502 != 200
----------------------------------------------------------------------
Basic VID Health Check                                        | PASS |
----------------------------------------------------------------------
Basic VNFSDK Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf5af710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                 | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check               | FAIL |
502 != 200
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |

Patch-set: 1
Label: Code-Review=+1