Update patch set 2
Patch Set 2:

this patchest triggered the deployment + tests of an ONAP (using versions referenced in OOM (+ patchset code) - no overwtritting with integration manifest )

patchset 1

Deployment completed
some errors in the tests

K8s status at the end of the installation
onap-appc-appc-ansible-server-598558f644-vfqbh                 0/1       CrashLoopBackOff   13         1h
onap-dcaegen2-dcae-bootstrap-595d9f9594-5fhdp                  0/1       ImagePullBackOff   0          1h
onap-dcaegen2-dcae-healthcheck-6ffbc5fdc9-76sv8                0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-bus-controller-577d694c69-98sbc               0/1       ErrImagePull       0          1h
onap-dmaap-dmaap-dr-node-6c4bbd55dd-zthhd                      0/1       Init:0/1           6          1h
onap-dmaap-dmaap-dr-prov-666444477f-tsmh7                      0/1       ImagePullBackOff   0          1h
onap-oof-oof-has-data-c7788fc4d-msnlw                          0/1       Init:2/4           6          1h
onap-oof-oof-has-reservation-6cb9fd8b48-hxkd4                  0/1       Init:2/4           6          1h
onap-oof-oof-has-solver-54f46bbccc-djw5w                       0/1       Init:2/4           5          1h
onap-sdnc-controller-blueprints-6547954976-f7rk4               0/1       CrashLoopBackOff   16         1h
onap-sdnc-sdnc-ueb-listener-7587fb798c-j7n4r                   0/1       CrashLoopBackOff   15         1h

healthcheck
Basic DMAAP Data Router Health Check | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7dc0643110>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 2