Update patch set 11
Patch Set 11:

Gitlab Orange 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//118880-11/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 28
 * Nb Failed Jobs: 2
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
   - onap-oof-has-healthcheck]
 * Nb Deployments: 153
 * Nb Failed Deployments: 13
 * List of Failed Deployments: [
   - onap-aaf-sms
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-dashboard
   - onap-dcae-deployment-handler
   - onap-dcae-policy-handler
   - onap-oof
   - onap-oof-has-api
   - onap-oof-has-controller
   - onap-oof-has-data
   - onap-oof-has-reservation
   - onap-oof-has-solver
   - onap-policy-clamp-fe]
 * Nb StatefulSets: 27
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 77
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 36
 * Nb Failed Helms: 0

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-04-03 16:51:13,580 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
500 != 204
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f65447dc410>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='policy-clamp-fe.onap', port=2443): Max retries exceeded with url: /restservices/clds/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f65443de790>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6544387ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f65443a1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
46 critical tests, 40 passed, 6 failed
46 tests total, 40 passed, 6 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests
Deploying PNF Simulator :: This test case deploys PNF simulator wi... | FAIL |
Deploying VES collector with CMPv2 :: This test case deploys secon... | FAIL |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | FAIL |
Send registration request to CMPv2 VES :: This test case triggers ... | FAIL |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | FAIL |
Send registration request to VES without CMPv2 certificate :: This... | FAIL |
Cmpv2 :: CMPv2 Usecase functionality                                  | FAIL |
--------> DCAEMOD tests
Deploy DCAE Simple Application Without Config Map In Config Spec J... | FAIL |
Deploy DCAE Simple Application With Config Map In Config Spec Json... | FAIL |
Deploy DCAE Simple Application With Config Map In Config Spec Json... | FAIL |
Dcaemod                                                               | FAIL |
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (03:17)
--------> CDS tests
basic_cds: PASS (00:20)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
Setting Global Variables :: This test case checks suite if it is w... | PASS |
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | FAIL |
--------> basic_vm tests
basic_vm: PASS (10:14)
--------> basic_network tests
basic_network: PASS (07:02)
--------> basic_cnf tests
basic_cnf: FAIL (02:07)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> cis_kubernetes tests
cis_kubernetes: PASS (00:00)
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (01:05)
--------> jdpw_ports tests
jdpw_ports: PASS (07:32)
--------> kube_hunter tests
kube_hunter: PASS (00:06)
--------> root_pods tests
root_pods: FAIL (02:38)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (01:08)

____________________________________________________________

Patch-set: 11