Update patch set 1
Patch Set 1:

SDNC health check ok, other charts are not yet using common/elastic
release: "onap-sdnc" not found: but this is caused due to large sdnc chart. I have fixed this a couple of weeks ago, but meanwhile new functionality was added.
This should not prevent the merge.

Release "onap-sdnc" does not exist. Installing it now.
NAME:   onap-sdnc
Error: getting deployed release "onap-sdnc": release: "onap-sdnc" not found

Patch-set: 1
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 87 <87@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>