Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> (1 comment)
> 
> @guillaume, can you check this patch as it’s conflicting with your propositions?
> Thanks!

OK I can take care of rebasing it on top of mine if everybody agrees because they address partially the doc8 issue.

doc8 seems to pass the gate but it does not pass locally on my station even with this change
- see below.


$ git-review -d 124531
WARNING: Using global/system git-review config files (/etc/git-
review/git-review.conf) is deprecated and will be removed in a future
release
Downloading refs/changes/31/124531/2 from gerrit
Switched to branch "review/cedric_ollivier/124531"
$ rm -rf .tox/
$ tox -e doc8
doc8 create: /home/guillaume/git_ws/oom/.tox/doc8
doc8 installdeps: -r/home/guillaume/git_ws/oom/requirements.txt, -chttps://git.onap.org/doc/plain/etc/upper-constraints.os.txt, -chttps://git.onap.org/doc/plain/etc/upper-constraints.onap.txt
doc8 installed: alabaster==0.7.12,arrow==1.0.3,astroid==2.7.3,attrs==20.3.0,autopep8==1.5.7,Babel==2.9.0,blockdiag==2.0.1,certifi==2020.12.5,chardet==4.0.0,click==7.1.2,cycler==0.10.0,doc8==0.8.1,docutils==0.16,funcparserlib==1.0.0a0,future==0.18.2,gitlint==0.15.1,idna==2.10,imagesize==1.2.0,isort==5.9.3,Jinja2==2.11.3,jsonschema==3.2.0,kiwisolver==1.3.2,lazy-object-proxy==1.6.0,lfdocs-conf==0.7.7,MarkupSafe==1.1.1,matplotlib==3.4.3,mccabe==0.6.1,numpy==1.21.2,nwdiag==2.0.0,packaging==20.9,pbr==5.5.1,Pillow==8.1.2,platformdirs==2.4.0,pycodestyle==2.7.0,pyenchant==3.2.1,Pygments==2.8.1,pylint==2.10.2,pyparsing==2.4.7,pyrsistent==0.17.3,python-dateutil==2.8.1,pytz==2021.1,PyYAML==5.4.1,requests==2.25.1,requests-file==1.5.1,restructuredtext-lint==1.3.2,seqdiag==2.0.0,sh==1.14.1,six==1.15.0,snowballstemmer==2.1.0,Sphinx==4.2.0,sphinx-bootstrap-theme==0.8.0,sphinx-rtd-theme==1.0.0,sphinx-tabs==3.2.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-blockdiag==2.0.0,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-needs==0.5.6,sphinxcontrib-nwdiag==2.0.0,sphinxcontrib-plantuml==0.21,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-redoc==1.6.0,sphinxcontrib-seqdiag==2.0.0,sphinxcontrib-serializinghtml==1.1.5,sphinxcontrib-spelling==7.2.1,sphinxcontrib-swaggerdoc==0.1.7,stevedore==3.3.0,toml==0.10.0,urllib3==1.26.3,webcolors==1.11.1,wrapt==1.12.1
doc8 run-test-pre: PYTHONHASHSEED='4066990879'
doc8 run-test: commands[0] | doc8 docs/
Scanning...
Validating...
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:330: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:331: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:332: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:333: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:336: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:337: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:341: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:342: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:380: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:381: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:382: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:383: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:384: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:385: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:386: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:387: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:388: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:389: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:390: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:391: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:392: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:393: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:394: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:395: D001 Line too long
docs/_build/html/_sources/oom_setup_kubernetes_rancher.rst.txt:416: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:69: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:93: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:101: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:108: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:160: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:175: D001 Line too long
docs/_build/html/_sources/oom_quickstart_guide.rst.txt:214: D001 Line too long
docs/_build/html/_sources/release-notes.rst.txt:100: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:130: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:291: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:296: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:312: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:317: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:324: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:421: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:475: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:480: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:585: D001 Line too long
docs/_build/html/_sources/oom_developer_guide.rst.txt:590: D001 Line too long
docs/_build/html/_sources/oom_setup_paas.rst.txt:101: D001 Line too long
docs/_build/html/_sources/oom_setup_paas.rst.txt:103: D001 Line too long
docs/_build/html/_sources/oom_setup_paas.rst.txt:105: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:120: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:121: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:124: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:159: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:160: D001 Line too long
docs/_build/html/_sources/oom_setup_ingress_controller.rst.txt:161: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:134: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:161: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:175: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:183: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:201: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:207: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:317: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:397: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:399: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:403: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:440: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:448: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:459: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:564: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:565: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:566: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:567: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:568: D001 Line too long
docs/_build/html/_sources/oom_user_guide.rst.txt:585: D001 Line too long
========
Total files scanned = 41
Total files ignored = 0
Total accumulated errors = 72
Detailed error counts:
    - doc8.checks.CheckCarriageReturn = 0
    - doc8.checks.CheckIndentationNoTab = 0
    - doc8.checks.CheckMaxLineLength = 72
    - doc8.checks.CheckNewlineEndOfFile = 0
    - doc8.checks.CheckTrailingWhitespace = 0
    - doc8.checks.CheckValidity = 0
ERROR: InvocationError for command /home/guillaume/git_ws/oom/.tox/doc8/bin/doc8 docs/ (exited with code 1)
__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________
ERROR:   doc8: commands failed

Patch-set: 2
Reviewer: Gerrit User 3685 <3685@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>