Update patch set 6
Patch Set 6:

Gitlab Orange 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//114236-6/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 1
 * List of Failed Jobs: [
   - onap-sdc-be-config-backend]
 * Nb Deployments: 155
 * Nb Failed Deployments: 22
 * List of Failed Deployments: [
   - onap-cds-sdc-listener
   - onap-dcae-servicechange-handler
   - onap-oof-cmso-service
   - onap-sdc-be
   - onap-sdc-fe
   - onap-sdnc-ueb-listener
   - onap-so
   - onap-so-appc-orchestrator
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-cnf-adapter
   - onap-so-etsi-nfvo-ns-lcm
   - onap-so-monitoring
   - onap-so-nssmf-adapter
   - onap-so-oof-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-sdnc-adapter
   - onap-so-ve-vnfm-adapter
   - onap-so-vfc-adapter
   - onap-so-vnfm-adapter]
 * Nb StatefulSets: 29
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 78
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-11-04 13:37:13,078 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe3f6001810>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-11-04 13:36:44,168 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
13:41:41,702: Loading (INFO)
13:41:47,180: Running (INFO)
13:41:41,697: Loading (INFO)
13:41:45,747: /usr/lib/python3.8/site-packages/onaptests/configuration/basic_network_nomulticloud_settings.py:28: (WARNING)
13:41:47,178: Running (INFO)
cat: ./public/114236-6/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (00:53)
hv-ves: PASS (00:39)
5gbulkpm: PASS (07:20)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:02)
cat: ./public/114236-6/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (07:48)
kube_hunter: PASS (00:10)
root_pods: PASS (02:27)
unlimitted_pods: FAIL (00:41)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 6