Update patch set 2
Patch Set 2:

Install Casablanca:
helm deploy demo local/onap --version=3.0.0 --namespace onap --set global.pullPolicy=IfNotPresent --set so.enabled=true -f onap/resources/environments/disable-allcharts.yaml
 
kubectl get po -n onap -o wide                                                                                                                                  Fri Apr  5 04:17:13 2019

NAME                                             READY     STATUS    RESTARTS   AGE       IP              NODE        NOMINATED NODE
demo-so-so-64b7b95f7f-vrgg8                      1/1       Running   0          15m       10.42.8.14      new-k8s-1   <none>
demo-so-so-bpmn-infra-ff575b6f7-mld68            1/1       Running   0          15m       10.42.114.53    new-k8s-1   <none>
demo-so-so-catalog-db-adapter-84bf64b798-b6zc4   1/1       Running   0          15m       10.42.246.110   new-k8s-1   <none>
demo-so-so-mariadb-7ddfd57696-r9phm              1/1       Running   0          15m       10.42.11.248    new-k8s-1   <none>
demo-so-so-monitoring-74f4d4c6f9-49rv8           1/1       Running   0          15m       10.42.218.156   new-k8s-1   <none>
demo-so-so-openstack-adapter-77c4ffc496-lwms5    1/1       Running   0          15m       10.42.156.236   new-k8s-1   <none>
demo-so-so-request-db-adapter-6585cf6d5b-4k6c5   1/1       Running   0          15m       10.42.88.226    new-k8s-1   <none>
demo-so-so-sdc-controller-668557bf7b-gw5tb       1/1       Running   0          15m       10.42.173.91    new-k8s-1   <none>
demo-so-so-sdnc-adapter-588f87d8b7-m2hcc         1/1       Running   0          15m       10.42.153.113   new-k8s-1   <none>
demo-so-so-vfc-adapter-547d98f7c5-bbxvm          1/1       Running   0          15m       10.42.173.203   new-k8s-1   <none>

 
 
Upgrade to Dublin: 
helm deploy demo local/onap --version=4.0.0 --namespace onap --set global.pullPolicy=IfNotPresent --set so.enabled=true --set mariadb-galera.enabled=true --set so.global.migration.enabled=true --set so.global.migration.dbHost=so-mariadb --set so.global.migration.dbUser=root --set so.global.migration.dbPassword=password --verbose --set robot.enabled=true --timeout 1200
 
kubectl get po -n onap -o wide                                                                                                                                  Fri Apr  5 04:27:01 2019

NAME                                             READY     STATUS      RESTARTS   AGE       IP              NODE        NOMINATED NODE
demo-mariadb-galera-mariadb-galera-0             1/1       Running     0          8m        10.42.214.229   new-k8s-1   <none>
demo-mariadb-galera-mariadb-galera-1             1/1       Running     0          7m        10.42.211.27    new-k8s-1   <none>
demo-mariadb-galera-mariadb-galera-2             1/1       Running     0          6m        10.42.121.242   new-k8s-1   <none>
demo-robot-robot-785f67844-b852f                 1/1       Running     0          8m        10.42.228.253   new-k8s-1   <none>
demo-so-so-77b79b9d65-jl7sk                      1/1       Running     0          7m        10.42.75.239    new-k8s-1   <none>
demo-so-so-bpmn-infra-867fb96f55-f8bl9           1/1       Running     0          7m        10.42.139.103   new-k8s-1   <none>
demo-so-so-catalog-db-adapter-66f54dd85b-2c27v   1/1       Running     0          7m        10.42.52.131    new-k8s-1   <none>
demo-so-so-mariadb-backup-hqcrp                  0/1       Completed   0          8m        10.42.173.230   new-k8s-1   <none>
demo-so-so-mariadb-config-job-2xbtb              0/1       Completed   0          7m        10.42.118.112   new-k8s-1   <none>
demo-so-so-monitoring-74f4d4c6f9-49rv8           1/1       Running     0          25m       10.42.218.156   new-k8s-1   <none>
demo-so-so-openstack-adapter-55564686c4-47lzc    1/1       Running     0          7m        10.42.114.24    new-k8s-1   <none>
demo-so-so-request-db-adapter-66888658f8-x77vm   1/1       Running     0          7m        10.42.55.108    new-k8s-1   <none>
demo-so-so-sdc-controller-5888fd58fd-ns4f4       1/1       Running     0          7m        10.42.65.143    new-k8s-1   <none>
demo-so-so-sdnc-adapter-588f87d8b7-m2hcc         1/1       Running     0          25m       10.42.153.113   new-k8s-1   <none>
demo-so-so-vfc-adapter-5fdb746665-j5k9f          1/1       Running     0          7m        10.42.228.117   new-k8s-1   <none>
demo-so-so-vnfm-adapter-656f7fdcc6-t952t         1/1       Running     0          7m        10.42.149.105   new-k8s-1   <none>

 
root@new-k8s-1:~/Mahendra/OOM_Dublin/OOM_SO_RollingUpgrade/OOM_SO_RollingUpgrade/oom/kubernetes/robot# ./ete-k8s.sh onap health
++ export NAMESPACE=onap
++ NAMESPACE=onap
+++ kubectl --namespace onap get pods
+++ grep robot
+++ sed 's/ .*//'
++ POD=demo-robot-robot-785f67844-b852f
++ TAGS='-i health'
++ ETEHOME=/var/opt/ONAP
+++ kubectl --namespace onap exec demo-robot-robot-785f67844-b852f -- bash -c 'ls -1q /share/logs/ | wc -l'
++ export GLOBAL_BUILD_NUMBER=0
++ GLOBAL_BUILD_NUMBER=0
+++ printf %04d 0
++ OUTPUT_FOLDER=0000_ete_health
++ DISPLAY_NUM=90
++ VARIABLEFILES='-V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py'
++ VARIABLES='-v GLOBAL_BUILD_NUMBER:354'
++ kubectl --namespace onap exec demo-robot-robot-785f67844-b852f -- /var/opt/ONAP/runTags.sh -V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py -v GLOBAL_BUILD_NUMBER:354 -d /share/logs/0000_ete_health -i health --display 90
Starting Xvfb on display :90 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
Testsuites

Basic SDNC Health Check                                               [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b39cad0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b39ccd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b39ced0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b3280d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b359250>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /iui/usecaseui/
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd84b359450>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /iui/usecaseui/



Fresh Dublin Install:
helm deploy demo local/onap --version=4.0.0 --namespace onap --set global.pullPolicy=IfNotPresent --set so.enabled=true --set mariadb-galera.enabled=true --verbose --set robot.enabled=true --timeout 1200

kubectl get po -n onap -o wide                                                                                                                                  Fri Apr  5 04:44:50 2019

NAME                                             READY     STATUS      RESTARTS   AGE       IP              NODE        NOMINATED NODE
demo-mariadb-galera-mariadb-galera-0             1/1       Running     0          7m        10.42.83.88     new-k8s-1   <none>
demo-mariadb-galera-mariadb-galera-1             1/1       Running     0          7m        10.42.77.255    new-k8s-1   <none>
demo-mariadb-galera-mariadb-galera-2             1/1       Running     0          6m        10.42.138.191   new-k8s-1   <none>
demo-robot-robot-785f67844-gnkk2                 1/1       Running     0          7m        10.42.2.127     new-k8s-1   <none>
demo-so-so-77b79b9d65-fwwj7                      1/1       Running     0          7m        10.42.196.116   new-k8s-1   <none>
demo-so-so-bpmn-infra-867fb96f55-gvdtk           1/1       Running     0          7m        10.42.70.96     new-k8s-1   <none>
demo-so-so-catalog-db-adapter-66f54dd85b-bhb2q   1/1       Running     0          7m        10.42.121.105   new-k8s-1   <none>
demo-so-so-mariadb-config-job-fvn42              0/1       Completed   0          7m        10.42.206.26    new-k8s-1   <none>
demo-so-so-monitoring-74f4d4c6f9-wlblh           1/1       Running     0          7m        10.42.113.141   new-k8s-1   <none>
demo-so-so-openstack-adapter-55564686c4-lhpmm    1/1       Running     1          7m        10.42.3.128     new-k8s-1   <none>
demo-so-so-request-db-adapter-66888658f8-9bffs   1/1       Running     0          7m        10.42.116.200   new-k8s-1   <none>
demo-so-so-sdc-controller-5888fd58fd-f74fv       1/1       Running     0          7m        10.42.253.126   new-k8s-1   <none>
demo-so-so-sdnc-adapter-588f87d8b7-9qtkd         1/1       Running     0          7m        10.42.69.215    new-k8s-1   <none>
demo-so-so-vfc-adapter-5fdb746665-6ffng          1/1       Running     0          7m        10.42.35.121    new-k8s-1   <none>
demo-so-so-vnfm-adapter-656f7fdcc6-wx9wc         1/1       Running     0          7m        10.42.6.209     new-k8s-1   <none>


root@new-k8s-1:~/Mahendra/OOM_Dublin/OOM_SO_RollingUpgrade/OOM_SO_RollingUpgrade/oom/kubernetes/robot# ./ete-k8s.sh onap health
++ export NAMESPACE=onap
++ NAMESPACE=onap
+++ kubectl --namespace onap get pods
+++ grep robot
+++ sed 's/ .*//'
++ POD=demo-robot-robot-785f67844-gnkk2
++ TAGS='-i health'
++ ETEHOME=/var/opt/ONAP
+++ kubectl --namespace onap exec demo-robot-robot-785f67844-gnkk2 -- bash -c 'ls -1q /share/logs/ | wc -l'
++ export GLOBAL_BUILD_NUMBER=0
++ GLOBAL_BUILD_NUMBER=0
+++ printf %04d 0
++ OUTPUT_FOLDER=0000_ete_health
++ DISPLAY_NUM=90
++ VARIABLEFILES='-V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py'
++ VARIABLES='-v GLOBAL_BUILD_NUMBER:28940'
++ kubectl --namespace onap exec demo-robot-robot-785f67844-gnkk2 -- /var/opt/ONAP/runTags.sh -V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py -v GLOBAL_BUILD_NUMBER:28940 -d /share/logs/0000_ete_health -i health --display 90
Starting Xvfb on display :90 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
Testsuites
==============================================================================


------------------------------------------------------------------------------
Basic SDNC Health Check                                               [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e61110>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e61310>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e61510>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /restconf/operations/SLI-API:healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e616d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e67850>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /iui/usecaseui/
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7435e67a50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /iui/usecaseui/

Patch-set: 2