Update patch set 2
Patch Set 2:

here's the log:
cat .helm/plugins/deploy/cache/onap/logs/onap-dmaap.log
Release "onap-dmaap" does not exist. Installing it now.
NAME:   onap-dmaap
Error: getting deployed release "onap-dmaap": release: "onap-dmaap" not found

@Krzysztof, any idea?

Patch-set: 2
Reviewer: Gerrit User 4965 <4965@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>