Update patch set 2
Patch Set 2:

Cannot submit a new patch, git-review says it cannot rebase, and that there's a merge conflict.
Errors running git rebase -p -i remotes/gerrit/master
error: could not apply 3ce16e6... readd so filebeat sidecar ELK endpoint

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not pick 3ce16e6a7a5c6d06371692b027cfbc38fb6c7ee9
It is likely that your change has a merge conflict. You may resolve it in the working tree now as described above and then run 'git review' again, or if you do not want to resolve it yet (note that the change can not merge until the conflict is resolved) you may run 'git rebase --abort' then 'git review -R' to upload the change without rebasing.

Patch-set: 2
Reviewer: Gerrit User 2627 <2627@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0