Update patch set 6
Patch Set 6:

Gitlab Orange 4: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98436-6/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 212
 * Nb Failed Pods: 48
 * List of Failed Pods: [
   - dep-dcae-prh-54fcb87684-jxz5f
   - dep-dcae-ves-collector-77fb47cc4f-52k22
   - dep-dcae-ves-collector-77fb47cc4f-9878t
   - onap-aaf-aaf-service-7f99bc58fc-h5x4r
   - onap-aai-aai-data-router-7cd8669b68-jx92c
   - onap-aai-aai-graphadmin-67859ff78c-2gj69
   - onap-aai-aai-graphgraph-5875c7ffdb-cntvw
   - onap-cds-cds-blueprints-processor-76cf8d7b77-fhzqz
   - onap-cds-cds-command-executor-58b446997d-rgrhx
   - onap-cds-cds-sdc-listener-75c5fd5ffb-hqbgr
   - onap-clamp-clamp-dash-logstash-56bb7678c-284ml
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-659gl
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-7ktf6
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-b889n
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-dwn8r
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-jdcjb
   - onap-dcaegen2-dcae-cloudify-manager-6d86555847-nb6b2
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-96l9s
   - onap-esr-esr-gui-6d54d48898-f2qcv
   - onap-esr-esr-gui-6d54d48898-stk2w
   - onap-esr-esr-server-86b689bc5c-d9zbb
   - onap-log-log-logstash-575b4567b7-9q9xw
   - onap-msb-msb-iag-758fc5cf7b-q7km6
   - onap-multicloud-multicloud-azure-59fcb9c779-726sw
   - onap-multicloud-multicloud-lenovo-9675457fb-l8qcf
   - onap-oof-music-tomcat-6fcc8cdcb4-w965z
   - onap-oof-oof-cmso-service-66ff6f6cd8-h2cc9
   - onap-oof-oof-cmso-service-66ff6f6cd8-l44h4
   - onap-oof-oof-cmso-ticketmgt-5f8b89b4c4-fvdjj
   - onap-oof-oof-cmso-topology-7b458f47bd-brjtc
   - onap-oof-oof-has-api-5bb7b84888-q99wk
   - onap-oof-oof-has-controller-56f598fb9f-8lkgl
   - onap-oof-oof-has-data-d575ff6df-zgnzq
   - onap-oof-oof-has-reservation-547c8f4d7f-t68cp
   - onap-oof-oof-has-solver-746bff67d8-w5x7g
   - onap-pomba-pomba-contextaggregator-77bd58448d-mtqdg
   - onap-portal-portal-app-846f555cdc-vw2qm
   - onap-sdc-sdc-wfd-be-5c8747d55d-82zbp
   - onap-sdc-sdc-wfd-fe-fbccb85d-wh2l8
   - onap-sdnc-sdnc-dmaap-listener-7df88fddcb-rfpbv
   - onap-sdnc-sdnc-ueb-listener-5f57ff6d5f-rfqq8
   - onap-so-so-catalog-db-adapter-6699f5865d-mctwh
   - onap-so-so-vnfm-adapter-5ddfc68df7-6kstw
   - onap-so-so-vnfm-adapter-5ddfc68df7-9x9bf
   - onap-uui-uui-8c999dcb8-v5j22
   - onap-vfc-vfc-nslcm-67f99d7dc5-92rhh
   - onap-vfc-vfc-workflow-engine-7b5f499d97-8hk6h
   - onap-vfc-vfc-zte-vnfm-driver-6fcd6db6cc-zxnmb]
*********** Helm Results ***********
 * Nb Helm Charts: 35
 * Nb Failed Helm Charts: 0
 * List of Failed Helm Charts: []
******** Healthcheck Results *******
2019-12-06 10:45:50,721 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-service.onap', port=8100): Max retries exceeded with url: /authz/perms/user/demo@people.osaaf.org (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f606f81d190>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f606f54fed0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f606f75a490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f606f566610>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f606f4b8b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-contextaggregator.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f606f777750>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f606fa77fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 48 passed, 13 failed
61 tests total, 48 passed, 13 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-12-06 10:44:12,581 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
500 != 200

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 6
Label: Code-Review=0