Update patch set 33
Patch Set 33:

I've reinstated the secrets 
    clientIakExternalSecret: ejbca-server-client-iak
    raIakExternalSecret: ejbca-server-ra-iak

Now I am getting a Init:CreateContainerConfigError 

Error: secret "ejbca-server-client-iak" not found

I may be missing something somewhere

Patch-set: 33
Reviewer: Gerrit User 4893 <4893@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>