Update patch set 11
Patch Set 11: Verified-1

This does not deploy for me in 2 of my environments.  I have a k8s 1.8 and k8s 1.10 and it fails with the same thing in both:

error: release beast failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap: Data: ReadMapCB: expect { or n, parsing 27 ...","data":"... at {"apiVersion":"v1","data":"LOG_PATH:./logs/reqdb/","kind":"ConfigMap","metadata":{"name":"beast-so-request-db-adapter-configmap","namespace":"onap"}}


helm upgrade -i dev-so so --namespace onap --debug
[debug] Created tunnel using local port: '45290'

[debug] SERVER: "127.0.0.1:45290"

Release "dev-so" does not exist. Installing it now.
[debug] CHART PATH: /home/mkhinda/onap-gerrit/oom/kubernetes/so

Error: release dev-so failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|","data":"LOG_PATH:.|..., bigger context ...|{"apiVersion":"v1","data":"LOG_PATH:./logs/reqdb/","kind":"ConfigMap","metada|...


Something strange is going on with your configmaps....I tried to debug but didn't make much progress.  I see a lot of complexity and fancy stuff (cool btw!) in your charts so that might make troubleshooting a bit more difficult.

Did you see these problems when you tested with Brian?

Patch-set: 11
Label: Verified=-1