Update patch set 2
Patch Set 2:

Gitlab Azure 1: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//115252-2/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 7
 * List of Failed Jobs: [
   - onap-ejbca-config-config-job
   - onap-modeling-etsicatalog-config-job
   - onap-nbi-config-config-job
   - onap-nengdb-init-config-job
   - onap-sdnc-dbinit-job
   - onap-so-mariadb-config-job
   - onap-vid-mariadb-init-config-job]
 * Nb Deployments: 153
 * Nb Failed Deployments: 24
 * List of Failed Deployments: [
   - onap-ejbca
   - onap-modeling-etsicatalog
   - onap-nbi
   - onap-network-name-gen
   - onap-oof
   - onap-oom-cert-service
   - onap-sdnc-ansible-server
   - onap-sdnc-dgbuilder
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-sdnc-web
   - onap-so
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-nssmf-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-vfc-adapter
   - onap-vfc-nslcm
   - onap-vfc-vnflcm
   - onap-vfc-vnfmgr
   - onap-vfc-vnfres
   - onap-vid]
 * Nb StatefulSets: 28
 * Nb Failed StatefulSets: 3
 * List of Failed StatefulSets: [
   - onap-mariadb-galera
   - onap-sdnc
   - onap-vfc-mariadb]
 * Nb Persistent Volume Claims: 76
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 2
 * List of Failed Helms: [
   - onap-sdnc
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-11-24 05:59:04,002 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | FAIL |
ConnectionError: HTTPSConnectionPool(host='nbi.onap', port=8443): Max retries exceeded with url: /nbi/api/v4/status?fullStatus=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ff72b8050>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ff71ba690>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ff7187410>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/config/GENERIC-RESOURCE-API:services/service/GRSIdummy123 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ff72b8ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ff71acb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='vid.onap', port=8443): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ff7178d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 32 passed, 11 failed
43 tests total, 32 passed, 11 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-11-24 06:07:16,662 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
FAIL != PASS

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-11-24 05:59:00,080 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
cat: ./public/115252-2/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (08:01)
hv-ves: PASS (00:37)
5gbulkpm: PASS (07:36)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/115252-2/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (06:46)
kube_hunter: FAIL (00:00)
root_pods: FAIL (01:40)
unlimitted_pods: FAIL (00:34)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 2