Update patch set 3
Patch Set 3:

Krzysztof Opasiak, Thanks for your updates and it can execute "make vfc" without any error, but when we execute helm install, the following error has been reported:
root@ops-duanshuaixing:~/oom-202002121613/kubernetes# make vfc

[vfc]
make[1]: Entering directory '/root/oom-202002121613/kubernetes'
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ?Happy Helming!?
Saving 2 charts
Downloading common from repo http://127.0.0.1:8879/charts
Downloading mariadb-galera from repo http://127.0.0.1:8879/charts
Deleting outdated charts
==> Linting vfc
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
Successfully packaged chart and saved it to: /root/oom-202002121613/kubernetes/dist/packages/vfc-5.0.0.tgz
make[1]: Leaving directory '/root/oom-202002121613/kubernetes'
root@ops-duanshuaixing:~/oom-202002121613/kubernetes# helm install local/vfc --namespace onap --name dev-vfc --set global.pullPolicy=IfNotPresent --set global.repository=159.138.11.6:10001 --set global.masterPassword=test
Error: YAML parse error on vfc/charts/vfc-catalog/templates/deployment.yaml: error converting YAML to JSON: yaml: line 84: did not find expected '-' indicator

Patch-set: 3
Reviewer: Gerrit User 925 <925@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0