Update patch set 1
Patch Set 1:

details on reopened review 63235 - as we need a 304xx nodeport - this jira is really 2 parts (logging and exposing a new port) - we failed to test the conflict with pomba because my AWS CD system was temporarily not running - after the AAF/CLAMP merge for OOM-1174 in https://gerrit.onap.org/r/#/c/63235/
https://gerrit.onap.org/r/#/c/63235/1/kubernetes/clamp/values.yaml
https://git.onap.org/oom/tree/kubernetes/clamp/values.yaml#n98

reproduction:
amdocs@ubuntu:~/_dev/oom/kubernetes$ sudo helm upgrade -i onap local/onap --namespace onap -f dev.yaml
Error: UPGRADE FAILED: failed to create resource: Service "pomba-kibana" is invalid: spec.ports[0].nodePort: Invalid value: 30234: provided port is already allocated

see
OOM-1174
OOM-1364
OOM-1366

To speed this up - and not have to goto 304/306xx - Giving aaf/clamp my last 302
https://git.onap.org/logging-analytics/tree/reference/logging-kubernetes/logdemonode/charts/logdemonode/values.yaml#n76

That I was using for the logging RI container (reserved on july 26) - I will use a 304xx port for logging instead

38112900" target="_blank">https://wiki.onap.org/pages/viewpage.action?pageId=38112900
adjusting page

https://wiki.onap.org/display/DW/OOM+NodePort+List

Patch-set: 1