Update patch set 2
Patch Set 2: Code-Review-1

gating results

seems to introduce an error in so helm chart (first occurence then with this patch) - ServiceIP allocation to be checked

******** Kubernetes Results ********
 * Nb Pods: 185
 * Nb Failed Pods: 17
 * List of Failed Pods: [
   - onap-appc-appc-ansible-server-598558f644-lxcds
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-pwl6l
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-v6kmh
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-82lfk
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-dnd9f
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-nlnzk
   - onap-policy-brmsgw-59bbd998fb-9zgnt
   - onap-policy-drools-0
   - onap-policy-pap-6757df5484-zsbdq
   - onap-policy-pdp-0
   - onap-policy-policydb-7dcf98d6d7-g6qw5
   - onap-sdnc-blueprints-processor-6d8c669cb-r4rn5
   - onap-sdnc-controller-blueprints-64b8cf4c7c-778rf
   - onap-sdnc-sdnc-ansible-server-64f864fd54-vvcr4
   - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-jc4jw
   - onap-sdnc-sdnc-portal-848d54f7c4-x9pj9
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-xl4zj]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-so
   - onap-vnfsdk]

Chart onap-so
STATUS: FAILED
Chart problem
info:
  Description: |
    Release "onap-so" failed: Internal error occurred: failed to allocate a serviceIP: client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member http://etcd.kubernetes.rancher.internal:2379 has no leader
  first_deployed:
    nanos: 538283590
    seconds: 1553021748
  last_deployed:
    nanos: 538283590
    seconds: 1553021748
  status:
    code: 4
    notes: "1. main components included in umbrella chart\n-- api-handler-infra\n--
      asdc-controller\n-- bpmn-infra\n-- openstack-adapter\n-- sdnc-adapter\n-- vfc-adapter
      \n2. dependencies included in charts sub directory\n-- db-secrets\n-- ssl-secrets\n--
      catalog-db-adapter\n-- request-db-adapter\n4. Run the following helm command
      to deploy chart(s), remove --dry-run option\n\thelm upgrade -f ./helm/values.yaml
      --install --debug --dry-run so ./so\n"
name: onap-so
namespace: onap


healthcheck
***********
Basic A&AI Health Check                                     | PASS |
--------------------------------------------------------------------
Basic AAF Health Check                                      | PASS |
--------------------------------------------------------------------
Basic AAF SMS Health Check                                  | PASS |
--------------------------------------------------------------------
Basic APPC Health Check                                     | PASS |
--------------------------------------------------------------------
Basic CLI Health Check                                      | PASS |
--------------------------------------------------------------------
Basic CLAMP Health Check                                    | PASS |
--------------------------------------------------------------------
Basic DCAE Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic DMAAP Data Router Health Check                        | PASS |
--------------------------------------------------------------------
Basic DMAAP Message Router Health Check                     | PASS |
--------------------------------------------------------------------
Basic External API NBI Health Check                         | PASS |
--------------------------------------------------------------------
Basic Log Elasticsearch Health Check                        | PASS |
--------------------------------------------------------------------
Basic Log Kibana Health Check                               | PASS |
--------------------------------------------------------------------
Basic Log Logstash Health Check                             | PASS |
--------------------------------------------------------------------
Basic Microservice Bus Health Check                         | PASS |
--------------------------------------------------------------------
Basic Multicloud API Health Check                           | PASS |
--------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                     | PASS |
--------------------------------------------------------------------
Basic Multicloud-pike API Health Check                      | PASS |
--------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                 | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check            | PASS |
--------------------------------------------------------------------
Basic Multicloud-vio API Health Check                       | PASS |
--------------------------------------------------------------------
Basic OOF-Homing Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff44d22a110>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff44d1de490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-CMSO Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff44d1ded10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Policy Health Check                                   | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check  | PASS |
--------------------------------------------------------------------
Basic Portal Health Check                                   | PASS |
--------------------------------------------------------------------
Basic SDC Health Check                                      | PASS |
--------------------------------------------------------------------
Basic SDNC Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic SO Health Check                                       | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff44d216d50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic UseCaseUI API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC catalog API Health Check                          | PASS |
--------------------------------------------------------------------
Basic VFC emsdriver API Health Check                        | PASS |
--------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                      | PASS |
--------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                 | PASS |
--------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                   | PASS |
--------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                  | PASS |
--------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nslcm API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC resmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnflcm API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfres API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC workflow API Health Check                         | PASS |
--------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VID Health Check                                      | FAIL |
Resolving variable '${resp.json()['detailedMsg']}' failed: KeyError: 'detailedMsg'
--------------------------------------------------------------------
Basic VNFSDK Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff44d11e450>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Holmes Rule Management API Health Check               | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Holmes Engine Management API Health Check   | FAIL |
502 != 200
--------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 40 passed, 12 failed

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1