Update patch set 4
Patch Set 4: Code-Review-1

> > Gating results:
 > >
 > > AAI pods and healthcheck FAILED
 > >
 > > ******** Kubernetes Results ********
 > > * Nb Pods: 170
 > > * Nb Failed Pods: 23
 > > * List of Failed Pods: [
 > > - onap-aai-aai-79cdd4c578-4dff5
 > > - onap-aai-aai-champ-599cd94496-qhpch
 > > - onap-aai-aai-graphadmin-create-db-schema-vj9dg
 > > - onap-aai-aai-graphadmin-f6b4b849b-6zcmw
 > > - onap-aai-aai-resources-69d89f66f8-ft5tm
 > > - onap-aai-aai-sparky-be-5ff8689c54-g7248
 > > - onap-aai-aai-spike-77ccc5bf78-fzjkl
 > > - onap-aai-aai-traversal-85cbb49c8c-6lxrr
 > > - onap-aai-aai-traversal-update-query-data-llqnt
 > > - onap-contrib-netbox-app-695fd89fd-bgvlx
 > > - onap-contrib-netbox-app-provisioning-cp5mm
 > > - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-c78j2
 > > - onap-dcaegen2-dcae-cloudify-manager-d7b597474-kzvfg
 > > - onap-dcaegen2-dcae-deployment-handler-7745994f7f-k9vsc
 > > - onap-dcaegen2-dcae-healthcheck-84775fddd8-vwhph
 > > - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-9bwdr
 > > - onap-policy-pdp-0
 > > - onap-sdnc-blueprints-processor-6d8c669cb-7gjgn
 > > - onap-sdnc-controller-blueprints-64b8cf4c7c-98jcx
 > > - onap-sdnc-sdnc-ansible-server-64f864fd54-4d4vt
 > > - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-tnl72
 > > - onap-sdnc-sdnc-portal-848d54f7c4-2xjgf
 > > - onap-sdnc-sdnc-ueb-listener-7587fb798c-zbzbh]
 > > * Deployment Duration Estimation (s): 3600
 > > *********** Helm Results ***********
 > > * Nb Helm Charts: 25
 > > * Nb Failed Helm Charts: 2
 > > * List of Failed Helm Charts: [
 > > - onap-appc
 > > - onap-vnfsdk]
 > >
 > > logs at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/178991261/artifacts/download
 > >
 > > healthcheck
 > > ************
 > > Basic A&AI Health Check                                     |
 > FAIL
 > > |
 > > Test timeout 10 seconds exceeded.
 > > --------------------------------------------------------------------
 > > Basic AAF Health Check                                      |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic AAF SMS Health Check                                  |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic APPC Health Check                                     |
 > FAIL
 > > |
 > > ConnectionError: HTTPConnectionPool(host='appc.onap', port=8282):
 > > Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck
 > > (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
 > > object at 0x7f42622ac1d0>: Failed to establish a new connection:
 > > [Errno -2] Name does not resolve',))
 > > --------------------------------------------------------------------
 > > Basic CLI Health Check                                      |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic CLAMP Health Check                                    |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic DCAE Health Check                                     |
 > FAIL
 > > |
 > > Test timeout 10 seconds exceeded.
 > > --------------------------------------------------------------------
 > > Basic DMAAP Message Router Health Check                     |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic External API NBI Health Check                         |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Log Elasticsearch Health Check                        |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Log Kibana Health Check                               |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Log Logstash Health Check                             |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Microservice Bus Health Check                         |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Multicloud API Health Check                           |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Multicloud-ocata API Health Check                     |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Multicloud-pike API Health Check                      |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic OOF-Homing Health Check                               |
 > FAIL
 > > |
 > > ConnectionError: HTTPConnectionPool(host='oof-has-api.onap',
 > > port=8091): Max retries exceeded with url: /v1/plans/healthcheck
 > > (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
 > > object at 0x7f426236da50>: Failed to establish a new connection:
 > > [Errno -2] Name does not resolve',))
 > > --------------------------------------------------------------------
 > > Basic OOF-SNIRO Health Check                                |
 > FAIL
 > > |
 > > ConnectionError: HTTPConnectionPool(host='oof-osdf.onap',
 > > port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck
 > > (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
 > > object at 0x7f4262265290>: Failed to establish a new connection:
 > > [Errno -2] Name does not resolve',))
 > > --------------------------------------------------------------------
 > > Basic OOF-CMSO Health Check                                 |
 > FAIL
 > > |
 > > ConnectionError: HTTPConnectionPool(host='oof-cmso.onap',
 > > port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false
 > > (Caused by NewConnectionError('<urllib3.connection.HTTPConnection
 > > object at 0x7f4262164d50>: Failed to establish a new connection:
 > > [Errno -2] Name does not resolve',))
 > > --------------------------------------------------------------------
 > > Basic Policy Health Check                                   |
 > FAIL
 > > |
 > > Test timeout 10 seconds exceeded.
 > > --------------------------------------------------------------------
 > > Basic Portal Health Check                                   |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic SDC Health Check                                      |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic SDNC Health Check                                     |
 > FAIL
 > > |
 > > Test timeout 10 seconds exceeded.
 > > --------------------------------------------------------------------
 > > Basic SO Health Check                                       |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic UseCaseUI API Health Check                            |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic VID Health Check                                      |
 > PASS
 > > |
 > > --------------------------------------------------------------------
 > > Basic Holmes Rule Management API Health Check               |
 > FAIL
 > > |
 > > 502 != 200
 > > --------------------------------------------------------------------
 > > Basic Holmes Engine Management API Health Check             |
 > FAIL
 > > |
 > > 502 != 200
 > > ------------------------------------------------------------------------------
 > > Health-Check :: Testing ecomp components are available via calls.
 > >   | FAIL |
 > > 28 critical tests, 18 passed, 10 failed
 > > 28 tests total, 18 passed, 10 failed
 > 
 > It requires the cassandra chart, I think cassandra has not been
 > added to the build job.

you should indicate this in gerrit and create a dependency to the patch introducing the cassandra chart

see https://www.mediawiki.org/wiki/Gerrit/Advanced_usage#Create_a_dependency

Patch-set: 4