Update patch set 14
Patch Set 14: Code-Review+1

all smoke OK
only SO HC KO but I assume that it is due the fact that the test is not aligned with the SO changes..

SSLError: HTTPSConnectionPool(host='so-nssmf-adapter.onap', port=8088): Max retries exceeded with url: /manage/health (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
url=https://so-nssmf-adapter.onap:8088, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0

Patch-set: 14
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1