Update patch set 9
Patch Set 9:

the error on basic_onboard is a new exception when retrieving the list of CERTIFIED VSP
this could be linked to the update and a change of behavior not taken into account in the sdk
  File "/usr/lib/python3.8/site-packages/onapsdk/sdc/vsp.py", line 246, in load_status
    and item_details['results'][-1]['status'] == const.CERTIFIED):
IndexError: list index out of range

https://logs.onap.org/onap-integration/gating//117348-9/smoke-usecases/basic_onboard/basic_onboard/pythonsdk.debug.log.gz

or an init issue not detected so far because other tests were creating a VSP so the list was never empty - healthdist is Fail (no idea why the status is green on the dashboard, all the other robot status tests are correct, I do not see any risk as there were no several concurrent deployment)

basic_cnf is ok (using the same mechanism but basic_onboard is the first one, so the list of VSP is empty)
basic_network and vm are failing at the last stage of instantiation due to openstack certificates, it has been fixed. Rebasing and retesting shall fix this issue

Patch-set: 9
Reviewer: Gerrit User 6079 <6079@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>