Update patch set 2
Patch Set 2:

the DCAE error is the "usual" one:
Received content from dcae {"type":"summary","count":14,"ready":13,"items":[{"name":"onap-dcae-cloudify-manager","ready":1,"unavailable":0},{"name":"onap-dcae-config-binding-service","ready":1,"unavailable":0},{"name":"onap-dcae-inventory-api","ready":1,"unavailable":0},{"name":"onap-dcae-servicechange-handler","ready":1,"unavailable":0},{"name":"onap-dcae-deployment-handler","ready":1,"unavailable":0},{"name":"onap-dcae-policy-handler","ready":1,"unavailable":0},{"name":"onap-dcae-dashboard","ready":1,"unavailable":0},{"name":"dep-dcae-tca-analytics","ready":1,"unavailable":0},{"name":"dep-dcae-tcagen2","ready":1,"unavailable":0},{"name":"dep-dcae-prh","ready":1,"unavailable":0},{"name":"dep-dcae-hv-ves-collector","ready":1,"unavailable":0},{"name":"dep-dcae-ves-collector","ready":0,"unavailable":1},{"name":"dep-holmes-engine-mgmt","ready":1,"unavailable":0},{"name":"dep-holmes-rule-mgmt","ready":1,"unavailable":0}]}
dep-dcae-ves-collector is not present
see https://gating-results.onap.eu/results//108127-2/infrastructure-healthcheck/k8s/pod-onap-dcae-bootstrap-86c67576bd-t5vkn-dcae-bootstrap-logs.html

2020-05-26 16:05:44.987  CFY  'create_deployment_environment' workflow execution succeeded
An error occurred on the server: 500: Can't launch executions since environment creation for deployment ves-tls has failed: Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 524, in _handle_remote_workflow
    _include=['status'])
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/executions.py", line 196, in get
    response = self.api.get(uri, _include=_include)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 281, in get
    timeout=timeout)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 258, in do_request
    'the manager. Underlying reason: {0}'.format(e))
SSLError: An SSL-related error has occurred. This can happen if the specified REST certificate does not match the certificate on the manager. Underlying reason: HTTPSConnectionPool(host='10.233.73.115', port=53333): Max retries exceeded with url: /api/v3.1/executions/060633ec-975c-4aed-bf0d-59a46e944e02?_include=status (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:579)'),))

2020-05-26 16:05:50.604  CFY  Starting 'install' workflow execution

I propose not to merge and see why we have that (even if it's not related to SO, I would like to have this solved...)

@Andreas, do you have such issues in your deployments?

Patch-set: 2
Reviewer: Gerrit User 511 <511@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 93 <93@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 2679 <2679@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0