Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96223-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 200
 * Nb Failed Pods: 56
 * List of Failed Pods: [
   - onap-aaf-aaf-oauth-797569bfd6-m6wc4
   - onap-aai-aai-graphgraph-7b85fcb46-jffrn
   - onap-aai-aai-modelloader-85776bdff6-6zn8h
   - onap-aai-aai-sparky-be-68bcf7c4c-vb2g8
   - onap-cds-cds-blueprints-processor-944878fb6-vpgzq
   - onap-cds-cds-command-executor-74dffcb87d-hbvdt
   - onap-cds-cds-sdc-listener-75c5fd5ffb-9n6zc
   - onap-dcaegen2-dcae-dashboard-755449d876-466q5
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-vfmk5
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-4lpcn
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-258gk
   - onap-dmaap-message-router-0
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-mirrormaker-7974bb7697-99t9k
   - onap-esr-esr-gui-6d54d48898-dbnbv
   - onap-esr-esr-server-86b689bc5c-mk2p5
   - onap-modeling-modeling-genericparser-7c4d976d97-bjr5c
   - onap-oof-oof-d8f7dbfbf-rqj6d
   - onap-oof-oof-has-api-7b7f4c95b9-6kd6v
   - onap-oof-oof-has-controller-7db5bf5f8b-452mq
   - onap-oof-oof-has-data-8dc9c79dd-2nxxq
   - onap-oof-oof-has-reservation-589cc655f4-qjnjc
   - onap-oof-oof-has-solver-55d9849c69-5f25w
   - onap-policy-drools-0
   - onap-policy-policy-pap-f7cfc44b7-fzk8q
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-llfp9
   - onap-pomba-pomba-kibana-74f9c6b5cd-cjjk2
   - onap-sdc-sdc-be-565dcfd9d-d489m
   - onap-sdc-sdc-be-config-backend-527gv
   - onap-sdc-sdc-dcae-be-85c669ddbf-9qw8x
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-9lm7h
   - onap-sdc-sdc-dcae-fe-5488b88f8c-vpbkv
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-vr558
   - onap-sdc-sdc-fe-694f4d7576-xzg58
   - onap-sdc-sdc-kb-5b48c6fd44-wlnqr
   - onap-sdc-sdc-onboarding-be-58f66544b6-fp4fr
   - onap-sdc-sdc-onboarding-be-cassandra-init-w47ds
   - onap-sdc-sdc-wfd-be-54ff7b9948-w52dm
   - onap-sdc-sdc-wfd-fe-647d64468f-nkdnq
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-xvgzf
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-5pdfg
   - onap-so-so-monitoring-566cd5dcd6-p5x6t
   - onap-so-so-sdnc-adapter-66cc47dbd6-bwxks
   - onap-uui-uui-698f54566d-kw58t
   - onap-uui-uui-server-5c9bdc858d-zgtl4
   - onap-vfc-vfc-catalog-7467879cb6-j4sfj
   - onap-vfc-vfc-ems-driver-845b6dbc96-94bt6
   - onap-vfc-vfc-generic-vnfm-driver-65c4d9f888-djb2x
   - onap-vfc-vfc-juju-vnfm-driver-dbc776fb6-v4k8t
   - onap-vfc-vfc-nokia-v2vnfm-driver-8666cdcb6f-xdx49
   - onap-vfc-vfc-nslcm-ccc867b6f-7j7d4
   - onap-vfc-vfc-vnflcm-5f79cb477d-lzpf5
   - onap-vfc-vfc-vnfmgr-77fccd68fd-96mg6
   - onap-vfc-vfc-vnfres-7f786df9d9-kr2wc
   - onap-vnfsdk-vnfsdk-7b5746d6cd-pcsqw
   - onap-vnfsdk-vnfsdk-init-postgres-x89qt]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-25 18:32:08,326 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ee9923090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Label: Verified=0