Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//97161-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 217
 * Nb Failed Pods: 32
 * List of Failed Pods: [
   - onap-aai-aai-search-data-5fb74f8b4b-dzddj
   - onap-aai-aai-sparky-be-68bcf7c4c-2kdpv
   - onap-cds-cds-sdc-listener-75c5fd5ffb-2nhlz
   - onap-dcaegen2-dcae-dashboard-755449d876-s2tx5
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-jwpbv
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-lgt6x
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-qflnn
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-mirrormaker-5bd5cbc745-lksk8
   - onap-oof-music-tomcat-bdd9547bf-547dw
   - onap-oof-music-tomcat-bdd9547bf-mx8q2
   - onap-oof-music-tomcat-bdd9547bf-tqzwp
   - onap-oof-oof-cmso-topology-6b7f86d9dc-7j2rz
   - onap-oof-oof-d8f7dbfbf-2nvxp
   - onap-oof-oof-has-api-7b7f4c95b9-gdchp
   - onap-oof-oof-has-controller-7db5bf5f8b-wpjsv
   - onap-oof-oof-has-data-8dc9c79dd-gxzbl
   - onap-oof-oof-has-reservation-589cc655f4-567bv
   - onap-oof-oof-has-solver-55d9849c69-zlqgl
   - onap-policy-policy-api-664f4bf674-7s79j
   - onap-pomba-pomba-data-router-689596cff7-4lvsp
   - onap-sdc-sdc-be-config-backend-w89rn
   - onap-sdc-sdc-dcae-be-85c669ddbf-7wbzp
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-x9zl4
   - onap-sdc-sdc-dcae-fe-5488b88f8c-bdbk6
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-tg7m9
   - onap-sdc-sdc-fe-5cfcddf448-nh8kp
   - onap-sdc-sdc-kb-5b48c6fd44-7lp6w
   - onap-sdc-sdc-wfd-be-54ff7b9948-4kgcj
   - onap-sdc-sdc-wfd-fe-647d64468f-xs6mt
   - onap-sdnc-sdnc-ueb-listener-5d78c9c586-9nlzc
   - onap-vfc-vfc-workflow-engine-5ffdc84544-nv8dj]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc]
******** Healthcheck Results *******
******** healthdist Results *******
2019-10-16 14:53:45,096 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f24f8b23090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0