Update patch set 2
Patch Set 2: Verified-1

unfortunately, the spacing breaks by removing the hash :(
the SS in aai-cassandra has an example.

Error: error validating "": error validating data: found invalid field imagePullSecrets for v1.PersistentVolumeClaimSpec

Patch-set: 2
Label: Verified=-1