Update patch set 11
Patch Set 11:

> Patch Set 11:
> 
> @krzysztof, I've got this issue with "secretFast":
> UPGRADE FAILED
> Error: render error in "so/charts/so-vfc-adapter/templates/secret.yaml": template: so/charts/so-vfc-adapter/templates/secret.yaml:15:3: executing "so/charts/so-vfc-adapter/templates/secret.yaml" at <include "common.secretFast" .>: error calling include: template: so/charts/common/templates/_secret.tpl:451:6: executing "common.secretFast" at <include "common.secret.buildCache" $global>: error calling include: template: so/charts/common/templates/_secret.tpl:193:54: executing "common.secret.buildCache" at <$key>: wrong type for value; expected string; got []interface {}
> Error: UPGRADE FAILED: render error in "so/charts/so-vfc-adapter/templates/secret.yaml": template: so/charts/so-vfc-adapter/templates/secret.yaml:15:3: executing "so/charts/so-vfc-adapter/templates/secret.yaml" at <include "common.secretFast" .>: error calling include: template: so/charts/common/templates/_secret.tpl:451:6: executing "common.secretFast" at <include "common.secret.buildCache" $global>: error calling include: template: so/charts/common/templates/_secret.tpl:193:54: executing "common.secret.buildCache" at <$key>: wrong type for value; expected string; got []interface {}
> 
> 
> any ideas? (I'm using "generic" secret)

found, we also need to remove 'filePaths' like annotation in buildCache.
Do you want to do it or I do?

Patch-set: 11
Label: Code-Review=0