Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Gitlab Orange 4: 
> Full results can be seen here: https://logs.onap.org/onap-integration/gating//119054-1/index.html
> ______________ Results ______________________
> 
> ************************************************************
> ************************************************************
> ************ Infrastructure-healthcheck Results ************
> ************************************************************
> ************************************************************
> --------> onap-k8s
>  * Nb Jobs: 28
>  * Nb Failed Jobs: 0
>  * Nb Deployments: 150
>  * Nb Failed Deployments: 5
>  * List of Failed Deployments: [
>    - onap-aaf-sms
>    - onap-oof
>    - onap-oof-has-data
>    - onap-oof-has-reservation
>    - onap-oof-has-solver]
>  * Nb StatefulSets: 27
>  * Nb Failed StatefulSets: 0
>  * Nb Persistent Volume Claims: 74
>  * Nb Failed Persistent Volume Claims: 0
> --------> onap-helm
>  * Nb Helms: 33
>  * Nb Failed Helms: 0
> 
> ************************************************************
> ************************************************************
> ********************* Healthcheck Results ******************
> ************************************************************
> ************************************************************
> --------> robot full healthcheck tests
> 2021-03-10 14:56:50,472 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Basic A&AI Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced A&AI Health Check                                            | FAIL |
> 500 != 204
> ------------------------------------------------------------------------------
> Basic AAF Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic AAF SMS Health Check                                            | FAIL |
> ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f868b6b6b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic APPC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic CLI Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic CLAMP Health Check                                              | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Data Router Health Check                                  | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Message Router Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> ------------------------------------------------------------------------------
> Basic External API NBI Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Microservice Bus Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-pike API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-starlingx API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-vio API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-k8s API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-Homing Health Check                                         | FAIL |
> 500 != 200
> ------------------------------------------------------------------------------
> Basic OOF-OSDF Health Check                                           | FAIL |
> ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f868b2c3610>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic OOF-CMSO Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic Policy Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Enhanced Policy New Healthcheck                                       | FAIL |
> 200 != 202
> ------------------------------------------------------------------------------
> Basic Portal Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDC Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDC Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDNC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDNC Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic SO Health Check                                                 | PASS |
> ------------------------------------------------------------------------------
> Basic UseCaseUI API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC gvnfmdriver API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic VFC nslcm API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnflcm API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfmgr API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfres API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC ztevnfmdriver API Health Check                              | PASS |
> ------------------------------------------------------------------------------
> Basic VID Health Check                                                | FAIL |
> 500 != 200
> ------------------------------------------------------------------------------
> Basic VNFSDK Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-fcaps API Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic Modeling genericparser API Health Check                         | PASS |
> ------------------------------------------------------------------------------
> Enhanced CDS Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> 43 critical tests, 37 passed, 6 failed
> 43 tests total, 37 passed, 6 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/full/output.xml
> 
> ************************************************************
> ************************************************************
> ********************* Basic tests Results ******************
> ************************************************************
> ************************************************************
> --------> healthdist (vFW onboarding and distribution)
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> --------> postinstall tests (dmaap and A&AI)
> Post-Install-Tests :: Testing Installation                            | PASS |
> --------> CMPv2 tests
> Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
> Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
> Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
> Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
> Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
> Send registration request to VES without CMPv2 certificate :: This... | PASS |
> Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
> --------> HV-VES tests
> Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
> --------> VES collector tests
> Ves :: Suite for checking handling events by VES Collector            | PASS |
> --------> Basic Onboard tests (SDC)
> basic_onboard: PASS (04:28)
> --------> CDS tests
> basic_cds: PASS (00:19)
> 
> ************************************************************
> ************************************************************
> ******************** End to End usecases *******************
> ************************************************************
> ************************************************************
> --------> pnf-registrate tests
> PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
> Pnf-Registration :: Executes the PNF registration test cases inclu... | PASS |
> --------> 5gbulkpm tests
> Setting Global Variables :: This test case checks suite if it is w... | PASS |
> 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> --------> basic_vm tests
> basic_vm: FAIL (04:33)
> --------> basic_network tests
> basic_network: FAIL (01:48)
> --------> basic_cnf tests
> basic_cnf: FAIL (04:58)
> 
> ************************************************************
> ************************************************************
> ********************** Security tests **********************
> ************************************************************
> ************************************************************
> --------> cis_kubernetes tests
> cis_kubernetes: PASS (00:00)
> --------> nonssl_endpoints tests
> nonssl_endpoints: FAIL (01:11)
> --------> jdpw_ports tests
> jdpw_ports: PASS (07:58)
> --------> kube_hunter tests
> kube_hunter: PASS (00:04)
> --------> root_pods tests
> root_pods: FAIL (02:37)
> --------> unlimitted_pods tests
> unlimitted_pods: FAIL (00:55)
> 
> ____________________________________________________________

installation issues
6 HC failing including AAI, VID, 
the basic_cnf, basic_vnf and basic_network are failed due to the VID error (java exception)
it is a known issue not reproducible at each run (https://jira.onap.org/browse/VID-960?)..but restart of the vid is enough to fix the issue
I assume without the VID issue, results would have been OK (all SDC operations OK)..but we got the VID issue

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>