Update patch set 1
Patch Set 1:

Gating results

******* Kubernetes Results ********
 * Nb Pods: 198
 * Nb Failed Pods: 17
 * List of Failed Pods: [
   - onap-aai-aai-76dbf8f486-m6z2g
   - onap-aai-aai-champ-7f97f98976-9bl6d
   - onap-aai-aai-graphadmin-c79fb7fcf-689h5
   - onap-aai-aai-resources-557c6f9d78-tnp98
   - onap-aai-aai-sparky-be-5ff8689c54-hlmgz
   - onap-aai-aai-spike-77ccc5bf78-bh4lm
   - onap-aai-aai-traversal-7fb5558d98-zdwql
   - onap-aai-aai-traversal-update-query-data-7rbls
   - onap-contrib-netbox-app-695fd89fd-lsdbl
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-jsh5r
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-xx4lk
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-d5rlz
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-2rc9q
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-4qnl7
   - onap-dmaap-dmaap-bc-68f4565db7-2lc88
   - onap-sdnc-blueprints-processor-6d8c669cb-b6zwr
   - onap-sdnc-controller-blueprints-64b8cf4c7c-mslzf]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-03-21 16:22:56,125 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                      | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic AAF Health Check                                       | PASS |
----------------------------------------------------------------------
Basic AAF SMS Health Check                                   | PASS |
----------------------------------------------------------------------
Basic APPC Health Check                                      | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic CLI Health Check                                       | PASS |
----------------------------------------------------------------------
Basic CLAMP Health Check                                     | PASS |
----------------------------------------------------------------------
Basic DCAE Health Check                                      | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                         | PASS |
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                      | PASS |
----------------------------------------------------------------------
Basic External API NBI Health Check                          | PASS |
----------------------------------------------------------------------
Basic Log Elasticsearch Health Check                         | PASS |
----------------------------------------------------------------------
Basic Log Kibana Health Check                                | PASS |
----------------------------------------------------------------------
Basic Log Logstash Health Check                              | PASS |
----------------------------------------------------------------------
Basic Microservice Bus Health Check                          | PASS |
----------------------------------------------------------------------
Basic Multicloud API Health Check                            | PASS |
----------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                      | PASS |
----------------------------------------------------------------------
Basic Multicloud-pike API Health Check                       | PASS |
----------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                  | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check             | PASS |
----------------------------------------------------------------------
Basic Multicloud-vio API Health Check                        | PASS |
----------------------------------------------------------------------
Basic OOF-Homing Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa24c458810>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa24c2a8150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa24c250150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Policy Health Check                                   | PASS |
----------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                | PASS |
----------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                | PASS |
----------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check  | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                   | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                      | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                     | PASS |
----------------------------------------------------------------------
Basic SO Health Check                                       | PASS |
----------------------------------------------------------------------Basic UseCaseUI API Health Check                            | PASS |
----------------------------------------------------------------------
Basic VFC catalog API Health Check                          | PASS |
----------------------------------------------------------------------
Basic VFC emsdriver API Health Check                        | PASS |
----------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                      | PASS |
----------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                 | PASS |
----------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                   | PASS |
----------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                    | PASS |
----------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                  | PASS |
----------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                    | PASS |
----------------------------------------------------------------------
Basic VFC nslcm API Health Check                            | PASS |
----------------------------------------------------------------------
Basic VFC resmgr API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC vnflcm API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC vnfres API Health Check                           | PASS |
----------------------------------------------------------------------
Basic VFC workflow API Health Check                         | PASS |
----------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                    | PASS |
----------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                    | PASS |
----------------------------------------------------------------------
Basic VID Health Check                                      | PASS |
----------------------------------------------------------------------
Basic VNFSDK Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa24c0c4a50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check               | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check             | FAIL |
502 != 200
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 42 passed, 10 failed

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0