Update patch set 9
Patch Set 9: Code-Review+2 Verified+1

Node: DMaaP DR is failing consistently (not related to this commit)

onap          aaa-dmaap-dbc-pg-0                                        1/1       Running            0          3h
onap          aaa-dmaap-dbc-pg-1                                        1/1       Running            0          3h
onap          aaa-dmaap-dbc-pgpool-6ff9dd87c8-df7b6                     1/1       Running            0          3h
onap          aaa-dmaap-dbc-pgpool-6ff9dd87c8-xzwmz                     1/1       Running            0          3h
onap          aaa-dmaap-dmaap-bus-controller-6785c4668d-l655c           1/1       Running            0          3h
onap          aaa-dmaap-dmaap-dr-db-794b79cc4d-r4jxk                    1/1       Running            1          3h
onap          aaa-dmaap-dmaap-dr-node-5d5f9cc8b5-wc6xj                  0/1       Init:0/1           19         3h
onap          aaa-dmaap-dmaap-dr-prov-649c4cf585-xmtdb                  0/1       CrashLoopBackOff   42         3h
onap          aaa-dmaap-message-router-0                                1/1       Running            0          3h
onap          aaa-dmaap-message-router-kafka-0                          1/1       Running            0          3h
onap          aaa-dmaap-message-router-kafka-1                          1/1       Running            0          3h
onap          aaa-dmaap-message-router-kafka-2                          1/1       Running            0          3h
onap          aaa-dmaap-message-router-zookeeper-0                      1/1       Running            0          3h
onap          aaa-dmaap-message-router-zookeeper-1                      1/1       Running            0          3h
onap          aaa-dmaap-message-router-zookeeper-2                      1/1       Running            0          3h


------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ea986c750>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ea98736d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ea9873690>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
| FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9ea9873650>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------

root@borislav-rancher:~/onap/master/oom/kubernetes/robot# kg pv | grep -i dmaap
aaa-dmaap-dbc-pg-data0                    1Gi        RWO            Retain           Bound       onap/aaa-dmaap-dbc-pg-data-aaa-dmaap-dbc-pg-1                                     aaa-dmaap-dbc-pg-data                              3h
aaa-dmaap-dbc-pg-data1                    1Gi        RWO            Retain           Bound       onap/aaa-dmaap-dbc-pg-data-aaa-dmaap-dbc-pg-0                                     aaa-dmaap-dbc-pg-data                              3h
aaa-dmaap-dmaap-dr-db                     1Gi        RWX            Retain           Bound       onap/aaa-dmaap-dmaap-dr-db                                                                                                           3h
aaa-dmaap-message-router-kafka-0          2Gi        RWX            Retain           Bound       onap/kafka-data-aaa-dmaap-message-router-kafka-0                                                                                     3h
aaa-dmaap-message-router-kafka-1          2Gi        RWX            Retain           Bound       onap/kafka-data-aaa-dmaap-message-router-kafka-2                                                                                     3h
aaa-dmaap-message-router-kafka-2          2Gi        RWX            Retain           Bound       onap/kafka-data-aaa-dmaap-message-router-kafka-1                                                                                     3h
aaa-dmaap-message-router-zookeeper-0      2Gi        RWX            Retain           Bound       onap/zookeeper-data-aaa-dmaap-message-router-zookeeper-0                                                                             3h
aaa-dmaap-message-router-zookeeper-1      2Gi        RWX            Retain           Bound       onap/zookeeper-data-aaa-dmaap-message-router-zookeeper-2                                                                             3h
aaa-dmaap-message-router-zookeeper-2      2Gi        RWX            Retain           Bound       onap/zookeeper-data-aaa-dmaap-message-router-zookeeper-1                                           

root@borislav-rancher:~/onap/master/oom/kubernetes/robot# kg pvc -n onap | grep -i dmaap
aaa-dmaap-dbc-pg-data-aaa-dmaap-dbc-pg-0                                     Bound     aaa-dmaap-dbc-pg-data1                    1Gi        RWO            aaa-dmaap-dbc-pg-data                    3h
aaa-dmaap-dbc-pg-data-aaa-dmaap-dbc-pg-1                                     Bound     aaa-dmaap-dbc-pg-data0                    1Gi        RWO            aaa-dmaap-dbc-pg-data                    3h
aaa-dmaap-dmaap-dr-db                                                        Bound     aaa-dmaap-dmaap-dr-db                     1Gi        RWX                                                     3h
kafka-data-aaa-dmaap-message-router-kafka-0                                  Bound     aaa-dmaap-message-router-kafka-0          2Gi        RWX                                                     3h
kafka-data-aaa-dmaap-message-router-kafka-1                                  Bound     aaa-dmaap-message-router-kafka-2          2Gi        RWX                                                     3h
kafka-data-aaa-dmaap-message-router-kafka-2                                  Bound     aaa-dmaap-message-router-kafka-1          2Gi        RWX                                                     3h
zookeeper-data-aaa-dmaap-message-router-zookeeper-0                          Bound     aaa-dmaap-message-router-zookeeper-0      2Gi        RWX                                                     3h
zookeeper-data-aaa-dmaap-message-router-zookeeper-1                          Bound     aaa-dmaap-message-router-zookeeper-2      2Gi        RWX                                                     3h
zookeeper-data-aaa-dmaap-message-router-zookeeper-2                          Bound     aaa-dmaap-message-router-zookeeper-1      2Gi        RWX                                                     3h

Patch-set: 9
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2
Label: Verified=+1