Update patch set 2
Patch Set 2:

interesting:
02/10-14:35:32.071|org.onap.dmaap.datarouter.provisioning.internal||||main|||ERROR||||||PROV0010 **** DMaaP Data Router Provisioning Server failed to start. Exiting: java.lang.NullPointerException
java.lang.IllegalArgumentException: java.lang.NullPointerException

I don't expect this to be related but let's oom_redeploy to be sure

Patch-set: 2
Reviewer: Gerrit User 4965 <4965@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>