Update patch set 4
Patch Set 4:

> Vaibhav, you will need to update the ONAP chart's requirements
 > yaml.  It is looking for mock chart version 0.1.0 and you have just
 > changed it 2.0.0.
 > 
 > ...Successfully got an update from the "local" chart repository
 > Update Complete. \u2388Happy Helming!\u2388
 > Error: Can't get a valid version for repositories mock. Try
 > changing the version constraint in requirements.yaml
 > Makefile:42: recipe for target 'dep-onap' failed
 > make[1]: *** [dep-onap] Error 1
 > make[1]: Leaving directory '/home/mkhinda/onap-gerrit/oom/kubernetes'
 > Makefile:35: recipe for target 'onap' failed
 > make: *** [onap] Error 2

Changes Done, NowI think all are changed to 2.0.0

Patch-set: 4