Update patch set 1
Patch Set 1:

> I think I found the problem. It is before this patch, probably
 > unrelated:
 > # helm upgrade -i aaa-aai local/aai --namespace onap -f
 > ~/global-values.yaml --set global.pullPolicy=IfNotPresent,aai.enabled=true
 > Release "aaa-aai" does not exist. Installing it now.
 > Error: release aaa-aai failed: Deployment in version "v1beta1"
 > cannot be handled as a Deployment: v1beta1.Deployment: Spec:
 > v1beta1.DeploymentSpec: Template: v1.PodTemplateSpec: Spec:
 > v1.PodSpec: Containers: []v1.Container: v1.Container: Ports:
 > []v1.ContainerPort: v1.ContainerPort: ContainerPort: readUint32:
 > unexpected character: �, parsing 664 ...nerPort":n... at
 > {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"labels":{"app":"aai-sparky-be","chart":"aai-sparky-be-3.0.0","heritage":"Tiller","release":"aaa-aai"},"name":"aaa-aai-aai-sparky-be","namespace":"onap"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"aai-sparky-be"}},"template":{"metadata":{"labels":{"app":"aai-sparky-be","release":"aaa-aai"},"name":"aai-sparky-be"},"spec":{"containers":[{"image":"nexus3.onap.org:10001/onap/sparky-be:1.3.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"initialDelaySeconds":10,"periodSeconds":10,"tcpSocket":{"port":8000}},"name":"aai-sparky-be","ports":[{"containerPort":8000},{"containerPort":null}],"readinessProbe":{"initialDelaySeconds":10,"periodSeconds":10,"tcpSocket":{"port":8000}},"resources":{"limits":{"cpu":2,"memory":"4Gi"},"requests":{"cpu":0.25,"memory":"1Gi"}},"volumeMounts":[{"mountPath":"/etc/localtime","name":"localtime","readOnly":true},{"mountPath":"/opt/app/sparky/config/auth/","name":"aaa-aai-aai-sparky-be-auth-config"},{"mountPath":"/opt/app/sparky/config/portal/","name":"aaa-aai-aai-sparky-be-portal-config"},{"mountPath":"/opt/app/sparky/config/portal/BOOT-INF/classes/","name":"aaa-aai-aai-sparky-be-portal-config-props"},{"mountPath":"/var/log/onap","name":"aaa-aai-aai-sparky-be-logs"},{"mountPath":"/opt/app/sparky/config/application.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application.properties"},{"mountPath":"/opt/app/sparky/config/application-resources.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application-resources.properties"},{"mountPath":"/opt/app/sparky/config/application-ssl.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application-ssl.properties"},{"mountPath":"/opt/app/sparky/config/application-oxm-default.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application-oxm-default.properties"},{"mountPath":"/opt/app/sparky/config/application-oxm-override.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application-oxm-override.properties"},{"mountPath":"/opt/app/sparky/config/application-oxm-schema-prod.properties","name":"aaa-aai-aai-sparky-be-properties","subPath":"application-oxm-schema-prod.properties"},{"mountPath":"/opt/app/sparky/config/roles.config","name":"aaa-aai-aai-sparky-be-properties","subPath":"roles.config"},{"mountPath":"/opt/app/sparky/config/users.config","name":"aaa-aai-aai-sparky-be-properties","subPath":"users.config"}]},{"image":"docker.elastic.co/beats/filebeat:5.5.0","imagePullPolicy":"IfNotPresent","name":"filebeat-onap","volumeMounts":[{"mountPath":"/usr/share/filebeat/filebeat.yml","name":"filebeat-conf","subPath":"filebeat.yml"},{"mountPath":"/var/log/onap","name":"aaa-aai-aai-sparky-be-logs"},{"mountPath":"/usr/share/filebeat/data","name":"aai-sparky-filebeat"}]}],"imagePullSecrets":[{"name":"onap-docker-registry-key"}],"initContainers":[{"args":["--container-name","aai-elasticsearch","--container-name","aai-search-data","--container-name","aai"],"command":["/root/ready.py"],"env":[{"name":"NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"image":"oomk8s/readiness-check:2.0.0","imagePullPolicy":"IfNotPresent","name":"aai-sparky-be-readiness"}],"restartPolicy":"Always","volumes":[{"hostPath":{"path":"/etc/localtime"},"name":"localtime"},{"configMap":{"name":"aaa-aai-aai-sparky-be-prop"},"name":"aaa-aai-aai-sparky-be-properties"},{"configMap":{"name":"aaa-aai-aai-sparky-be"},"name":"aaa-aai-aai-sparky-be-config"},{"configMap":{"name":"aaa-aai-aai-sparky-be-portal"},"name":"aaa-aai-aai-sparky-be-portal-config"},{"configMap":{"name":"aaa-aai-aai-sparky-be-portal-props"},"name":"aaa-aai-aai-sparky-be-portal-config-props"},{"name":"aaa-aai-aai-sparky-be-auth-config","secret":{"secretName":"aaa-aai-aai-sparky-be"}},{"configMap":{"name":"aai-filebeat"},"name":"filebeat-conf"},{"emptyDir":{},"name":"aaa-aai-aai-sparky-be-logs"},{"emptyDir":{},"name":"aai-sparky-filebeat"},{"emptyDir":{},"name":"modeldir"}]}}}}
 > 
 > However my version of k8s is 1.8.10 so I am not sure whether it is
 > the version or aai.

Actually this fix has nothing to do with aai functionality. This only applicable when NodeSelector is used. Also resources are properly placed for all containers based on flavor defined. I am not sure why its failing actually

Patch-set: 1