Update patch set 3
Patch Set 3: Code-Review-1

Gating results
https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/183992156


******** Kubernetes Results ********
 * Nb Pods: 198
 * Nb Failed Pods: 25
 * List of Failed Pods: [
   - onap-aai-aai-7764c69fd6-h9kwv
   - onap-aai-aai-champ-7f97f98976-zz2f6
   - onap-aai-aai-graphadmin-c79fb7fcf-8nlgx
   - onap-aai-aai-graphadmin-create-db-schema-826b6
   - onap-aai-aai-resources-557c6f9d78-dlxpk
   - onap-aai-aai-sparky-be-5ff8689c54-xzk2x
   - onap-aai-aai-spike-77ccc5bf78-q8cmm
   - onap-aai-aai-traversal-7fb5558d98-7hvnq
   - onap-aai-aai-traversal-update-query-data-bdsh4
   - onap-contrib-netbox-app-695fd89fd-b6zrr
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-cq72z
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-tzlsk
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-qnqsg
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-2vnqq
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-zl2wm
   - onap-dmaap-dmaap-bc-68f4565db7-dwqkw
   - onap-sdnc-blueprints-processor-6d8c669cb-h7qfk
   - onap-sdnc-controller-blueprints-64b8cf4c7c-gnrhx
   - onap-so-so-bpmn-infra-7b4cf7dbf4-m5p5n
   - onap-so-so-catalog-db-adapter-684f7f7f57-62tjr
   - onap-so-so-openstack-adapter-6c75fcdd89-h4w9r
   - onap-so-so-request-db-adapter-6797d64c57-bsnkp
   - onap-so-so-sdc-controller-849949db55-xbwbm
   - onap-so-so-vfc-adapter-6df5476d68-zw65t]
 * Deployment Duration Estimation (s): 3600

*********** Helm Results ***********
 * Nb Helm Charts: 27
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]

******** Healthcheck Results *******

new pomba healthcheck run but 2 Pomba healthcheck tests Fail

Basic Pomba AAI-context-builder Health Check           | PASS |
----------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check           | PASS |
----------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check  | PASS |
----------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check              | PASS |
----------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check     | PASS |
----------------------------------------------------------------------
Basic Pomba Validation-Service Health Check                 | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-validation-service.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f284c7b3f50>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                    | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-kibana.onap', port=5601): Max retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', BadStatusLine("''",)))
----------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                  | PASS |

Patch-set: 3
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1