Update patch set 7
Patch Set 7: Code-Review-1

gating: errors on OOF healthcheck

Basic OOF-Homing Health Check                                         | FAIL |
SSLError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by SSLError(SSLError(1, u'[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)'),))

Patch-set: 7
Label: Code-Review=-1