Update patch set 1
Patch Set 1:

Results of the OOM Gating
temporarily available at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169430139/artifacts/download

k8s status checks at the end of the installation
onap-aai-aai-sparky-be-8664d99588-2nddd                        1/2       CrashLoopBackOff   11         48m
onap-appc-appc-ansible-server-598558f644-zh65h                 0/1       CrashLoopBackOff   10         48m
onap-dmaap-dmaap-bus-controller-577d694c69-zzgvm               0/1       ImagePullBackOff   0          47m
onap-dmaap-dmaap-dr-node-b488b99b5-sgzpv                       1/2       CrashLoopBackOff   11         47m

Note on previous OOM gating (https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169330807) onap-aai-aai-sparky-be-8664d99588-2nddd was up&running

helm 
Chart onap-sdnc
STATUS: FAILED
Chart problem

Healthcheck (5 errors on medium)

Basic APPC Health Check                                  | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                        | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb73b84690>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------Basic SDNC Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb7393cb50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic SO Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb739a1490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                         | FAIL |

Patch-set: 1