Update patch set 1
Patch Set 1:

> > > > I think I found the problem.
 > > > > It is in sparky-be deployment
 > > > > ports:
 > > > > - containerPort: 8000
 > > > > - containerPort:
 > > > >
 > > > > In manifest it is:
 > > > > ports:
 > > > > - containerPort: {{ .Values.service.internalPort }}
 > > > > - containerPort: {{ .Values.service.internalPort2 }}
 > > > > while internalPort2 is not defined.
 > > >
 > > > OK; not sure how come that commit was made
 > >
 > > Tried to fix this (by removing the offending line in
 > > deployment.yaml)
 > > Still aai deployment fails. Guess the chart is too big.
 > > # helm upgrade -i aaa-aai local/aai --namespace onap -f
 > > ~/global-values.yaml --set global.pullPolicy=IfNotPresent,aai.enabled=true
 > > Release "aaa-aai" does not exist. Installing it now.
 > > NAME:   aaa-aai
 > > Error: getting deployed release "aaa-aai": release: "aaa-aai" not
 > > found
 > >
 > > # helm upgrade -i aaa-aai local/aai --namespace onap -f
 > > ~/global-values.yaml --set global.pullPolicy=IfNotPresent,aai.enabled=true
 > > --debug --dry-run > /tmp/aai-deploy.txt
 > > # ls -l /tmp/aai-deploy.txt
 > > -rw-r--r-- 1 root root 1070321 Dec 19 08:23 /tmp/aai-deploy.txt
 > > Will open a bug.
 > 
 > https://jira.onap.org/browse/OOM-1556

I saw the other problem with ONAP itself. Helm is unable to handle all the charts  since ONAP is too big? It fails saying that release not found but it actually deploys the pods

Patch-set: 1
Reviewer: Gerrit User 1551 <1551@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0