Update patch set 1
Patch Set 1:

@Dominik,
here's what I could retrieve:

cat .helm/plugins/deploy/cache/onap/logs/onap-policy.log

Release "onap-policy" does not exist. Installing it now.
Error: YAML parse error on policy/charts/policy-distribution/templates/deployment.yaml: error converting YAML to JSON: yaml: line 43: did not find expected key

Patch-set: 1