Update patch set 21
Patch Set 21:

I'm not sure it's the issue but it seems we have an SQL issue also:
2021-03-28 13:09:29 [main] ERROR org.onap.ccsdk.sli.core.sli.SvcLogicLoader - Couldn't load graph at /opt/onap/sdnc/svclogic/graphs/datachange/DataChange_tapi-update-network-to-aai.xml
org.onap.ccsdk.sli.core.sli.SvcLogicException: Could not write object to database
	at org.onap.ccsdk.sli.core.sli.SvcLogicLoader.saveGraph(SvcLogicLoader.java:147)
	at org.onap.ccsdk.sli.core.sli.SvcLogicLoader.loadGraphs(SvcLogicLoader.java:116)
	at org.onap.ccsdk.sli.core.sli.SvcLogicLoader.loadAndActivate(SvcLogicLoader.java:61)
	at org.onap.ccsdk.sli.core.sli.SvcLogicParser.main(SvcLogicParser.java:411)
Caused by: org.onap.ccsdk.sli.core.sli.SvcLogicException: Could not write object to database
	at org.onap.ccsdk.sli.core.sli.SvcLogicJdbcStore.store(SvcLogicJdbcStore.java:482)
	at org.onap.ccsdk.sli.core.sli.SvcLogicLoader.saveGraph(SvcLogicLoader.java:145)
	... 3 more
Caused by: java.sql.SQLDataException: (conn=354) Data too long for column 'graph' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:231)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:248)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:192)
	at org.onap.ccsdk.sli.core.sli.SvcLogicJdbcStore.store(SvcLogicJdbcStore.java:477)
	... 4 more
Caused by: java.sql.SQLException: Data too long for column 'graph' at row 1
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:289)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)
	... 7 more

Patch-set: 21
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>