Update patch set 3
Patch Set 3:

Gitlab.com: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 224
 * Nb Failed Pods: 7
 * List of Failed Pods: [
   - onap-dmaap-message-router-zookeeper-0
   - onap-policy-policy-distribution-69c9f645f-h9s42
   - onap-sdnc-cds-blueprints-processor-bbd6db67d-p75z6
   - onap-sdnc-cds-command-executor-56554848b9-l4wsg
   - onap-sdnc-cds-controller-blueprints-69c69fbf88-9pwrw
   - onap-sdnc-cds-sdc-listener-6f88c56dfc-gxqz6
   - onap-so-so-openstack-adapter-564678bf7f-cspt7
   - onap-so-so-sdc-controller-979dcb8cc-cwv6h]
*********** Helm Results ***********
 * Nb Helm Charts: 30
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-sdnc]
******** Healthcheck Results *******
2019-08-28 22:22:53,473 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='policy-distribution.onap', port=6969): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f465f4c0490>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f465f41e990>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-sdc-controller.onap', port=8085): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f465f414510>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f465f318d90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 54 passed, 7 failed
61 tests total, 54 passed, 7 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 3
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0