Update patch set 12
Patch Set 12:

you have an issue with helm: Release "onap-policy" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.initContainers[0].volumeMounts[0]): unknown field "valueFrom" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.initContainers[0].volumeMounts[0]): missing required field "mountPath" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.initContainers[0].volumeMounts[1]): unknown field "valueFrom" in io.k8s.api.core.v1.VolumeMount, ValidationError(Deployment.spec.template.spec.initContainers[0].volumeMounts[1]): missing required field "mountPath" in io.k8s.api.core.v1.VolumeMount]

Patch-set: 12
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>