Update patch set 13
Patch Set 13:

> Patch Set 13:
> 
> > Patch Set 13:
> > 
> > > Patch Set 13: Code-Review-1
> > > 
> > > basic network => requestState":"FAILED","statusMessage":"STATUS: Error Source: SDNC, Error Message: Error from SDNC: 'Error: No preload-network found with network-name =' + $tmp.network-instance-name + ' in md-sal' FLOW STATUS: UnassignNetworkBB has failed.
> > > 
> > > basic_cnf looping stuck in PROGRESS state on vnf creation using à la carte flow
> > > 
> > > basic_vm: SDC issue
> > 
> > I need to see the sdnc log from when this was run.  The onap-sdnc-0 log stops before the test is run, so I can't see what the error is.
> 
> https://logs.onap.org/onap-integration/gating//118284-13/infrastructure-healthcheck/k8s-teardown/kubernetes-status/pod-onap-sdnc-0-sdnc-logs.html
> 
> I see dozen of:
> 2021-03-23T01:41:54,176 | ERROR | qtp1626453181-778 | ExecuteNodeExecutor              | 274 - org.onap.ccsdk.sli.core.sli-provider-base - 1.2.0 | SvcLogicGraph [module=A1-ADAPTER-API, rpc=getA1Policy, mode=sync, version=1.1.1, md5sum=9c922f4e29ca0e30dad6d011737a1615] - 8 (execute)  | Could not execute plugin. SvcLogic status will be set to failure.
> org.onap.ccsdk.sli.core.sli.SvcLogicException: 500: Exception while posting http request to client URI is not absolute

Thanks for the full log - I found the culprit:
2021-03-23T01:04:46,674 | ERROR | qtp1626453181-124 | MdsalHelper                      | 273 - org.onap.ccsdk.sli.core.sli-provider - 1.2.0 |  -   | Caught exception trying to convert List returned by org.opendaylight.yang.gen.v1.org.onap.sdnc.northbound.generic.resource.rev170824.preload.network.topology.information.PreloadNetworkTopologyInformation.getVpnBindings() to Properties entry
java.lang.NullPointerException: null

We're hitting an error when we try to load the preload data - it's not properly handling the case where some data is missing.  The code fix looks pretty straightforward - should be ready no later than tomorrow (today, if I can get all the builds done and merged ... that's the real bottleneck.)

Patch-set: 13
Reviewer: Gerrit User 87 <87@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>