Update patch set 1
Patch Set 1: Code-Review+1

the patchset triggered the deployment of a OOM solution (versions based on OOM helm chart + patchset) + some tests
all results are temporarily stored at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/168983086.

errors not linked to the patchset (sdc-wfd-fe)

6 pods not in Running state at the end of the installation
onap-appc-appc-ansible-server-598558f644-bqrxl                 0/1       CrashLoopBackOff   15         1h
onap-dmaap-dmaap-bus-controller-577d694c69-66bqd               0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-b488b99b5-bv62d                       1/2       CrashLoopBackOff   19         1h
onap-oof-oof-has-data-c7788fc4d-4sh7m                          0/1       Init:2/4           5          1h
onap-oof-oof-has-reservation-6cb9fd8b48-55hww                  0/1       Init:2/4           6          1h
onap-oof-oof-has-solver-54f46bbccc-qmmb2                       0/1       Init:2/4           6          1h

1 helm chart in FAILED status (onap-vnfsdk)
first occurence of this error

----------------------------------------------------------------------
Basic APPC Health Check                         | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------Basic DMAAP Data Router Health Check            | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c869fab10>: Failed to establish a new connection: [Errno 111] Connection refused',))

E2E not executed

but 
Basic SDC Health Check     | PASS |

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1