Update patch set 3
Patch Set 3:

FYI after this was merged, I'm getting this error on helm install:

Error: error validating "": error validating data: found invalid field imagePullSecrets for v1.PersistentVolumeClaimSpec

I've updated OOM-779 to report this issue.

Patch-set: 3
Reviewer: Gerrit User 35 <35@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0