Update patch set 3
Patch Set 3:

> Error: found in requirements.yaml, but missing in charts/
 > directory: common
 > The command helm returned with error code 1

This Error, We usually gets as we need to update the dependencies as well before running helm install


so here, we need to run helm dep up robot before install and as well we need to install setup component too.

I dont think, If createall.bash covers this type of installation.

So we may need to derive new script or to document this installation process with standardization tasks going inside.

Patch-set: 3
Reviewer: Gerrit User 2903 <2903@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0