Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//97224-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 209
 * Nb Failed Pods: 33
 * List of Failed Pods: [
   - onap-aai-aai-sparky-be-68bcf7c4c-k94fn
   - onap-cds-cds-sdc-listener-75c5fd5ffb-x7xmd
   - onap-dcaegen2-dcae-dashboard-755449d876-wn8gg
   - onap-dcaegen2-dcae-deployment-handler-66986dbf7b-plhbj
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-zvhk5
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-b4trf
   - onap-dmaap-message-router-mirrormaker-5bd5cbc745-rqtvr
   - onap-oof-oof-d8f7dbfbf-c4bjh
   - onap-oof-oof-has-api-7b7f4c95b9-n5bxm
   - onap-oof-oof-has-controller-7db5bf5f8b-vsmng
   - onap-oof-oof-has-data-8dc9c79dd-mpnxk
   - onap-oof-oof-has-reservation-589cc655f4-9vdjr
   - onap-oof-oof-has-solver-55d9849c69-sjsjt
   - onap-sdc-sdc-be-8485bc5558-z4jq5
   - onap-sdc-sdc-dcae-be-85c669ddbf-4wf5m
   - onap-sdc-sdc-dcae-be-tools-zn488
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-th7vm
   - onap-sdc-sdc-dcae-fe-5488b88f8c-bx659
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-pxhvz
   - onap-sdc-sdc-fe-5cfcddf448-d5bm2
   - onap-sdc-sdc-kb-5b48c6fd44-rzpn7
   - onap-sdc-sdc-onboarding-be-8c84cb794-s7wcj
   - onap-sdc-sdc-onboarding-be-cassandra-init-twxkc
   - onap-sdc-sdc-wfd-be-54ff7b9948-7pxvl
   - onap-sdc-sdc-wfd-fe-647d64468f-9v4mk
   - onap-sdnc-sdnc-ueb-listener-5d78c9c586-fhmxt
   - onap-so-so-55844c65cf-drjwg
   - onap-so-so-bpmn-infra-6f4bf9bd69-4hz95
   - onap-so-so-catalog-db-adapter-b7db48446-gxdpx
   - onap-so-so-openstack-adapter-558795cbb6-dswkt
   - onap-so-so-request-db-adapter-68f6988cbd-744g9
   - onap-so-so-sdc-controller-59fc7d59d4-dzczl
   - onap-so-so-vfc-adapter-65f66cbbd9-lcxvf]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-10-17 03:25:04,916 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f44da314090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1