Update patch set 1
Patch Set 1:

Gitlab Orange 3: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98968-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 226
 * Nb Failed Pods: 23
 * List of Failed Pods: [
   - onap-aai-aai-6c667745-pgjnm
   - onap-aai-aai-data-router-7cd8669b68-srlx2
   - onap-aai-aai-graphadmin-67859ff78c-4jsth
   - onap-aai-aai-graphadmin-create-db-schema-sl6xh
   - onap-aai-aai-graphgraph-5875c7ffdb-8k7kh
   - onap-aai-aai-resources-59b7c66784-4sftq
   - onap-aai-aai-sparky-be-756d5dc559-6mkpn
   - onap-aai-aai-traversal-b8b5498db-jbv5n
   - onap-cassandra-cassandra-2
   - onap-cds-cds-sdc-listener-75c5fd5ffb-xwgg4
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-962f9
   - onap-sdc-sdc-be-569bf64759-kwxwn
   - onap-sdc-sdc-dcae-be-877f5d9c4-hdtkz
   - onap-sdc-sdc-dcae-dt-77fbfbcb7-4wdrw
   - onap-sdc-sdc-dcae-fe-779f6767cd-lwz6j
   - onap-sdc-sdc-dcae-tosca-lab-86956f76c6-48lsd
   - onap-sdc-sdc-fe-cdcc4cfff-vx62z
   - onap-sdc-sdc-onboarding-be-59dc6f9f9f-bzxr7
   - onap-sdc-sdc-wfd-be-5c8747d55d-5v26b
   - onap-sdc-sdc-wfd-be-workflow-init-gfdrr
   - onap-sdc-sdc-wfd-fe-fbccb85d-t9l5p
   - onap-sdnc-sdnc-ueb-listener-5f57ff6d5f-v6q49
   - onap-vfc-vfc-ems-driver-86bdb477f4-zbcfl]
*********** Helm Results ***********
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 0
 * List of Failed Helm Charts: []
******** Healthcheck Results *******
2019-11-29 18:46:56,636 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fab2d0e2ad0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fab2d4ea590>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 53 passed, 8 failed
61 tests total, 53 passed, 8 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-11-29 18:44:53,334 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2a5651e750>: Failed to establish a new connection: [Errno 111] Connection refused',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1