Update patch set 1
Patch Set 1:

Weird that after applying this patch helm upgrade fails for AAI.  I am not sure what in this patch is causing it since it is all configmaps changes.

There is a long gross error but the jist of it is: 

Error: UPGRADE FAILED: Job.batch "aai-aai-graphadmin-create-db-schema"
is invalid: spec.template: Invalid value: core.PodTemplateSpec {
....
....

field is immutable


to reproduce..deploy aai without this patch,
-cherry-pick it, re-make the aai chart 
-upgrade the existing release with the newly built one that includes this change..
-see it fail.

Purging and re-installing works fine....Waiting to hear back from you folks before proceeding with this one..

Patch-set: 1