Update patch set 2
Patch Set 2: Code-Review-1

==============================================================================
Basic SO Health Check                                                 [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1426bafed0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1426bafc90>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1426baf1d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
| FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1426baf390>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Testsuites.Health-Check :: Test that ONAP components are available... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

Patch-set: 2