Update patch set 9
Patch Set 9: Code-Review+2

results directly from the k8s (gating results has gone mad):
onap-dmaap-dbc-pg-0                                            1/1     Running            0          120m
onap-dmaap-dbc-pg-1                                            1/1     Running            0          119m
onap-dmaap-dbc-pgpool-5894b6b587-2966j                         1/1     Running            0          120m
onap-dmaap-dbc-pgpool-5894b6b587-sgf5j                         1/1     Running            0          120m
onap-dmaap-dmaap-bc-5dcc9997c4-psf7l                           1/1     Running            0          96m
onap-dmaap-dmaap-bc-post-install-ll78s                         0/1     Completed          0          120m
onap-dmaap-dmaap-dr-db-0                                       1/1     Running            0          120m
onap-dmaap-dmaap-dr-db-1                                       1/1     Running            0          119m
onap-dmaap-dmaap-dr-node-0                                     2/2     Running            0          120m
onap-dmaap-dmaap-dr-prov-584b6bdd88-x9psc                      2/2     Running            0          120m
onap-dmaap-message-router-0                                    1/1     Running            0          120m
onap-dmaap-message-router-kafka-0                              1/1     Running            0          120m
onap-dmaap-message-router-kafka-1                              1/1     Running            0          120m
onap-dmaap-message-router-kafka-2                              1/1     Running            2          120m
onap-dmaap-message-router-mirrormaker-56d96bf84-d9nbw          1/1     Running            3          120m
onap-dmaap-message-router-zookeeper-0                          1/1     Running            0          120m
onap-dmaap-message-router-zookeeper-1                          1/1     Running            0          120m
onap-dmaap-message-router-zookeeper-2                          1/1     Running            0          120m




kubectl logs -n onap onap-dmaap-dmaap-bc-5dcc9997c4-psf7l
+ config
+ echo 'ENTER config'
+ set -x
+ '[' '!' -d /opt/app/dmaapbc ]
+ cd /opt/app/dmaapbc
+ '[' '!' -f /opt/app/config/conf/buscontroller.env ]
+ source /opt/app/config/conf/buscontroller.env
ENTER config
+ DMAAPBC_WAIT_TO_EXIT=Y
+ '[' Y '!=' Y ]
+ echo 'Not creating /opt/app/dmaapbc/ok_to_exit'
Not creating /opt/app/dmaapbc/ok_to_exit
+ . misc/havecert.tmpl
+ cat
+ date '+%F %T,000'
+ chmod +x etc/havecert
+ '[' -f /opt/app/config/conf/dmaapbc.properties ]
+ PROPS=/opt/app/config/conf/dmaapbc.properties
+ '[' '!' -f config/PolicyEngineApi.properties ]
+ . misc/PolicyEngineApi.properties.tmpl
+ cat
+ set +x
+ authcheck
+ set -x
ENTER start
+ id -n -u
+ ID=dbc
+ id -n -g
+ GRP=onap
+ '[' dbc '!=' dbc ]
+ '[' onap '!=' onap ]
+ set +x
/opt/app/dmaapbc
+ ps -ef
+ grep java
+ grep org.onap.dmaap.dbcapi.server.Main
+ sed -e 's/[^ ]* *//' -e 's/ .*//'
+ set +x
log4j:WARN No appenders could be found for logger (org.onap.dmaap.dbcapi.aaf.DmaapPerm).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
org.eclipse.jetty.server.Server@5ae50ce6[9.4.z-SNAPSHOT] - STARTED
 += QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}] - STARTED
 |   += ReservedThreadExecutor@435871cb{s=0/2,p=0} - STARTED
 |   +> 28 qtp1691875296-28-acceptor-0@68f6f96c-ServerConnector@a4b2d8f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} ACCEPTING RUNNABLE @ sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) prio=3
 |   +> 33 qtp1691875296-33 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
 |   +> 34 qtp1691875296-34 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
 |   +> 32 qtp1691875296-32 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
 |   +> 29 qtp1691875296-29-acceptor-0@2e5c7043-ServerConnector@590c73d3{SSL,[ssl, http/1.1]}{0.0.0.0:8443} ACCEPTING RUNNABLE @ sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) prio=3
 |   +> 31 qtp1691875296-31 IDLE TIMED_WAITING @ sun.misc.Unsafe.park(Native Method)
 |   +> 27 qtp1691875296-27 SELECTING RUNNABLE @ sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 |   +> 30 qtp1691875296-30 SELECTING RUNNABLE @ sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 |   +> jobs - size=0
 += ServerConnector@a4b2d8f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} - STARTED
 |   +~ org.eclipse.jetty.server.Server@5ae50ce6[9.4.z-SNAPSHOT] - STARTED
 |   +~ QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}] - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@12d3a4e9 - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@609640d5
 |   += HttpConnectionFactory@14a2f921[HTTP/1.1] - STARTED
 |   |   +- HttpConfiguration@79da1ec0{32768/8192,8192/8192,https://:8443,[]}
 |   += SelectorManager@ServerConnector@a4b2d8f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} - STARTED
 |   |   += org.eclipse.jetty.io.ManagedSelector@4a3329b9 id=0 keys=0 selected=0 updates=0 - STARTED
 |   |       += EatWhatYouKill@3dddefd8/SelectorProducer@285c08c8/PRODUCING/p=false/QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}][pc=0,pic=0,pec=0,epc=0]@2019-12-10T14:09:29.534Z - STARTED
 |   |       |   +- SelectorProducer@285c08c8
 |   |       |   +~ QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}] - STARTED
 |   |       +> updates @ 2019-12-10T14:09:29.528Z
 |   |       +> keys @ 2019-12-10T14:09:29.532Z
 |   |           +- sun.nio.ch.EPollSelectorImpl@25b0ddeb keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:8080]
 |   +- qtp1691875296-28-acceptor-0@68f6f96c-ServerConnector@a4b2d8f{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
 += ServerConnector@590c73d3{SSL,[ssl, http/1.1]}{0.0.0.0:8443} - STARTED
 |   +~ org.eclipse.jetty.server.Server@5ae50ce6[9.4.z-SNAPSHOT] - STARTED
 |   +~ QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}] - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@3e3047e6 - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@295eaa7c
 |   += SslConnectionFactory@37e547da{SSL->http/1.1} - STARTED
 |   |   += SslContextFactory@51cd7ffc[provider=null,keyStore=file:///opt/app/dmaapbc/etc/keystore,trustStore=file:///opt/app/dmaapbc/etc/org.onap.dmaap-bc.trust.jks] trustAll=false
 |   |       +- Protocol Selections
 |   |       |   +- Enabled (size=3)
 |   |       |   |   +- TLSv1
 |   |       |   |   +- TLSv1.1
 |   |       |   |   +- TLSv1.2
 |   |       |   +- Disabled (size=2)
 |   |       |       +- SSLv2Hello - ConfigExcluded:'SSLv2Hello'
 |   |       |       +- SSLv3 - JreDisabled:java.security, ConfigExcluded:'SSLv3'
 |   |       +- Cipher Suite Selections
 |   |           +- Enabled (size=28)
 |   |           |   +- TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
 |   |           |   +- TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
 |   |           |   +- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
 |   |           |   +- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
 |   |           |   +- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
 |   |           |   +- TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
 |   |           |   +- TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
 |   |           |   +- TLS_RSA_WITH_AES_128_CBC_SHA256
 |   |           |   +- TLS_RSA_WITH_AES_128_GCM_SHA256
 |   |           |   +- TLS_RSA_WITH_AES_256_CBC_SHA256
 |   |           |   +- TLS_RSA_WITH_AES_256_GCM_SHA384
 |   |           +- Disabled (size=14)
 |   |               +- TLS_DHE_DSS_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_DHE_DSS_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_DHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_DHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDH_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_ECDH_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_RSA_WITH_AES_128_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   |               +- TLS_RSA_WITH_AES_256_CBC_SHA - ConfigExcluded:'^.*_(MD5|SHA|SHA1)$'
 |   += HttpConnectionFactory@2b6856dd[HTTP/1.1] - STARTED
 |   |   +- HttpConfiguration@56c9bbd8{32768/8192,8192/8192,https://:8443,[SecureRequestCustomizer@630cb4a4]}
 |   += SelectorManager@ServerConnector@590c73d3{SSL,[ssl, http/1.1]}{0.0.0.0:8443} - STARTED
 |   |   += org.eclipse.jetty.io.ManagedSelector@636e8cc id=0 keys=0 selected=0 updates=0 - STARTED
 |   |       += EatWhatYouKill@f79a760/SelectorProducer@14f5da2c/PRODUCING/p=false/QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}][pc=0,pic=0,pec=0,epc=0]@2019-12-10T14:09:29.548Z - STARTED
 |   |       |   +- SelectorProducer@14f5da2c
 |   |       |   +~ QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}] - STARTED
 |   |       +> updates @ 2019-12-10T14:09:29.548Z
 |   |       +> keys @ 2019-12-10T14:09:29.548Z
 |   |           +- sun.nio.ch.EPollSelectorImpl@6c40d175 keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:8443]
 |   +- qtp1691875296-29-acceptor-0@2e5c7043-ServerConnector@590c73d3{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
 += o.e.j.s.ServletContextHandler@7c2b6087{/,null,AVAILABLE} - STARTED
 |   += org.eclipse.jetty.server.session.SessionHandler316335490==dftMaxIdleSec=-1 - STARTED
 |   |   += org.eclipse.jetty.servlet.ServletHandler@239b0f9d - STARTED
 |   |   |   += org.glassfish.jersey.servlet.ServletContainer-5dd6264@16440921==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=1,inst=true - STARTED
 |   |   |   |   +- jersey.config.server.provider.packages=org.onap.dmaap.dbcapi.resources
 |   |   |   |   +- javax.ws.rs.Application=org.onap.dmaap.dbcapi.server.ApplicationConfig
 |   |   |   +- [/webapi/*]=>org.glassfish.jersey.servlet.ServletContainer-5dd6264
 |   |   |   += org.eclipse.jetty.servlet.DefaultServlet-5e316c74@bb02a7d7==org.eclipse.jetty.servlet.DefaultServlet,jsp=null,order=-1,inst=false - STARTED
 |   |   |   |   +- pathInfoOnly=true
 |   |   |   |   +- resourceBase=www
 |   |   |   +- [/*]=>org.eclipse.jetty.servlet.DefaultServlet-5e316c74
 |   |   |   += org.onap.dmaap.dbcapi.resources.AAFAuthenticationFilter-bef2d72 - STARTED
 |   |   |   +- [/webapi/*]/[]==3=>org.onap.dmaap.dbcapi.resources.AAFAuthenticationFilter-bef2d72
 |   |   |   += org.onap.dmaap.dbcapi.resources.AAFAuthorizationFilter-6fe7aac8 - STARTED
 |   |   |   +- [/webapi/*]/[]==3=>org.onap.dmaap.dbcapi.resources.AAFAuthorizationFilter-6fe7aac8
 |   |   |   += org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-43195e57@579e006d==org.eclipse.jetty.servlet.ServletHandler$Default404Servlet,jsp=null,order=-1,inst=false - STARTED
 |   |   |   +- [/]=>org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-43195e57
 |   |   += org.eclipse.jetty.server.session.DefaultSessionCache@1eb6749b[evict=-1,removeUnloadable=false,saveOnCreate=false,saveOnInactiveEvict=false] - STARTED
 |   |   |   += org.eclipse.jetty.server.session.NullSessionDataStore@652a7737[passivating=false,graceSec=3600] - STARTED
 |   |   +~ org.eclipse.jetty.server.session.DefaultSessionIdManager@5b7ea70d[worker=node0] - STARTED
 |   +> No ClassLoader
 |   +> Handler attributes o.e.j.s.ServletContextHandler@7c2b6087{/,null,AVAILABLE}
 |   |   +- org.eclipse.jetty.server.Executor=QueuedThreadPool[qtp1691875296]@64d7f7e0{STARTED,8<=8<=200,i=4,q=0}[ReservedThreadExecutor@435871cb{s=0/2,p=0}]
 |   +> Context attributes o.e.j.s.ServletContextHandler@7c2b6087{/,null,AVAILABLE}
 |   |   +- org.eclipse.jetty.util.DecoratedObjectFactory=org.eclipse.jetty.util.DecoratedObjectFactory[decorators=1]
 |   +> Initparams o.e.j.s.ServletContextHandler@7c2b6087{/,null,AVAILABLE}
 += org.eclipse.jetty.server.handler.ErrorHandler@2bef51f2 - STARTED
 += org.eclipse.jetty.server.session.DefaultSessionIdManager@5b7ea70d[worker=node0] - STARTED
 |   += org.eclipse.jetty.server.session.HouseKeeper@650eab8[interval=600000, ownscheduler=true] - STARTED
 +> sun.misc.Launcher$AppClassLoader@7852e922
     +- file:/opt/app/dmaapbc/etc/
     +- file:/opt/app/dmaapbc/lib/dmaap-bc.jar
     +- sun.misc.Launcher$ExtClassLoader@6e0e048a
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/cldrdata.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/dnsns.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/jaccess.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/localedata.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/nashorn.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/sunec.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/sunjce_provider.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/sunpkcs11.jar
         +- file:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext/zipfs.jar
+ ps -ef
+ grep java
+ grep org.onap.dmaap.dbcapi.server.Main
+ sed -e 's/[^ ]* *//' -e 's/ .*//'
+ set +x

==============================================================================
Testsuites
==============================================================================
Testsuites.Health-Check :: Test that ONAP components are available via basi...
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                (DMaaP:UP)
| PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43a21b5650>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /manage/health
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43a21b58d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /manage/health
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43a21b5b50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /manage/health
| FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f43a28aead0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Testsuites.Health-Check :: Test that ONAP components are available... | FAIL |
6 critical tests, 5 passed, 1 failed
6 tests total, 5 passed, 1 failed
==============================================================================
Testsuites                                                            | FAIL |
6 critical tests, 5 passed, 1 failed
6 tests total, 5 passed, 1 failed
==============================================================================



So if Dom is OK, merge is good for me

Patch-set: 9
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2