Update patch set 6
Patch Set 6: Code-Review-1

Release "onap-cert-wrapper" does not exist. Installing it now.
Error: render error in "cert-wrapper/charts/certInitializer/templates/secret.yaml": template: cert-wrapper/charts/certInitializer/templates/secret.yaml:17:3: executing "cert-wrapper/charts/certInitializer/templates/secret.yaml" at <include "common.secretFast" .>: error calling include: template: no template "common.secretFast" associated with template "gotpl"

Patch-set: 6
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1