Update patch set 3
Patch Set 3:

Release "onap-so" does not exist. Installing it now.
2021/01/07 19:12:10 Warning: Merging destination map for chart 'so-cnf-adapter'. Overwriting table item 'wait_for', with non table value: [so-mariadb-config]
NAME:   onap-so
Error: getting deployed release "onap-so": release: "onap-so" not found

Patch-set: 3
Reviewer: Gerrit User 897 <897@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>