Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> > Patch Set 11: Code-Review-1
> > 
> > > Patch Set 11:
> > > 
> > > Gitlab Azure AKS 4: 
> > > Full results can be seen here: https://logs.onap.org/onap-integration/gating//118421-11/index.html
> > > ______________ Results ______________________
> > > 
> > > ************************************************************
> > > ************************************************************
> > > ************ Infrastructure-healthcheck Results ************
> > > ************************************************************
> > > ************************************************************
> > > --------> onap-k8s
> > >  * Nb Jobs: 29
> > >  * Nb Failed Jobs: 3
> > >  * List of Failed Jobs: [
> > >    - integration-onap-internal-check-certs
> > >    - onap-oof-has-healthcheck
> > >    - onap-sdc-be-config-backend]
> > >  * Nb Deployments: 151
> > >  * Nb Failed Deployments: 10
> > >  * List of Failed Deployments: [
> > >    - onap-aai-sparky-be
> > >    - onap-cds-sdc-listener
> > >    - onap-dcae-servicechange-handler
> > >    - onap-dcae-ves-openapi-manager
> > >    - onap-oof-has-data
> > >    - onap-oof-has-reservation
> > >    - onap-oof-has-solver
> > >    - onap-sdc-be
> > >    - onap-sdc-fe
> > >    - onap-sdnc-ueb-listener]
> > >  * Nb StatefulSets: 27
> > >  * Nb Failed StatefulSets: 0
> > >  * Nb Persistent Volume Claims: 75
> > >  * Nb Failed Persistent Volume Claims: 1
> > >  * List of Failed Persistent Volume Claims: [
> > >    - onap-aaf-sshsm-distcenter]
> > > --------> onap-helm
> > >  * Nb Helms: 34
> > >  * Nb Failed Helms: 0
> > > 
> > > ************************************************************
> > > ************************************************************
> > > ********************* Healthcheck Results ******************
> > > ************************************************************
> > > ************************************************************
> > > --------> robot full healthcheck tests
> > > 2021-03-05 02:30:29,714 - xtesting.core.robotframework - INFO - 
> > > ==============================================================================
> > > Health-Check :: Test that ONAP components are available via basic API calls   
> > > ==============================================================================
> > > Basic A&AI Health Check                                               | PASS |
> > > ------------------------------------------------------------------------------
> > > Enhanced A&AI Health Check                                            | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic AAF Health Check                                                | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic AAF SMS Health Check                                            | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic APPC Health Check                                               | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic CLI Health Check                                                | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic CLAMP Health Check                                              | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic DCAE Health Check                                               | FAIL |
> > > 500 != 200
> > > ------------------------------------------------------------------------------
> > > Basic DMAAP Data Router Health Check                                  | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic DMAAP Message Router Health Check                               | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic External API NBI Health Check                                   | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Microservice Bus Health Check                                   | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud API Health Check                                     | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-pike API Health Check                                | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-starlingx API Health Check                           | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-vio API Health Check                                 | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-k8s API Health Check                                 | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic OOF-Homing Health Check                                         | FAIL |
> > > Test timeout 20 seconds exceeded.
> > > ------------------------------------------------------------------------------
> > > Basic OOF-OSDF Health Check                                           | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic OOF-CMSO Health Check                                           | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Policy Health Check                                             | PASS |
> > > ------------------------------------------------------------------------------
> > > Enhanced Policy New Healthcheck                                       | FAIL |
> > > 200 != 202
> > > ------------------------------------------------------------------------------
> > > Basic Portal Health Check                                             | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic SDC Health Check                                                | FAIL |
> > > ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f55dd1d42d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > > ------------------------------------------------------------------------------
> > > Enhanced SDC Health Check                                             | FAIL |
> > > ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f55dc917b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > > ------------------------------------------------------------------------------
> > > Basic SDNC Health Check                                               | PASS |
> > > ------------------------------------------------------------------------------
> > > Enhanced SDNC Health Check                                            | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic SO Health Check                                                 | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic UseCaseUI API Health Check                                      | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC gvnfmdriver API Health Check                                | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC nslcm API Health Check                                      | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC vnflcm API Health Check                                     | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC vnfmgr API Health Check                                     | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC vnfres API Health Check                                     | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VFC ztevnfmdriver API Health Check                              | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic VID Health Check                                                | FAIL |
> > > 500 != 200
> > > ------------------------------------------------------------------------------
> > > Basic VNFSDK Health Check                                             | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Multicloud-fcaps API Health Check                               | PASS |
> > > ------------------------------------------------------------------------------
> > > Basic Modeling genericparser API Health Check                         | PASS |
> > > ------------------------------------------------------------------------------
> > > Enhanced CDS Health Check                                             | PASS |
> > > ------------------------------------------------------------------------------
> > > Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> > > 43 critical tests, 37 passed, 6 failed
> > > 43 tests total, 37 passed, 6 failed
> > > ==============================================================================
> > > Output:  /var/lib/xtesting/results/full/output.xml
> > > 
> > > ************************************************************
> > > ************************************************************
> > > ********************* Basic tests Results ******************
> > > ************************************************************
> > > ************************************************************
> > > --------> healthdist (vFW onboarding and distribution)
> > > Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> > > --------> postinstall tests (dmaap and A&AI)
> > > Post-Install-Tests :: Testing Installation                            | PASS |
> > > --------> CMPv2 tests
> > > Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
> > > Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
> > > Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
> > > Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
> > > Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
> > > Send registration request to VES without CMPv2 certificate :: This... | PASS |
> > > Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
> > > --------> HV-VES tests
> > > Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
> > > --------> VES collector tests
> > > Ves :: Suite for checking handling events by VES Collector            | PASS |
> > > --------> Basic Onboard tests (SDC)
> > > basic_onboard: FAIL (04:33)
> > > --------> CDS tests
> > > basic_cds: PASS (00:22)
> > > 
> > > ************************************************************
> > > ************************************************************
> > > ******************** End to End usecases *******************
> > > ************************************************************
> > > ************************************************************
> > > --------> pnf-registrate tests
> > > PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
> > > Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
> > > --------> 5gbulkpm tests
> > > Setting Global Variables :: This test case checks suite if it is w... | PASS |
> > > 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> > > --------> basic_vm tests
> > > basic_vm: FAIL (04:33)
> > > --------> basic_network tests
> > > basic_network: FAIL (04:33)
> > > --------> basic_cnf tests
> > > basic_cnf: FAIL (04:33)
> > > 
> > > ************************************************************
> > > ************************************************************
> > > ********************** Security tests **********************
> > > ************************************************************
> > > ************************************************************
> > > --------> cis_kubernetes tests
> > > cis_kubernetes: PASS (00:00)
> > > --------> nonssl_endpoints tests
> > > nonssl_endpoints: FAIL (00:50)
> > > --------> jdpw_ports tests
> > > jdpw_ports: PASS (05:43)
> > > --------> kube_hunter tests
> > > kube_hunter: FAIL (00:00)
> > > --------> root_pods tests
> > > root_pods: FAIL (02:53)
> > > --------> unlimitted_pods tests
> > > unlimitted_pods: FAIL (00:58)
> > > 
> > > ____________________________________________________________
> > 
> > https://logs.onap.org/onap-integration/experimental-gating//118421-11/index.html
> > 
> > 2 deployments failing 
> > onap-dcae-servicechange-handler 	0/1 	1 	0
> > onap-dcae-ves-openapi-manager 	0/1 	1 	0
> > 
> > DCAE HC failing
> 
> onap-dcae-servicechange-handler is not up bcoz of dependency on SDC-BE (which is failed for some reason).
> 
> ves-openapi-manager was merged yesterday; just rebased to check if that clears the problem.

Actually  ves-openapi-manager also has SDC-BE dependency hence stuck on init. Hopefully redeploy will clear SDC issue.

Patch-set: 12
Reviewer: Gerrit User 93 <93@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>