Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> @Sylvain
> This patch is already on the top of master but oof-cmso HC still fails...

I believe it is not related to this review, probably OOF team should take a look at it, seems that the oof container is not coming up based on the 111 errno.

ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbd6499e090>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 2