Update patch set 1
Patch Set 1: Code-Review+1

the patchset triggered the deployment of a OOM solution (versions based on OOM helm chart + patchset) + some tests
all results are temporarily stored at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/168860061/artifacts/download

errors not linked to patch (pomba) but to the installation in general

- VID helm chart in status FAILED
- 3 pods in non Running state
onap-appc-appc-ansible-server-598558f644-r7w2t                 0/1       CrashLoopBackOff   9          42m
onap-dmaap-dmaap-bus-controller-577d694c69-s5tbj               0/1       ImagePullBackOff   0          42m
onap-dmaap-dmaap-dr-node-b488b99b5-kstxb                       1/2       CrashLoopBackOff   11         42m

Healthcheck 6 fails

Basic DCAE Health Check                 | FAIL |
500 != 200
---------------------------------------------------
Basic DMAAP Data Router Health Check    | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88ff0b2c50>: Failed to establish a new connection: [Errno 111] Connection refused',))
---------------------------------------------------
Basic Multicloud-starlingx API Health Check     | FAIL |
502 != 200
---------------------------------------------------
Basic VID Health Check                          | FAIL |
ConnectionError: HTTPConnectionPool(host='vid.onap', port=8080): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f88fed296d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
---------------------------------------------------
Basic Holmes Rule Management API Health Check     | FAIL |
502 != 200
---------------------------------------------------
Basic Holmes Engine Management API Health Check   | FAIL |
502 != 200

E2E tests not triggered

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1