Update patch set 1
Patch Set 1:

1. SDC running with comman cassandra cluster.
root@new-k8s-1:~/Mahendra/OOM_Dublin/oom_running/oom/kubernetes# helm deploy demo local/onap --version=4.0.0 --namespace onap -f ~/Mahendra/OOM_Dublin/oom_running/oom/kubernetes/onap/resources/environments/disable-allcharts.yaml --set global.pullPolicy=IfNotPresent --set sdc.enabled=true --set cassandra.enabled=true --set robot.enabled=true
fetching local/onap
release "demo" deployed
release "demo-cassandra" deployed
release "demo-robot" deployed
release "demo-sdc" deployed

root@new-k8s-1:~/Mahendra/OOM_Dublin/oom_running/oom/kubernetes# kubectl get po -n onap |egrep "Running|Completed"
demo-cassandra-cassandra-0                        1/1       Running      0          28m
demo-cassandra-cassandra-1                        1/1       Running      0          27m
demo-cassandra-cassandra-2                        1/1       Running      0          26m
demo-robot-robot-785f67844-t2qwc                  1/1       Running      0          3m
demo-sdc-sdc-be-6955d648b6-qr9wt                  2/2       Running      0          28m
demo-sdc-sdc-be-config-backend-hc4kl              0/1       Completed    0          28m
demo-sdc-sdc-cs-config-cassandra-m5vp9            0/1       Completed    0          28m
demo-sdc-sdc-dcae-be-5f8875dcf-zzj6m              2/2       Running      0          28m
demo-sdc-sdc-dcae-be-tools-9hzk9                  0/1       Completed    0          8m
demo-sdc-sdc-dcae-dt-dd758b9b4-cwdk8              2/2       Running      0          28m
demo-sdc-sdc-dcae-fe-8cdf999db-7d7ss              2/2       Running      0          28m
demo-sdc-sdc-dcae-tosca-lab-785d7bc576-7rbl4      2/2       Running      0          28m
demo-sdc-sdc-es-6fcdf64d59-ps9h5                  1/1       Running      0          28m
demo-sdc-sdc-es-config-elasticsearch-d9jmr        0/1       Completed    0          28m
demo-sdc-sdc-fe-6587579785-gggjr                  2/2       Running      0          28m
demo-sdc-sdc-kb-868cbcbcf5-45w28                  1/1       Running      0          28m
demo-sdc-sdc-onboarding-be-55b7547ddc-lvskl       2/2       Running      0          28m
demo-sdc-sdc-onboarding-be-cassandra-init-wzws4   0/1       Completed    0          28m
demo-sdc-sdc-wfd-be-5bb99767dd-cmpbk              1/1       Running      0          28m
demo-sdc-sdc-wfd-be-workflow-init-bs8mj           0/1       Completed    0          28m
demo-sdc-sdc-wfd-fe-7d74bf7d88-b5q82              2/2       Running      0          28m


Basic SDC Health Check                                                (DMaaP:None)| PASS |


2. SDC running with comman cassandra and own cassandra cluster and using own cluster
helm deploy demo local/onap --version=4.0.0 --namespace onap -f ~/Mahendra/OOM_Dublin/oom_running/oom/kubernetes/onap/resources/environments/disable-allcharts.yaml --set global.pullPolicy=IfNotPresent --set sdc.enabled=true --set cassandra.enabled=true --set robot.enabled=true --set sdc.global.cassandra.localCluster=true
fetching local/onap
release "demo" deployed
release "demo-cassandra" deployed
release "demo-robot" deployed
release "demo-sdc" deployed
NAME                                              READY     STATUS       RESTARTS   AGE
demo-cassandra-cassandra-0                        1/1       Running      0          1h
demo-cassandra-cassandra-1                        1/1       Running      0          1h
demo-cassandra-cassandra-2                        1/1       Running      0          1h
demo-robot-robot-785f67844-z85fz                  1/1       Running      0          1h
demo-sdc-sdc-be-6955d648b6-q79hj                  2/2       Running      0          1h
demo-sdc-sdc-be-config-backend-q8495              0/1       Completed    0          1h
demo-sdc-sdc-cs-0                                 1/1       Running      0          1h
demo-sdc-sdc-cs-config-cassandra-ttbdv            0/1       Completed    0          1h
demo-sdc-sdc-dcae-be-5f8875dcf-xrdz4              2/2       Running      0          1h
demo-sdc-sdc-dcae-be-tools-4jfn8                  0/1       Init:Error   0          1h
demo-sdc-sdc-dcae-be-tools-qcvjx                  0/1       Completed    0          1h
demo-sdc-sdc-dcae-dt-dd758b9b4-thspn              2/2       Running      0          1h
demo-sdc-sdc-dcae-fe-8cdf999db-tpjhb              2/2       Running      0          1h
demo-sdc-sdc-dcae-tosca-lab-785d7bc576-kgspm      2/2       Running      0          1h
demo-sdc-sdc-es-6fcdf64d59-dbv8l                  1/1       Running      0          1h
demo-sdc-sdc-es-config-elasticsearch-4fslq        0/1       Completed    0          1h
demo-sdc-sdc-fe-6587579785-25ncm                  2/2       Running      0          1h
demo-sdc-sdc-kb-868cbcbcf5-6mq89                  1/1       Running      0          1h
demo-sdc-sdc-onboarding-be-55b7547ddc-q45b8       2/2       Running      0          1h
demo-sdc-sdc-onboarding-be-cassandra-init-l2rhp   0/1       Completed    0          1h
demo-sdc-sdc-wfd-be-7fbd94b847-w8vjw              1/1       Running      0          52m
demo-sdc-sdc-wfd-be-workflow-init-nd59t           0/1       Completed    0          1h
demo-sdc-sdc-wfd-fe-7d74bf7d88-nd5tl              2/2       Running      0          1h



asic Portal Health Check                                             [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cd8391ed0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /ONAPPORTAL/portalApi/healthCheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cd8bcb890>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /ONAPPORTAL/portalApi/healthCheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cd83a01d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /ONAPPORTAL/portalApi/healthCheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='portal-app.onap', port=8989): Max retries exceeded with url: /ONAPPORTAL/portalApi/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9cd83a0390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SDC Health Check                                                (DMaaP:None)| PASS |
------------------------------------------------------------------------------

Patch-set: 1