Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 231
 * Nb Failed Pods: 3
 * List of Failed Pods: [
   - onap-sdnc-cds-blueprints-processor-5677dfdd56-scrcn
   - onap-sdnc-cds-command-executor-7bd7d9dd69-kwgsv
   - onap-sdnc-cds-controller-blueprints-65c75f8b8b-g9mst
   - onap-sdnc-cds-sdc-listener-66bcdd564c-mdr7s]
 * Deployment Duration Estimation (s): 6840
*********** Helm Results ***********
 * Nb Helm Charts: 31
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-sdnc]
******** Healthcheck Results *******
2019-07-12 23:01:22,558 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-thinkcloud API Health Check                          | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa965997810>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
61 critical tests, 60 passed, 1 failed
61 tests total, 60 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0