Update patch set 17
Patch Set 17: Code-Review-1

Make finished with error with helm 3.3.4 and k8S 1.18.12 Logs below


[cmpv2-cert-provider]
make[5]: Entering directory '/home/ubuntu/oom/kubernetes/platform/components'
Hang tight while we grab the latest from your chart repositories...
2020-12-02T11:31:22.249Z        ESC[34mINFOESC[0m       [425] Request served    {"path": "/index.yaml", "comment": "", "clientIP": "127.0.0.1", "method": "GET", "statusCode": 200, "latency": "67.447815ms", "reqID": "302ff511-1565-4088-953d-d91e53daf985"}
...Successfully got an update from the "local" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo http://127.0.0.1:8879
2020-12-02T11:31:22.286Z        ESC[34mINFOESC[0m       [426] Request served    {"path": "/charts/common-7.0.0.tgz", "comment": "", "clientIP": "127.0.0.1", "method": "GET", "statusCode": 200, "latency": "215.459µs", "reqID": "a4ae75d0-1b9c-4974-95f9-4b61464102b4"}
Deleting outdated charts
==> Linting cmpv2-cert-provider
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/configuration.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/deployment.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/roles.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/service.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253

Error: 1 chart(s) linted, 1 chart(s) failed
Makefile:41: recipe for target 'lint-cmpv2-cert-provider' failed
make[5]: *** [lint-cmpv2-cert-provider] Error 1
make[5]: Leaving directory '/home/ubuntu/oom/kubernetes/platform/components'
Makefile:31: recipe for target 'cmpv2-cert-provider' failed
make[4]: *** [cmpv2-cert-provider] Error 2
make[4]: Leaving directory '/home/ubuntu/oom/kubernetes/platform/components'
Makefile:34: recipe for target 'make-components' failed
make[3]: *** [make-components] Error 2
make[3]: Leaving directory '/home/ubuntu/oom/kubernetes/platform'
Makefile:30: recipe for target 'components' failed
make[2]: *** [components] Error 2
make[2]: Leaving directory '/home/ubuntu/oom/kubernetes/platform'
Makefile:64: recipe for target 'make-platform' failed
make[1]: *** [make-platform] Error 2
make[1]: Leaving directory '/home/ubuntu/oom/kubernetes'
Makefile:48: recipe for target 'platform' failed
make: *** [platform] Error 2

Patch-set: 17
Reviewer: Gerrit User 6347 <6347@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1