Update patch set 4
Patch Set 4:

Gating
* installation OK: https://gitlab.com/Orange-OpenSource/lfn/onap/onap_oom_automatic_installation/-/jobs/169771202
* tests: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169806828

k8s
8 pods (on 176) are not in Running state
--------------------------------------------------------------------------------------
NAME                                                           READY     STATUS             RESTARTS   AGE
onap-appc-appc-ansible-server-598558f644-vzcz8                 0/1       CrashLoopBackOff   14         1h
onap-dmaap-dmaap-bus-controller-577d694c69-c968p               0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-5c498cd687-chgzl                      0/1       CrashLoopBackOff   21         1h
onap-oof-oof-bfbd844d8-gkqgd                                   0/1       Init:0/2           7          1h
onap-policy-brmsgw-59bbd998fb-9n6mm                            0/1       Init:0/1           6          1h
onap-policy-pap-6757df5484-kvxhz                               0/2       PodInitializing    0          1h
onap-policy-pdp-0                                              0/2       Init:0/1           6          1h
onap-sdnc-controller-blueprints-64b8cf4c7c-hnfzj               0/1       CrashLoopBackOff   15         1h

helm
Chart onap-dcaegen2
STATUS: FAILED

healthcheck (medium)

Basic APPC Health Check                                | FAIL |
Test timeout 10 seconds exceeded.
E2E tests not triggered due to healthcheck issues

----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                      | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb73b84690>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic SDNC Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb7393cb50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic SO Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcb739a1490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                          | FAIL |
502 != 200

Patch-set: 4
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0