Update patch set 1
Patch Set 1: Code-Review+2 Verified+1

I still see two restarts of vfc-generic-vnfm-driver and vfc-zte-vnfm-driver

onap          aaa-vfc-catalog-b7c4c87fd-rbnsz                 2/2       Running            0          12m
onap          aaa-vfc-db-68ffc78cb6-9dg8w                     1/1       Running            0          12m
onap          aaa-vfc-ems-driver-cb4dd4c6b-tbv8t              1/1       Running            0          12m
onap          aaa-vfc-generic-vnfm-driver-7867b64f78-mnl2c    2/2       Running            1          12m
onap          aaa-vfc-huawei-vnfm-driver-6d54ff844c-j5vt8     2/2       Running            0          12m
onap          aaa-vfc-juju-vnfm-driver-574688f644-qxsvh       2/2       Running            0          12m
onap          aaa-vfc-multivim-proxy-f4d65568c-nr6nf          1/1       Running            0          12m
onap          aaa-vfc-nokia-v2vnfm-driver-744d648d4-4p59w     1/1       Running            0          12m
onap          aaa-vfc-nokia-vnfm-driver-7864b47f4c-mhgkv      2/2       Running            0          12m
onap          aaa-vfc-nslcm-85d6578f75-bgzh8                  2/2       Running            0          12m
onap          aaa-vfc-resmgr-8675d5d4f7-qz96l                 2/2       Running            0          12m
onap          aaa-vfc-vnflcm-6fcf76dcc4-8ffbf                 2/2       Running            0          12m
onap          aaa-vfc-vnfmgr-7bdb74c596-p58k8                 2/2       Running            0          12m
onap          aaa-vfc-vnfres-566f4fd649-cg856                 2/2       Running            0          12m
onap          aaa-vfc-workflow-7674c8cfc5-6w7lf               1/1       Running            0          12m
onap          aaa-vfc-workflow-engine-9696cbffd-xvndx         1/1       Running            0          12m
onap          aaa-vfc-zte-sdnc-driver-5d54859c8c-8n676        1/1       Running            0          12m
onap          aaa-vfc-zte-vnfm-driver-65fd8cf885-4z7kt        2/2       Running            1          12m

There is also an error I see in log:
root@borislav-rancher:~/onap/master/oom/kubernetes# k logs -n onap          aaa-vfc-generic-vnfm-driver-7867b64f78-mnl2c -c vfc-generic-vnfm-driver
SERVICE_IP=10.42.202.226
MSB_ADDR=msb-iag:80
Wait for MSB initialization
# Copyright 2017 ZTE Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [MSB]
MSB_SERVICE_IP = 'msb-iag'
MSB_SERVICE_PORT = '80'

# [MDC]
SERVICE_NAME = "gvnfmdriver"
FORWARDED_FOR_FIELDS = ["HTTP_X_FORWARDED_FOR", "HTTP_X_FORWARDED_HOST",
                        "HTTP_X_FORWARDED_SERVER"]

# [register]
REG_TO_MSB_WHEN_START = True
REG_TO_MSB_REG_URL = "/api/microservices/v1/services"
REG_TO_MSB_REG_PARAM = {
    "serviceName": "gvnfmdriver",
    "version": "v1",
    "url": "/api/gvnfmdriver/v1",
    "protocol": "REST",
    "visualRange": "1",
    "nodes": [{
        "ip": "10.42.202.226",
        "port": "8484",
        "ttl": 0
    }]
}
2018-08-20 12:30:42|||||driver.pub.utils.restcall||139804494792448||call_req||DEBUG||[da61dffe-a474-11e8-82fe-021e61146559]call_req('http://msb-iag:80/','','',0,'/api/microservices/v1/services','POST','{"protocol": "REST", "version": "v1", "url": "/api/gvnfmdriver/v1", "visualRange": "1", "serviceName": "gvnfmdriver", "nodes": [{"ip": "10.42.202.226", "port": "8484", "ttl": 0}]}')||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:32:49|||||driver.pub.utils.restcall||139804494792448||call_req||ERROR||Traceback (most recent call last):
  File "/service/vfc/nfvo/driver/vnfm/gvnfm/gvnfmadapter/driver/pub/utils/restcall.py", line 62, in call_req
    raise ex
error: [Errno 110] Connection timed out
||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:32:49|||||driver.pub.utils.restcall||139804494792448||call_req||ERROR||[da61dffe-a474-11e8-82fe-021e61146559]ret=(<class 'socket.error'>, error(110, 'Connection timed out'), <traceback object at 0x7f26c408e098>)||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:32:49|||||driver.pub.utils.restcall||139804494792448||call_req||DEBUG||[da61dffe-a474-11e8-82fe-021e61146559]ret=[3, "(<class 'socket.error'>, error(110, 'Connection timed out'), <traceback object at 0x7f26c408e098>)", '']||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:33:18|||||driver.pub.utils.restcall||139683803559680||call_req||DEBUG||[37cd502e-a475-11e8-a164-021e61146559]call_req('http://msb-iag:80/','','',0,'/api/microservices/v1/services','POST','{"protocol": "REST", "version": "v1", "url": "/api/gvnfmdriver/v1", "visualRange": "1", "serviceName": "gvnfmdriver", "nodes": [{"ip": "10.42.202.226", "port": "8484", "ttl": 0}]}')||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:33:18|||||driver.pub.utils.restcall||139683803559680||call_req||DEBUG||[37cd502e-a475-11e8-a164-021e61146559][0]status=201,resp_body={"serviceName":"gvnfmdriver","version":"v1","url":"/api/gvnfmdriver/v1","protocol":"REST","visualRange":"1","lb_policy":"","publish_port":"","namespace":"","network_plane_type":"","host":"","path":"","enable_ssl":false,"nodes":[{"ip":"10.42.202.226","port":"8484","checkType":"","checkUrl":"","tls_skip_verify":true,"ha_role":"","nodeId":"_v1_gvnfmdriver_10.42.202.226_8484","status":"passing"},{"ip":"10.43.162.84","port":"8484","checkType":"","checkUrl":"","tls_skip_verify":true,"ha_role":"","nodeId":"_v1_gvnfmdriver_10.43.162.84_8484","status":"passing"}],"metadata":[],"labels":[],"status":"1","is_manual":false})||||requestID= invocationID= serviceName= serviceIP=
2018-08-20 12:33:18|||||driver.pub.utils.restcall||139683803559680||call_req||DEBUG||[37cd502e-a475-11e8-a164-021e61146559]ret=[0, u'{"serviceName":"gvnfmdriver","version":"v1","url":"/api/gvnfmdriver/v1","protocol":"REST","visualRange":"1","lb_policy":"","publish_port":"","namespace":"","network_plane_type":"","host":"","path":"","enable_ssl":false,"nodes":[{"ip":"10.42.202.226","port":"8484","checkType":"","checkUrl":"","tls_skip_verify":true,"ha_role":"","nodeId":"_v1_gvnfmdriver_10.42.202.226_8484","status":"passing"},{"ip":"10.43.162.84","port":"8484","checkType":"","checkUrl":"","tls_skip_verify":true,"ha_role":"","nodeId":"_v1_gvnfmdriver_10.43.162.84_8484","status":"passing"}],"metadata":[],"labels":[],"status":"1","is_manual":false}', '201']||||requestID= invocationID= serviceName= serviceIP=
Probably it is related to the fact that msb didn't start yet at that point. Not sure, but you would maybe like to add a dependency on msb.
Anyway, both are not really blocking this review from getting in.

Patch-set: 1
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2
Label: Verified=+1