Update patch set 1
Patch Set 1:

Gitlab.com: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 173
 * Nb Failed Pods: 47
 * List of Failed Pods: [
   - onap-aaf-aaf-cm-546df8b44f-4hh9t
   - onap-aai-aai-7fb4f44bd-td7h4
   - onap-aai-aai-elasticsearch-598c7dc48d-ctsl9
   - onap-aai-aai-graphadmin-7486cb568f-ww8ct
   - onap-aai-aai-resources-54f7c87fbc-2vtch
   - onap-aai-aai-sparky-be-7f64bd64cd-726h9
   - onap-aai-aai-traversal-7d45f55f9c-skxj8
   - onap-aai-aai-traversal-update-query-data-qjzvv
   - onap-clamp-clamp-96b98bc7d-cr5zs
   - onap-clamp-clamp-dash-es-6799d79889-t7sxg
   - onap-clamp-clamp-dash-kibana-7c7dd9cbcf-lltj9
   - onap-clamp-clamp-dash-logstash-999bd9d69-nmr6g
   - onap-clamp-clampdb-b656b9c87-ww9zn
   - onap-contrib-awx-0
   - onap-dcaegen2-dcae-bootstrap-797cbf7cf7-m2nkv
   - onap-dcaegen2-dcae-cloudify-manager-58c4f6f45-jvrbj
   - onap-dmaap-dmaap-bc-post-install-qcw6w
   - onap-multicloud-multicloud-k8s-595645cb7c-m5d6s
   - onap-oof-music-tomcat-5c86d8cd64-qnss9
   - onap-oof-oof-647df44686-vc2nv
   - onap-oof-oof-cmso-topology-59d5795fd4-q8drz
   - onap-oof-oof-has-api-b64964974-dj7rw
   - onap-oof-oof-has-controller-7bbd59f57f-55plq
   - onap-oof-oof-has-data-6dbff6ffc-9kdw2
   - onap-oof-oof-has-healthcheck-zkcts
   - onap-oof-oof-has-onboard-9phck
   - onap-oof-oof-has-reservation-b998684c-f9l4k
   - onap-oof-oof-has-solver-795dbb8946-h6gkp
   - onap-policy-policy-apex-pdp-0
   - onap-pomba-pomba-contextaggregator-8487647dd6-6wwp2
   - onap-portal-portal-app-67454b5f76-tfnbd
   - onap-portal-portal-db-bc4484db5-lwnwg
   - onap-portal-portal-sdk-6569569844-jrgf8
   - onap-portal-portal-widget-57744b9f5d-kcdhr
   - onap-sdc-sdc-dcae-be-6f4fd4499d-mtrcr
   - onap-sdc-sdc-dcae-be-tools-gvjtr
   - onap-sdc-sdc-dcae-dt-744f8588c8-mwp49
   - onap-sdc-sdc-dcae-fe-79db78bfd5-8whjn
   - onap-sdc-sdc-fe-86d6b4df86-2svs6
   - onap-sdc-sdc-wfd-fe-669665c69d-wdkch
   - onap-sdnc-cds-blueprints-processor-cffdb76b9-djt5v
   - onap-sdnc-cds-command-executor-f559b46c4-dxtjw
   - onap-sdnc-cds-sdc-listener-66bb8d5bfd-bpfh9
   - onap-sdnc-cds-ui-d7f8c8f5-tw722
   - onap-sdnc-sdnc-dmaap-listener-548f6b6464-5rzzv
   - onap-sdnc-sdnc-ueb-listener-59ddbbcb6b-bv82j
   - onap-so-so-openstack-adapter-564678bf7f-s27zt
   - onap-vfc-vfc-workflow-engine-6989dcc96c-2x27k]
*********** Helm Results ***********
 * Nb Helm Charts: 31
 * Nb Failed Helm Charts: 4
 * List of Failed Helm Charts: [
   - onap-dcaegen2
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
2019-08-29 01:17:55,965 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='appc.onap', port=8443): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f748da09c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='clamp.onap', port=8443): Max retries exceeded with url: /restservices/clds/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f748da77050>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-healthcheck.onap', port=80): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748d953c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f748d88a310>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='policy-apex-pdp.onap', port=6969): Max retries exceeded with url: /policy/apex-pdp/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f748da77090>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='portal-app.onap', port=8989): Max retries exceeded with url: /ONAPPORTAL/portalApi/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748d86b5d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748d82e350>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='vid.onap', port=8443): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f748d76d090>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f748d6f0350>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 48 passed, 13 failed
61 tests total, 48 passed, 13 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1