Update patch set 5
Patch Set 5: Verified-1

After running "make all", I run this command: 
helm upgrade -i aaa local/onap --namespace onap --set global.pullPolicy=IfNotPresent -f ~/global-values.yaml --set pomba.enabled=false

Release "aaa" does not exist. Installing it now.
Error: [unable to decode "": Object 'Kind' is missing in '{"apiVersion":"v1","metadata":{"labels":{"app":"clamp-dash-es","chart":"clamp-dash-es-2.0.0","heritage":"Tiller","name":"aaa-clamp-dash-es","release":"aaa"},"name":"aaa-clamp-dash-es","namespace":"onap"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"4Gi"},"hostPath":{"path":"/dockerdata-nfs/aaa/clamp/dashboard-elasticsearch/data"},"persistentVolumeReclaimPolicy":"Retain"}}', unable to decode "": Object 'Kind' is missing in '{"apiVersion":"v1","metadata":{"labels":{"app":"clamp-dash-es","chart":"clamp-dash-es-2.0.0","heritage":"Tiller","release":"aaa"},"name":"aaa-clamp-dash-es","namespace":"onap"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"4Gi"}},"selector":{"matchLabels":{"name":"aaa-clamp-dash-es"}}}}']

Patch-set: 5
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=-1