Update patch set 1
Patch Set 1: Code-Review-1

Release "onap-dcaegen2" does not exist. Installing it now.
Error: release onap-dcaegen2 failed: Deployment.apps "onap-dcae-cloudify-manager" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"

Patch-set: 1
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1