Update patch set 2
Patch Set 2:

Pods running today:

root@linux-r4ap:~/oom/kubernetes# kubectl get pods -n onap -o wide
NAME                                                 READY     STATUS    RESTARTS   AGE       IP           NODE         NOMINATED NODE
demo-dmaap-dbc-pg-0                                  1/1       Running   0          5m        10.32.0.33   linux-r4ap   <none>
demo-dmaap-dbc-pg-1                                  1/1       Running   0          4m        10.32.0.45   linux-r4ap   <none>
demo-dmaap-dbc-pgpool-7796f4cd76-7qrgn               1/1       Running   0          5m        10.32.0.27   linux-r4ap   <none>
demo-dmaap-dbc-pgpool-7796f4cd76-dzmbg               1/1       Running   0          5m        10.32.0.24   linux-r4ap   <none>
demo-dmaap-dmaap-bus-controller-659d9bc676-9lfd4     1/1       Running   0          5m        10.32.0.25   linux-r4ap   <none>
demo-dmaap-dmaap-dr-db-7756fccdb4-drbkl              1/1       Running   0          5m        10.32.0.26   linux-r4ap   <none>
demo-dmaap-dmaap-dr-node-768db797d8-tjgws            1/1       Running   0          5m        10.32.0.29   linux-r4ap   <none>
demo-dmaap-dmaap-dr-prov-847664d544-kgsjq            1/1       Running   0          5m        10.32.0.30   linux-r4ap   <none>
demo-dmaap-message-router-698fd44dfb-nsjb6           1/1       Running   0          5m        10.32.0.32   linux-r4ap   <none>
demo-dmaap-message-router-kafka-6888fb854-jwk2x      1/1       Running   0          5m        10.32.0.37   linux-r4ap   <none>
demo-dmaap-message-router-zookeeper-795fc75c-4jfs8   1/1       Running   0          5m        10.32.0.31   linux-r4ap   <none>
demo-log-log-elasticsearch-6c7879c84c-2ccgh          1/1       Running   0          5m        10.32.0.39   linux-r4ap   <none>
demo-log-log-kibana-5c6866fcc6-bf598                 0/1       Running   0          5m        10.32.0.42   linux-r4ap   <none>
demo-log-log-logstash-58b98f5f99-pzb9n               1/1       Running   0          5m        10.32.0.43   linux-r4ap   <none>
demo-log-log-logstash-58b98f5f99-q8gtr               1/1       Running   0          5m        10.32.0.35   linux-r4ap   <none>
demo-log-log-logstash-58b98f5f99-qfxnm               1/1       Running   0          5m        10.32.0.38   linux-r4ap   <none>
demo-log-log-logstash-58b98f5f99-vvcrn               1/1       Running   0          5m        10.32.0.41   linux-r4ap   <none>
demo-log-log-logstash-58b98f5f99-wrldm               1/1       Running   0          5m        10.32.0.40   linux-r4ap   <none>
demo-robot-robot-d87f9b64-g8lpc                      1/1       Running   0          4m        10.32.0.44   linux-r4ap   <none>

Healthcheck passing:
root@linux-r4ap:~/oom/kubernetes# ./robot/ete-k8s.sh onap health
...
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc491dce50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc490dc390>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc49040f50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /nbi/api/v3/status
| FAIL |
ConnectionError: HTTPConnectionPool(host='nbi.onap', port=8080): Max retries exceeded with url: /nbi/api/v3/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efc491d5810>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------

Patch-set: 2