Update patch set 2
Patch Set 2: Code-Review-1

Gating results (based on OOM Master without integration stagging overwrite so some pods may be docker versions may be older than expected)

Installation: OK
Tests: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/175666520
logs: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/175666520/artifacts/download

see https://wiki.onap.org/display/DW/OOM+Gating for details

helm
****
Chart onap-policy
STATUS: FAILED
Chart problem
info:
  Description: 'Release "onap-policy" failed: client: etcd member http://etcd.kubernetes.rancher.internal:2379
    has no leader'
  first_deployed:
    nanos: 208552682
    seconds: 1552341654
  last_deployed:
    nanos: 208552682
    seconds: 1552341654
  status:
    code: 4
    notes: |
      # Copyright 2018 AT&T, Amdocs, Bell Canada Intellectual Property. All rights reserved
      #
      # Licensed under the Apache License, Version 2.0 (the "License");
      # you may not use this file except in compliance with the License.
      # You may obtain a copy of the License at
      #
      #         http://www.apache.org/licenses/LICENSE-2.0
      #
      # Unless required by applicable law or agreed to in writing, software
      # distributed under the License is distributed on an "AS IS" BASIS,
      # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      # See the License for the specific language governing permissions and
      # limitations under the License.

      1. Get the application URL by running these commands:
        export NODE_PORT=$(kubectl get --namespace onap -o jsonpath="{.spec.ports[0].nodePort}" services pap)
        export NODE_IP=$(kubectl get nodes --namespace onap -o jsonpath="{.items[0].status.addresses[0].address}")
        echo http://$NODE_IP:$NODE_PORT
name: onap-policy
namespace: onap

k8s
***
policy pods not started


healthcheck
***********
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='drools.onap', port=6969): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe8de195490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))

18 failed on 52 tests

End to End
**********
not triggerreed (errors in healthcheck)

Patch-set: 2
Label: Code-Review=-1