Update patch set 3
Patch Set 3: Code-Review-1

I tested this change on my WindRiver k8s instance, and found this change breaks SDNC.  The pods appear to come up clean in kubectl get pods, but the container's REST interface does not come up. In reviewing logs, found it is due to this error:
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(hos
t=mariadb-galera)(port=3306)(type=master) : Access denied for user 'sdnctl'@'dev
-sdnc-0.sdnc-cluster.onap.svc.cluster.local' (using password: YES)

Looks like database password is not being set correctly.

Patch-set: 3
Label: Code-Review=-1