Update patch set 1
Patch Set 1: Verified+1

Tested a lower helm version install/upgrade.  It worked.  I don't have a K8s 1.7 or something lower than 1.8.8 to test that side of it.

helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}


helm upgrade -i dev local/onap --namespace onap -f onap/resources/environments/disable-allcharts.yaml --dry-run

Release "dev" does not exist. Installing it now.
Error: Chart incompatible with Tiller v2.7.2

Patch-set: 1
Reviewer: Gerrit User 131 <131@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=+1