Update patch set 3
Patch Set 3:

it seems that for "me" it's still too big:
cat .local/share/helm/plugins/deploy/cache/onap/logs/onap-aai.log
Release "onap-aai" does not exist. Installing it now.
Error: create: failed to create: Secret "sh.helm.release.v1.onap-aai.v1" is invalid: data: Too long: must have at most 1048576 bytes

would you be kind to give the data size of your sh.helm.release.v1.onap-aai.v1?

Patch-set: 3
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>