Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98436-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 221
 * Nb Failed Pods: 51
 * List of Failed Pods: [
   - onap-aaf-aaf-cass-8986cbd6d-vcwxw
   - onap-aaf-aaf-cm-788f96b74b-9fzr7
   - onap-aai-aai-data-router-7cd8669b68-p6n8q
   - onap-aai-aai-elasticsearch-b6d9d7857-x9hdr
   - onap-aai-aai-graphgraph-5875c7ffdb-d22kp
   - onap-aai-aai-sparky-be-756d5dc559-7wlxq
   - onap-aai-aai-sparky-be-756d5dc559-fp45k
   - onap-aai-aai-sparky-be-756d5dc559-n2cw4
   - onap-cds-cds-blueprints-processor-76cf8d7b77-vc24x
   - onap-cds-cds-command-executor-58b446997d-8prml
   - onap-cds-cds-sdc-listener-75c5fd5ffb-j2t69
   - onap-dcaegen2-dcae-bootstrap-777f675d79-c98rv
   - onap-dcaegen2-dcae-pgpool-6b8dfc85fc-8v87m
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-q7k45
   - onap-multicloud-multicloud-windriver-7b78995b4c-kgns7
   - onap-oof-music-tomcat-6fcc8cdcb4-ctrcw
   - onap-oof-music-tomcat-6fcc8cdcb4-f8lcb
   - onap-oof-music-tomcat-6fcc8cdcb4-wdchj
   - onap-oof-oof-has-api-5bb7b84888-hrmqf
   - onap-oof-oof-has-data-d575ff6df-qwk7v
   - onap-oof-oof-has-solver-746bff67d8-l2nw6
   - onap-oof-oof-has-solver-746bff67d8-lgpv9
   - onap-pomba-pomba-aaictxbuilder-74546dc759-2872w
   - onap-pomba-pomba-contextaggregator-77bd58448d-psd5z
   - onap-pomba-pomba-sdncctxbuilder-69b65c7c94-5d24f
   - onap-pomba-pomba-sdncctxbuilder-69b65c7c94-mdj26
   - onap-pomba-pomba-validation-service-5cb4c66f88-nfdl4
   - onap-pomba-pomba-validation-service-5cb4c66f88-xb24p
   - onap-portal-portal-cassandra-7b6bb9c789-9lwnd
   - onap-portal-portal-cassandra-7b6bb9c789-xb9kz
   - onap-portal-portal-zookeeper-bd88545cf-7nqrl
   - onap-sdc-sdc-dcae-be-877f5d9c4-2ttzg
   - onap-sdc-sdc-dcae-be-877f5d9c4-6h2s2
   - onap-sdc-sdc-onboarding-be-59dc6f9f9f-gvqpk
   - onap-sdnc-network-name-gen-85ff6b896c-c45qh
   - onap-sdnc-network-name-gen-85ff6b896c-hgbpg
   - onap-sdnc-sdnc-dmaap-listener-7df88fddcb-wh8fs
   - onap-sdnc-sdnc-ueb-listener-5f57ff6d5f-x8twm
   - onap-sniro-emulator-sniro-emulator-7c6d477f5f-4r8x4
   - onap-so-so-openstack-adapter-7cdb6cd4b-hb6cq
   - onap-so-so-openstack-adapter-7cdb6cd4b-klnjm
   - onap-so-so-vnfm-adapter-5ddfc68df7-dl5vj
   - onap-so-so-vnfm-adapter-5ddfc68df7-wc7cc
   - onap-uui-uui-server-676957854d-qrvdl
   - onap-vfc-vfc-catalog-6df6d4b9d8-ptcgs
   - onap-vfc-vfc-vnfmgr-f4c9598f6-r8xst
   - onap-vfc-vfc-zte-sdnc-driver-56bd6d4745-6jhzf
   - onap-vfc-vfc-zte-sdnc-driver-56bd6d4745-cj7th
   - onap-vid-vid-64789c887b-c4c7b
   - onap-vid-vid-64789c887b-h26s4
   - onap-vnfsdk-vnfsdk-6ff5767447-pfrqt]
*********** Helm Results ***********
 * Nb Helm Charts: 31
 * Nb Failed Helm Charts: 0
 * List of Failed Helm Charts: []
******** Healthcheck Results *******
2019-11-20 18:21:11,827 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34eef0b5d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34eed707d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f34eed70c10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-contextaggregator.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34ef2263d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34ef3a4b10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 50 passed, 11 failed
61 tests total, 50 passed, 11 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-11-20 18:19:17,699 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
500 != 200

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1