Update patch set 55
Patch Set 55:

Gitlab Azure 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//107976-55/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 4
 * List of Failed Jobs: [
   - onap-sdc-be-config-backend
   - onap-sdc-cs-config-cassandra
   - onap-sdc-onboarding-be-cassandra-init
   - onap-sdc-wfd-be-workflow-init]
 * Nb Deployments: 154
 * Nb Failed Deployments: 9
 * List of Failed Deployments: [
   - onap-cds-sdc-listener
   - onap-dcae-servicechange-handler
   - onap-sdc-be
   - onap-sdc-fe
   - onap-sdc-onboarding-be
   - onap-sdc-wfd-be
   - onap-sdc-wfd-fe
   - onap-sdnc-ueb-listener
   - onap-so-oof-adapter]
 * Nb StatefulSets: 29
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 78
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-10-22 17:59:57,375 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faa0cd8a550>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-onboarding-be.onap', port=8445): Max retries exceeded with url: /onboarding-api/v1.0/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faa0cd0a7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 40 passed, 3 failed
43 tests total, 40 passed, 3 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-10-22 18:00:30,529 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f49b8dcc310>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-10-22 18:00:08,020 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
End to End VNF use cases not executed!

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/107976-55/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (07:28)
kube_hunter: FAIL (00:00)
root_pods: PASS (01:34)
unlimitted_pods: FAIL (00:34)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 55
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>