Update patch set 1
Patch Set 1:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 232
 * Nb Failed Pods: 77
 * List of Failed Pods: [
   - onap-aaf-aaf-sms-7c45447d4f-5vlkq
   - onap-aaf-aaf-sms-7c45447d4f-8xgth
   - onap-aaf-aaf-sms-7c45447d4f-djxlz
   - onap-aaf-aaf-sms-7c45447d4f-fhx6x
   - onap-aaf-aaf-sms-7c45447d4f-h6jlt
   - onap-aaf-aaf-sms-7c45447d4f-jqqpx
   - onap-aaf-aaf-sms-7c45447d4f-k2kcp
   - onap-aaf-aaf-sms-7c45447d4f-k54nq
   - onap-aaf-aaf-sms-7c45447d4f-krp92
   - onap-aaf-aaf-sms-7c45447d4f-n9xs9
   - onap-aaf-aaf-sms-7c45447d4f-q4wmd
   - onap-aaf-aaf-sms-7c45447d4f-qkvrj
   - onap-aaf-aaf-sms-7c45447d4f-thbmn
   - onap-aaf-aaf-sms-7c45447d4f-zlz2b
   - onap-aai-aai-7d6c77d64-7vcbm
   - onap-aai-aai-champ-7f97f98976-mvr9c
   - onap-aai-aai-graphadmin-c79fb7fcf-znvw7
   - onap-aai-aai-graphadmin-create-db-schema-64cr6
   - onap-aai-aai-resources-557c6f9d78-46j6d
   - onap-aai-aai-resources-557c6f9d78-6nfm2
   - onap-aai-aai-resources-557c6f9d78-8mcxr
   - onap-aai-aai-resources-557c6f9d78-ctfh2
   - onap-aai-aai-resources-557c6f9d78-cvd59
   - onap-aai-aai-resources-557c6f9d78-cxf29
   - onap-aai-aai-resources-557c6f9d78-k7lvz
   - onap-aai-aai-resources-557c6f9d78-k84xt
   - onap-aai-aai-resources-557c6f9d78-qds86
   - onap-aai-aai-resources-557c6f9d78-qwgsk
   - onap-aai-aai-resources-557c6f9d78-qxbpq
   - onap-aai-aai-resources-557c6f9d78-qxbwx
   - onap-aai-aai-resources-557c6f9d78-ssjmg
   - onap-aai-aai-resources-557c6f9d78-v5rrv
   - onap-aai-aai-resources-557c6f9d78-vr7tm
   - onap-aai-aai-resources-557c6f9d78-vx8v9
   - onap-aai-aai-resources-557c6f9d78-xnhdm
   - onap-aai-aai-schema-service-6f88774649-kx5v5
   - onap-aai-aai-sparky-be-5ff8689c54-4lcbt
   - onap-aai-aai-spike-77ccc5bf78-8q8vr
   - onap-aai-aai-traversal-7fb5558d98-ntkf9
   - onap-aai-aai-traversal-update-query-data-4rmbf
   - onap-appc-appc-ansible-server-6c5c7cb8f5-cbp25
   - onap-contrib-netbox-app-695fd89fd-4fl9j
   - onap-contrib-netbox-app-695fd89fd-8dk7l
   - onap-contrib-netbox-app-695fd89fd-975gr
   - onap-contrib-netbox-app-695fd89fd-d4pk6
   - onap-contrib-netbox-app-695fd89fd-dxpjm
   - onap-contrib-netbox-app-695fd89fd-kbndv
   - onap-contrib-netbox-app-695fd89fd-m7nqj
   - onap-contrib-netbox-app-695fd89fd-ms2mp
   - onap-contrib-netbox-app-695fd89fd-n6pjp
   - onap-contrib-netbox-app-695fd89fd-nknjt
   - onap-contrib-netbox-app-695fd89fd-nqtqx
   - onap-contrib-netbox-app-695fd89fd-s7vzg
   - onap-contrib-netbox-app-695fd89fd-srp7k
   - onap-contrib-netbox-app-695fd89fd-sxgkj
   - onap-contrib-netbox-app-695fd89fd-t7hv9
   - onap-contrib-netbox-app-provisioning-cqkjg
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-qzl8d
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-c5wgg
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-tql4t
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-xp6l4
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-2fnhn
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-rqpcl
   - onap-dmaap-message-router-mirrormaker-86d74c7c57-d44lw
   - onap-log-log-logstash-7dd49fd4d-ft5n5
   - onap-msb-msb-discovery-b47c65875-g6l6g
   - onap-policy-policy-api-6db49d977f-jpd87
   - onap-policy-policy-pap-85845569c5-t7w57
   - onap-policy-policy-xacml-pdp-7df865f5cc-5ctvx
   - onap-sdc-sdc-be-config-backend-8zjbf
   - onap-sdc-sdc-dcae-be-559494db5c-6ctzj
   - onap-sdc-sdc-dcae-be-tools-67wtl
   - onap-sdc-sdc-dcae-be-tools-9tvsn
   - onap-sdc-sdc-dcae-dt-7f49b64bd8-lzhrb
   - onap-sdc-sdc-dcae-fe-5b7fdcdc68-74l5z
   - onap-sdc-sdc-dcae-tosca-lab-74d894f9c4-z55qk
   - onap-sdc-sdc-fe-597ff794c8-rtgnt]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 4
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-so
   - onap-vfc
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-08 11:04:48,557 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef4ecd4f50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef4ed91c10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef4ec56790>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef4ede6f90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fef4eb8fe90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 30 passed, 28 failed
58 tests total, 30 passed, 28 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0