Update patch set 7
Patch Set 7:

Release "onap-aai" does not exist. Installing it now.
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8447},{"nam|..., bigger context ...|e":"changeit"},{"name":"INTERNAL_PORT_1","value":8447},{"name":"INTERNAL_PORT_2","value":5005}],"ima|...

Patch-set: 7
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>