Update patch set 6
Patch Set 6:

Gitlab Orange 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//119912-6/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 26
 * Nb Failed Jobs: 3
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
   - onap-netbox-app-provisioning
   - onap-oof-has-healthcheck]
 * Nb Deployments: 144
 * Nb Failed Deployments: 21
 * List of Failed Deployments: [
   - onap-aaf-sms
   - onap-cds-blueprints-processor
   - onap-cds-command-executor
   - onap-cds-sdc-listener
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-dashboard
   - onap-dcae-deployment-handler
   - onap-dcae-policy-handler
   - onap-dcae-servicechange-handler
   - onap-netbox-app
   - onap-oof
   - onap-oof-has-api
   - onap-oof-has-controller
   - onap-oof-has-data
   - onap-oof-has-reservation
   - onap-oof-has-solver
   - onap-policy-xacml-pdp
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-so-sdc-controller]
 * Nb StatefulSets: 24
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 67
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-dmaap]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-03-30 09:38:18,367 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
412 != 201
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fac5466dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-dr-node.onap', port=8443): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fac5424dd10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac542bda10>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fac543e1950>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fac54235310>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fac542414d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
'False' should be true.
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | FAIL |
400 != 200
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-sdc-controller.onap', port=8085): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac54281a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fac5417f090>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 31 passed, 12 failed
43 tests total, 31 passed, 12 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | FAIL |
--------> CMPv2 tests
Deploying PNF Simulator :: This test case deploys PNF simulator wi... | FAIL |
Deploying VES collector with CMPv2 :: This test case deploys secon... | FAIL |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | FAIL |
Send registration request to CMPv2 VES :: This test case triggers ... | FAIL |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | FAIL |
Send registration request to VES without CMPv2 certificate :: This... | FAIL |
Cmpv2 :: CMPv2 Usecase functionality                                  | FAIL |
--------> DCAEMOD tests
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | FAIL |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | FAIL |
--------> Basic Onboard tests (SDC)
basic_onboard:  Result.EX_ERROR
basic_onboard hasn't finished well, check logs
--------> CDS tests
basic_cds: FAIL (09:16)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | FAIL |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | FAIL |
--------> basic_vm tests
basic_vm: FAIL (03:57)
--------> basic_network tests
basic_network: FAIL (00:39)
--------> basic_cnf tests
basic_cnf: FAIL (03:25)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> cis_kubernetes tests
cis_kubernetes: PASS (00:00)
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (01:38)
--------> jdpw_ports tests
jdpw_ports: PASS (06:55)
--------> kube_hunter tests
kube_hunter: PASS (00:08)
--------> root_pods tests
root_pods: PASS (02:29)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (01:13)

____________________________________________________________

Patch-set: 6