Update patch set 7
Patch Set 7:

I am seeing the error below repeating, it appears we have the wrong DB host alias defined in configuration files:
16:17:02.537 [DBResourcemanagerWatchThread] ERROR org.apache.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=appc-sdnctldb01.onap)(port=3306)(type=master) : appc-sdnctldb01.onap
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:156) [189:org.mariadb.jdbc:2.1.1]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) [189:org.mariadb.jdbc:2.1.1]
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.throwException(ExceptionMapper.java:92) [189:org.mariadb.jdbc:2.1.1]
        at org.mariadb.jdbc.Driver.connect(Driver.java:102) [189:org.mariadb.jdbc:2.1.1]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:735) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:667) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:482) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) [148:org.apache.tomcat.jdbc:8.5.14]
        at org.onap.ccsdk.sli.core.dblib.CachedDataSource.getConnection(CachedDataSource.java:105) [196:org.onap.ccsdk.sli.core.dblib-provider:0.3.0.SNAPSHOT]
        at org.onap.ccsdk.sli.core.dblib.CachedDataSource.testConnection(CachedDataSource.java:348) [196:org.onap.ccsdk.sli.core.dblib-provider:0.3.0.SNAPSHOT]
        at org.onap.ccsdk.sli.core.dblib.CachedDataSource.testConnection(CachedDataSource.java:338) [196:org.onap.ccsdk.sli.core.dblib-provider:0.3.0.SNAPSHOT]
        at org.onap.ccsdk.sli.core.dblib.DBResourceManager$RecoveryMgr.resetConnectionPool(DBResourceManager.java:368) [196:org.onap.ccsdk.sli.core.dblib-provider:0.3.0.SNAPSHOT]
        at org.onap.ccsdk.sli.core.dblib.DBResourceManager$RecoveryMgr.run(DBResourceManager.java:341) [196:org.onap.ccsdk.sli.core.dblib-provider:0.3.0.SNAPSHOT]
Caused by: java.sql.SQLException: Could not connect to address=(host=appc-sdnctldb01.onap)(port=3306)(type=master) : appc-sdnctldb01.onap
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1040) ~[?:?]
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490) ~[?:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:97) ~[?:?]
        ... 14 more
Caused by: java.net.UnknownHostException: appc-sdnctldb01.onap
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:589) ~[?:?]
        at java.net.Socket.connect(Socket.java:538) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:399) ~[?:?]
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1035) ~[?:?]
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:490) ~[?:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:97) ~[?:?]

Patch-set: 7