Update patch set 2
Patch Set 2:

Gitlab Azure 1: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//113423-2/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 23
 * Nb Failed Jobs: 0
 * Nb Deployments: 147
 * Nb Failed Deployments: 3
 * List of Failed Deployments: [
   - onap-cds-sdc-listener
   - onap-dcae-servicechange-handler
   - onap-sdnc-ueb-listener]
 * Nb StatefulSets: 29
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 78
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 32
 * Nb Failed Helms: 7
 * List of Failed Helms: [
   - onap-sdnc
   - onap-oof
   - onap-policy
   - onap-portal
   - onap-dmaap
   - onap-sdc
   - onap-clamp]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-10-12 20:45:28,018 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f27da198d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-onboarding-be.onap', port=8445): Max retries exceeded with url: /onboarding-api/v1.0/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f27d9f87f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
SSLError: HTTPSConnectionPool(host='so-nssmf-adapter.onap', port=8088): Max retries exceeded with url: /manage/health (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 39 passed, 4 failed
43 tests total, 39 passed, 4 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-10-12 20:44:54,151 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb91864c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-10-12 20:44:29,669 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
End to End VNF use cases not executed!

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/113423-2/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (07:24)
kube_hunter: FAIL (00:00)
root_pods: FAIL (01:34)
unlimitted_pods: FAIL (00:27)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 2