Update patch set 6
Patch Set 6:

the gating job triggered on patchset 6 lead to a deployment + some tests


25 pods (on 225) are not in Running state
--------------------------------------------------------------------------------------
NAME                                                        READY     STATUS             RESTARTS   AGE
dep-dcae-prh-5bf67b6fdf-vr5f7                               1/2       ImagePullBackOff   0          1h
dep-policy-handler-7574dbf899-p52ld                         2/2       Unknown            0          1h
onap-aaf-aaf-oauth-6f7948698b-x5krw                         1/1       Unknown            0          1h
onap-aai-aai-cassandra-0                                    1/1       Unknown            0          1h
onap-aai-aai-elasticsearch-8697596bbc-5nqjh                 1/1       Unknown            0          1h
onap-aai-aai-traversal-586ddbdbcf-8szwp                     2/2       Unknown            0          1h
onap-appc-appc-ansible-server-598558f644-v8zw8              0/1       CrashLoopBackOff   16         1h
onap-appc-appc-db-0                                         1/1       Unknown            0          1h
onap-dmaap-dmaap-dr-db-0                                    0/1       CrashLoopBackOff   7          1h
onap-dmaap-dmaap-dr-db-1                                    0/1       CrashLoopBackOff   8          1h
onap-dmaap-dmaap-dr-node-b488b99b5-kxlp6                    1/2       CrashLoopBackOff   22         1h
onap-dmaap-dmaap-dr-prov-64c9b6b677-bf6gn                   2/2       Unknown            0          1h
onap-dmaap-dmaap-dr-prov-64c9b6b677-crw96                   1/2       CrashLoopBackOff   8          19m
onap-log-log-kibana-5d7b987b5d-66jbk                        1/1       Unknown            0          1h
onap-multicloud-multicloud-windriver-5d695b4c45-944np       2/2       Unknown            0          1h
onap-nbi-nbi-648b594ccb-m5xbv                               1/1       Unknown            3          1h
onap-oof-oof-has-reservation-6cb9fd8b48-jh5tc               1/1       Unknown            0          1h
onap-portal-portal-widget-597bb6f96f-gz6xf                  1/1       Unknown            0          1h
onap-sdc-sdc-dcae-dt-7f49b64bd8-gspkd                       2/2       Unknown            0          1h
onap-sdnc-controller-blueprints-6547954976-zrmlm            0/1       CrashLoopBackOff   4          1h
onap-sdnc-sdnc-portal-848d54f7c4-h4rff                      1/1       Unknown            0          1h
onap-sdnc-sdnc-ueb-listener-7587fb798c-vmfng                0/1       CrashLoopBackOff   17         1h
onap-so-so-openstack-adapter-6c75fcdd89-tvt4m               1/1       Unknown            3          1h
onap-vfc-vfc-ems-driver-76bdc4d97f-4zhk8                    1/1       Unknown            1          1h
onap-vfc-vfc-generic-vnfm-driver-86c8b8d6cd-8slm5           2/2       Unknown            1          1h

which is reflected by the default healthcheck results
2019-02-21 10:52:03,844 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff6edbbcb10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
29 critical tests, 26 passed, 3 failed
29 tests total, 26 passed, 3 failed

Patch-set: 6
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0