Update patch set 1
Patch Set 1:

vaibhav111    vaibhav111-brmsgw-d49d89556-g9rgp             1/1       Running   0          1h
vaibhav111    vaibhav111-drools-0                           1/1       Running   0          1h
vaibhav111    vaibhav111-nexus-8cb5c4fd8-wsgjj              1/1       Running   0          1h
vaibhav111    vaibhav111-pap-58cf4569d8-lwmcr               2/2       Running   0          1h
vaibhav111    vaibhav111-pdp-0                              2/2       Running   0          1h
vaibhav111    vaibhav111-policy-apex-pdp-0                  1/1       Running   0          1h
vaibhav111    vaibhav111-policydb-84fc79c495-rtqjp          1/1       Running   0          1h



root@ubuntu:/jayas_res/oom/kubernetes# kubectl descibe vaibhav111-pdp-0
Error: unknown command "descibe" for "kubectl"

Did you mean this?
        describe

Run 'kubectl --help' for usage.
root@ubuntu:/jayas_res/oom/kubernetes# kubectl describe vaibhav111-pdp-0
the server doesn't have a resource type "vaibhav111-pdp-0"
root@ubuntu:/jayas_res/oom/kubernetes# kubectl describe pods vaibhav111-pdp-0
Error from server (NotFound): pods "vaibhav111-pdp-0" not found
root@ubuntu:/jayas_res/oom/kubernetes# kubectl describe pods vaibhav111-pdp-0 -n vaibhav111
Name:           vaibhav111-pdp-0
Namespace:      vaibhav111
Node:           ubuntu/172.17.0.1
Start Time:     Fri, 17 Aug 2018 01:37:37 -0400
Labels:         app=pdp
                controller-revision-hash=vaibhav111-pdp-6795465756
                release=vaibhav111
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"vaibhav111","name":"vaibhav111-pdp","uid":"a5625e25-a1df-11e8-b67a-023d0066767f"...
Status:         Running
IP:             10.42.53.126
Created By:     StatefulSet/vaibhav111-pdp
Controlled By:  StatefulSet/vaibhav111-pdp
Init Containers:
  pdp-readiness:
    Container ID:  docker://5abe36c96a4bd95a7174775148b6d27715431cac3c806f5e43d3daa92ba81836
    Image:         oomk8s/readiness-check:2.0.0
    Image ID:      docker-pullable://oomk8s/readiness-check@sha256:7daa08b81954360a1111d03364febcb3dcfeb723bcc12ce3eb3ed3e53f2323ed
    Port:          <none>
    Command:
      /root/ready.py
    Args:
      --container-name
      pap
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 17 Aug 2018 01:39:55 -0400
      Finished:     Fri, 17 Aug 2018 01:48:54 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      NAMESPACE:  vaibhav111 (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gc94p (ro)
Containers:
  pdp:
    Container ID:  docker://f48f1ad6cb1f9d1877ca17424016fe056b4c5e67b0ecfc1dba50810e81a7ca5a
    Image:         nexus3.onap.org:10001/onap/policy-pe:1.3-SNAPSHOT-latest
    Image ID:      docker-pullable://nexus3.onap.org:10001/onap/policy-pe@sha256:5a6c73ac498871c5af798e751406721346f0ef610fbb9ef8064ba31f562a7a56
    Port:          8081/TCP
    Command:
      /bin/bash
      ./do-start.sh
      pdp
    State:          Running
      Started:      Fri, 17 Aug 2018 01:51:04 -0400
    Ready:          True
    Restart Count:  0
    Liveness:       tcp-socket :8081 delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :8081 delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/localtime from localtime (ro)
      /tmp/logback.xml from policy-logback (rw)
      /tmp/policy-install/config/base.conf from pe (rw)
      /tmp/policy-install/config/pdp-tweaks.sh from pe-pdp (rw)
      /tmp/policy-install/config/pdp.conf from pe-pdp (rw)
      /tmp/policy-install/config/pdplp.conf from pe-pdp (rw)
      /tmp/policy-install/do-start.sh from pe-scripts (rw)
      /var/log/onap from policy-logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gc94p (ro)
  filebeat-onap:
    Container ID:   docker://bb966af012a141121c1bc247d8399f6beec164e94b9a325fc467e9afd4df4f0a
    Image:          docker.elastic.co/beats/filebeat:5.5.0
    Image ID:       docker-pullable://docker.elastic.co/beats/filebeat@sha256:fe7602b641ed8ee288f067f7b31ebde14644c4722d9f7960f176d621097a5942
    Port:           <none>
    State:          Running
      Started:      Fri, 17 Aug 2018 01:52:25 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:        10m
      memory:     1Gi
    Environment:  <none>
    Mounts:

Patch-set: 1
Label: Code-Review=0