Update patch set 4
Patch Set 4: Verified-1 Code-Review-1

It is still failing for me too.
aaa-aai                 1               Thu Mar 28 07:29:12 2019        FAILED          aai-3.0.0               onap
Release "aaa-aai" does not exist. Installing it now.
[debug] CHART PATH: /root/.helm/cache/archive/aai-3.0.0.tgz

Error: release aaa-aai failed: Deployment.apps "aaa-aai-aai" is invalid: [spec.template.spec.volumes[3].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: "aai-pem"]

Patch-set: 4
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1
Label: Verified=-1