Update patch set 14
Patch Set 14: Code-Review+2 Verified+1

All pods come up and 1 of 2 health checks pass in OOM. This is the same result as in heat. I am merging this patch to move forward. The remaining health check issue can be resolved through a separate patch.


onap          dev-oof-584cd9d55b-rk25t                    1/1       Running    0          3h        10.42.87.83     oom-k8s-1
onap          dev-oof-has-api-555b5cd8df-r46b6            1/1       Running    0          3h        10.42.86.47     oom-k8s-1
onap          dev-oof-has-cassandra-94bd57d8f-xh4sg       1/1       Running    0          3h        10.42.212.32    oom-k8s-2
onap          dev-oof-has-controller-6dd4559db4-dn54j     1/1       Running    0          3h        10.42.140.38    oom-k8s-1
onap          dev-oof-has-data-6b4566f68d-k64td           1/1       Running    0          3h        10.42.26.65     oom-k8s-2
onap          dev-oof-has-music-8584d555fd-qpf2r          1/1       Running    0          3h        10.42.104.220   oom-k8s-1
onap          dev-oof-has-reservation-6bfbdcfc84-6t97v    1/1       Running    0          3h        10.42.55.129    oom-k8s-2
onap          dev-oof-has-solver-9b69674f6-xnsng          1/1       Running    0          3h        10.42.196.161   oom-k8s-1
onap          dev-oof-has-zookeeper-7dd694b949-2j4vp      1/1       Running    0          3h        10.42.227.1     oom-k8s-2

------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /api/oof/v1/healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /api/oof/v1/healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /api/oof/v1/healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))

Patch-set: 14
Reviewer: Gerrit User 127 <127@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2
Label: Verified=+1