Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 192
 * Nb Failed Pods: 19
 * List of Failed Pods: [
   - onap-aai-aai-ccc6c5559-4lc49
   - onap-aai-aai-champ-7f97f98976-nzrcc
   - onap-aai-aai-graphadmin-c79fb7fcf-lhbch
   - onap-aai-aai-graphadmin-create-db-schema-kbvsd
   - onap-aai-aai-resources-557c6f9d78-6gjdf
   - onap-aai-aai-sparky-be-5ff8689c54-b6xsg
   - onap-aai-aai-spike-77ccc5bf78-9v7p4
   - onap-aai-aai-traversal-7fb5558d98-qjggl
   - onap-aai-aai-traversal-update-query-data-tss85
   - onap-contrib-netbox-app-695fd89fd-w2bk4
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-2h8tx
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-tz7dh
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-2mkqt
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-8fkh6
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-7cg6k
   - onap-dmaap-dmaap-bc-post-install-cs9fv
   - onap-policy-policy-pap-85845569c5-f74hk
   - onap-sdnc-blueprints-processor-6d8c669cb-qsnck
   - onap-sdnc-controller-blueprints-64b8cf4c7c-scd9k]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-appc
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-04 13:41:03,570 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='appc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba181e6710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba18155410>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba17fbca10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba17fd6210>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | FAIL |
Variable '${POMBA_AAICONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | FAIL |
Variable '${POMBA_SDCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | FAIL |
Variable '${POMBA_NETWORKDISCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | FAIL |
Variable '${POMBA_SERVICEDECOMPOSITION_ENDPOINT}' not found. Did you mean:
    ${POMBA_SERVICEDECOMPOSITION_PATH}
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | FAIL |
Variable '${POMBA_NETWORKDISCOVERY_MICROSERVICE_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | FAIL |
Variable '${POMBA_KIBANA_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | FAIL |
Variable '${POMBA_ELASTICSEARCH_ENDPOINT}' not found. Did you mean:
    ${LOG_ELASTICSEARCH_ENDPOINT}
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | FAIL |
Variable '${POMBA_SDNCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
Variable '${POMBA_CONTEXTAGGREGATOR_ENDPOINT}' not found. Did you mean:
    ${POMBA_CONTEXTAGGREGATOR_PATH}
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba17e8bb90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 39 passed, 19 failed
58 tests total, 39 passed, 19 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2