Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 198
 * Nb Failed Pods: 27
 * List of Failed Pods: [
   - onap-aai-aai-bc7cfc65f-bm776
   - onap-aai-aai-champ-7f97f98976-68g7k
   - onap-aai-aai-graphadmin-c79fb7fcf-2kghx
   - onap-aai-aai-graphadmin-create-db-schema-556mq
   - onap-aai-aai-resources-557c6f9d78-9nvjj
   - onap-aai-aai-sparky-be-5ff8689c54-dj8h4
   - onap-aai-aai-spike-77ccc5bf78-24fhf
   - onap-aai-aai-traversal-7fb5558d98-wxv42
   - onap-aai-aai-traversal-update-query-data-c2g4g
   - onap-contrib-netbox-app-695fd89fd-4b652
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-s9tm4
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-btv4j
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-x77xh
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-w4jxz
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-8n8jc
   - onap-dmaap-dmaap-bc-post-install-74k7q
   - onap-policy-policy-api-6db49d977f-4xzcs
   - onap-policy-policy-pap-85845569c5-w22sp
   - onap-sdnc-blueprints-processor-6d8c669cb-xpggc
   - onap-sdnc-controller-blueprints-64b8cf4c7c-q8cp2
   - onap-so-so-58cc7d9965-7hptr
   - onap-so-so-bpmn-infra-7bc448579f-xwms2
   - onap-so-so-catalog-db-adapter-5c8f76f4c8-nxg7g
   - onap-so-so-openstack-adapter-85d658bf8-dpgz6
   - onap-so-so-request-db-adapter-64b7f54f98-ngf9p
   - onap-so-so-sdc-controller-7bb4cbdf44-4pm88
   - onap-so-so-vfc-adapter-559686cf49-4qjgs]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-05 00:22:31,614 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51263e0d90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51263a0150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51264137d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | FAIL |
Variable '${POMBA_AAICONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | FAIL |
Variable '${POMBA_SDCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | FAIL |
Variable '${POMBA_NETWORKDISCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | FAIL |
Variable '${POMBA_SERVICEDECOMPOSITION_ENDPOINT}' not found. Did you mean:
    ${POMBA_SERVICEDECOMPOSITION_PATH}
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | FAIL |
Variable '${POMBA_NETWORKDISCOVERY_MICROSERVICE_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | FAIL |
Variable '${POMBA_KIBANA_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | FAIL |
Variable '${POMBA_ELASTICSEARCH_ENDPOINT}' not found. Did you mean:
    ${LOG_ELASTICSEARCH_ENDPOINT}
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | FAIL |
Variable '${POMBA_SDNCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
Variable '${POMBA_CONTEXTAGGREGATOR_ENDPOINT}' not found. Did you mean:
    ${POMBA_CONTEXTAGGREGATOR_PATH}
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5126289fd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 39 passed, 19 failed
58 tests total, 39 passed, 19 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2