Update patch set 5
Patch Set 5: Verified-1

Doesn't build.
You need to update the onap/requirements.yaml with the correct version of multi-cloud:

onap]
make[1]: Entering directory '/home/mkhinda/onap-gerrit/oom/kubernetes'
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ?Happy Helming!?
Error: Can't get a valid version for repositories multicloud. Try changing the version constraint in requirements.yaml
Makefile:42: recipe for target 'dep-onap' failed
make[1]: *** [dep-onap] Error 1
make[1]: Leaving directory '/home/mkhinda/onap-gerrit/oom/kubernetes'
Makefile:35: recipe for target 'onap' failed
make: *** [onap] Error 2

Patch-set: 5
Label: Verified=-1