Update patch set 3
Patch Set 3:

Gitlab Orange 2: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 243
 * Nb Failed Pods: 30
 * List of Failed Pods: [
   - onap-dcaegen2-dcae-deployment-handler-59c957fcd8-v6xd4
   - onap-dcaegen2-dcae-inventory-api-c595b848-5rbnc
   - onap-dcaegen2-dcae-policy-handler-788575d5d8-fqmnh
   - onap-dcaegen2-dcae-servicechange-handler-65d6d9dc99-qww7m
   - onap-dmaap-dmaap-bc-78f6bf78dc-qq4jf
   - onap-dmaap-message-router-mirrormaker-955cf758c-vvl5c
   - onap-multicloud-multicloud-85655f7775-4jdpk
   - onap-multicloud-multicloud-ocata-f867bf85d-hf8mn
   - onap-multicloud-multicloud-pike-56f99db55f-5fthx
   - onap-multicloud-multicloud-vio-7b7466bf4c-dzrbl
   - onap-multicloud-multicloud-windriver-57f449c5c6-pd82p
   - onap-nbi-nbi-f797896cd-5fdxr
   - onap-oof-oof-69c4dcb5c6-6zb6v
   - onap-oof-oof-has-api-9bfcb8b45-9tgcr
   - onap-oof-oof-has-controller-6c8f46d7f4-765dc
   - onap-oof-oof-has-data-9f6d5fff6-gltng
   - onap-oof-oof-has-healthcheck-n4tqx
   - onap-oof-oof-has-reservation-7695d4c5cb-qrngx
   - onap-oof-oof-has-solver-f5d96647-wqd6d
   - onap-pomba-pomba-data-router-5655d6d97d-rv748
   - onap-sdc-sdc-dcae-be-5cb8df478c-lz7k6
   - onap-sdc-sdc-dcae-be-tools-zp99f
   - onap-sdc-sdc-dcae-dt-7844b684cd-7z4gj
   - onap-sdc-sdc-dcae-fe-f5c95bff6-55xl7
   - onap-sdc-sdc-dcae-tosca-lab-8b6dd6bd4-f62x9
   - onap-sdc-sdc-fe-fc6d8d456-z64gd
   - onap-sdnc-network-name-gen-b44d584d4-962gg
   - onap-sdnc-sdnc-ansible-server-7dbf557968-6rd7z
   - onap-sdnc-sdnc-dmaap-listener-6c4fc99569-zt6pj
   - onap-sdnc-sdnc-ueb-listener-7f458b54f-hdvcf]
 * Deployment Duration Estimation (s): 480
*********** Helm Results ***********
 * Nb Helm Charts: 30
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-so]
******** Healthcheck Results *******
2019-05-05 10:11:48,065 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f10693b6a90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1069112550>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='nbi.onap', port=8080): Max retries exceeded with url: /nbi/api/v3/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1069159790>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-thinkcloud API Health Check                          | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f106908d690>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f10690a9b90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
400 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic Portal Health Check                                             | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1069012610>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f106909d090>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
60 critical tests, 39 passed, 21 failed
60 tests total, 39 passed, 21 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 3
Label: Code-Review=0