Update patch set 48
Patch Set 48: Code-Review-1

Release "onap-sdc" does not exist. Installing it now.
2020/09/30 10:08:27 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/30 10:08:27 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/30 10:08:27 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/30 10:08:28 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/30 10:08:28 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
Error: release onap-sdc failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: illegal base64 data at input byte 10, error found in #10 byte of ...|mo123456!","aaf_user|..., bigger context ...|Version":"v1","data":{"aaf_password":"demo123456!","aaf_username":"aaf_admin@people.osaaf.org","cadi|...

Patch-set: 48
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1