Update patch set 7
Patch Set 7:

Gitlab Experimental Azure 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/experimental-gating//116648-7/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
grep: /tmp/archives/k8s/k8s/kubernetes-status/onap-k8s.log: No such file or directory
--------> onap-helm
grep: /tmp/archives/k8s/k8s/onap-helm/onap-helm.log: No such file or directory

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2021-01-15 13:50:14,399 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-vfc-adapter.onap', port=8084): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b457699d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 42 passed, 1 failed
43 tests total, 42 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2021-01-15 13:46:34,792 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2021-01-15 13:43:07,269 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
--------> CMPv2 tests
2021-01-15 13:49:07,473 - xtesting.core.robotframework - INFO - 
==============================================================================
Cmpv2 :: CMPv2 Usecase functionality                                          
==============================================================================
Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
------------------------------------------------------------------------------
Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
------------------------------------------------------------------------------
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
------------------------------------------------------------------------------
Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
------------------------------------------------------------------------------
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
------------------------------------------------------------------------------
Send registration request to VES without CMPv2 certificate :: This... | PASS |
------------------------------------------------------------------------------
Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
6 critical tests, 6 passed, 0 failed
6 tests total, 6 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/cmpv2/output.xml
--------> HV-VES tests
2021-01-15 13:44:06,050 - xtesting.core.robotframework - INFO - 
==============================================================================
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message is sent ...
==============================================================================
HV-VES SSL test case                                                  | PASS |
------------------------------------------------------------------------------
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/hv-ves/output.xml
--------> VES collector tests
2021-01-15 13:52:06,677 - xtesting.core.robotframework - INFO - 
==============================================================================
Ves :: Suite for checking handling events by VES Collector                    
==============================================================================
Send standard event to VES and check if is routed to proper topic ... | PASS |
------------------------------------------------------------------------------
Send 3GPP Fault Supervision event to VES and check if is routed to... | PASS |
------------------------------------------------------------------------------
Send 3GPP Heartbeat event to VES and check if is routed to proper ... | PASS |
------------------------------------------------------------------------------
Send 3GPP Performance Assurance event to VES and check if is route... | PASS |
------------------------------------------------------------------------------
Send 3GPP Provisioning event to VES and check if is routed to prop... | PASS |
------------------------------------------------------------------------------
Ves :: Suite for checking handling events by VES Collector            | PASS |
5 critical tests, 5 passed, 0 failed
5 tests total, 5 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/ves-collector/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
End to End VNF use cases not executed!

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
nonssl_endpoints: FAIL (00:54)
jdpw_ports: PASS (08:44)
kube_hunter: FAIL (00:00)
root_pods: FAIL (02:51)
unlimitted_pods: FAIL (00:50)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 7