Update patch set 18
Patch Set 18: Code-Review-1

Error: error validating "": error validating data: field spec.serviceName for v1beta1.StatefulSetSpec is required

serviceName filed is required for statefulset and is missing in the statefulset.yaml file.

Patch-set: 18
Reviewer: Gerrit User 1881 <1881@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1