Update patch set 37
Patch Set 37: Code-Review-1

we still have a cert error:


Release "onap-sdc" does not exist. Installing it now.
2020/09/18 09:14:55 Warning: Merging destination map for chart 'sdc-be'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ tpl (default "" .Values.config.userCredentialsExternalSecret) . }} login:{{ .Values.sdc_user }} password:{{ .Values.sdc_password }} passwordPolicy:generate type:basicAuth uid:sdc-user-creds] map[externalSecret:{{ tpl (default "" .Values.config.userCredentialsExternalSecret) . }} login:{{ .Values.dmaap.username }} password:{{ .Values.dmaap.password }} passwordPolicy:generate type:basicAuth uid:dmaap-user-creds] map[externalSecret:{{ tpl (default "" .Values.config.userCredentialsExternalSecret) . }} login:{{ .Values.aaf.username }} password:{{ .Values.aaf.password }} passwordPolicy:required type:basicAuth uid:aaf-user-creds] map[externalSecret:{{ tpl (default "" .Values.config.truststorePasswordExternalSecret) . }} password:{{ .Values.cs_truststore_password }} passwordPolicy:required type:password uid:cs-truststore-password] map[externalSecret:{{ tpl (default "" .Values.config.userCredentialsExternalSecret) . }} login:{{ .Values.sod.username }} password:{{.Values.sod.password}} passwordPolicy:required type:basicAuth uid:sod-user-creds] map[externalSecret:{{ tpl (default "" .Values.config.cadiTruststorePasswordExternalSecret) . }} password:{{ .Values.aaf.cadi_truststore_password }} passwordPolicy:required type:password uid:cadi-truststore-password] map[externalSecret:{{ tpl (default "" .Values.config.dmaapTruststorePasswordExternalSecret) . }} password:{{.Values.dmaap.truststore_password}} passwordPolicy:generate type:password uid:dmaap-truststore-pwd] map[externalSecret:{{ tpl (default "" .Values.config.sdcAccessRestrictionSecurityKeyExternalSecret) . }} password:{{.Values.authCookie.securityKey}} passwordPolicy:required type:password uid:sdc-access-restriction-security-key]]
2020/09/18 09:14:55 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/18 09:14:55 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/18 09:14:55 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/18 09:14:55 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/18 09:14:55 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
Error: release onap-sdc failed: Deployment.apps "onap-sdc-be" is invalid: [spec.template.spec.initContainers[5].env[0].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[1].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[2].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[3].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[4].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[5].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[6].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[7].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[8].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[9].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[10].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.initContainers[5].env[11].valueFrom.secretKeyRef.name: Invalid value: "some secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]

Patch-set: 37
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1