Update patch set 5
Patch Set 5:

Gitlab Orange 2: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98993-5/index.html
______________ Results _________________

************ Infrastructure-healthcheck Results ************
--------> onap-k8s
 * Nb Pods: 216
 * Nb Failed Pods: 31
 * List of Failed Pods: [
   - onap-aaf-aaf-gui-c8b9f4b6f-qwkm4
   - onap-aaf-aaf-sms-c94596d94-vhqws
   - onap-aai-aai-traversal-update-query-data-fhzsh
   - onap-cds-cds-sdc-listener-75c5fd5ffb-sv2m6
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-swzjj
   - onap-dmaap-dmaap-dr-prov-5b46b4979d-s6ls6
   - onap-dmaap-message-router-mirrormaker-56d96bf84-kv2f6
   - onap-oof-oof-86c448d5c7-2q6g8
   - onap-oof-oof-cmso-optimizer-5884678759-59hws
   - onap-oof-oof-cmso-service-66ff6f6cd8-dtp4c
   - onap-oof-oof-has-api-5bb7b84888-rdqrk
   - onap-oof-oof-has-controller-56f598fb9f-sff8p
   - onap-oof-oof-has-data-d575ff6df-8bbng
   - onap-oof-oof-has-reservation-547c8f4d7f-hmmtq
   - onap-oof-oof-has-solver-746bff67d8-62z9b
   - onap-sdc-sdc-be-6f5b895d6d-7m9j5
   - onap-sdc-sdc-cs-config-cassandra-75tbf
   - onap-sdc-sdc-dcae-be-877f5d9c4-xwc5p
   - onap-sdc-sdc-dcae-be-tools-85th5
   - onap-sdc-sdc-dcae-dt-77fbfbcb7-dz8m4
   - onap-sdc-sdc-dcae-fe-779f6767cd-fmbk5
   - onap-sdc-sdc-dcae-tosca-lab-86956f76c6-5hvzm
   - onap-sdc-sdc-fe-69c9d7b4d4-87j76
   - onap-sdc-sdc-onboarding-be-6766df566d-twgsr
   - onap-sdc-sdc-onboarding-be-cassandra-init-4sj7r
   - onap-sdc-sdc-wfd-be-866fd7c884-cf2dd
   - onap-sdc-sdc-wfd-fe-5bb84c977b-zb8q4
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-6ffc9d4945-qzw26
   - onap-sdnc-sdnc-dmaap-listener-847666c7c8-6zx97
   - onap-sdnc-sdnc-ueb-listener-5f757dd5b9-d4hqg]
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-dmaap]
************************************************************

********************* Healthcheck Results ******************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-01-29 18:18:08,336 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f55704e3090>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-01-29 18:17:29,662 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
403 != 200
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
************************************************************

********************** Smoke usecases **********************
End to End VNF use cases not executed!
************************************************************

********************** Security tests **********************
|           root_pods           |     security     |     security     |      03:21       |      FAIL      |
|        unlimitted_pods        |     security     |     security     |      00:44       |      FAIL      |
|         cis_kubernetes        |     security     |     security     |      00:01       |      FAIL      |
|     http_public_endpoints     |     security     |     security     |      02:51       |      FAIL      |
|        nodeport_ingress       |     security     |     security     |      00:03       |      FAIL      |
|           jdpw_ports          |     security     |     security     |      05:30       |      FAIL      |
+-------------------------------+------------------+------------------+------------------+----------------+

--------> cis tests
Test FAIL: 34 assertions not passed
[FAIL] 1.1.9 Ensure that the --repair-malformed-updates argument is set to false (Scored)
[FAIL] 1.1.11 Ensure that the admission control plugin AlwaysPullImages is set (Scored)
[FAIL] 1.1.15 Ensure that the --audit-log-path argument is set as appropriate (Scored)
[FAIL] 1.1.16 Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Scored)
[FAIL] 1.1.17 Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Scored)
[FAIL] 1.1.18 Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Scored)
[FAIL] 1.1.21 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Scored)
[FAIL] 1.1.24 Ensure that the admission control plugin PodSecurityPolicy is set (Scored)
[FAIL] 1.1.27 Ensure that the admission control plugin ServiceAccount is set(Scored)
[FAIL] 1.1.34 Ensure that the --encryption-provider-config argument is set as appropriate (Scored)
[FAIL] 1.1.36 Ensure that the admission control plugin EventRateLimit is set (Scored)
[FAIL] 1.1.37b Ensure that the AdvancedAuditing argument is not set to false (Scored)
[FAIL] 1.2.1 Ensure that the --profiling argument is set to false (Scored)
[FAIL] 1.3.6 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
[FAIL] 1.4.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.2 Ensure that the API server pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.4 Ensure that the controller manager pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.6 Ensure that the scheduler pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
[FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
[FAIL] 1.4.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.14 Ensure that the admin.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.16 Ensure that the scheduler.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.18 Ensure that the controller-manager.conf file ownership is set to root:root (Scored)
[FAIL] 1.5.1 Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.2 Ensure that the --client-cert-auth argument is set to true (Scored)
[FAIL] 1.5.4 Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.5 Ensure that the --peer-client-cert-auth argument is set to true (Scored)
34 checks FAIL
____________________________________

Patch-set: 5