Update patch set 2
Patch Set 2:

root@rke-exp-control-1:~/onap/staging/oom/kubernetes# hl
NAME                    REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
aaa                     1               Thu Aug  1 12:04:44 2019        DEPLOYED        onap-5.0.0              El Alto         onap
aaa-aaf                 1               Thu Aug  1 12:04:48 2019        DEPLOYED        aaf-5.0.0                               onap
aaa-aai                 1               Thu Aug  1 12:04:58 2019        DEPLOYED        aai-5.0.0                               onap
aaa-appc                1               Thu Aug  1 12:05:19 2019        DEPLOYED        appc-5.0.0                              onap
aaa-cassandra           1               Thu Aug  1 12:05:26 2019        DEPLOYED        cassandra-5.0.0                         onap
aaa-clamp               1               Thu Aug  1 12:05:28 2019        DEPLOYED        clamp-5.0.0                             onap
aaa-cli                 1               Thu Aug  1 12:05:32 2019        DEPLOYED        cli-5.0.0                               onap
aaa-consul              1               Thu Aug  1 12:05:33 2019        DEPLOYED        consul-5.0.0                            onap
aaa-contrib             1               Thu Aug  1 12:05:36 2019        DEPLOYED        contrib-5.0.0                           onap
aaa-dcaegen2            1               Thu Aug  1 12:05:43 2019        DEPLOYED        dcaegen2-5.0.0                          onap
aaa-dmaap               1               Thu Aug  1 12:05:56 2019        FAILED          dmaap-5.0.0                             onap
aaa-esr                 1               Thu Aug  1 12:39:20 2019        DEPLOYED        esr-5.0.0                               onap
aaa-log                 1               Thu Aug  1 12:39:23 2019        DEPLOYED        log-5.0.0                               onap
aaa-mariadb-galera      1               Thu Aug  1 12:39:26 2019        DEPLOYED        mariadb-galera-5.0.0                    onap
aaa-msb                 1               Thu Aug  1 12:39:28 2019        DEPLOYED        msb-5.0.0                               onap
aaa-multicloud          1               Thu Aug  1 12:39:32 2019        DEPLOYED        multicloud-5.0.0                        onap
aaa-nbi                 1               Thu Aug  1 12:39:39 2019        DEPLOYED        nbi-5.0.0                               onap
aaa-oof                 1               Thu Aug  1 12:39:44 2019        DEPLOYED        oof-5.0.0                               onap
aaa-policy              1               Thu Aug  1 12:39:55 2019        DEPLOYED        policy-5.0.0                            onap
aaa-pomba               1               Thu Aug  1 12:40:04 2019        DEPLOYED        pomba-5.0.0                             onap
aaa-portal              1               Thu Aug  1 12:40:14 2019        DEPLOYED        portal-5.0.0                            onap
aaa-robot               1               Thu Aug  1 12:40:21 2019        DEPLOYED        robot-5.0.0                             onap
aaa-sdc                 1               Thu Aug  1 12:40:24 2019        DEPLOYED        sdc-5.0.0                               onap
aaa-sdnc                1               Thu Aug  1 12:40:36 2019        DEPLOYED        sdnc-5.0.0                              onap
aaa-sniro-emulator      1               Thu Aug  1 12:40:46 2019        DEPLOYED        sniro-emulator-5.0.0                    onap
aaa-so                  1               Thu Aug  1 12:40:49 2019        DEPLOYED        so-5.0.0                                onap
aaa-uui                 1               Thu Aug  1 12:45:42 2019        DEPLOYED        uui-5.0.0                               onap
aaa-vfc                 1               Thu Aug  1 12:45:45 2019        DEPLOYED        vfc-5.0.0                               onap
aaa-vid                 1               Thu Aug  1 12:45:54 2019        DEPLOYED        vid-5.0.0                               onap
aaa-vnfsdk              1               Thu Aug  1 12:45:58 2019        DEPLOYED        vnfsdk-5.0.0                            onap


# cat ~/.helm/plugins/deploy/cache/onap/logs/aaa-dmaap.log
Release "aaa-dmaap" does not exist. Installing it now.
Error: timed out waiting for the condition

Patch-set: 2