Update patch set 4
Patch Set 4:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 203
 * Nb Failed Pods: 35
 * List of Failed Pods: [
   - onap-aai-aai-69f66c5ff4-2hlzp
   - onap-aai-aai-champ-599cd94496-nlhwg
   - onap-aai-aai-graphadmin-create-db-schema-gssw4
   - onap-aai-aai-graphadmin-f6b4b849b-5wz9c
   - onap-aai-aai-resources-69d89f66f8-2b7pf
   - onap-aai-aai-sparky-be-5ff8689c54-c6hlt
   - onap-aai-aai-spike-77ccc5bf78-v52pg
   - onap-aai-aai-traversal-85cbb49c8c-wqf4v
   - onap-aai-aai-traversal-update-query-data-6vxld
   - onap-appc-appc-ansible-server-598558f644-t7lfm
   - onap-contrib-netbox-app-695fd89fd-qbdfs
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-m2vk8
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-wpzww
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-b7wtp
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-6f9bm
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-zx78r
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-nxxqr
   - onap-dmaap-dmaap-bc-post-install-vkhvn
   - onap-policy-policy-api-6db49d977f-qqxtz
   - onap-policy-policy-pap-85845569c5-2pcrd
   - onap-sdc-sdc-be-6569fd96b-p9gls
   - onap-sdc-sdc-dcae-be-559494db5c-m8bls
   - onap-sdc-sdc-dcae-be-tools-xdftw
   - onap-sdc-sdc-dcae-dt-7f49b64bd8-8q26c
   - onap-sdc-sdc-dcae-fe-5b7fdcdc68-4vbxr
   - onap-sdc-sdc-dcae-tosca-lab-74d894f9c4-vg4pq
   - onap-sdc-sdc-fe-597ff794c8-7j2nh
   - onap-sdc-sdc-onboarding-be-6d9479b4b7-n8bbv
   - onap-sdc-sdc-wfd-be-6c6787ff5c-vfqdt
   - onap-sdc-sdc-wfd-be-workflow-init-sxcsm
   - onap-sdc-sdc-wfd-fe-74c6768594-grtvx
   - onap-sdnc-blueprints-processor-6d8c669cb-wgc67
   - onap-sdnc-controller-blueprints-64b8cf4c7c-lx2m8
   - onap-sdnc-sdnc-portal-848d54f7c4-6cwpk
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-tkrb8]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-11 01:09:48,763 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559d130d90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559d143150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559d166850>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | FAIL |
Variable '${POMBA_AAICONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | FAIL |
Variable '${POMBA_SDCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | FAIL |
Variable '${POMBA_NETWORKDISCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | FAIL |
Variable '${POMBA_SERVICEDECOMPOSITION_ENDPOINT}' not found. Did you mean:
    ${POMBA_SERVICEDECOMPOSITION_PATH}
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | FAIL |
Variable '${POMBA_NETWORKDISCOVERY_MICROSERVICE_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | FAIL |
Variable '${POMBA_KIBANA_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | FAIL |
Variable '${POMBA_ELASTICSEARCH_ENDPOINT}' not found. Did you mean:
    ${LOG_ELASTICSEARCH_ENDPOINT}
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | FAIL |
Variable '${POMBA_SDNCCONTEXTBUILDER_ENDPOINT}' not found.
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
Variable '${POMBA_CONTEXTAGGREGATOR_ENDPOINT}' not found. Did you mean:
    ${POMBA_CONTEXTAGGREGATOR_PATH}
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Variable '${SO_VNFM_ENDPOINT}' not found. Did you mean:
    ${SO_VFC_ENDPOINT}
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f559cfdb510>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 38 passed, 20 failed
58 tests total, 38 passed, 20 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 4