Update patch set 6
Patch Set 6:

> Patch Set 6: Code-Review-1
> 
> Release "onap-cert-wrapper" does not exist. Installing it now.
> Error: render error in "cert-wrapper/charts/certInitializer/templates/secret.yaml": template: cert-wrapper/charts/certInitializer/templates/secret.yaml:17:3: executing "cert-wrapper/charts/certInitializer/templates/secret.yaml" at <include "common.secretFast" .>: error calling include: template: no template "common.secretFast" associated with template "gotpl"

Got it!

Order of processing in Makefile is what causes troubles here.
cert-wrapper is processed before certInitializer thus if you've never built certInitializer it will lack dependencies to common

I'll try to figure out how to fix this

Patch-set: 6