Revert "[AAI][SPARKY] Automatically retrieve certs"
This reverts commit a9a41d84026f059aae70f9042c0b99af5b72e619.

aai-sparky-be with this patch fails often in the gate.
I expect this to be related to this patch as the stack trace contains
below error message:

java.io.IOException: keystore password was incorrect

Issue-ID: OOM-2683
Signed-off-by: Krzysztof Opasiak <k.opasiak@samsung.com>
Change-Id: I53650671eae700ef553b2f9158744ab72d881820