Update patch set 6
Patch Set 6: Code-Review-1

The gating job failed to deploy AAI with the following error:

Release "onap-aai" does not exist. Installing it now.
Error: create: failed to create: Secret "sh.helm.release.v1.onap-aai.v1" is invalid: data: Too long: must have at most 1048576 bytes

Patch-set: 6
Reviewer: Gerrit User 75 <75@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1