Update patch set 4
Patch Set 4: Code-Review-1

Release "onap-so" does not exist. Installing it now.
Error: release onap-so failed: secrets "onap-so-server-actuator-creds" already exists

Patch-set: 4
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1