Update patch set 14
Patch Set 14: Code-Review-1

https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/pipelines/264420416
k8s-status FAIL
onap-aai 	0/1 	1 	0
onap-aai-babel 	1/1 	1 	1
onap-aai-graphadmin 	0/1 	1 	0
onap-aai-modelloader 	1/1 	1 	1
onap-aai-resources 	0/1 	1 	0
onap-aai-schema-service 	0/1 	1 	0
onap-aai-sparky-be 	0/1 	1 	0
onap-aai-traversal 	0/1 	1 	0

both AAI HC are fail
Basic A&AI Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52ff7b4550>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v19/service-design-and-creation/models/model/AAI-HealthCheck-Dummy (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f52ff38e890>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 14
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1