Update patch set 7
Patch Set 7:

Gating results

Installation OK
Tests: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/170369420/artifacts/download

SO helm chart in FAILED state, no so-so pods available


k8s
***

4 pods (on 174) are not in Running state
----------------------------------------------------------------------
NAME                                                           READY     STATUS             RESTARTS   AGE
onap-appc-appc-ansible-server-598558f644-8c7wh                 0/1       CrashLoopBackOff   10         49m
onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-jsjwl              0/2       Init:0/3           0          48m
onap-dmaap-dmaap-bus-controller-577d694c69-vdsnm               0/1       ImagePullBackOff   0          48m
onap-oof-oof-bfbd844d8-94d6c                                   0/1       Init:0/2           4          45m

but only 174 pods running, several not started due to helm chart issues

helm
****

Chart onap-so
STATUS: FAILED

lots of helm charts with this status (vid, vfc, sdnc, msb)
healthcheck
unfortunately no additional logs, changes have been done in order to collect more info on helm char error

healthcheck (core)
***********
Basic A&AI Health Check                                   | PASS |
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                      | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd16729ca90>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                   | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                 | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                    | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1660a0a90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic SO Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1660bded0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.| FAIL |

Patch-set: 7
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0