Update patch set 13
Patch Set 13:

I have again amended with patch 13 with changes to robot as I understand them. There were a few more variables required to get it to the point it is at. Unfortunately, either through miss configuration of robot or the state of the endpoints, I was not able to get health check to pass.

------------------------------------------------------------------------------
Basic OOF-Homing Health Check
| FAIL |
Test timeout 1 minute exceeded.
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb82b4c0150>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/oof/v1/healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb82b4b5750>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/oof/v1/healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb82b4a7510>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 13