Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 220
 * Nb Failed Pods: 40
 * List of Failed Pods: [
   - onap-aai-aai-785bf54b6f-nqtdj
   - onap-aai-aai-champ-7f97f98976-jcw5j
   - onap-aai-aai-graphadmin-c79fb7fcf-s54c7
   - onap-aai-aai-graphadmin-create-db-schema-h28fn
   - onap-aai-aai-resources-557c6f9d78-vjfn4
   - onap-aai-aai-sparky-be-5ff8689c54-xvhzk
   - onap-aai-aai-spike-77ccc5bf78-grvhd
   - onap-aai-aai-traversal-7fb5558d98-8r7b6
   - onap-aai-aai-traversal-update-query-data-pqjs6
   - onap-contrib-netbox-app-695fd89fd-j622r
   - onap-dcaegen2-dcae-deployment-handler-64b59c864d-fftjz
   - onap-dcaegen2-dcae-policy-handler-6446f84665-5zpf6
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-68dvm
   - onap-dmaap-message-router-mirrormaker-86d74c7c57-kc2tz
   - onap-policy-policy-api-6db49d977f-zzcww
   - onap-policy-policy-pap-85845569c5-77st5
   - onap-policy-policy-xacml-pdp-7df865f5cc-5c74x
   - onap-sdc-sdc-be-6569fd96b-j5kzx
   - onap-sdc-sdc-be-config-backend-xh4cd
   - onap-sdc-sdc-dcae-be-559494db5c-n48rn
   - onap-sdc-sdc-dcae-be-tools-hjnkj
   - onap-sdc-sdc-dcae-dt-7f49b64bd8-pl8wf
   - onap-sdc-sdc-dcae-fe-5b7fdcdc68-zw4wg
   - onap-sdc-sdc-dcae-tosca-lab-74d894f9c4-x928j
   - onap-sdc-sdc-fe-597ff794c8-crjdx
   - onap-sdc-sdc-onboarding-be-6d9479b4b7-lxrbn
   - onap-sdc-sdc-onboarding-be-cassandra-init-rmqtx
   - onap-sdc-sdc-wfd-be-5c7bc88ff9-2qgtc
   - onap-sdc-sdc-wfd-be-workflow-init-sdppg
   - onap-sdc-sdc-wfd-fe-74c6768594-2s84g
   - onap-sdnc-blueprints-processor-5ccf47bc9d-t7s27
   - onap-sdnc-controller-blueprints-d9dff59fb-bnhdc
   - onap-sdnc-network-name-gen-86ccdf56b4-n5gr9
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-69d84d7bb4-lrvnd
   - onap-sdnc-sdnc-dgbuilder-64dfb5f957-4ss4f
   - onap-sdnc-sdnc-dmaap-listener-7f775c6445-wwn7n
   - onap-sdnc-sdnc-portal-6c75f6f74b-49vjt
   - onap-sdnc-sdnc-ueb-listener-675b897f8f-nsm2k
   - onap-so-so-vnfm-adapter-7f5474dc79-25bcb]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-12 02:39:40,480 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c22c69a10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c22c17f90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c22c2b3d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c22a964d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 48 passed, 10 failed
58 tests total, 48 passed, 10 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2