Update patch set 3
Patch Set 3:

> Uploaded patch set 4.

Robot Health Check passing.
root@k8s-1:/vaibhav/Robot_Patch/oom/kubernetes/robot# ./ete-k8s.sh onap health
Starting Xvfb on display :88 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
OpenECOMP ETE
==============================================================================
OpenECOMP ETE.Robot
==============================================================================
OpenECOMP ETE.Robot.Testsuites
==============================================================================
OpenECOMP ETE.Robot.Testsuites.Health-Check :: Testing ecomp components are...
==============================================================================
Basic DCAE Health Check                                               [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65c6203410>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65c61fead0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65c44fd5d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-controller.onap', port=8080): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65c44c8a10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SDNGC Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic MSO Health Check                                                | PASS |
------------------------------------------------------------------------------

(tested for few components)

Patch-set: 3