Update patch set 1
Patch Set 1: Code-Review+1

re-run (no timeout on dmaap)
dmaap healthcheck PASS

******** Kubernetes Results ********
 * Nb Pods: 178
 * Nb Failed Pods: 26
 * List of Failed Pods: [
   - onap-aai-aai-7b6595b4bb-zm7pq
   - onap-aai-aai-champ-7f97f98976-8x9tf
   - onap-aai-aai-graphadmin-c79fb7fcf-4bnpr
   - onap-aai-aai-resources-557c6f9d78-rs4pc
   - onap-aai-aai-sparky-be-5ff8689c54-5gskk
   - onap-aai-aai-spike-77ccc5bf78-rd5rh
   - onap-aai-aai-traversal-7fb5558d98-5k6mp
   - onap-aai-aai-traversal-update-query-data-ks6kl
   - onap-contrib-netbox-app-695fd89fd-shqjg
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-cvgms
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-x986q
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-zzmfz
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-qvx8z
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-zqln8
   - onap-sdnc-blueprints-processor-6d8c669cb-rlwvl
   - onap-sdnc-controller-blueprints-64b8cf4c7c-hp9qk
   - onap-sdnc-sdnc-ansible-server-64f864fd54-mkfs4
   - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-lqgq5
   - onap-sdnc-sdnc-portal-848d54f7c4-4rpl9
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-9j7q6
   - onap-so-so-bpmn-infra-7b4cf7dbf4-d5xh2
   - onap-so-so-catalog-db-adapter-684f7f7f57-gj5cg
   - onap-so-so-f57fb6c78-wc69l
   - onap-so-so-openstack-adapter-6c75fcdd89-wdgq2
   - onap-so-so-request-db-adapter-6797d64c57-6jqkr
   - onap-so-so-vfc-adapter-6df5476d68-8c8cn]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-vfc
   - onap-vnfsdk]

******** Healthcheck Results *******
Basic A&AI Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic AAF Health Check                                        | PASS |
----------------------------------------------------------------------
Basic AAF SMS Health Check                                    | PASS |
----------------------------------------------------------------------
Basic APPC Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic CLI Health Check                                        | PASS |
----------------------------------------------------------------------
Basic CLAMP Health Check                                      | PASS |
----------------------------------------------------------------------
Basic DCAE Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Message Router Health Check                       | PASS |
----------------------------------------------------------------------
Basic External API NBI Health Check                           | PASS |
----------------------------------------------------------------------
Basic Log Elasticsearch Health Check                          | PASS |
----------------------------------------------------------------------
Basic Log Kibana Health Check                                 | PASS |
----------------------------------------------------------------------
Basic Log Logstash Health Check                               | PASS |
----------------------------------------------------------------------
Basic Microservice Bus Health Check                           | PASS |
----------------------------------------------------------------------
Basic Multicloud API Health Check                             | PASS |
----------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                       | PASS |
----------------------------------------------------------------------
Basic Multicloud-pike API Health Check                        | PASS |
----------------------------------------------------------------------
Basic OOF-Homing Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71d0463ed0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71d02ae1d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71d02ae0d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Policy Health Check                                     | PASS |
----------------------------------------------------------------------
Basic Portal Health Check                                     | PASS |
----------------------------------------------------------------------
Basic SDC Health Check                                        | PASS |
----------------------------------------------------------------------
Basic SDNC Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic SO Health Check                                         | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic UseCaseUI API Health Check                              | PASS |
----------------------------------------------------------------------
Basic VID Health Check                                        | PASS |
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                 | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check               | FAIL |
502 != 200
----------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
28 critical tests, 18 passed, 10 failed


logs: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/179747727/artifacts/download

Patch-set: 1
Label: Code-Review=+1