Update patch set 3
Patch Set 3: Verified-1 Code-Review-2

I've pulled down patch set 3, but am unable to get the helm charts to successfully 'make': 

[dmaap]
make[1]: Entering directory '/home/jmac/work/master/oom.test/kubernetes'
make[2]: Entering directory '/home/jmac/work/master/oom.test/kubernetes/dmaap'
cd components && helm dep up dmaap-bus-controller && helm lint dmaap-bus-controller
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading common from repo http://127.0.0.1:8879/charts
Downloading postgres from repo http://127.0.0.1:8879/charts
Deleting outdated charts
==> Linting dmaap-bus-controller
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
cd components && helm dep up message-router && helm lint message-router
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo http://127.0.0.1:8879/charts
Deleting outdated charts
==> Linting message-router
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
cd components && helm dep up dmaap-dr-node && helm lint dmaap-dr-node
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading common from repo http://127.0.0.1:8879/charts
Deleting outdated charts
==> Linting dmaap-dr-node
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
cd components && helm dep up dmaap-dr-prov && helm lint dmaap-dr-prov
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "local" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading common from repo http://127.0.0.1:8879/charts
Downloading mariadb-galera from repo http://127.0.0.1:8879/charts
Deleting outdated charts
==> Linting dmaap-dr-prov
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
make[2]: Leaving directory '/home/jmac/work/master/oom.test/kubernetes/dmaap'
Error: error unpacking dmaap-data-router in dmaap: chart metadata (Chart.yaml) missing
Makefile:42: recipe for target 'dep-dmaap' failed
make[1]: *** [dep-dmaap] Error 1
make[1]: Leaving directory '/home/jmac/work/master/oom.test/kubernetes'
Makefile:35: recipe for target 'dmaap' failed
make: *** [dmaap] Error 2

Patch-set: 3