Update patch set 2
Patch Set 2:

Gitlab Azure 1: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//114537-2/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 2
 * List of Failed Jobs: [
   - onap-dmaap-bc-dmaap-provisioning
   - onap-vid-galera-config]
 * Nb Deployments: 154
 * Nb Failed Deployments: 3
 * List of Failed Deployments: [
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-vid]
 * Nb StatefulSets: 29
 * Nb Failed StatefulSets: 2
 * List of Failed StatefulSets: [
   - onap-dmaap-dr-node
   - onap-vid-galera]
 * Nb Persistent Volume Claims: 77
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2020-11-05 08:41:18,636 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-dr-node.onap', port=8443): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f96e274b350>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f96e25a4610>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='vid.onap', port=8443): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f96e23ed850>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 40 passed, 3 failed
43 tests total, 40 passed, 3 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2020-11-05 08:46:05,985 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-11-05 08:40:32,300 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
08:47:11,378: Loading (INFO)
08:47:11,743: Running (INFO)
basic_network: PASS (08:20)
basic_cnf: PASS (09:07)
pnf-registrate: FAIL (00:49)
hv-ves: PASS (00:42)
5gbulkpm: FAIL (12:05)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/114537-2/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (07:33)
kube_hunter: FAIL (00:00)
root_pods: FAIL (01:59)
unlimitted_pods: FAIL (00:51)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 2