Update patch set 43
Patch Set 43: Code-Review-1

you still have an issue with secrets I'm sorry

Release "onap-sdc" does not exist. Installing it now.
2020/09/21 14:55:22 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/21 14:55:23 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/21 14:55:23 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/21 14:55:23 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
2020/09/21 14:55:23 Warning: Merging destination map for chart 'certInitializer'. The destination item 'secrets' is a table and ignoring the source 'secrets' as it has a non-table value of: [map[externalSecret:{{ ternary (tpl (default "" .Values.aafDeployCredsExternalSecret) .) "aafIsDisabled" .Values.global.aafEnabled }} login:{{ .Values.aafDeployFqi }} password:{{ .Values.aafDeployPass }} passwordPolicy:required type:basicAuth uid:deployer-creds] map[externalSecret:{{ tpl (default "" .Values.truststoreCredsExternalSecret) . }} password:{{ .Values.truststorePassword }} passwordPolicy:required type:password uid:truststore-creds]]
NAME:   onap-sdc
Error: getting deployed release "onap-sdc": release: "onap-sdc" not found

Patch-set: 43
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1