Update patch set 3
Patch Set 3:

> Patch Set 3: Verified-1
> 
> Build Failed 
> 
> https://jenkins.onap.org/job/oom-master-verify-helm/6405/ : FAILURE
> 
> Build took too long to execute. Rerunning may solve the issue ( https://jenkins.onap.org/job/oom-master-verify-helm/6405/ )
> 
> Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/oom-master-verify-helm/6405
> 
> https://jenkins.onap.org/job/oom-master-image-verify/20/ : FAILURE
> 
> No problems were identified. If you know why this problem occurred, please add a suitable Cause for it. ( https://jenkins.onap.org/job/oom-master-image-verify/20/ )
> 
> Logs: https://logs.onap.org/production/vex-yul-ecomp-jenkins-1/oom-master-image-verify/20

Hi Sylvain - Errors are related to helm server access issues - most probably, HELM server seems down and this would be the reason for the failure here...

make[3]: Entering directory '/w/workspace/oom-master-verify-helm/kubernetes/common'
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused

Thanks!

Patch-set: 3