Update patch set 1
Patch Set 1: Verified-1

Something still not right.  I had to disable persistence and the nfs provisioner because I run a k8s cluster.
I did so like this:
sdnc:
  enabled: true
  mysql:
    disableNfsProvisioner: true
    persistence:
      enabled: false

Things seem like the come up but the sdnc app pod is in a restart loop.  I suspect the liveness probe is restarting it because port 8181 isn't open? Here are some logs.

02:29:54.265 [main] INFO  o.o.c.sli.core.sli.SvcLogicLoader - Activating SvcLogicGraph [module=SUBNET-API, rpc=subnet-allocated-notification, mode=sync, version=1.3.1-SNAPSHOT]
Load and activate finished at Wed Apr 11 02:29:54 UTC 2018
Load and activate took 3.82862663269 seconds
Installing Opendaylight cluster features
Authentication failed
Authentication failed
Update cluster information statically
Get current Hostname deep-sdnc-0
################################################
##             Configure Cluster              ##
################################################
Configuring unique name in akka.conf
Configuring hostname in akka.conf
Configuring data and rpc seed nodes in akka.conf
modules = [
	
	{
		name = "inventory"
		namespace = "urn:opendaylight:inventory"
		shard-strategy = "module"
	},
	{
		name = "topology"
		namespace = "urn:TBD:params:xml:ns:yang:network-topology"
		shard-strategy = "module"
	},
	{
		name = "toaster"
		namespace = "http://netconfcentral.org/ns/toaster"
		shard-strategy = "module"
	}
]
Configuring replication type in module-shards.conf
################################################
##   NOTE: Manually restart controller to     ##
##         apply configuration.               ##
################################################
Restarting OpenDaylight
karaf: There is a Root instance already running with name root and pid 240




Also the sdnc portal is restarting with these logs:

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
index.js
dbFabric=false
checking dbIP:null
Express server listening on port 8843
Error: connect ECONNREFUSED 127.0.0.1:3306

I am not sure if this patch is meant to result in the SDNC staying running or if it fixes something else that I don't know what to look for.

Patch-set: 1