Update patch set 7
Patch Set 7: Verified-1

onap          iii-aai-57d977969d-nw56c                        1/1       Running                 0          23m
onap          iii-aai-babel-6c9987b66c-gvrf7                  2/2       Running                 0          23m
onap          iii-aai-cassandra-0                             1/1       Running                 0          23m
onap          iii-aai-cassandra-1                             1/1       Running                 0          22m
onap          iii-aai-cassandra-2                             1/1       Running                 0          22m
onap          iii-aai-champ-7b64bb685d-6nrth                  1/1       Running                 0          23m
onap          iii-aai-data-router-85bdb7dccf-c5cz4            0/1       CrashLoopBackOff        6          23m
onap          iii-aai-elasticsearch-688879db44-wzvwx          0/1       CrashLoopBackOff        8          23m
onap          iii-aai-gizmo-6dcb6d4856-sks9t                  2/2       Running                 0          23m
onap          iii-aai-graphadmin-69fc49f4d9-znhdc             2/2       Running                 0          23m
onap          iii-aai-modelloader-97596b567-gvc5n             2/2       Running                 0          23m
onap          iii-aai-resources-748cfd4f4b-r75db              2/2       Running                 0          23m
onap          iii-aai-search-data-7549d4cbcd-z5nqw            2/2       Running                 0          23m
onap          iii-aai-sparky-be-6c44f56ddd-wwf9z              0/2       Init:0/1                2          23m
onap          iii-aai-spike-5b4fc44974-npfsp                  2/2       Running                 0          23m
onap          iii-aai-traversal-6444c56cbc-ljjgh              2/2       Running                 0          23m
root@borislav-rancher:~/onap/master/oom/kubernetes# k logs -n onap          iii-aai-elasticsearch-688879db44-wzvwx
[2018-09-17T08:14:43,279][INFO ][o.e.n.Node               ] [ES_ONAP] initializing ...
[2018-09-17T08:14:43,302][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [ES_ONAP] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.2.jar:6.1.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.2.jar:6.1.2]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.2.jar:6.1.2]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.2.jar:6.1.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.2.jar:6.1.2]
        ... 6 more

Patch-set: 7
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=-1