Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> > Patch Set 12: Code-Review+1
> > 
> > Latest results look good, hope this can be merged soon
> 
> Do we have anyone looking into the 5gBulkPm suite? Or is this an expected fail?
> 
> Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "onap-dcae-datafile-collector-read" in namespace "onap" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "onap-dcae-datafile-collector": current value is "onap-dcaegen2-services"
> helm.go:94: [debug] ServiceAccount "onap-dcae-datafile-collector-read" in namespace "onap" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "onap-dcae-datafile-collector": current value is "onap-dcaegen2-services"
> rendered manifests contain a resource that already exists. Unable to continue with install

Aah okay missed to noticed bulkpm failure. This test as setup currently will fail due to k8s resource name conflicts. 
Prior to this patch bulkPM services (DFC and PM-Mapper) were being installed part of smoke test execution. Since these services are now deployed on default/gating with this patch, causing these errors now.

Possibly two options to resolve 
1) Modify BulkPM tests to include a check if active service deployed before install and tear-down (if exist - skip helm install/un-install of DFC/PM-Mapper) and continue rest of the tests
2) Change BulkPM deployment to use different service name via chart override to avoid conflict (basically this would be duplicate instances installed/tear-down under bulk-pm test)

KK - Any other thought/suggestions?

Patch-set: 12
Reviewer: Gerrit User 4481 <4481@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Reviewer: Gerrit User 93 <93@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>