Update patch set 1
Patch Set 1:

Gitlab Orange 3: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//100770-1/index.html
______________ Results _________________

************ Infrastructure-healthcheck Results ************
--------> onap-k8s
 * Nb Pods: 195
 * Nb Failed Pods: 41
 * List of Failed Pods: [
   - onap-aaf-cm-55fbbd77b4-hq6vz
   - onap-aaf-gui-58b54756d8-qnzq6
   - onap-aaf-sms-85f8d9c8df-jwgfn
   - onap-awx-0
   - onap-cds-sdc-listener-58944c9d89-sd277
   - onap-dcae-dashboard-5985445bf5-2n9kl
   - onap-dcae-deployment-handler-5959d76bdf-n4tpm
   - onap-dcae-policy-handler-78946c585c-xrmh5
   - onap-dcae-servicechange-handler-85fcd94dcf-qmvgt
   - onap-dmaap-dr-node-0
   - onap-dmaap-dr-prov-569957f55b-l5c8x
   - onap-message-router-kafka-1
   - onap-message-router-mirrormaker-5746586c74-djfpk
   - onap-modeling-etsicatalog-56cdcc98f9-l724b
   - onap-modeling-mariadb-0
   - onap-nbi-799dfc9f6b-hwppv
   - onap-oof-677d5f79-lc4hd
   - onap-oof-cmso-optimizer-759fcc7768-b6zdc
   - onap-oof-cmso-service-6c6ff64586-7kx75
   - onap-oof-has-api-6c584d75d8-w7bsp
   - onap-oof-has-controller-56dd64cf55-tzb6w
   - onap-oof-has-data-55f99b749b-s8p7s
   - onap-oof-has-reservation-58d975f846-k8j6s
   - onap-oof-has-solver-756bf8c8c5-fgnkp
   - onap-portal-app-59c599b54f-d6jrb
   - onap-sdc-be-7f845b85d9-wpckw
   - onap-sdc-dcae-be-56ff9659d8-g5kqw
   - onap-sdc-dcae-dt-6c86ddc6b5-6xzms
   - onap-sdc-dcae-fe-5984fc4998-cll58
   - onap-sdc-dcae-tosca-lab-7c6559d5d4-8dr7x
   - onap-sdc-fe-599498b66b-bk7lm
   - onap-sdc-kb-7cc868fd68-gw5mq
   - onap-sdc-onboarding-be-78b497484b-vdzs4
   - onap-sdc-onboarding-be-cassandra-init-rwk6r
   - onap-sdc-wfd-be-56c9c98494-pxfbv
   - onap-sdc-wfd-be-workflow-init-nqs9j
   - onap-sdc-wfd-fe-56587d8dd4-x28rc
   - onap-sdnc-ueb-listener-86b5d84cf9-kjf25
   - onap-uui-server-6dcfd5cb56-hsd57
   - onap-vid-74548d76cb-bvj6c
   - onap-vid-galera-1]
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
************************************************************

********************* Healthcheck Results ******************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-02-05 11:09:48,040 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe324aa8750>: Failed to establish a new connection: [Errno -3] Try again'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-02-05 11:09:46,794 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | FAIL |
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
403 != 200
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
************************************************************

********************** Smoke usecases **********************
End to End VNF use cases not executed!
************************************************************

********************** Security tests **********************
|           root_pods           |     security     |     security     |      03:01       |      FAIL      |
|        unlimitted_pods        |     security     |     security     |      01:06       |      FAIL      |
|         cis_kubernetes        |     security     |     security     |      00:01       |      FAIL      |
|     http_public_endpoints     |     security     |     security     |      01:50       |      FAIL      |
|        nodeport_ingress       |     security     |     security     |      00:01       |      FAIL      |
|           jdpw_ports          |     security     |     security     |      05:27       |      FAIL      |
+-------------------------------+------------------+------------------+------------------+----------------+

--------> cis tests
Test FAIL: 34 assertions not passed
[FAIL] 1.1.9 Ensure that the --repair-malformed-updates argument is set to false (Scored)
[FAIL] 1.1.11 Ensure that the admission control plugin AlwaysPullImages is set (Scored)
[FAIL] 1.1.15 Ensure that the --audit-log-path argument is set as appropriate (Scored)
[FAIL] 1.1.16 Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Scored)
[FAIL] 1.1.17 Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Scored)
[FAIL] 1.1.18 Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Scored)
[FAIL] 1.1.21 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Scored)
[FAIL] 1.1.24 Ensure that the admission control plugin PodSecurityPolicy is set (Scored)
[FAIL] 1.1.27 Ensure that the admission control plugin ServiceAccount is set(Scored)
[FAIL] 1.1.34 Ensure that the --encryption-provider-config argument is set as appropriate (Scored)
[FAIL] 1.1.36 Ensure that the admission control plugin EventRateLimit is set (Scored)
[FAIL] 1.1.37b Ensure that the AdvancedAuditing argument is not set to false (Scored)
[FAIL] 1.2.1 Ensure that the --profiling argument is set to false (Scored)
[FAIL] 1.3.6 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
[FAIL] 1.4.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.2 Ensure that the API server pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.4 Ensure that the controller manager pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.6 Ensure that the scheduler pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
[FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
[FAIL] 1.4.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.14 Ensure that the admin.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.16 Ensure that the scheduler.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.18 Ensure that the controller-manager.conf file ownership is set to root:root (Scored)
[FAIL] 1.5.1 Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.2 Ensure that the --client-cert-auth argument is set to true (Scored)
[FAIL] 1.5.4 Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.5 Ensure that the --peer-client-cert-auth argument is set to true (Scored)
34 checks FAIL
____________________________________

Patch-set: 1