standardizing SDC helm charts
sdc-be is not starting, problems in the modified python
script used to check if a job is completed or not.
it was provided as a config map but probably could be
integrated with the existing ready.py script in a better way

do we need a pv/pvc for the logs?

kubectl -n onap logs -f dev-sdc-be-549697d65f-vfs4q sdc-be-job-completion
Traceback (most recent call last):
  File "/root/readiness/sdc_check_job_completion.py", line 17, in <module>
    client.configuration.api_key['authorization'] = token
AttributeError: 'module' object has no attribute 'api_key'

Issue-ID: OOM-747

Change-Id: Id6f1e57fdaf3cd6d9f75e8bc1e5bfde39b91235e
Signed-off-by: Mandeep Khinda <mandeep.khinda@amdocs.com>
(cherry picked from commit fe3e499547c91eadd71bde630594720b918c2af9)