Update patch set 2
Patch Set 2:

all E2E tests OK
2 policy healthcheck tests in timeout
policy-pap pod Running but not ready

https://logs.onap.org/onap-integration/gating//119727-2/infrastructure-healthcheck/k8s-teardown/kubernetes-status/pod-onap-policy-pap-674dc7d548-hxpg6.html

issue with cert
23:04:23.979 [PapGroup-6969] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@d5bb1c4{/,null,AVAILABLE}
23:04:24.098 [PapGroup-6969] ERROR o.o.p.c.e.h.s.i.JettyServletServer - JettyJerseyServer [Jerseyservlets={/*=org.glassfish.jersey.servlet.ServletContainer-7102ac3e@9f434f1e==org.glassfish.jersey.servlet.ServletContainer,jsp=null,order=0,inst=true,async=true}, swaggerId=swagger-6969, toString()=JettyServer [name=PapGroup, host=0.0.0.0, port=6969, user=healthcheck, password=true, contextPath=/, jettyServer=Server@695c938d{FAILED}[9.4.33.v20201020], context=o.e.j.s.ServletContextHandler@d5bb1c4{/,null,AVAILABLE}, connector=PapGroup@5ebffb44{SSL, (ssl, http/1.1)}{0.0.0.0:6969}, jettyThread=Thread[PapGroup-6969,5,main]]]: error found while bringing up server
java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(Unknown Source)
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1191)
	at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:323)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.onap.policy.common.endpoints.http.server.internal.JettyServletServer.run(JettyServletServer.java:305)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 22 common frames omitted

Patch-set: 2
CC: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>