Update patch set 1
Patch Set 1:

Gitlab Orange 4: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//102588-1/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 24
 * Nb Failed Jobs: 11
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
 onap-nbi-config-config-job
 onap-nengdb-init-config-job
 onap-oof-has-healthcheck
 onap-sdc-be-config-backend
 onap-sdc-cs-config-cassandra
 onap-sdc-dcae-be-tools
 onap-sdc-onboarding-be-cassandra-init
 onap-sdc-wfd-be-workflow-init
 onap-sdnc-dbinit-job
 onap-so-mariadb-config-job]
 * Nb Deployments: 166
 * Nb Failed Deployments: 41
 * List of Failed Deployments: [
   - onap-aaf-gui
 onap-aaf-sms
 onap-cds-sdc-listener
 onap-dcae-bootstrap
 onap-dcae-cloudify-manager
 onap-dcae-config-binding-service
 onap-dcae-dashboard
 onap-dcae-deployment-handler
 onap-dcae-policy-handler
 onap-dcae-servicechange-handler
 onap-dmaap-dr-prov
 onap-message-router-mirrormaker
 onap-nbi
 onap-network-name-gen
 onap-oof
 onap-oof-has-api
 onap-oof-has-controller
 onap-oof-has-data
 onap-oof-has-reservation
 onap-oof-has-solver
 onap-sdc-be
 onap-sdc-dcae-be
 onap-sdc-dcae-dt
 onap-sdc-dcae-fe
 onap-sdc-dcae-tosca-lab
 onap-sdc-fe
 onap-sdc-onboarding-be
 onap-sdc-wfd-be
 onap-sdc-wfd-fe
 onap-sdnc-ansible-server
 onap-sdnc-dgbuilder
 onap-sdnc-dmaap-listener
 onap-sdnc-ueb-listener
 onap-so
 onap-so-bpmn-infra
 onap-so-catalog-db-adapter
 onap-so-openstack-adapter
 onap-so-request-db-adapter
 onap-so-sdc-controller
 onap-so-vfc-adapter
 onap-uui-server]
 * Nb StatefulSets: 30
 * Nb Failed StatefulSets: 5
 * List of Failed StatefulSets: [
   - onap-awx
 onap-dmaap-dr-node
 onap-mariadb-galera
 onap-modeling-mariadb
 onap-sdnc]
 * Nb Persistent Volume Claims: 84
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-02-28 15:49:42,228 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fed207ea090>: Failed to establish a new connection: [Errno -3] Try again'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-02-28 15:49:13,917 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics/TEST_TOPIC_ACL/producers/iPIxkpAMI8qTcQj8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc419e02a10>: Failed to establish a new connection: [Errno -3] Try again'))
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v16/service-design-and-creation/models/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc419f21550>: Failed to establish a new connection: [Errno -3] Try again'))
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
freeradius_nbi: FAIL (04:36)
clearwater_ims: FAIL (04:36)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: FAIL (00:03)
http_public_endpoints: FAIL (01:60)
jdpw_ports: FAIL (03:60)
kube_hunter: FAIL (00:12)
root_pods: FAIL (02:10)
unlimitted_pods: FAIL (00:37)

--------> FOCUS on CIS errors
Test FAIL: 33 assertions not passed
[FAIL] 1.1.9 Ensure that the --repair-malformed-updates argument is set to false (Scored)
[FAIL] 1.1.11 Ensure that the admission control plugin AlwaysPullImages is set (Scored)
[FAIL] 1.1.15 Ensure that the --audit-log-path argument is set as appropriate (Scored)
[FAIL] 1.1.16 Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Scored)
[FAIL] 1.1.17 Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Scored)
[FAIL] 1.1.18 Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Scored)
[FAIL] 1.1.21 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Scored)
[FAIL] 1.1.24 Ensure that the admission control plugin PodSecurityPolicy is set (Scored)
[FAIL] 1.1.34 Ensure that the --encryption-provider-config argument is set as appropriate (Scored)
[FAIL] 1.1.36 Ensure that the admission control plugin EventRateLimit is set (Scored)
[FAIL] 1.1.37b Ensure that the AdvancedAuditing argument is not set to false (Scored)
[FAIL] 1.2.1 Ensure that the --profiling argument is set to false (Scored)
[FAIL] 1.3.6 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
[FAIL] 1.4.1 Ensure that the API server pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.2 Ensure that the API server pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.3 Ensure that the controller manager pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.4 Ensure that the controller manager pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.5 Ensure that the scheduler pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.6 Ensure that the scheduler pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
[FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
[FAIL] 1.4.13 Ensure that the admin.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.14 Ensure that the admin.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.15 Ensure that the scheduler.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.16 Ensure that the scheduler.conf file ownership is set to root:root (Scored)
[FAIL] 1.4.17 Ensure that the controller-manager.conf file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.18 Ensure that the controller-manager.conf file ownership is set to root:root (Scored)
[FAIL] 1.5.1 Ensure that the --cert-file and --key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.2 Ensure that the --client-cert-auth argument is set to true (Scored)
[FAIL] 1.5.4 Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate (Scored)
[FAIL] 1.5.5 Ensure that the --peer-client-cert-auth argument is set to true (Scored)
33 checks FAIL

____________________________________________________________

Patch-set: 1