Update patch set 1
Patch Set 1:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 244
 * Nb Failed Pods: 40
 * List of Failed Pods: [
   - onap-aai-aai-54f8fd4cb4-v9sqf
   - onap-aai-aai-data-router-d8754c64c-tdzjx
   - onap-aai-aai-traversal-update-query-data-qzpjt
   - onap-appc-appc-db-0
   - onap-clamp-clamp-dash-es-56cf5f5bd6-69ljb
   - onap-clamp-clampdb-7fbc7755b9-v7xd2
   - onap-dcaegen2-dcae-bootstrap-764478994d-27qg9
   - onap-dcaegen2-dcae-pgpool-7569845ccd-gn7gr
   - onap-dcaegen2-dcae-policy-handler-7976df4fb6-zs72v
   - onap-dmaap-dbc-pg-0
   - onap-dmaap-dmaap-bc-6b86d987f-lsl6h
   - onap-dmaap-message-router-kafka-1
   - onap-dmaap-message-router-mirrormaker-78cb664858-xbjkn
   - onap-dmaap-message-router-zookeeper-1
   - onap-mariadb-galera-mariadb-galera-1
   - onap-nbi-nbi-7d948d8878-s52gt
   - onap-oof-oof-69c4dcb5c6-gq5p8
   - onap-oof-oof-has-api-9bfcb8b45-jz729
   - onap-oof-oof-has-controller-6c8f46d7f4-j7jzh
   - onap-oof-oof-has-data-9f6d5fff6-jmdgk
   - onap-oof-oof-has-healthcheck-7bvsw
   - onap-oof-oof-has-reservation-7695d4c5cb-wlzmh
   - onap-oof-oof-has-solver-f5d96647-6cmx9
   - onap-policy-brmsgw-665f798fc4-rsd78
   - onap-policy-drools-0
   - onap-policy-policy-api-79445874cc-f8tfw
   - onap-policy-policy-xacml-pdp-84d89f9bc4-jxrpf
   - onap-pomba-pomba-data-router-5655d6d97d-755hj
   - onap-pomba-pomba-sdcctxbuilder-dfd49c578-jgppv
   - onap-sdnc-nengdb-0
   - onap-sdnc-sdnc-dmaap-listener-6c4fc99569-ghdct
   - onap-sdnc-sdnc-dmaap-listener-6c4fc99569-hmglc
   - onap-vfc-vfc-db-5d69c78c74-fmdts
   - onap-vfc-vfc-mariadb-2
   - onap-vfc-vfc-nokia-vnfm-driver-5d9b48dcfc-gs6cv
   - onap-vfc-vfc-nokia-vnfm-driver-5d9b48dcfc-l2gn6
   - onap-vfc-vfc-resmgr-c447d9b7-xphmf
   - onap-vfc-vfc-workflow-7f77f777b8-ll5gw
   - onap-vfc-vfc-workflow-7f77f777b8-m2mpv]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 30
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-aaf
   - onap-dmaap]
******** Healthcheck Results *******
2019-04-26 13:28:17,333 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-service.onap', port=8100): Max retries exceeded with url: /authz/perms/user/demo@people.osaaf.org (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f430124c150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
No keyword with name 'dev-aaf' found.
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4301325650>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic MUSIC Health Check                                              | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f430111d250>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic MUSIC Cassa Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/service/musicHealthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f430115b1d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4301175210>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4301314e90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
400 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='drools.onap', port=6969): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f430111d5d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
61 critical tests, 49 passed, 12 failed
61 tests total, 49 passed, 12 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1
Label: Verified=0