Update patch set 1
Patch Set 1:

Gating results

so pods not running and SO healthcheck FAIL

******** Kubernetes Results ********
 * Nb Pods: 197
 * Nb Failed Pods: 33
 * List of Failed Pods: [
   - onap-aai-aai-56465c547f-btkjb
   - onap-aai-aai-champ-7f97f98976-fswvw
   - onap-aai-aai-graphadmin-c79fb7fcf-zfvmr
   - onap-aai-aai-graphadmin-create-db-schema-txfrq
   - onap-aai-aai-resources-557c6f9d78-xp8gs
   - onap-aai-aai-sparky-be-5ff8689c54-st948
   - onap-aai-aai-spike-77ccc5bf78-kj5rc
   - onap-aai-aai-traversal-7fb5558d98-465sf
   - onap-aai-aai-traversal-update-query-data-hw2j4
   - onap-contrib-netbox-app-695fd89fd-nstxn
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-8d7s6
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-ss8lp
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-qd4fc
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-jkwh7
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-pvjsf
   - onap-policy-brmsgw-59bbd998fb-k4m9m
   - onap-policy-drools-0
   - onap-policy-pap-6757df5484-hl8p4
   - onap-policy-pdp-0
   - onap-policy-policydb-7dcf98d6d7-mcpfx
   - onap-sdnc-blueprints-processor-6d8c669cb-w6hlf
   - onap-sdnc-controller-blueprints-64b8cf4c7c-f6j9w
   - onap-sdnc-sdnc-ansible-server-64f864fd54-rv9tb
   - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-vknm8
   - onap-sdnc-sdnc-portal-848d54f7c4-zffkr
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-hvxb7
   - onap-so-so-bpmn-infra-7b4cf7dbf4-ksm7g
   - onap-so-so-catalog-db-adapter-684f7f7f57-dpqnc
   - onap-so-so-f57fb6c78-62xbc
   - onap-so-so-openstack-adapter-6c75fcdd89-j9nld
   - onap-so-so-request-db-adapter-6797d64c57-mpxqg
   - onap-so-so-sdc-controller-849949db55-f4sjk
   - onap-so-so-vfc-adapter-6df5476d68-f9clk]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
Basic A&AI Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic AAF Health Check                                      | PASS |
--------------------------------------------------------------------
Basic AAF SMS Health Check                                  | PASS |
--------------------------------------------------------------------
Basic APPC Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic CLI Health Check                                      | PASS |
--------------------------------------------------------------------
Basic CLAMP Health Check                                    | PASS |
--------------------------------------------------------------------
Basic DCAE Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic DMAAP Data Router Health Check                        | PASS |
--------------------------------------------------------------------
Basic DMAAP Message Router Health Check                     | PASS |
--------------------------------------------------------------------
Basic External API NBI Health Check                         | PASS |
--------------------------------------------------------------------
Basic Log Elasticsearch Health Check                        | PASS |
--------------------------------------------------------------------
Basic Log Kibana Health Check                               | PASS |
--------------------------------------------------------------------
Basic Log Logstash Health Check                             | PASS |
--------------------------------------------------------------------
Basic Microservice Bus Health Check                         | PASS |
--------------------------------------------------------------------
Basic Multicloud API Health Check                           | PASS |
--------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                     | PASS |
--------------------------------------------------------------------
Basic Multicloud-pike API Health Check                      | PASS |
--------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                 | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check            | PASS |
--------------------------------------------------------------------
Basic Multicloud-vio API Health Check                       | PASS |
--------------------------------------------------------------------
Basic OOF-Homing Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478cc72190>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478cc38b90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-CMSO Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478cbcd390>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Policy Health Check                                   | PASS |
--------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check  | PASS |
--------------------------------------------------------------------
Basic Portal Health Check                                   | PASS |
--------------------------------------------------------------------
Basic SDC Health Check                                      | PASS |
--------------------------------------------------------------------
Basic SDNC Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic SO Health Check                                       | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478cb8aed0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic UseCaseUI API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC catalog API Health Check                          | PASS |
--------------------------------------------------------------------
Basic VFC emsdriver API Health Check                        | PASS |
--------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                      | PASS |
--------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                 | PASS |
--------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                   | PASS |
--------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                  | PASS |
--------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nslcm API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC resmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnflcm API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfres API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC workflow API Health Check                         | PASS |
--------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VID Health Check                                      | PASS |
--------------------------------------------------------------------
Basic VNFSDK Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f478cb299d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Holmes Rule Management API Health Check               | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Holmes Engine Management API Health Check   | FAIL |
502 != 200
--------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 40 passed, 12 failed

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0