Update patch set 5
Patch Set 5:

> Patch Set 5: Code-Review-1
> 
> my bad, I did just have a look at the dashboard
> but if we click on the test results => https://logs.onap.org/onap-integration/gating//124280-5/root_pods/root_pods/root_pods.log
> 
> error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "9397418d6a066a2448307b472785a2596d86fc95426f5bd8e796e29a180f5c64": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "id": executable file not found in $PATH: unknown

yeah it's there for some time. Our containers got so small that now they sometimes even don't have the id command inside;)

We could fix that by adding other checks like:
cat /proc/self/status | grep Uid

but the problem is that some other containers don't have cat inside xD
So we basically need to either provide our own binary (kubectl cp) or try few methods instead of just one

but in general this is unrelated to this change

Patch-set: 5
Reviewer: Gerrit User 4965 <4965@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>