Update patch set 14
Patch Set 14:

> Patch Set 14: Code-Review+1
> 
> all smoke OK
> only SO HC KO but I assume that it is due the fact that the test is not aligned with the SO changes..
> 
> SSLError: HTTPSConnectionPool(host='so-nssmf-adapter.onap', port=8088): Max retries exceeded with url: /manage/health (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])")))
> url=https://so-nssmf-adapter.onap:8088, headers={},                     cookies=None, auth=None, timeout=None, proxies=None, verify=False,                     debug=0

note that when we check the certificates, we also got similar stuff https://logs.onap.org/onap-integration/weekly/onap_weekly_pod4_master/10-11-2020_05-10/infrastructure-healthcheck/internal-certificates/
SSL version error when testing so-nssmf-adapter on port 8088

the test has been added 5 days ago
https://github.com/onap/testsuite/commit/f8a43939aff21f0340ed3c1bcae467ce5900f791
the associated config change is here: https://github.com/onap/testsuite-oom/blob/34913f2223539640c81ae9e7a65744a09a95c9ce/resources/config/eteshare/config/robot_properties.py

I assume it is http not https, so just amending the robot_properties will fix the issue.
I can give a try (wait for the daily) then perform a test. if Ok I will submit a patch.

Patch-set: 14
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>