Update patch set 1
Patch Set 1: Code-Review+1

errors on gating not linked to gizmo pod

k8s pod errors:
dep-dcae-prh-78fb87d694-hxzk9                                  1/2       ImagePullBackOff   0          24m
onap-appc-appc-ansible-server-598558f644-hfwvs                 0/1       CrashLoopBackOff   8          37m
onap-dmaap-dmaap-dr-node-65cdb854d4-xrkm7                      0/1       CrashLoopBackOff   11         37m
onap-sdnc-sdnc-ansible-server-6d9967d6d4-qxt7h                 0/1       CrashLoopBackOff   9          34m

Core healthcheck fail due to dmaap

Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f477dfc3a10>: Failed to establish a new connection: [Errno 111] Connection refused',))


On full healthcheck errors are
Basic Policy Health Check | FAIL |
Basic Multicloud-starlingx API Health Check | FAIL |
Basic DMAAP Data Router Health Check | FAIL |
Basic DCAE Health Check | FAIL |

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1