Update patch set 2
Patch Set 2: Code-Review-1

I believe we have an issue on the onboarding:

#### Certificate Authorization Artifact
2020-10-07T23:27:53.846+0000 INIT [cadi] cadi_keyfile points to /opt/app/osaaf/local/org.onap.nbi.keyfile
2020-10-07T23:27:53.865+0000 INIT [cadi] https.protocols set by cadi_protocols in CADI Properties
2020-10-07T23:27:53.865+0000 INIT [cadi] jdk.tls.client.protocols set from Default Protocols
2020-10-07T23:27:54.893+0000: Trans Info
         Read Artifact 454.5089ms
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:227)
	at org.onap.aaf.cadi.configure.Agent.readArtifact(Agent.java:558)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:321)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:239)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
 
#### Certificate Authorization Artifact must be valid to continue

Patch-set: 2
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1