Update patch set 3
Patch Set 3: Code-Review-1

Gating results

installation OK
test results: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169912979/artifacts/download

k8s
****
43 pods not in Running state
dep-dcae-datafile-collector-7c75bc8ddf-nsbmw                   1/2       ErrImagePull       0          1h
onap-aaf-aaf-cm-7568c5fcd9-cbc84                               0/1       Init:1/2           7          1h
onap-aaf-aaf-cs-6fd5f8d4cb-wbq8k                               0/1       Pending            0          1h
onap-aaf-aaf-fs-7b4c776986-wdccj                               0/1       Init:1/2           7          1h
onap-aaf-aaf-gui-79b45d94f6-qrq6m                              0/1       Init:1/2           7          1h
onap-aaf-aaf-hello-8f5c897b7-bttxb                             0/1       Init:1/2           7          1h
onap-aaf-aaf-locate-5b6f8b64c6-lxh7l                           0/1       Init:1/2           7          1h
onap-aaf-aaf-oauth-6f7948698b-8grgl                            0/1       Init:1/2           7          1h
onap-aaf-aaf-service-6775579698-f74td                          0/1       Init:1/2           7          1h
onap-aaf-aaf-sms-7c45447d4f-dvkwj                              0/1       Pending            0          1h
onap-aaf-aaf-sms-preload-mrdkh                                 0/1       Init:0/1           7          1h
onap-aaf-aaf-sms-quorumclient-0                                0/1       Pending            0          1h
onap-aaf-aaf-sms-vault-0                                       0/2       Pending            0          1h
onap-aaf-aaf-sshsm-distcenter-k4724                            0/1       Pending            0          1h
onap-aaf-aaf-sshsm-testca-5c8vp                                0/1       Pending            0          1h
onap-aai-aai-777f944866-6jsn8                                  0/1       Init:0/1           7          1h
onap-aai-aai-cassandra-0                                       0/1       Pending            0          1h
onap-aai-aai-champ-5577966998-wf9fp                            0/2       Init:0/1           7          1h
onap-aai-aai-graphadmin-5bf9bdf88-bxnt6                        0/2       Init:0/1           7          1h
onap-aai-aai-resources-5cf7b9b48-whlr7                         0/2       Init:0/1           7          1h
onap-aai-aai-sparky-be-6bb68b595-znt58                         0/2       Init:0/1           0          1h
onap-aai-aai-traversal-8446ff4f64-d45pd                        0/2       Init:0/1           7          1h
onap-aai-aai-traversal-update-query-data-792p8                 0/1       Init:0/1           7          1h
onap-appc-appc-0                                               0/2       Pending            0          1h
onap-appc-appc-ansible-server-598558f644-ww8v5                 0/1       Init:0/1           7          1h
onap-appc-appc-db-0                                            0/1       Pending            0          1h
onap-appc-appc-dgbuilder-6869cc9d9-cq8lt                       0/1       Init:0/1           7          1h
onap-clamp-clamp-5788db7b6-qsb52                               0/2       Init:0/1           7          1h
onap-clamp-clamp-dash-es-6d4bcdcbc8-rf8ml                      0/1       Pending            0          1h
onap-clamp-clamp-dash-kibana-6dd9c9c7fd-t55b6                  0/1       Init:0/1           7          1h
onap-clamp-clamp-dash-logstash-74dff7886-ts5k8                 0/1       Init:0/1           7          1h
onap-clamp-clampdb-86c7bd4fdb-ngm72                            0/1       Pending            0          1h
onap-dmaap-dmaap-bus-controller-577d694c69-bcn6q               0/1       ErrImagePull       0          1h
onap-dmaap-dmaap-dr-node-b488b99b5-dbw25                       1/2       CrashLoopBackOff   21         1h
onap-oof-oof-bfbd844d8-ckqrk                                   0/1       Init:1/2           1          1h
onap-oof-oof-has-api-7597966cb9-kszzh                          0/1       Init:0/3           7          1h
onap-oof-oof-has-controller-755f689584-q2w8k                   0/1       Init:0/3           1          1h
onap-oof-oof-has-data-c7788fc4d-4bcqk                          0/1       Init:2/4           6          1h
onap-oof-oof-has-healthcheck-nqv7r                             0/1       Init:0/1           7          1h
onap-oof-oof-has-reservation-6cb9fd8b48-vwcgb                  0/1       Init:2/4           6          1h
onap-oof-oof-has-solver-54f46bbccc-v4dgq                       0/1       Init:2/4           6          1h
onap-sdnc-blueprints-processor-6d8c669cb-7sf84                 0/1       Init:0/1           6          1h
onap-sdnc-controller-blueprints-64b8cf4c7c-rnbpr               0/1       Init:0/1           7          1h

helm
****
Chart onap-vnfsdk
STATUS: FAILED

healthcheck (core)
***********

Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b1c2964d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 3
Label: Code-Review=-1