Update patch set 1
Patch Set 1:

Gitlab Orange 2: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96129-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 214
 * Nb Failed Pods: 69
 * List of Failed Pods: [
   - dep-dcae-hv-ves-collector-57c4f99848-s48bt
   - dep-dcae-ves-collector-79d4c9f47b-wd2l5
   - identity-wrapper-79c7dbc8db-8mghc
   - onap-aaf-aaf-cass-8986cbd6d-4wvw9
   - onap-aaf-aaf-cass-8986cbd6d-6lnkw
   - onap-aaf-aaf-cass-8986cbd6d-bhpqr
   - onap-aaf-aaf-gui-55cb4b6ff-f5ts5
   - onap-aai-aai-7cddcf4578-wvqth
   - onap-cds-cds-blueprints-processor-c5c8f585-76d9v
   - onap-cds-cds-command-executor-74dffcb87d-mgm2m
   - onap-cds-cds-controller-blueprints-5c9b695fcf-lvqqf
   - onap-cds-cds-sdc-listener-75c5fd5ffb-cpxpl
   - onap-cli-cli-5687d88b75-9tvbh
   - onap-cli-cli-5687d88b75-bmww5
   - onap-dcaegen2-dcae-dashboard-755449d876-nqstz
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-w9r7j
   - onap-msb-msb-iag-f849fd556-4swjp
   - onap-msb-msb-iag-f849fd556-b68dj
   - onap-msb-msb-iag-f849fd556-fkppf
   - onap-msb-msb-iag-f849fd556-jj72k
   - onap-multicloud-multicloud-lenovo-6d594979d5-7l5jg
   - onap-multicloud-multicloud-lenovo-6d594979d5-ccv67
   - onap-multicloud-multicloud-lenovo-6d594979d5-flsfx
   - onap-multicloud-multicloud-lenovo-6d594979d5-fvnsl
   - onap-multicloud-multicloud-pike-67bff7fc56-8gh8z
   - onap-multicloud-multicloud-pike-67bff7fc56-jjr6b
   - onap-multicloud-multicloud-pike-67bff7fc56-lbx85
   - onap-multicloud-multicloud-pike-67bff7fc56-vqp9j
   - onap-multicloud-multicloud-starlingx-58c5454b67-9xzgr
   - onap-nbi-nbi-587766c7d4-89j2p
   - onap-oof-music-tomcat-bdd9547bf-c2gb8
   - onap-oof-music-tomcat-bdd9547bf-mmxlt
   - onap-oof-music-tomcat-bdd9547bf-nq65d
   - onap-oof-music-tomcat-bdd9547bf-pr7ws
   - onap-oof-oof-cmso-optimizer-769ffdd7d-8k66w
   - onap-oof-oof-cmso-optimizer-769ffdd7d-k2tck
   - onap-oof-oof-d8f7dbfbf-hw4h8
   - onap-policy-policy-apex-pdp-0
   - onap-policy-policy-api-664f4bf674-bt6fd
   - onap-pomba-pomba-aaictxbuilder-5b58bb8d64-5p6f2
   - onap-pomba-pomba-contextaggregator-86cc6cbc8c-zp6dh
   - onap-pomba-pomba-sdncctxbuilder-56cc9b86b5-25xc2
   - onap-pomba-pomba-sdncctxbuilder-56cc9b86b5-2k8rj
   - onap-pomba-pomba-sdncctxbuilder-56cc9b86b5-6kmjn
   - onap-pomba-pomba-sdncctxbuilder-56cc9b86b5-774sd
   - onap-pomba-pomba-servicedecomposition-5b7d6bc-8h99h
   - onap-pomba-pomba-validation-service-5f78d4f9dd-cs72c
   - onap-pomba-pomba-validation-service-5f78d4f9dd-pqmg8
   - onap-pomba-pomba-validation-service-5f78d4f9dd-sbphq
   - onap-pomba-pomba-validation-service-5f78d4f9dd-sk47q
   - onap-portal-portal-zookeeper-8586f7df94-7dgth
   - onap-portal-portal-zookeeper-8586f7df94-dp9rx
   - onap-portal-portal-zookeeper-8586f7df94-f9wlj
   - onap-portal-portal-zookeeper-8586f7df94-nwhqp
   - onap-sdc-sdc-es-5f494767fb-6ppx8
   - onap-sdc-sdc-es-5f494767fb-jdshs
   - onap-sdc-sdc-es-5f494767fb-s4kbc
   - onap-sdc-sdc-es-5f494767fb-th2sk
   - onap-sdc-sdc-onboarding-be-68867d5787-2shgg
   - onap-sdc-sdc-onboarding-be-68867d5787-jkkdf
   - onap-sdc-sdc-onboarding-be-68867d5787-w4nfb
   - onap-sdnc-network-name-gen-85ff6b896c-ht26r
   - onap-sdnc-network-name-gen-85ff6b896c-lswt8
   - onap-sdnc-network-name-gen-85ff6b896c-qkn5h
   - onap-sdnc-sdnc-ansible-server-648f95867c-l52xg
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-jsfrm
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-s6g25
   - onap-uui-uui-698f54566d-nx458
   - onap-vfc-vfc-huawei-vnfm-driver-657668ccd6-4vgxm]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-dmaap]
******** Healthcheck Results *******
2019-09-23 15:20:43,298 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1e1faaf90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='message-router.onap', port=3904): Max retries exceeded with url: /topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1e1b35910>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd1e1b35710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
401 != 200
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-contextaggregator.onap', port=9529): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1e1c80110>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic CDS Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='cds-blueprints-processor-http.onap', port=8080): Max retries exceeded with url: /api/v1/execution-service/health-check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1e190bf90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 49 passed, 12 failed
61 tests total, 49 passed, 12 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
2019-09-23 15:20:41,737 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
500 != 200

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Label: Verified=0