Update patch set 2
Patch Set 2: Code-Review+1

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > @Sylvain
> > > This patch is already on the top of master but oof-cmso HC still fails...
> > 
> > I believe it is not related to this review, probably OOF team should take a look at it, seems that the oof container is not coming up based on the 111 errno.
> > 
> > ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbd6499e090>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> No worries Jorge I fully agree with you, it's not related to your patch. I'm just letting Sylvain's know that the revert that we submitted today has not fixed the all the issues that we observe in the gating

HC errors are due to the fact the the oof deployement is not completed => no pod => no connection => HC fail
It is clearly not related to this patch
This patch was rebased at 1:49 PM yesterday
it is on frankfurt branch (we did not merge the AAF patch on frankfurt) so it is not related to the AAF issue and its revert detected on master.
On the 3 last daily frankfurt runs the HC full are all OK
so I am a bit puzzled

But as policy HC are OK, healthdist and postinstall are OK (which was not the case with the AAF patch) +  basic E2E tests are OK, it is fine for me

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1