Update patch set 12
Patch Set 12:

Gitlab Azure AKS 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//132396-12/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s NOT executed
--------> onap-helm
 * Nb Helms: 35
 * Nb Failed Helms: 0

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2023-01-26 02:37:35,495 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/util/echo?action=long (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f07e201c810>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v19/service-design-and-creation/models/model/AAI-HealthCheck-Dummy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f07e206ac50>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
37 critical tests, 35 passed, 2 failed
37 tests total, 35 passed, 2 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | FAIL |
--------> CMPv2 tests
Send registration request to CMPv2 VES :: This test case triggers ... | FAIL |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | FAIL |
Send registration request to VES without CMPv2 certificate :: This... | FAIL |
Cmpv2 :: CMPv2 Usecase functionality                                  | FAIL |
--------> DCAEMOD tests
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic onboard tests NOT executed
--------> CDS tests NOT executed

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | FAIL |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
--------> basic_vm tests NOT executed
--------> basic_network tests NOT executed
--------> basic_cnf tests NOT executed
--------> basic_vm_macro tests NOT executed
--------> basic_clamp tests NOT executed
--------> pnf_macro tests NOT executed
--------> cds_resource_resolution tests NOT executed
--------> basic_cnf_macro tests NOT executed

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests NOT executed
--------> jdpw_ports tests NOT executed
--------> kube_hunter tests NOT executed
--------> root_pods tests NOT executed
--------> unlimitted_pods tests NOT executed

____________________________________________________________

Patch-set: 12