Update patch set 2
Patch Set 2: Code-Review+2 Verified+1

Approved and verified in OpenLab.
root@borislav-oom-rancher:~/master/oom/kubernetes/robot# ./ete-k8s.sh health
Starting Xvfb on display :88 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
OpenECOMP ETE
==============================================================================
OpenECOMP ETE.Robot
==============================================================================
OpenECOMP ETE.Robot.Testsuites
==============================================================================
OpenECOMP ETE.Robot.Testsuites.Health-Check :: Testing ecomp components are...
==============================================================================
Basic DCAE Health Check                                               [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f116c217190>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f116df6a350>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f116c273110>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /healthcheck
| FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-controller.onap-dcae', port=8080): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f116c234090>: Failed to establish a new connection: [Errno -2] Name or service not known',))
------------------------------------------------------------------------------
Basic SDNGC Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic MSO Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic ASDC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Message Router Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |

Patch-set: 2
Reviewer: Gerrit User 497 <497@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2
Label: Verified=+1