Update patch set 2
Patch Set 2:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 206
 * Nb Failed Pods: 23
 * List of Failed Pods: [
   - onap-contrib-netbox-app-64ddd5494d-2f569
   - onap-dcaegen2-dcae-bootstrap-547758b4f5-75w24
   - onap-dcaegen2-dcae-cloudify-manager-7dfb76fc44-np9j2
   - onap-dcaegen2-dcae-deployment-handler-98469598-vld9v
   - onap-dcaegen2-dcae-healthcheck-cf6559d84-dw248
   - onap-dcaegen2-dcae-policy-handler-5fd67bfb5c-l94jw
   - onap-dcaegen2-dcae-servicechange-handler-65d6d9dc99-2b7b7
   - onap-dmaap-dmaap-bc-post-install-lnrfm
   - onap-policy-policy-api-794fc87f89-mt25b
   - onap-policy-policy-pap-578c574d77-w4dkx
   - onap-policy-policy-xacml-pdp-688dbbdbc9-m8269
   - onap-sdc-sdc-be-c7b6969f6-n7k5f
   - onap-sdc-sdc-dcae-be-5cb8df478c-b79ff
   - onap-sdc-sdc-dcae-dt-84698bb888-jkh96
   - onap-sdc-sdc-dcae-fe-f5c95bff6-p5wbv
   - onap-sdc-sdc-dcae-tosca-lab-8b6dd6bd4-j56lp
   - onap-sdc-sdc-fe-568b95dc5b-r4wx5
   - onap-sdc-sdc-onboarding-be-6796c5576f-zzvp8
   - onap-sdc-sdc-wfd-be-7864b74798-zx475
   - onap-sdc-sdc-wfd-be-workflow-init-pcm6j
   - onap-sdc-sdc-wfd-fe-5d48444cbd-plctx
   - onap-sdnc-sdnc-ueb-listener-75d98567df-rphr4
   - onap-so-so-vnfm-adapter-6486b77447-kk4pp]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-16 13:54:37,368 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
No keyword with name 'dev-aaf' found.
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='appc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f729102d690>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-healthcheck.onap', port=80): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72911e7f90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic MUSIC Health Check                                              | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290f4fb10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic MUSIC Cassa Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='music.onap', port=8080): Max retries exceeded with url: /MUSIC/rest/v2/service/musicHealthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290f2ba50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290f5e110>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290ef05d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290f41190>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290ecfb90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-vnfm-adapter.onap', port=9092): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290e6e090>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7290d76450>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
59 critical tests, 46 passed, 13 failed
59 tests total, 46 passed, 13 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 2
Label: Code-Review=0