Update patch set 47
Patch Set 47:

> Patch Set 47:
> 
> @Adam, @Pawel when the init_container is invoked I am currently getting an error in certService
> 
> 2020-05-20 12:04:18.122 ERROR 1 [io-8443-exec-10] o.o.a.c.c.i.Cmpv2HttpClient              : IOException error null, while trying to connect CA RA
> 2020-05-20 12:04:18.123 ERROR 1 [io-8443-exec-10] o.o.a.c.a.a.CertificationExceptionAdvice : Exception occurred calling cmp client:
> 
> org.onap.aaf.certservice.cmpv2client.exceptions.CmpClientException: IOException error while trying to connect CA RA
> 	at org.onap.aaf.certservice.cmpv2client.impl.Cmpv2HttpClient.postRequest(Cmpv2HttpClient.java:78)
> 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.retrieveCertificates(CmpClientImpl.java:227)
> 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.createCertificate(CmpClientImpl.java:99)
> 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.createCertificate(CmpClientImpl.java:105)
> 	at org.onap.aaf.certservice.certification.CertificationProvider.signCsr(CertificationProvider.java:57)
> 	at org.onap.aaf.certservice.certification.CertificationModelFactory.createCertificationModel(CertificationModelFactory.java:67)
> 	at org.onap.aaf.certservice.api.CertificationController.signCertificate(CertificationController.java:92)
> 
> 
> Would this suggest that the certService cannot connect to the EJBCA rather than some configuration issue?

Also need to change protocol from http to https (I just saw the same in my local test env)

Patch-set: 47
Reviewer: Gerrit User 87 <87@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0