Update patch set 1
Patch Set 1: Code-Review-1

Lab test shows following issue: 
- syntax 
   value: "{{ .Values.vnfsdk-postgres.nameOverride }}.{{ include "common.namespace" . }}"
make all throws message : 
27-Apr-2018 14:34:19.425 SEVERE [http-nio-8702-exec-8] org.postgresql.Driver.connect Connection error:
 org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
  change to :  value: "{{ index .Values "vnfsdk-postgres" "nameOverride" }}.{{ include "common.namespace" . }}"

- position 
  put this environment variable under containers instead of init ccontainer, otherwise environment variable won't be transfered as expected. 
      containers:
      - image: "{{ include "common.repository" . }}/{{ .Values.image }}"
        imagePullPolicy: {{ .Values.pullPolicy | default .Values.global.pullPolicy }}
        name: {{ include "common.name" . }}
        env:
        - name: POSTGRES_IP
          value: "{{ index .Values "vnfsdk-postgres" "nameOverride" }}.{{ include "common.namespace" . }}"

- after above two change, POSTGRES_IP shows up as environment variable 
# printenv | grep POSTGRES
POSTGRES_IP=vnfsdk-postgres.onap
POSTGRES_SERVICE_PORT_HTTP=5432
POSTGRES_PORT_5432_TCP_ADDR=10.43.151.226
POSTGRES_SERVICE_HOST=10.43.151.226
POSTGRES_PORT_5432_TCP_PORT=5432
POSTGRES_PORT_5432_TCP_PROTO=tcp
POSTGRES_SERVICE_PORT=5432
POSTGRES_PORT=tcp://10.43.151.226:5432
POSTGRES_PORT_5432_TCP=tcp://10.43.151.226:5432

while error is still seen in log: 
cat /service/logs/catalina.out | more 
.....
27-Apr-2018 14:57:02.672 SEVERE [http-nio-8702-exec-7] org.postgresql.Driver.connect Connection error:
 org.postgresql.util.PSQLException: The connection attempt failed.

Seems POSTGRES_IP is not recognized.  
look at the other environment variables: 

service ClusterIP port:  POSTGRES_SERVICE_HOST=10.43.151.226 
root@k8s1:/stage/oom751/kubernetes# kubectl get services --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
.......
onap          postgres               ClusterIP   10.43.151.226   <none>        5432/TCP                     2d
onap          refrepo                NodePort    10.43.219.57    <none>        8702:30297/TCP               2d
onap          robot                  NodePort    10.43.46.154    <none>        88:30209/TCP                 2d

postgres DB IP: 
root@k8s1:/stage/oom751/kubernetes# kubectl describe pod dev-vnfsdk-postgres-588b6cc5c8-n56zg -n onap | grep IP
IP:             10.42.142.61

VNFSDK pod IP: 
root@k8s1:/stage/oom751/kubernetes# kubectl describe pod dev-vnfsdk-8d5869cbc-z8ww5 -n onap | grep IP
IP:             10.42.9.14

Have you tried service IP:  POSTGRES_SERVICE_HOST=10.43.151.226
it might be a better choice than postgres DB IP.

Patch-set: 1
Label: Code-Review=-1