Update patch set 47
Patch Set 47:

> Patch Set 47:
> 
> > Patch Set 47:
> > 
> > > Patch Set 47:
> > > 
> > > > Patch Set 47:
> > > > 
> > > > > Patch Set 47:
> > > > > 
> > > > > > Patch Set 47:
> > > > > > 
> > > > > > > Patch Set 47:
> > > > > > > 
> > > > > > > @Adam, @Pawel when the init_container is invoked I am currently getting an error in certService
> > > > > > > 
> > > > > > > 2020-05-20 12:04:18.122 ERROR 1 [io-8443-exec-10] o.o.a.c.c.i.Cmpv2HttpClient              : IOException error null, while trying to connect CA RA
> > > > > > > 2020-05-20 12:04:18.123 ERROR 1 [io-8443-exec-10] o.o.a.c.a.a.CertificationExceptionAdvice : Exception occurred calling cmp client:
> > > > > > > 
> > > > > > > org.onap.aaf.certservice.cmpv2client.exceptions.CmpClientException: IOException error while trying to connect CA RA
> > > > > > > 	at org.onap.aaf.certservice.cmpv2client.impl.Cmpv2HttpClient.postRequest(Cmpv2HttpClient.java:78)
> > > > > > > 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.retrieveCertificates(CmpClientImpl.java:227)
> > > > > > > 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.createCertificate(CmpClientImpl.java:99)
> > > > > > > 	at org.onap.aaf.certservice.cmpv2client.impl.CmpClientImpl.createCertificate(CmpClientImpl.java:105)
> > > > > > > 	at org.onap.aaf.certservice.certification.CertificationProvider.signCsr(CertificationProvider.java:57)
> > > > > > > 	at org.onap.aaf.certservice.certification.CertificationModelFactory.createCertificationModel(CertificationModelFactory.java:67)
> > > > > > > 	at org.onap.aaf.certservice.api.CertificationController.signCertificate(CertificationController.java:92)
> > > > > > > 
> > > > > > > 
> > > > > > > Would this suggest that the certService cannot connect to the EJBCA rather than some configuration issue?
> > > > > > 
> > > > > > Also need to change protocol from http to https (I just saw the same in my local test env)
> > > > > 
> > > > > Did it pass validation once you changed to https Dan?
> > > > 
> > > > Do you have cmpServers.json properly configured?
> > > 
> > > It's the one in resources/test just with the amended ejbca address
> > 
> > Actually, no - sorry,  I should have held off posting that comment until I tested.
> > 
> > We have a problem - AAF throws an exception if you configure a CMPv2 server to use https instead of http.  However, ejbca (the CMPv2 server they're using) is now configured to use https instead of http.
> > 
> > So, either ejbca needs to be reconfigured to use http OR we need a code change in aaf-certservice to support https
> 
> That's what I was thinking Dan and I would err towards changing the aaf-certservice because that is the one we control as opposed to the third party ejbca.

But it's configurable in EJBCA. When I was working with EJBCA charts it was set to http and whole flow was tested over http. Why is it working over https now?

Patch-set: 47
Reviewer: Gerrit User 3771 <3771@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>