Update patch set 3
Patch Set 3: Code-Review+1

Gating results

installation OK
results available: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169583698/artifacts/download

SO related tests are all OK

onap-so-so-bpmn-infra-7b4cf7dbf4-6z9gj                         1/1       Running            0          37m
onap-so-so-catalog-db-adapter-684f7f7f57-p9255                 1/1       Running            0          37m
onap-so-so-f57fb6c78-ms4jx                                     1/1       Running            0          36m
onap-so-so-mariadb-64765bffd8-82fvs                            1/1       Running            0          37m
onap-so-so-monitoring-594bd744b6-5wvl2                         1/1       Running            0          37m
onap-so-so-openstack-adapter-6c75fcdd89-lgx7v                  1/1       Running            2          37m
onap-so-so-request-db-adapter-6797d64c57-xvrkw                 1/1       Running            0          36m
onap-so-so-sdc-controller-849949db55-wp9hp                     1/1       Running            0          36m
onap-so-so-sdnc-adapter-64b78944c6-b8qq2                       1/1       Running            0          36m
onap-so-so-vfc-adapter-6df5476d68-hhkdj                        1/1       Running            0          36m

so                                 10.43.187.18    <nodes>                                8080:30277/TCP                                                37m
so-bpmn-infra                      10.43.227.172   <none>                                 8081/TCP                                                      37m
so-catalog-db-adapter              10.43.208.221   <none>                                 8082/TCP                                                      37m
so-mariadb                         10.43.146.235   <nodes>                                3306:30252/TCP                                                37m
so-monitoring                      10.43.100.134   <nodes>                                9091:30224/TCP                                                37m
so-openstack-adapter               10.43.51.28     <none>                                 8087/TCP                                                      37m
so-request-db-adapter              10.43.117.4     <none>                                 8083/TCP                                                      37m
so-sdc-controller                  10.43.153.58    <none>                                 8085/TCP                                                      37m
so-sdnc-adapter                    10.43.147.161   <none>                                 8086/TCP                                                      37m
so-vfc-adapter                     10.43.102.25    <none>                                 8084/TCP                                                      37m

Basic SO Health Check                                 | PASS |

Errors (a priori not related to the patch)
k8s
3 pods (on 225) are not in Running state
--------------------------------------------------------------------------------------
NAME                                                           READY     STATUS             RESTARTS   AGE
onap-appc-appc-ansible-server-598558f644-cs92c                 0/1       CrashLoopBackOff   9          42m
onap-dmaap-dmaap-bus-controller-577d694c69-xf7wb               0/1       ImagePullBackOff   0          42m
onap-dmaap-dmaap-dr-node-b488b99b5-qrw2w                       1/2       CrashLoopBackOff   11         42m

helm
all helm charts are DEPLOYED

healthcheck (medium)
Basic APPC Health Check                                 | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                       | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa100cce290>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check           | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check         | FAIL |
502 != 200

E2E tests not triggered due to healthcheck errors

Patch-set: 3
Label: Code-Review=+1