Update patch set 2
Patch Set 2:

The issue with sdnc-cds is probably not linked to this patch as the error raised on other recent patchsets...
Need to find the patch to blame but apparently it has already been merged..
 
the error is due to  onap-sdnc-cds-blueprints-processor (the other faulty pods are waiting for this one)

019-09-01 03:08:12,034|||main||||ERROR||||||| Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'primaryDatabaseConfiguration' defined in URL [jar:file:/opt/app/onap/lib/org.onap.ccsdk.cds.blueprintsprocessor-db-lib-0.5.1.jar!/org/onap/ccsdk/cds/blueprintsprocessor/db/primary/PrimaryDatabaseConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'primary-database-properties' defined in class path resource [org/onap/ccsdk/cds/blueprintsprocessor/db/BluePrintDBLibConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.onap.ccsdk.cds.blueprintsprocessor.db.PrimaryDataSourceProperties]: Factory method 'getPrimaryProperties' threw exception; nested exception is java.util.NoSuchElementException: No value bound

see https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results/94475-2/k8s/onap-k8s.log

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0