Update patch set 5
Patch Set 5: Code-Review+1

> Patch Set 5:
> 
> Gitlab Orange 1: 
> Full results can be seen here: https://gating-results.onap.eu/results//108825-5/index.html

good news AAF-SMS, OOF error is fixed!

However we got new HC errors (see https://gating-results.onap.eu/results/108825-5/healthcheck/full/full/report.html#totals?all)
- we got a 500 on DCAE, which is an error that occurs time to time
no log from https://gating-results.onap.eu/results/108825-5/infrastructure-healthcheck/k8s/pod-onap-dcae-healthcheck-7965c86b54-zl75c.html
- connection error on dmaap bus controller HC, service is declared but there were some init errors
https://gating-results.onap.eu/results/108825-5/infrastructure-healthcheck/k8s/service-dmaap-bc.html
- timeout on 1 of the VFC HC (ems driver)
I cans see 20299 [alarmManager] DEBUG org.onap.vfc.nfvo.emsdriver.collector.alarm.AlarmManager  - The configuration properties from /service/emsdriver/conf/config.properties is not load
java.net.UnknownHostException: dcae-ves-collector
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
in the pod logs https://gating-results.onap.eu/results/108825-5/infrastructure-healthcheck/k8s/pod-onap-vfc-ems-driver-84995cd654-5d86m-vfc-ems-driver-logs.html so I assume it could be an induced effect of DCAE error

the End2End freeradius is PASS but seen as fail in CI due to an error when cleaning the resources
The End2End clearwater was Ok up to Openstack (Onboarding/distri/instantiation from ONAP perspective)
the End2End error is something we observe (404 from AAI when requesting PNF info)
 
So from a AAF-SMS perspective I think it is OK..I would prefer a full green but I cannot say if some of the errors could be a side effect

Patch-set: 5
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1