Update patch set 10
Patch Set 10: Code-Review-1

you have an issue with helm: Release "onap-postgres" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "onap-postgres-db-root-password" in namespace "onap" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "onap-postgres": current value is "onap-policy"

please look at how dcae is using postgres in dedicated mode

Patch-set: 10
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1