Update patch set 2
Patch Set 2:

Strangely, after this commit merge deployment started failing on my v1.7.16 env.
[root@kubernetes-master-borislavto-2282-05-01-18 kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.16", GitCommit:"e8846c1d7e7e632d4bd5ed46160eff3dc4c993c5", GitTreeState:"clean", BuildDate:"2018-04-04T08:47:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@kubernetes-master-borislavto-2282-05-01-18 kubernetes]# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
[root@kubernetes-master-borislavto-2282-05-01-18 kubernetes]# helm upgrade -i aaa local/onap --namespace onap -f onap/resources/environments/disable-allcharts.yaml --set global.pullPolicy=IfNotPresent
Release "aaa" does not exist. Installing it now.
Error: Chart requires kubernetesVersion: ^1 ~1.7.14 || ~1.8.9 which is incompatible with Kubernetes v1.7.16

Propose to revert until further analysis.

Patch-set: 2