Update patch set 7
Patch Set 7:

> Patch Set 7: Code-Review-1
> 
> Error: YAML parse error on portal/charts/portal-app/templates/deployment.yaml: error converting YAML to JSON: yaml: line 60: did not find expected key

Hi Sylvain - I am extremely sorry...I had tested these in my deployment...Maybe something is wrong, with respect to spaces/extra characters etc. Not able to figure out, and will continue to find the root cause...I would appreciate if you let me know if you notice anything as well...Thank you very much!

Patch-set: 7
Reviewer: Gerrit User 213 <213@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>