Update patch set 1
Patch Set 1:

gating results

still lots of errors
no new error introduced by the patch a priori

logs: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180600721/artifacts/download

******** Kubernetes Results ********
 * Nb Pods: 170
 * Nb Failed Pods: 21
 * List of Failed Pods: [
   - onap-aai-aai-6f5878c75b-6hnmx
   - onap-aai-aai-champ-7f97f98976-9q29g
   - onap-aai-aai-graphadmin-c79fb7fcf-gtr5q
   - onap-aai-aai-graphadmin-create-db-schema-4dv9l
   - onap-aai-aai-resources-557c6f9d78-kfmql
   - onap-aai-aai-sparky-be-5ff8689c54-9k99g
   - onap-aai-aai-spike-77ccc5bf78-t95fk
   - onap-aai-aai-traversal-7fb5558d98-nqlzh
   - onap-aai-aai-traversal-update-query-data-qm5gs
   - onap-contrib-netbox-app-695fd89fd-m5knw
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-f69rn
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-jt6n8
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-64ttc
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-ssw68
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-lpjj6
   - onap-dcaegen2-dcae-servicechange-handler-566b98997-l4z7r
   - onap-so-so-bpmn-infra-7b4cf7dbf4-x5g72
   - onap-so-so-f57fb6c78-2zwf5
   - onap-so-so-request-db-adapter-6797d64c57-2l8rf
   - onap-so-so-sdc-controller-849949db55-cbbt4
   - onap-so-so-vfc-adapter-6df5476d68-brjn9]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 24
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdc
   - onap-vid]

Basic A&AI Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic AAF Health Check                                      | PASS |
--------------------------------------------------------------------
Basic AAF SMS Health Check                                  | PASS |
--------------------------------------------------------------------
Basic APPC Health Check                                     | FAIL |
Resolving variable '${resp.json()['output']['response-code']}' failed: ValueError: No JSON object could be decoded
--------------------------------------------------------------------
Basic CLI Health Check                                      | PASS |
--------------------------------------------------------------------
Basic CLAMP Health Check                                    | PASS |
--------------------------------------------------------------------
Basic DCAE Health Check                                     | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic DMAAP Data Router Health Check                        | PASS |
--------------------------------------------------------------------
Basic DMAAP Message Router Health Check                     | PASS |
--------------------------------------------------------------------
Basic External API NBI Health Check                         | PASS |
--------------------------------------------------------------------
Basic Log Elasticsearch Health Check                        | PASS |
--------------------------------------------------------------------
Basic Log Kibana Health Check                               | PASS |
--------------------------------------------------------------------
Basic Log Logstash Health Check                             | PASS |
--------------------------------------------------------------------
Basic Microservice Bus Health Check                         | PASS |
--------------------------------------------------------------------
Basic Multicloud API Health Check                           | PASS |
--------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                     | PASS |
--------------------------------------------------------------------
Basic Multicloud-pike API Health Check                      | PASS |
--------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                 | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check            | PASS |
--------------------------------------------------------------------
Basic Multicloud-vio API Health Check                       | PASS |
--------------------------------------------------------------------
Basic OOF-Homing Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835cf20b90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835ce92ad0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic OOF-CMSO Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835ce252d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Policy Health Check                                   | PASS |
--------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                | PASS |
--------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check  | PASS |
--------------------------------------------------------------------
Basic Portal Health Check                                   | PASS |
--------------------------------------------------------------------
Basic SDC Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='sdc-fe.onap', port=8181): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835ce60d50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic SDNC Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='sdnc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835ce60750>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic SO Health Check                                       | FAIL |
Test timeout 10 seconds exceeded.
--------------------------------------------------------------------
Basic UseCaseUI API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC catalog API Health Check                          | PASS |
--------------------------------------------------------------------
Basic VFC emsdriver API Health Check                        | PASS |
--------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                      | PASS |
--------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                 | PASS |
--------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                   | PASS |
--------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                  | PASS |
--------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC nslcm API Health Check                            | PASS |
--------------------------------------------------------------------
Basic VFC resmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnflcm API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC vnfres API Health Check                           | PASS |
--------------------------------------------------------------------
Basic VFC workflow API Health Check                         | PASS |
--------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                    | PASS |
--------------------------------------------------------------------
Basic VID Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='vid.onap', port=8080): Max retries exceeded with url: /vid/healthCheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835cd7dad0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic VNFSDK Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f835cd94dd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
--------------------------------------------------------------------
Basic Holmes Rule Management API Health Check               | FAIL |
502 != 200
--------------------------------------------------------------------
Basic Holmes Engine Management API Health Check             | FAIL |
502 != 200
--------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 38 passed, 14 failed

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0