Update patch set 2
Patch Set 2:

Gating results

Installation OK
Test results: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/170523664/artifacts/download

test issues not related to the patchset (issues seen also in other gatings)

k8s
6 pods (on 183) are not in Running state
----------------------------------------------------------------------
NAME                                                        READY     STATUS             RESTARTS   AGE
dep-dcae-datafile-collector-54ccf857b5-jcdml                1/2       ImagePullBackOff   0          1h
onap-appc-appc-ansible-server-598558f644-qr67d              0/1       CrashLoopBackOff   14         1h
onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-pdclq           0/2       Init:0/3           0          1h
onap-dmaap-dmaap-bus-controller-577d694c69-tm74z            0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-b488b99b5-5wkvc                    0/2       Init:0/1           6          1h
onap-dmaap-dmaap-dr-prov-64c9b6b677-q4gw6                   0/2       Init:0/1           7          1h

Helm
All charts successfully deployed

Healthcheck
Basic DCAE Health Check                                    | FAIL |
500 != 200
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                      | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15976b5950>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                | FAIL |
502 != 200
----------------------------------------------------------------------
Basic OOF-Homing Health Check                             | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15974ad310>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-SNIRO Health Check                             | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15974ad950>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic OOF-CMSO Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15974b7dd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Policy Health Check                                  | FAIL |
ConnectionError: HTTPSConnectionPool(host='drools.onap', port=6969): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f15974c3e50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check              | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-aaictxbuilder.onap', port=9530): Max retries exceeded with url: /aaicontextbuilder/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f159749ed50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check               | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-sdcctxbuilder.onap', port=9530): Max retries exceeded with url: /sdccontextbuilder/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f159745a050>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check   | FAIL |
ConnectionError: HTTPConnectionPool(host='pomba-networkdiscoveryctxbuilder.onap', port=9530): Max retries exceeded with url: /ndcontextbuilder/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15974ad110>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check              | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check            | FAIL |
502 != 200

E2E tests not triggered

Patch-set: 2
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0