Update patch set 5
Patch Set 5:

Gitlab Orange 3: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//99860-5/index.html
______________ Results _________________
************ Infrastructure-healthcheck Results ************
--------> onap-k8s
 * Nb Pods: 209
 * Nb Failed Pods: 34
 * List of Failed Pods: [
   - onap-aaf-aaf-sms-c94596d94-6bvxz
   - onap-aai-aai-54b878b7bb-5sbwd
   - onap-aai-aai-data-router-7cd8669b68-hvltn
   - onap-aai-aai-graphadmin-685b96b959-2npzf
   - onap-aai-aai-graphadmin-create-db-schema-8wbhw
   - onap-aai-aai-resources-5b9756d844-xxp4n
   - onap-aai-aai-sparky-be-756d5dc559-lff6c
   - onap-aai-aai-traversal-7fff868546-97hlp
   - onap-cassandra-cassandra-0
   - onap-cds-cds-sdc-listener-75c5fd5ffb-mhccn
   - onap-contrib-awx-0
   - onap-dcaegen2-dcae-servicechange-handler-6555db5d47-5r5mk
   - onap-dmaap-dmaap-dr-prov-8644899b67-xbm7g
   - onap-oof-oof-86c448d5c7-zxf6s
   - onap-oof-oof-has-api-5bb7b84888-c7r2f
   - onap-oof-oof-has-controller-56f598fb9f-566jg
   - onap-oof-oof-has-data-d575ff6df-4n679
   - onap-oof-oof-has-reservation-547c8f4d7f-f8dzb
   - onap-oof-oof-has-solver-746bff67d8-5z9fv
   - onap-portal-portal-app-846f555cdc-gthc4
   - onap-sdc-sdc-be-569bf64759-9ndvg
   - onap-sdc-sdc-be-config-backend-rmfsd
   - onap-sdc-sdc-cs-config-cassandra-x5849
   - onap-sdc-sdc-dcae-be-877f5d9c4-mxk7t
   - onap-sdc-sdc-dcae-dt-77fbfbcb7-q825j
   - onap-sdc-sdc-dcae-fe-779f6767cd-ckmth
   - onap-sdc-sdc-dcae-tosca-lab-86956f76c6-jvbp7
   - onap-sdc-sdc-fe-cdcc4cfff-wbn64
   - onap-sdc-sdc-onboarding-be-59dc6f9f9f-m2kww
   - onap-sdc-sdc-wfd-be-58556cf84d-rm78t
   - onap-sdc-sdc-wfd-fe-5bb84c977b-fj5l5
   - onap-sdnc-sdnc-ueb-listener-5f757dd5b9-tmmjp
   - onap-uui-uui-server-676957854d-46psn
   - onap-vid-vid-7fc999ff94-dk6sg]
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-dmaap]
************************************************************
********************* Healthcheck Results ******************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-01-06 17:32:12,385 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0ef3d23220>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-01-06 17:30:16,779 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='aai.onap', port=8443): Max retries exceeded with url: /aai/v16/service-design-and-creation/models/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff8e5d3dbe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
************************************************************
********************** Smoke usecases **********************
End to End VNF use cases not executed!
____________________________________

Patch-set: 5
Label: Code-Review=0