Update patch set 14
Patch Set 14:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//98185-14/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 243
 * Nb Failed Pods: 3
 * List of Failed Pods: [
   - onap-aai-aai-data-router-7cd8669b68-ds8v6
   - onap-aai-aai-graphgraph-5875c7ffdb-dkn2g
   - onap-nbi-nbi-67bbf99cf7-pfb9g]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-nbi]
******** Healthcheck Results *******
2019-11-19 17:18:32,692 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='nbi.onap', port=8080): Max retries exceeded with url: /nbi/api/v4/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5528d38290>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
SSLError: HTTPSConnectionPool(host='so-vnfm-adapter.onap', port=9092): Max retries exceeded with url: /manage/health (Caused by SSLError(SSLError(1, u'[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)'),))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 56 passed, 5 failed
61 tests total, 56 passed, 5 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
******** healthdist Results *******
____________________________________

Patch-set: 14
Label: Code-Review=0