Update patch set 18
Patch Set 18:

Gitlab Orange 2: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96159-18/index.html
______________ Results _________________
************ Infrastructure-healthcheck Results ************
--------> onap-k8s
 * Nb Pods: 230
 * Nb Failed Pods: 13
 * List of Failed Pods: [
   - onap-aaf-aaf-cm-76bf68f7bf-zsqk2
   - onap-aaf-aaf-gui-c8b9f4b6f-fvhld
   - onap-aaf-aaf-sms-c94596d94-gcgst
   - onap-dmaap-dmaap-dr-prov-5b46b4979d-45zsj
   - onap-dmaap-message-router-mirrormaker-56d96bf84-5ltd9
   - onap-oof-oof-86c448d5c7-nsn45
   - onap-oof-oof-cmso-optimizer-5884678759-ctp9h
   - onap-oof-oof-cmso-service-66ff6f6cd8-vhlms
   - onap-oof-oof-has-api-5bb7b84888-c4997
   - onap-oof-oof-has-controller-56f598fb9f-88lcs
   - onap-oof-oof-has-data-d575ff6df-gjbbz
   - onap-oof-oof-has-reservation-547c8f4d7f-hp4nf
   - onap-oof-oof-has-solver-746bff67d8-xglvw]
--------> onap-helm
 * Nb Helm Charts: 36
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sniro-emulator]
************************************************************
********************* Healthcheck Results ******************
--------> robot  full healthcheck tests
2020-01-18 18:55:22,950 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c79ab8cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
500 != 200
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c792efcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c793dccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c79314950>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPSConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c79ab8e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic CDS Health Check                                                | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
46 critical tests, 37 passed, 9 failed
46 tests total, 37 passed, 9 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
--------> postinstall tests (dmaap and A&AI)
2020-01-18 18:52:58,882 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
403 != 200
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml
************************************************************
********************** Smoke usecases **********************
--------> End to End tests (onap-tests)
+------------------------+---------------------+------------------------+------------------+----------------+
|       TEST CASE        |       PROJECT       |          TIER          |     DURATION     |     RESULT     |
+------------------------+---------------------+------------------------+------------------+----------------+
|        basic_vm        |     integration     |     smoke-usecases     |      XX:XX       |      FAIL      |
|     freeradius_nbi     |     integration     |     smoke-usecases     |      04:29       |      FAIL      |
|     clearwater_ims     |     integration     |     smoke-usecases     |      00:00       |      SKIP      |
+------------------------+---------------------+------------------------+------------------+----------------+

____________________________________

Patch-set: 18
Label: Code-Review=0