Update patch set 7
Patch Set 7: Code-Review+1

Gating results

ready to merge :)
Basic Multicloud-starlingx API Health Check            | PASS |

logs: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/182807150

results

******** Kubernetes Results ********
 * Nb Pods: 197
 * Nb Failed Pods: 10
 * List of Failed Pods: [
   - onap-appc-appc-ansible-server-598558f644-vzgsg
   - onap-contrib-netbox-app-695fd89fd-5qnhv
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-7lbw6
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-rq8tg
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-ht5qt
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-cxnl2
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-fcjsb
   - onap-dmaap-dmaap-bc-68f4565db7-hbrn5
   - onap-sdnc-blueprints-processor-6d8c669cb-2xv2c
   - onap-sdnc-controller-blueprints-64b8cf4c7c-7f9p5]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 27
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]

Basic A&AI Health Check                                  | PASS |
-----------------------------------------------------------------
Basic AAF Health Check                                   | PASS |
-----------------------------------------------------------------
Basic AAF SMS Health Check                               | PASS |
-----------------------------------------------------------------
Basic APPC Health Check                                  | FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic CLI Health Check                                   | PASS |
-----------------------------------------------------------------
Basic CLAMP Health Check                                 | PASS |
-----------------------------------------------------------------
Basic DCAE Health Check                                  | FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic DMAAP Data Router Health Check                     | PASS |
-----------------------------------------------------------------
Basic DMAAP Message Router Health Check                  | PASS |
-----------------------------------------------------------------
Basic External API NBI Health Check                      | PASS |
-----------------------------------------------------------------
Basic Log Elasticsearch Health Check                     | PASS |
-----------------------------------------------------------------
Basic Log Kibana Health Check                            | PASS |
-----------------------------------------------------------------
Basic Log Logstash Health Check                          | PASS |
-----------------------------------------------------------------
Basic Microservice Bus Health Check                      | PASS |
-----------------------------------------------------------------
Basic Multicloud API Health Check                        | PASS |
-----------------------------------------------------------------
Basic Multicloud-ocata API Health Check                  | PASS |
-----------------------------------------------------------------
Basic Multicloud-pike API Health Check                   | PASS |
-----------------------------------------------------------------
Basic Multicloud-starlingx API Health Check              | PASS |
-----------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check         | PASS |
-----------------------------------------------------------------
Basic Multicloud-vio API Health Check                    | PASS |
-----------------------------------------------------------------
Basic OOF-Homing Health Check                            | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c201284d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic OOF-SNIRO Health Check                             | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c200e0850>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic OOF-CMSO Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c202d28d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic Policy Health Check                                | PASS |
-----------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check             | PASS |
-----------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check             | PASS |
-----------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check| PASS |
-----------------------------------------------------------------
Basic Portal Health Check                                | PASS |
-----------------------------------------------------------------
Basic SDC Health Check                                   | PASS |
-----------------------------------------------------------------
Basic SDNC Health Check                                  | PASS |
-----------------------------------------------------------------
Basic SO Health Check                                    | FAIL |
Variable '${SO_VNFM_ENDPOINT}' not found. Did you mean:
    ${SO_VFC_ENDPOINT}
-----------------------------------------------------------------
Basic UseCaseUI API Health Check                         | PASS |
-----------------------------------------------------------------
Basic VFC catalog API Health Check                       | PASS |
-----------------------------------------------------------------
Basic VFC emsdriver API Health Check                     | PASS |
-----------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                   | PASS |
-----------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check              | PASS |
-----------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                | PASS |
-----------------------------------------------------------------
Basic VFC multivimproxy API Health Check                 | PASS |
-----------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check               | PASS |
-----------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                 | PASS |
-----------------------------------------------------------------
Basic VFC nslcm API Health Check                         | PASS |
-----------------------------------------------------------------
Basic VFC resmgr API Health Check                        | PASS |
-----------------------------------------------------------------
Basic VFC vnflcm API Health Check                        | PASS |
-----------------------------------------------------------------
Basic VFC vnfmgr API Health Check                        | PASS |
-----------------------------------------------------------------
Basic VFC vnfres API Health Check                        | PASS |
-----------------------------------------------------------------
Basic VFC workflow API Health Check                      | PASS |
-----------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                 | PASS |
-----------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                 | PASS |
-----------------------------------------------------------------
Basic VID Health Check                                   | PASS |
-----------------------------------------------------------------
Basic VNFSDK Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8c1ffc5dd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic Holmes Rule Management API Health Check            | FAIL |
502 != 200
-----------------------------------------------------------------
Basic Holmes Engine Management API Health Check          | FAIL |
502 != 200
-----------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 43 passed, 9 failed

Patch-set: 7
Label: Code-Review=+1