Update patch set 1
Patch Set 1:

in theory patch has no impact
on gating we see that all healthcheck tests are still OK
but 2 pods in crashloopbackup leading to model distribution errors, which explains why healthdist and vnf tests are FAIL.

in the log of onap-sdnc-cds-sdc-listener-5c8c4f6c89-45sc9 we can see 
java.lang.reflect.UndeclaredThrowableException: Failed to invoke event listener method
HandlerMethod details: 
Bean [org.onap.ccsdk.cds.sdclistener.client.SdcListenerClient]
Method [public void org.onap.ccsdk.cds.sdclistener.client.SdcListenerClient.initSdcClient() throws org.onap.ccsdk.cds.sdclistener.exceptions.SdcListenerException]
Resolved arguments: 

	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:276)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.onap.ccsdk.cds.sdclistener.SdcListenerApplication.main(SdcListenerApplication.java:26)
Caused by: org.onap.ccsdk.cds.sdclistener.exceptions.SdcListenerException: SDC distribution client init failed with reason:authorization failure for user vid
	at org.onap.ccsdk.cds.sdclistener.client.SdcListenerClient.startSdcClientBasedOnTheResult(SdcListenerClient.java:73)
	at org.onap.ccsdk.cds.sdclistener.client.SdcListenerClient.initSdcClient(SdcListenerClient.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:259)
	... 13 common frames omitted
2019-06-25 19:14:18,341|||main||||INFO||||||| Shutting down ExecutorService 'applicationTaskExecutor'
2019-06-25 19:14:18,342|||main||||INFO||||||| Stopping GRPC connection to CDS backend

Patch-set: 1