Update patch set 3
Patch Set 3:

> FYI after this was merged, I'm getting this error on helm install:
 > 
 > Error: error validating "": error validating data: found invalid
 > field imagePullSecrets for v1.PersistentVolumeClaimSpec
 > 
 > I've updated OOM-779 to report this issue.

Same when deploying only appc:

#  helm upgrade -i aaa local/onap --namespace onap -f onap/resources/environments/disable-allcharts.yaml --set appc.enabled=true,global.pullPolicy=IfNotPresent

Release "aaa" does not exist. Installing it now.
2018/05/02 06:45:08 warning: skipped value for image: Not a table.
NAME:   aaa
LAST DEPLOYED: Wed May  2 06:45:09 2018
NAMESPACE: onap
STATUS: DEPLOYED

RESOURCES:
==> v1/PersistentVolumeClaim
NAME              STATUS  VOLUME            CAPACITY  ACCESS MODES  STORAGECLASS      AGE
aaa-appc-db-data  Bound   aaa-appc-db-data  1Gi       RWX           aaa-appc-db-data  0s

==> v1beta1/StatefulSet
NAME         DESIRED  CURRENT  AGE
aaa-appc-db  1        1        0s
aaa-appc     3        3        0s
aaa-dbcl-db  2        1        0s

==> v1beta1/Deployment
NAME                      DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
aaa-appc-cdt              1        1        1           0          0s
aaa-appc-dgbuilder        1        1        1           0          0s
aaa-dmaap-bus-controller  1        1        1           0          0s

==> v1/Pod(related)
NAME                                       READY  STATUS             RESTARTS  AGE
aaa-appc-cdt-54df796868-77bxv              0/1    ContainerCreating  0         0s
aaa-appc-dgbuilder-856445d5d-bvtmp         0/1    Init:0/1           0         0s
aaa-dmaap-bus-controller-6d7b65cdb8-w2pss  0/1    Init:0/1           0         0s
aaa-appc-db-0                              0/2    Init:0/2           0         0s
aaa-appc-0                                 0/2    Pending            0         0s
aaa-appc-1                                 0/2    Pending            0         0s
aaa-appc-2                                 0/2    Pending            0         0s
aaa-dbcl-db-0                              0/1    Pending            0         0s

==> v1/Secret
NAME                      TYPE                     DATA  AGE
aaa-appc-dgbuilder        Opaque                   1     0s
aaa-appc-db               Opaque                   1     0s
aaa-appc                  Opaque                   1     0s
aaa-dbcl-db               Opaque                   3     0s
onap-docker-registry-key  kubernetes.io/dockercfg  1     0s

==> v1/ConfigMap
NAME                                DATA  AGE
aaa-appc-dgbuilder-config           1     0s
aaa-appc-dgbuilder-scripts          2     0s
aaa-appc-db-db-configmap            2     0s
aaa-appc-logging-cfg                1     0s
aaa-appc-onap-sdnc-svclogic-bin     1     0s
aaa-appc-onap-appc-bin              2     0s
aaa-appc-onap-sdnc-svclogic-config  1     0s
aaa-appc-onap-sdnc-bin              2     0s
aaa-appc-filebeat                   1     0s
aaa-appc-onap-appc-svclogic-bin     1     0s
aaa-appc-onap-appc-data-properties  4     0s
aaa-appc-onap-appc-svclogic-config  1     0s
aaa-appc-onap-sdnc-data-properties  3     0s
aaa-dmaap-bus-controller-config     1     0s

==> v1/PersistentVolume
NAME               CAPACITY  ACCESS MODES  RECLAIM POLICY  STATUS     CLAIM                                STORAGECLASS      REASON  AGE
aaa-appc-db-data   1Gi       RWX           Retain          Bound      onap/aaa-appc-db-data                aaa-appc-db-data  0s
aaa-appc-data2     1Gi       RWO           Retain          Bound      onap/aaa-appc-data-aaa-appc-0        aaa-appc-data     0s
aaa-appc-data1     1Gi       RWO           Retain          Bound      onap/aaa-appc-data-aaa-appc-1        aaa-appc-data     0s
aaa-appc-data0     1Gi       RWO           Retain          Bound      onap/aaa-appc-data-aaa-appc-2        aaa-appc-data     0s
aaa-dbcl-db-data0  1Gi       RWO           Retain          Bound      onap/aaa-dbcl-db-data-aaa-dbcl-db-0  aaa-dbcl-db-data  0s
aaa-dbcl-db-data1  1Gi       RWO           Retain          Available  aaa-dbcl-db-data                     0s

==> v1beta1/ClusterRoleBinding
NAME          AGE
onap-binding  0s

==> v1/Service
NAME              TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)                        AGE
appc-cdt          NodePort   10.43.217.161  <none>       80:30289/TCP                   0s
appc-dgbuilder    NodePort   10.43.176.19   <none>       3000:30228/TCP                 0s
appc-sdnctldb02   ClusterIP  None           <none>       3306/TCP                       0s
appc-sdnctldb01   ClusterIP  None           <none>       3306/TCP                       0s
appc-dbhost-read  ClusterIP  10.43.178.164  <none>       3306/TCP                       0s
appc-dbhost       ClusterIP  None           <none>       3306/TCP                       0s
appc-cluster      ClusterIP  None           <none>       2550/TCP                       0s
appc              NodePort   10.43.139.29   <none>       8282:30230/TCP,1830:30231/TCP  0s
dbcl-postgres     ClusterIP  10.43.229.74   <none>       5432/TCP                       0s
dbcl-pg-primary   ClusterIP  10.43.97.238   <none>       5432/TCP                       0s
dbcl-pg-replica   ClusterIP  10.43.219.157  <none>       5432/TCP                       0s
dmaap-bc          ClusterIP  10.43.39.75    <none>       8080/TCP,8443/TCP              0s

Patch-set: 3