Update patch set 1
Patch Set 1: Code-Review-1

looks like some glitch in the patch:

Error: release dupa failed: Secret "dupa-mariadb-init-ynsaUCru6mUNwGal" is invalid: metadata.name: Invalid value: "dupa-mariadb-init-ynsaUCru6mUNwGal": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')


maybe you broke the relation chain and this one should be on the top of the other oof patch?

Patch-set: 1
Reviewer: Gerrit User 4965 <4965@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1