Update patch set 3
Patch Set 3:

Gitlab Azure AKS 4: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//118427-3/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 10
 * Nb Failed Jobs: 8
 * List of Failed Jobs: [
   - integration-onap-internal-check-certs
   - onap-aaf-sms-preload
   - onap-aai-graphadmin-create-db-schema
   - onap-aai-traversal-update-query-data
   - onap-awx
   - onap-dmaap-bc-dmaap-provisioning
   - onap-ejbca-config-config-job
   - onap-netbox-app-provisioning]
 * Nb Deployments: 65
 * Nb Failed Deployments: 52
 * List of Failed Deployments: [
   - onap-a1policymanagement
   - onap-aaf-cm
   - onap-aaf-fs
   - onap-aaf-gui
   - onap-aaf-locate
   - onap-aaf-oauth
   - onap-aaf-service
   - onap-aaf-sms
   - onap-aai
   - onap-aai-graphadmin
   - onap-aai-resources
   - onap-aai-sparky-be
   - onap-aai-traversal
   - onap-appc-cdt
   - onap-appc-dgbuilder
   - onap-cds-blueprints-processor
   - onap-cds-command-executor
   - onap-cds-sdc-listener
   - onap-cli
   - onap-cps
   - onap-cps-postgres-primary
   - onap-cps-postgres-replica
   - onap-dbc-pg-primary
   - onap-dbc-pg-replica
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-config-binding-service
   - onap-dcae-dashboard
   - onap-dcae-dashboard-pg-primary
   - onap-dcae-dashboard-pg-replica
   - onap-dcae-db-primary
   - onap-dcae-db-replica
   - onap-dcae-deployment-handler
   - onap-dcae-inv-pg-primary
   - onap-dcae-inv-pg-replica
   - onap-dcae-inventory-api
   - onap-dcae-policy-handler
   - onap-dcae-servicechange-handler
   - onap-dcaemod-db-primary
   - onap-dcaemod-db-replica
   - onap-dcaemod-designtool
   - onap-dcaemod-distributor-api
   - onap-dcaemod-genprocessor
   - onap-dcaemod-nifi-registry
   - onap-dcaemod-onboarding-api
   - onap-dcaemod-runtime-api
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-ejbca
   - onap-esr-gui
   - onap-esr-server
   - onap-netbox-app]
 * Nb StatefulSets: 15
 * Nb Failed StatefulSets: 11
 * List of Failed StatefulSets: [
   - onap-appc
   - onap-appc-ansible-server
   - onap-appc-db
   - onap-awx
   - onap-cassandra
   - onap-cds-db
   - onap-dmaap-dr-db
   - onap-dmaap-dr-node
   - onap-message-router
   - onap-message-router-kafka
   - onap-message-router-zookeeper]
 * Nb Persistent Volume Claims: 44
 * Nb Failed Persistent Volume Claims: 12
 * List of Failed Persistent Volume Claims: [
   - kafka-data-onap-message-router-kafka-0
   - kafka-data-onap-message-router-kafka-1
   - kafka-data-onap-message-router-kafka-2
   - onap-aaf-sshsm-distcenter
   - onap-dbc-pg-primary
   - onap-dbc-pg-replica
   - onap-dmaap-dr-db-onap-dmaap-dr-db-0
   - onap-dmaap-dr-node-event-logs-onap-dmaap-dr-node-0
   - onap-dmaap-dr-node-spool-onap-dmaap-dr-node-0
   - zookeeper-data-onap-message-router-zookeeper-0
   - zookeeper-data-onap-message-router-zookeeper-1
   - zookeeper-data-onap-message-router-zookeeper-2]
--------> onap-helm
 * Nb Helms: 22
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-oof]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-03-04 18:46:40,229 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | FAIL |
200 != 202
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-fe.onap', port=9443): Max retries exceeded with url: /sdc1/rest/healthCheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1a138e2190>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so.onap', port=8080): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a137f7f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 40 passed, 3 failed
43 tests total, 40 passed, 3 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests
Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
Send registration request to VES without CMPv2 certificate :: This... | PASS |
Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: FAIL (04:33)
--------> CDS tests
basic_cds: PASS (00:31)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
Setting Global Variables :: This test case checks suite if it is w... | PASS |
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
--------> basic_vm tests
basic_vm: FAIL (04:33)
--------> basic_network tests
basic_network: FAIL (04:34)
--------> basic_cnf tests NOT executed

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> cis_kubernetes tests
cis_kubernetes: PASS (00:00)
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (00:52)
--------> jdpw_ports tests
jdpw_ports: PASS (05:42)
--------> kube_hunter tests
kube_hunter: FAIL (00:00)
--------> root_pods tests
root_pods: FAIL (02:47)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (01:13)

____________________________________________________________

Patch-set: 3