Update patch set 25
Patch Set 25:

> Patch Set 25:
> 
> Gitlab Orange 4: 
> Full results can be seen here: https://logs.onap.org/onap-integration/gating//119309-25/index.html
> ______________ Results ______________________
> 
> ************************************************************
> ************************************************************
> ************ Infrastructure-healthcheck Results ************
> ************************************************************
> ************************************************************
> --------> onap-k8s
>  * Nb Jobs: 28
>  * Nb Failed Jobs: 2
>  * List of Failed Jobs: [
>    - onap-aaf-sms-preload
>    - onap-oof-has-healthcheck]
>  * Nb Deployments: 152
>  * Nb Failed Deployments: 7
>  * List of Failed Deployments: [
>    - onap-aaf-sms
>    - onap-oof
>    - onap-oof-has-api
>    - onap-oof-has-controller
>    - onap-oof-has-data
>    - onap-oof-has-reservation
>    - onap-oof-has-solver]
>  * Nb StatefulSets: 27
>  * Nb Failed StatefulSets: 1
>  * List of Failed StatefulSets: [
>    - onap-aaf-sms-vault]
>  * Nb Persistent Volume Claims: 75
>  * Nb Failed Persistent Volume Claims: 0
> --------> onap-helm
>  * Nb Helms: 35
>  * Nb Failed Helms: 0
> 
> ************************************************************
> ************************************************************
> ********************* Healthcheck Results ******************
> ************************************************************
> ************************************************************
> --------> robot full healthcheck tests
> 2021-03-27 09:55:29,564 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Basic A&AI Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced A&AI Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic AAF Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic AAF SMS Health Check                                            | FAIL |
> ConnectionError: HTTPSConnectionPool(host='aaf-sms.onap', port=10443): Max retries exceeded with url: /v1/sms/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdf204c6950>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic APPC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic CLI Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic CLAMP Health Check                                              | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Microservices Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Data Router Health Check                                  | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Message Router Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> ------------------------------------------------------------------------------
> Basic External API NBI Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Microservice Bus Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-pike API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-starlingx API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-vio API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-k8s API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-Homing Health Check                                         | FAIL |
> ConnectionError: HTTPSConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdf20174110>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic OOF-OSDF Health Check                                           | FAIL |
> ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdf20222550>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic OOF-CMSO Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic Policy Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Enhanced Policy New Healthcheck                                       | PASS |
> ------------------------------------------------------------------------------
> Basic Portal Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDC Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDC Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDNC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDNC Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic SO Health Check                                                 | PASS |
> ------------------------------------------------------------------------------
> Basic UseCaseUI API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC gvnfmdriver API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic VFC nslcm API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnflcm API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfmgr API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfres API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC ztevnfmdriver API Health Check                              | PASS |
> ------------------------------------------------------------------------------
> Basic VID Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic VNFSDK Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-fcaps API Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic Modeling genericparser API Health Check                         | PASS |
> ------------------------------------------------------------------------------
> Enhanced CDS Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> 44 critical tests, 41 passed, 3 failed
> 44 tests total, 41 passed, 3 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/full/output.xml
> 
> ************************************************************
> ************************************************************
> ********************* Basic tests Results ******************
> ************************************************************
> ************************************************************
> --------> healthdist (vFW onboarding and distribution)
> Health-Check :: Test that ONAP components are available via basic ... | PASS |
> --------> postinstall tests (dmaap and A&AI)
> Post-Install-Tests :: Testing Installation                            | PASS |
> --------> CMPv2 tests
> Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
> Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
> Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
> Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
> Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
> Send registration request to VES without CMPv2 certificate :: This... | PASS |
> Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
> --------> DCAEMOD tests
> Deploy DCAE Simple Application Without Config Map In Config Spec J... | PASS |
> Deploy DCAE Simple Application With Config Map In Config Spec Json... | PASS |
> Deploy DCAE Simple Application With Config Map In Config Spec Json... | PASS |
> Dcaemod                                                               | PASS |
> --------> HV-VES tests
> Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
> --------> VES collector tests
> Ves :: Suite for checking handling events by VES Collector            | PASS |
> --------> Basic Onboard tests (SDC)
> basic_onboard: PASS (02:44)
> --------> CDS tests
> basic_cds: PASS (00:21)
> 
> ************************************************************
> ************************************************************
> ******************** End to End usecases *******************
> ************************************************************
> ************************************************************
> --------> pnf-registrate tests
> PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | FAIL |
> Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
> --------> 5gbulkpm tests
> Setting Global Variables :: This test case checks suite if it is w... | PASS |
> 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> --------> basic_vm tests
> basic_vm: FAIL (36:46)
> --------> basic_network tests
> basic_network: PASS (15:45)
> --------> basic_cnf tests
> basic_cnf: FAIL (36:09)
> 
> ************************************************************
> ************************************************************
> ********************** Security tests **********************
> ************************************************************
> ************************************************************
> --------> cis_kubernetes tests
> cis_kubernetes: PASS (00:00)
> --------> nonssl_endpoints tests
> nonssl_endpoints: FAIL (01:05)
> --------> jdpw_ports tests
> jdpw_ports: PASS (07:55)
> --------> kube_hunter tests
> kube_hunter: PASS (00:05)
> --------> root_pods tests
> root_pods: FAIL (02:38)
> --------> unlimitted_pods tests
> unlimitted_pods: FAIL (01:05)
> 
> ____________________________________________________________



I still see the issue on the TEXT_ column of the reported.
Cory, could you please check if there is somethin else missing from the camunda 7.14 perspective in the code.


org.camunda.bpm.engine.impl.jobexecutor.ExecuteJobsRunnable.run(ExecuteJobsRunnable.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.camunda.bpm.engine.ProcessEngineException: ENGINE-03004 Exception while executing Database Operation 'INSERT HistoricVariableInstanceEntity[1e7cc3bb-8ee5-11eb-9fc0-ea508ef963cc]' with message '
### Error flushing statements.  Cause: org.apache.ibatis.executor.BatchExecutorException: org.camunda.bpm.engine.impl.persistence.entity.HistoricVariableInstanceEntity.insertHistoricVariableInstance (batch index #1) failed. Cause: java.sql.BatchUpdateException: (conn=3097) Data too long for column 'TEXT_' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: org.camunda.bpm.engine.impl.persistence.entity.HistoricVariableInstanceEntity.insertHistoricVariableInstance (batch index #1) failed. Cause: java.sql.BatchUpdateException: (conn=3097) Data too long for column 'TEXT_' at row 1
java.sql.BatchUpdateException: (conn=3097) Data too long for column 'TEXT_' at row 1
java.sql.SQLSyntaxErrorException: (conn=3097) Data too long for column 'TEXT_' at row 1
org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Data too long for column 'TEXT_' at row 1
java.sql.SQLException: Data too long for column 'TEXT_' at row 1
'. Flush summary:

Patch-set: 25