Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//96252-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 180
 * Nb Failed Pods: 76
 * List of Failed Pods: [
   - onap-aaf-aaf-sms-74975b77f-ngqxh
   - onap-aai-aai-65845d5d97-qx7qx
   - onap-aai-aai-graphadmin-6c5544c67c-fw4bd
   - onap-aai-aai-graphgraph-7b85fcb46-lsmlj
   - onap-aai-aai-resources-5955466f6f-rrb8c
   - onap-aai-aai-sparky-be-68bcf7c4c-29jtt
   - onap-aai-aai-traversal-7f77cb867c-vl9tx
   - onap-appc-appc-cdt-5fdf6cb46d-t9kx8
   - onap-cds-cds-blueprints-processor-944878fb6-bqzzt
   - onap-cds-cds-command-executor-74dffcb87d-k8nl6
   - onap-cds-cds-db-0
   - onap-cds-cds-sdc-listener-75c5fd5ffb-phjx7
   - onap-clamp-clamp-backend-8ccc4cf8c-vqrbn
   - onap-contrib-awx-0
   - onap-dcaegen2-dcae-dashboard-755449d876-ht6dq
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-s5nbg
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-zgq2l
   - onap-dmaap-dmaap-dr-node-0
   - onap-dmaap-message-router-0
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-mirrormaker-7974bb7697-ngmk5
   - onap-oof-music-tomcat-bdd9547bf-4w887
   - onap-oof-music-tomcat-bdd9547bf-cw27d
   - onap-oof-music-tomcat-bdd9547bf-hcwjq
   - onap-oof-oof-cmso-optimizer-769ffdd7d-8l4pv
   - onap-oof-oof-d8f7dbfbf-h4fnx
   - onap-oof-oof-has-api-7b7f4c95b9-pp5ms
   - onap-oof-oof-has-controller-7db5bf5f8b-dzqq2
   - onap-oof-oof-has-data-8dc9c79dd-rmphl
   - onap-oof-oof-has-reservation-589cc655f4-rsjg7
   - onap-oof-oof-has-solver-55d9849c69-w9d4w
   - onap-policy-policy-api-664f4bf674-cwwbm
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-gj9qv
   - onap-sdc-sdc-be-565dcfd9d-lksdh
   - onap-sdc-sdc-dcae-be-85c669ddbf-h86r4
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-g5cbk
   - onap-sdc-sdc-dcae-fe-5488b88f8c-5jz9r
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-7nbrx
   - onap-sdc-sdc-fe-694f4d7576-5gbd9
   - onap-sdc-sdc-kb-5b48c6fd44-ttbdt
   - onap-sdc-sdc-onboarding-be-58f66544b6-n4psb
   - onap-sdnc-network-name-gen-85ff6b896c-gqwc4
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-648f95867c-ktpv8
   - onap-sdnc-sdnc-dbinit-job-x9nmb
   - onap-sdnc-sdnc-dgbuilder-94dcbdf77-dkxxc
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-zsnmd
   - onap-sdnc-sdnc-portal-6876fc8849-wj25b
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-7hp7r
   - onap-so-so-55844c65cf-c96mv
   - onap-so-so-bpmn-infra-6f4bf9bd69-lnl6w
   - onap-so-so-catalog-db-adapter-b7db48446-cp5ck
   - onap-so-so-mariadb-config-job-nfk9f
   - onap-so-so-openstack-adapter-558795cbb6-5n5kd
   - onap-so-so-request-db-adapter-68f6988cbd-j5qd8
   - onap-so-so-sdc-controller-59fc7d59d4-d69xv
   - onap-so-so-sdnc-adapter-66cc47dbd6-4896r
   - onap-so-so-sdnc-adapter-66cc47dbd6-5rfws
   - onap-so-so-sdnc-adapter-66cc47dbd6-bgk2b
   - onap-so-so-sdnc-adapter-66cc47dbd6-fc8zr
   - onap-so-so-sdnc-adapter-66cc47dbd6-pzgcc
   - onap-so-so-sdnc-adapter-66cc47dbd6-qfxz7
   - onap-so-so-sdnc-adapter-66cc47dbd6-r75w9
   - onap-so-so-sdnc-adapter-66cc47dbd6-vcng7
   - onap-so-so-sdnc-adapter-66cc47dbd6-wgct5
   - onap-so-so-sdnc-adapter-66cc47dbd6-zlbgd
   - onap-so-so-vfc-adapter-65f66cbbd9-qq46j
   - onap-so-so-vnfm-adapter-5fcb47c8c-z55g6
   - onap-vfc-vfc-catalog-7467879cb6-j226b
   - onap-vfc-vfc-generic-vnfm-driver-65c4d9f888-rldhp
   - onap-vfc-vfc-nslcm-ccc867b6f-lgkpt
   - onap-vfc-vfc-vnflcm-5f79cb477d-794tg
   - onap-vfc-vfc-vnfmgr-77fccd68fd-cmdxz
   - onap-vfc-vfc-vnfres-7f786df9d9-nksnh
   - onap-vnfsdk-vnfsdk-7b5746d6cd-8ls7n
   - onap-vnfsdk-vnfsdk-init-postgres-h48zj]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-26 03:46:22,889 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c6676e090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0