Update patch set 2
Patch Set 2:

Same on k8s v1.10
[root@kubernetes-master-borislavto-13099-05-13-18 kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
[root@kubernetes-master-borislavto-13099-05-13-18 kubernetes]# helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
[root@kubernetes-master-borislavto-13099-05-13-18 kubernetes]# helm upgrade -i aaa local/onap --namespace onap -f onap/resources/environments/disable-allcharts.yaml --set global.pullPolicy=IfNotPresent
Release "aaa" does not exist. Installing it now.
Error: Chart requires kubernetesVersion: ^1 ~1.7.14 || ~1.8.9 which is incompatible with Kubernetes v1.10.2

Patch-set: 2