Update patch set 1
Patch Set 1: -Code-Review

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1: Code-Review+2
> > > > 
> > > > just have a question before merge.
> > > > I see in logs:
> > > > 2020-10-21T11:32:36.553Z||main|||||ERROR|500||Error reading truststore, TLS connection will fail.
> > > > java.io.FileNotFoundException: ServletContext resource [/opt/app/osaaf/local/org.onap.so.trust.jks] cannot be resolved to URL because it does not exist
> > > > 
> > > > and /opt/app/osaaf/local/org.onap.so.trust.jks is the place where the truststore is supposed to be (at least that's what we see in cert initializer logs)
> > > > 
> > > > any reason for that?
> > > 
> > > What pod are you seeing this??? if it is spring boot application and you have property defined for it in application.yaml then try it with "file:/opt/app/osaaf/local/org.onap.so.trust.jks" and make sure you have correct permission for this file
> > 
> > here: https://logs.onap.org/onap-integration/gating//114085-1/infrastructure-healthcheck/k8s/kubernetes-status/pod-onap-so-etsi-nfvo-ns-lcm-7f7b87b9-bj4vz-so-etsi-nfvo-ns-lcm-logs.html
> > 
> > so gating pod with default dir
> 
> Replace it with "file:/opt/app/osaaf/local/org.onap.so.trust.jks" and that should resolve FileNotFoundException
> 
> does this JKS file contains MSB cert? if not it might break the communication between ETSI-NFVO and ETSI_Catalog

well, the more I see etsi-nfvo, the less I understand :( 

in override.yaml, I can see ${TRUSTSTORE}

so I believe from what you say that the value of ${TRUSTSTORE} should be file:/opt/app/osaaf/local/org.onap.so.trust.jks no?

But, I don't see where this value is set ($TRUSTORE) as it's not in the deployment ENV part...

for the msb part, it should be there, although MSB should move to AAF but that's another story, but I've just seen that the import init container didn't worked so I have to dig into that.

Patch-set: 1
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0