Update patch set 3
Patch Set 3: Code-Review-1

https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/pipelines/264286568

Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-bpmn-infra.onap', port=8081): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf4bfbf850>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 3
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1