Update patch set 2
Patch Set 2:

onnectionError: HTTPConnectionPool(host='appc.onap', port=8282): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fba181e6710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------

sounds like the hostname is not right. and I did not change this config in this gerrit.

We did the same test in appc-csit jenkins job. all are successful.

https://jenkins.onap.org/view/appc/job/appc-master-csit-healthcheck/

Patch-set: 2