Update patch set 1
Patch Set 1:

OOM Gating triggered (as any OOM patchset)

installation OK
test results temporarily (artifacts stored for 2 days) available at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/169330807/artifacts/download

10 pods (on 229) are not in Running state
--------------------------------------------------------------------------------------
NAME                                                           READY     STATUS             RESTARTS   AGE
onap-appc-appc-ansible-server-598558f644-bnq6l                 0/1       CrashLoopBackOff   14         1h
onap-dmaap-dmaap-bus-controller-577d694c69-wmmjb               0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-b488b99b5-h98bk                       1/2       CrashLoopBackOff   17         1h
onap-oof-oof-has-api-7597966cb9-wwzbh                          0/1       CrashLoopBackOff   16         1h
onap-oof-oof-has-controller-755f689584-lt8vc                   0/1       CrashLoopBackOff   15         1h
onap-oof-oof-has-data-c7788fc4d-x8l4t                          0/1       Init:2/4           6          1h
onap-oof-oof-has-healthcheck-7g72h                             0/1       Init:0/1           6          1h
onap-oof-oof-has-reservation-6cb9fd8b48-lv825                  0/1       Init:2/4           6          1h
onap-oof-oof-has-solver-54f46bbccc-fr4hc                       0/1       Init:2/4           6          1h
onap-vnfsdk-vnfsdk-init-postgres-p4h7q                         0/1       Init:0/1           0          43s

All helm chart in DEPLOYED status

Healthcheck tests

3 errors (medium) 
Basic APPC Health Check                            | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check                   | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4e1e395350>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic OOF-Homing Health Check                             | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------

E2E tests not triggered due to dmaap errors (core healthcheck FAIL is blocking)

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=0