Update patch set 2
Patch Set 2:

So I tested again with:
kubernetes 1.12.7 and helm 2.12.3.
I still have the error:

    - execute "bash"  "/tmp/chef-script20190416-14-rklfrp"
  * bash[excuting-titanSchemaCreation.sh] action run
    [execute] java -Dlogback.configurationFile=/tmp/sdctool/scripts/../config/logback.xml -cp ::/tmp/sdctool/scripts/../asdctool-1.4.0-SNAPSHOT-jar-with-dependencies.jar: org.openecomp.sdc.asdctool.main.DataSchemaMenu create-titan-structures /tmp/sdctool/config
              2019-04-16T13:21:22.227Z|||main||SDC-TOOL||ERROR|MAJOR||beFqdn_IS_UNDEFINED||o.o.s.c.config.EcompErrorLogUtil||ActivityType=<log>, Desc=<Invalid configuration in YAML file. Could not set error info type for message id >
              2019-04-16T13:21:22.244Z|||main||SDC-TOOL||WARN|||beFqdn_IS_UNDEFINED||o.o.s.c.util.YamlToObjectConverter||ActivityType=<log>, Desc=<The file /tmp/sdctool/config/neo4j-errors-configuration.yaml cannot be found. Ignore reading configuration.>
              2019-04-16T13:21:22.245Z|||main||SDC-TOOL||WARN|||beFqdn_IS_UNDEFINED||o.o.s.c.util.YamlToObjectConverter||ActivityType=<log>, Desc=<The file /tmp/sdctool/config/ecomp-error-configuration.yaml cannot be found. Ignore reading configuration.>
              2019-04-16T13:21:22.246Z|||main||SDC-TOOL||WARN|||beFqdn_IS_UNDEFINED||o.o.s.c.util.YamlToObjectConverter||ActivityType=<log>, Desc=<The file /tmp/sdctool/config/distribution-engine-configuration.yaml cannot be found. Ignore reading configuration.>
              2019-04-16T13:21:22.253Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||o.o.s.a.impl.TitanGraphInitializer||ActivityType=<createGraph>, Desc=<** createGraph with /tmp/sdctool/config//titan.properties>
              2019-04-16T13:21:22.253Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||o.o.s.a.impl.TitanGraphInitializer||ActivityType=<createGraph>, Desc=<createGraph : try to load file /tmp/sdctool/config//titan.properties>
              2019-04-16T13:21:22.678Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.n.a.c.i.ConnectionPoolMBeanManager||ActivityType=<registerMonitor>, Desc=<Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool>
              2019-04-16T13:21:22.694Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.n.a.c.i.CountingConnectionPoolMonitor||ActivityType=<onHostAdded>, Desc=<AddHost: cassandra.onap>
              2019-04-16T13:21:22.809Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.n.a.c.i.ConnectionPoolMBeanManager||ActivityType=<registerMonitor>, Desc=<Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=KeyspaceTitanConnectionPool,ServiceType=connectionpool>
              2019-04-16T13:21:22.810Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.n.a.c.i.CountingConnectionPoolMonitor||ActivityType=<onHostAdded>, Desc=<AddHost: cassandra.onap>
              2019-04-16T13:21:22.843Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.n.a.c.i.CountingConnectionPoolMonitor||ActivityType=<onHostRemoved>, Desc=<RemoveHost: cassandra.onap>
              2019-04-16T13:21:45.359Z|||main||SDC-TOOL||INFO|||beFqdn_IS_UNDEFINED||c.t.t.d.util.BackendOperation||ActivityType=<executeDirect>, Desc=<Temporary exception during backend operation [getConfiguration]. Attempting backoff retry.>
              com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Temporary failure in storage backend
              	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:114)
              	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:78)
              	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:67)
              	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:91)
              	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration$1.call(KCVSConfiguration.java:88)
              	at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:133)
              	at com.thinkaurelius.titan.diskstorage.util.BackendOperation$1.call(BackendOperation.java:147)
              	at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
              	at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
              	at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:144)
              	at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.get(KCVSConfiguration.java:88)
              	at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.isFrozen(BasicConfiguration.java:93)
              	at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1338)
              	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
              	at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:62)
              	at org.openecomp.sdc.asdctool.impl.TitanGraphInitializer.createGraph(TitanGraphInitializer.java:55)
              	at org.openecomp.sdc.asdctool.main.DataSchemaMenu.main(DataSchemaMenu.java:68)
              Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
              	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init>(RoundRobinExecuteWithFailover.java:48)
              	at com.netflix.astyanax.connectionpool.impl.TokenAwareConnectionPoolImpl.newExecuteWithFailover(TokenAwareConnectionPoolImpl.java:83)
              	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
              	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:538)
              	at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:112)
              	... 16 common frames omitted

Patch-set: 2
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0