Update patch set 6
Patch Set 6:

> hi Mahendra and Mike, all crashed component contain a mysql
 > database in their docker image. that's why they are looking for
 > database at their own pod IP:3306 and localhost:3306. How do you
 > suggest that we fix this issue.Should we set the database ip to the
 > service name of their component?

Hi Yan,

The issue appears when VFC is deployed in a multi-node kubernetes cluster. The databases do not seem to come up.

[33] 20 Apr 17:53:44.794 # Server started, Redis version 2.8.4
[33] 20 Apr 17:53:44.794 * The server is now ready to accept connections on port 6379
 * Starting MySQL database server mysqld
   ...fail!
start create nfvocatalog db
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
failed to create nfvocatalog database
Unhandled exception in thread started by <function wrapper at 0x7f33a1ed2ed8>
. . . .
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)”)

Not sure why they are failing, needs to be investigated. There are other pods that are also failing in a multi-node environment. These have been traced back to communication-related issues, like not using the service names for hostname resolution.  If you discover this is a communication issue and need the ip assigned to the pod, this can be made available through environment variables and or configuration.

If you and Mahendra need a working environment in the open lab to test with, please look at this guide to set one up https://wiki.onap.org/display/DW/ONAP+on+Windriver+ONAP+Developer+Cloud. Or ping me and I can build one for you.

Patch-set: 6
Reviewer: Gerrit User 127 <127@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0