Update patch set 16
Patch Set 16:

Latest patch set failed due to Mariadb error which prevents us from installing our directed graphs:

java.sql.SQLNonTransientConnectionException: (conn=599) WSREP has not yet prepared node for application use

Seems like a timing error related to Galera replication. Can try rerunning gating test to see if that helps

Patch-set: 16
Reviewer: Gerrit User 87 <87@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>