Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2: Code-Review-1
> > 
> > all DCAE pods are failing
> 
> Looking at the report on orange-opensource.gitlab.io, it appears that
> - healthcheck and inventory-api are running as expected
> - bootstrap, cloudify-manager, dashboard, deployment-handler, and policy-handler are in the init state, waiting for other components to come up
> - config-binding-service and service-change-handler are in crash loop backoff during their init states.
> 
> To investigate further, it would be helpful to have log output for:
> 
> onap-dcaegen2-dcae-config-binding-service-bc98b8449-hsxsb, containers dcae-config-binding-service-readiness and init-tls
> 
> onap-dcaegen2-dcae-servicechange-handler-d4f8c6c59-tfprm, containers dcae-servicechange-handler-readiness and init-tls

first "all" was maybe (cough cough ;) ) exaggerated ;)

At the end of https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//99998-2/infrastructure-healthcheck/k8s/onap-k8s.log, 
you can see the logs (actually the stdout of the pods but in this case it's OK) of all containers of a failed pod:

example for onap-dcaegen2-dcae-config-binding-service-bc98b8449-hsxsb:
#### Certificate Authorization Artifact
2020-01-15T11:15:06.204+0000 INIT [cadi] cadi_keyfile points to /opt/app/osaaf/local/org.onap.dcae.keyfile
2020-01-15T11:15:06.215+0000 INIT [cadi] https.protocols set by cadi_protocols in CADI Properties
2020-01-15T11:15:06.215+0000 INIT [cadi] jdk.tls.client.protocols set from Default Protocols
2020-01-15T11:15:07.200+0000: Trans Info
         Read Artifact 477.66675ms
 
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.readArtifact(Agent.java:542)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:313)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
#### Certificate Authorization Artifact must be valid to continue
Initialization complete
+ /opt/app/aaf_config/bin/agent.sh aafcli showpass dcae@dcae.onap.org dcae
+ grep cadi_keystore_password_p12
+ cut -d = -f 2-
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.showPass(Agent.java:774)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:325)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
+ /opt/app/aaf_config/bin/agent.sh aafcli showpass dcae@dcae.onap.org dcae
+ grep cadi_keystore_password_jks=
+ cut -d = -f 2-
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.showPass(Agent.java:774)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:325)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
+ /opt/app/aaf_config/bin/agent.sh aafcli showpass dcae@dcae.onap.org dcae+ 
grep cadi_truststore_password=
+ cut -d = -f 2-
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.showPass(Agent.java:774)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:325)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
+ cp /opt/app/osaaf/local/org.onap.dcae.p12 /opt/app/osaaf/cert.p12

Compared to "official" aaf container, the good part is that you fails when retrieval is not good. here it seems that a value is not good and so you fail

for onap-dcaegen2-dcae-servicechange-handler-d4f8c6c59-tfprm , it seems to be the same issue:


#### Certificate Authorization Artifact
2020-01-15T11:18:46.795+0000 INIT [cadi] cadi_keyfile points to /opt/app/osaaf/local/org.onap.dcae.keyfile
2020-01-15T11:18:46.806+0000 INIT [cadi] https.protocols set by cadi_protocols in CADI Properties
2020-01-15T11:18:46.806+0000 INIT [cadi] jdk.tls.client.protocols set from Default Protocols
2020-01-15T11:18:47.895+0000: Trans Info
         Read Artifact 562.3394ms
 
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.readArtifact(Agent.java:542)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:313)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more

Patch-set: 2