Update patch set 5
Patch Set 5:

@Sylvain and @Krzysztof, from the looks of the logs now, it looks like the issue is SO not even able to start and its coming from the SO service not connecting to the maria db.
This patch shouldn't affect that so we are not sure what is going on here.

```
https://logs.onap.org/onap-integration/gating//123671-5/k8s/k8s/kubernetes-status/pod-onap-so-mariadb-config-job-945fb-so-mariadb-config-logs.html

ERROR 1049 (42000) at line 18: Unknown database 'camundabpmn'
ERROR 1046 (3D000) at line 20: No database selected
ERROR 1046 (3D000) at line 28: No database selected
ERROR 1046 (3D000) at line 34: No database selected
ERROR 1046 (3D000) at line 48: No database selected
ERROR 1046 (3D000) at line 60: No database selected
ERROR 1046 (3D000) at line 67: No database selected
ERROR 1046 (3D000) at line 75: No database selected
ERROR 1046 (3D000) at line 80: No database selected
ERROR 1046 (3D000) at line 85: No database selected
ERROR 1046 (3D000) at line 89: No database selected
ERROR 1046 (3D000) at line 93: No database selected
ERROR 1046 (3D000) at line 98: No database selected
ERROR 1046 (3D000) at line 103: No database selected
```

```
https://logs.onap.org/onap-integration/gating//123671-5/k8s/k8s/kubernetes-status/pod-onap-so-nssmf-adapter-cc76479b5-m287t-so-nssmf-adapter-logs.html

2021-09-10T14:23:33.177Z||main|||||INFO|500||HikariPool-1 - Starting...
2021-09-10T14:23:34.377Z||main|||||ERROR|500||HikariPool-1 - Exception during pool initialization.
java.sql.SQLSyntaxErrorException: Could not connect to address=(host=mariadb-galera)(port=3306)(type=master) : (conn=1761) Unknown database 'requestdb'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1372)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.(HikariPool.java:115)
```

Can you help us with identifying the root cause with the SO services not starting?

Patch-set: 5
Reviewer: Gerrit User 75 <75@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>