Update patch set 5
Patch Set 5:

@Jorge, When I did helm deploy, built with this patch, I got the following errors:

fetching local/onap
Release "dev-policy" does not exist. Installing it now.
Error: release dev-policy failed: secrets "dev-policy-db-secret" already exists

my command was "helm deploy dev-policy local/onap -f /root/oom/kubernetes/onap/resources/environments/public-cloud.yaml -f /root/integration-override.yaml --namespace onap --verbose"

do I need to clean up the cache under deploy plugin? not sure how to fix it.

Patch-set: 5
Reviewer: Gerrit User 2477 <2477@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>