Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3: Code-Review-1
> > > 
> > > It is common practice to make changes to the original commit and reply to any code review comments.
> > > https://gerrit.onap.org/r/c/oom/+/130214
> > > 
> > > Without them we lose historical changes to the patch.
> > > 
> > > Also, could you please build, deploy and test this change locally before pushing to gerrit.
> > > On each patch set, a new set of gating runs are triggered which uses unnecessary resources.
> > 
> > well,i followed your tips to use oom postgres, but i met the following errors:
> > 
> > i use 
> > `Make SKIP_LINT=TRUE uui`
> > to build helm charts
> > then i use
> > `helm install dev-uui local/uui --set globalPassword=123456 -n uui`
> > the readiness probe cannot get access to init-postgres. it logs  http 403.
> > and my server didn`t start.
> > i found it met same situation in vnfsdk ,when i use command:
> > `helm install dev-vnfsdk local/vnfsdk --set globalPassword=123456 -n uui`
> > the readiness probe cannot get access to init-postgres. it logs  http 403.
> > 
> > 
> > i thought it might be questions about my local env. so i committed once for test. 
> > therefore,i found no logs about my first three commit-lint check. Is there any tips about recheck my lint error?
> 
> So I think you will have to deploy the common postgres chart also.
> I don't tend to use helm install, rather the helm deploy plugin developed internally. This is also what is used in gating.
> 
> You can make all with:
> make SKIP_LINT=TRUE all, then
> 
> use the following overrides to deploy the required components with the following cmd:
> 
> helm deploy onap local/onap --verbose --namespace onap --create-namespace --set global.masterPassword=test -f overrides_uui.yaml
> 
> ########
> overrides_uui.yaml
> 
> global:
>   repository: nexus3.onap.org:10001
>   pullPolicy: IfNotPresent
>   masterPassword: 'test'
> 
>   # Change to an unused port prefix range to prevent port conflicts
>   # with other instances running within the same k8s cluster
>   nodePortPrefix: 302
>   nodePortPrefixExt: 304
> 
>   # ONAP Repository
>   # Uncomment the following to enable the use of a single docker
>   # repository but ONLY if your repository mirrors all ONAP
>   # docker images. This includes all images from dockerhub and
>   # any other repository that hosts images for ONAP components.
>   #repository: nexus3.onap.org:10001
>   repositoryCred:
>     user: docker
>     password: docker
>   dockerHubRepository: docker.io
> 
>   busyboxRepository: docker.io
> 
>    # common global images
>   # Busybox for simple shell manipulation
>   busyboxImage: busybox:1.34.1
> 
>   # curl image
>   curlImage: curlimages/curl:7.80.0
> 
>   # env substitution image
>   envsubstImage: dibi/envsubst:1
> 
>   # generate htpasswd files image
>   # there's only latest image for htpasswd
>   htpasswdImage: xmartlabs/htpasswd:latest
> 
>   # kubenretes client image
>   kubectlImage: bitnami/kubectl:1.22.4
> 
>   # logging agent
>   loggingImage: beats/filebeat:5.5.0
> 
>   # mariadb client image
>   mariadbImage: bitnami/mariadb:10.7.3
> 
>   # nginx server image
>   nginxImage: bitnami/nginx:1.21.4
> 
>   # postgreSQL client and server image
>   postgresImage: crunchydata/crunchy-postgres:centos8-13.2-4.6.1
> 
>   # readiness check image
>   readinessImage: onap/oom/readiness:3.0.1
> 
>   # default mount path root directory referenced
>   # by persistent volumes and log files
>   persistence:
>     mountPath: /dockerdata-nfs
>     enableDefaultStorageclass: false
>     parameters: {}
>     storageclassProvisioner: kubernetes.io/no-provisioner
>     volumeReclaimPolicy: Retain
> 
>   # override default resource limit flavor for all charts
>   flavor: unlimited
> 
>   # flag to enable debugging - application support required
>   debugEnabled: false
> 
>   # default password complexity
>   # available options: phrase, name, pin, basic, short, medium, long, maximum security
>   # More datails: https://masterpassword.app/masterpassword-algorithm.pdf
>   passwordStrength: short
> 
>   # configuration to set log level to all components (the one that are using
>   # "common.log.level" to set this)
>   # can be overrided per components by setting logConfiguration.logLevelOverride
>   # to the desired value
>   logLevel: DEBUG
> 
>   clusterName: cluster.local
> 
>   #Global ingress configuration
>   ingress:
>     enabled: false
>     virtualhost:
>         enabled: true
>         baseurl: "simpledemo.onap.org"
> 
>   # Global Service Mesh configuration
>   # POC Mode, don't use it in production
>   serviceMesh:
>     enabled: false
>     tls: true
> 
>   # Disabling AAF
>   # POC Mode, only for use in development environment
>   # Keep it enabled in production
>   aafEnabled: true
>   aafAgentImage: onap/aaf/aaf_agent:2.1.20
> 
> aaf:
>   enabled: true
> postgres:
>   enabled: true
> uui:
>   enabled: true


i have tried my best to identify the lint problem , it logs:
```Release "onap-uui" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].volumeMounts[3]): missing required field "name" in io.k8s.api.core.v1.VolumeMount```

then i use
helm template onap local/onap --namespace onap  --set global.masterPassword=test -f /home/junyi/overrides_uui.yaml >/home/junyi/onap.yaml
to get my template. 
i figured it that my volumeMounts declared:
```         {{- if .Values.global.aafEnabled }}
          volumeMounts: {{ include "common.certInitializer.volumeMount" . | nindent 10 }}
          - mountPath: /uui/run.sh
            name: entrypoint
            subPath: run.sh
          - mountPath: /config/application.properties
            name: config
            subPath: application.properties
      volumes: {{ include "common.certInitializer.volumes" . | nindent 6 }}
      - name: config
        configMap:
          name: {{ include "common.fullname" . }}
      - name: entrypoint
        configMap:
          name: {{ include "common.fullname" . }}-entrypoint
          defaultMode: 0755
      {{- end }}
```
but the result shows that:
```          volumeMounts: 
          - mountPath: /opt/app/osaaf
            name: onap-uui-server-aaf-config
          - mountPath: /uui/run.sh
            name: entrypoint
            subPath: run.sh
          - mountPath: /config/application.properties
            name: config
            subPath: application.properties
          - mountPath: /
```

i don`t know why the last line came out without a mount name

```- mountPath: /```

i dont know how to solve this problem 

i tried to add:

```
          - mountPath: /
            name: empty
```

in my uui-server/template/deployment.yaml , but it didn`t work. the error occured as well.

if there is any solution or experience,please reply.

Patch-set: 3