Update patch set 1
Patch Set 1: Code-Review+1

gating result
seems OK:
onap-dmaap-message-router-kafka-0                              1/1       Running            1          1h
onap-dmaap-message-router-kafka-1                              1/1       Running            0          1h
onap-dmaap-message-router-kafka-2                              1/1       Running            1          1h
onap-dmaap-message-router-zookeeper-0                          1/1       Running            0          1h
onap-dmaap-message-router-zookeeper-1                          1/1       Running            0          1h
onap-dmaap-message-router-zookeeper-2                          1/1       Running            0          1h



Jobs with issue:
- Step: apps_test
  * Project: xtesting-onap-gitlab-com
  * Status: failed
  * Pipeline: 'https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/pipelines/52604458'
  * API pipeline url: 'https://gitlab.com/api/v4/projects/10614465/pipelines/52604458'
  * Failed jobs:
  *   - id: 180438330
  *     name: healthcheck-k8s/onap_healthcheck_k8s
  *     status: failed
  *     duration: 143.65059
  *     link: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180438330
  *   - id: 180438331
  *     name: healthcheck-onap/onap_healthcheck_core
  *     status: failed
  *     duration: 204.632665
  *     link: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180438331
  *   - id: 180438332
  *     name: healthcheck-onap/onap_healthcheck_small
  *     status: failed
  *     duration: 197.866049
  *     link: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180438332
  *   - id: 180438333
  *     name: healthcheck-onap/onap_healthcheck_medium
  *     status: failed
  *     duration: 197.642514
  *     link: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180438333
  *   - id: 180438334
  *     name: healthcheck-onap/onap_healthcheck_full
  *     status: failed
  *     duration: 198.287979
  *     link: https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/180438334


______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 195
 * Nb Failed Pods: 27
 * List of Failed Pods: [
   - onap-appc-appc-ansible-server-598558f644-gvqst
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-pklks
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-z6nmv
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-gcd5d
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-tnjrh
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-rwcq9
   - onap-dmaap-dmaap-dr-db-0
   - onap-dmaap-dmaap-dr-node-0
   - onap-dmaap-dmaap-dr-prov-76bbc6f4b9-vwd8m
   - onap-portal-portal-app-6bc896647f-dlzvg
   - onap-portal-portal-db-5b747697b6-lj5d9
   - onap-portal-portal-db-config-9mhqm
   - onap-portal-portal-sdk-6c7cdc58f9-pwnl2
   - onap-portal-portal-widget-597bb6f96f-lj988
   - onap-sdnc-blueprints-processor-6d8c669cb-q295z
   - onap-sdnc-controller-blueprints-64b8cf4c7c-5d248
   - onap-sdnc-sdnc-ansible-server-64f864fd54-g5qws
   - onap-sdnc-sdnc-dmaap-listener-7c99c9dc6f-2gftv
   - onap-sdnc-sdnc-portal-848d54f7c4-sqm9c
   - onap-sdnc-sdnc-ueb-listener-7587fb798c-jrlnt
   - onap-so-so-bpmn-infra-7b4cf7dbf4-hwrrm
   - onap-so-so-catalog-db-adapter-684f7f7f57-6sjzs
   - onap-so-so-f57fb6c78-5smpw
   - onap-so-so-openstack-adapter-6c75fcdd89-ww4tk
   - onap-so-so-request-db-adapter-6797d64c57-lr284
   - onap-so-so-sdc-controller-849949db55-8nwm5
   - onap-so-so-vfc-adapter-6df5476d68-5n8nc]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-03-19 16:53:30,227 - xtesting.core.robotframework - INFO -
==============================================================================
Health-Check :: Testing ecomp components are available via calls.
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5801a3c10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa58019b190>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5801480d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa58014e890>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | FAIL |
Resolving variable '${resp.json()['detailedMsg']}' failed: KeyError: 'detailedMsg'
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa5800dac10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
52 critical tests, 38 passed, 14 failed
52 tests total, 38 passed, 14 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Chart onap-dmaap
STATUS: FAILED
Chart problem
info:
  Description: 'Release "onap-dmaap" failed post-install: timed out waiting for the
    condition'
  first_deployed:
    nanos: 60260142
    seconds: 1553009423
  last_deployed:
    nanos: 60260142
    seconds: 1553009423
  status:
    code: 4
name: onap-dmaap
namespace: onap

Patch-set: 1
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+1