Update patch set 4
Patch Set 4:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//93750-4/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 186
 * Nb Failed Pods: 67
 * List of Failed Pods: [
   - onap-aaf-aaf-service-7f99bc58fc-dxqpd
   - onap-aai-aai-modelloader-85776bdff6-rqmvf
   - onap-aai-aai-sparky-be-68bcf7c4c-qrqxj
   - onap-appc-appc-0
   - onap-appc-appc-dgbuilder-856dc44bf-grz8q
   - onap-cds-cds-blueprints-processor-944878fb6-tsl5k
   - onap-cds-cds-command-executor-74dffcb87d-6szsr
   - onap-cds-cds-sdc-listener-75c5fd5ffb-tk9ht
   - onap-contrib-awx-0
   - onap-dcaegen2-dcae-dashboard-755449d876-6sbwg
   - onap-dcaegen2-dcae-inventory-api-5c6b949bbf-2dq6n
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-9gmrt
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-4dshq
   - onap-dmaap-dmaap-bc-84cf999b96-srl8g
   - onap-dmaap-message-router-0
   - onap-dmaap-message-router-kafka-0
   - onap-dmaap-message-router-kafka-1
   - onap-dmaap-message-router-mirrormaker-7974bb7697-phswq
   - onap-modeling-modeling-genericparser-7c4d976d97-4xskw
   - onap-msb-msb-discovery-777f7bb588-lw9lx
   - onap-multicloud-multicloud-pike-f6b446c58-ghrmd
   - onap-oof-oof-cmso-optimizer-769ffdd7d-l5c66
   - onap-oof-oof-cmso-service-656c5dbfb5-q5g2d
   - onap-oof-oof-d8f7dbfbf-pxldb
   - onap-oof-oof-has-api-7b7f4c95b9-qrdmw
   - onap-oof-oof-has-controller-7db5bf5f8b-6m5nt
   - onap-oof-oof-has-data-8dc9c79dd-v8mwn
   - onap-oof-oof-has-reservation-589cc655f4-d8ts7
   - onap-oof-oof-has-solver-55d9849c69-mlkc9
   - onap-policy-policy-api-664f4bf674-fd255
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-g42f6
   - onap-pomba-pomba-kibana-74f9c6b5cd-bhj7c
   - onap-pomba-pomba-sdncctxbuilder-9478c9bfc-7wt9x
   - onap-sdc-sdc-be-565dcfd9d-b7r8g
   - onap-sdc-sdc-be-config-backend-7fj5d
   - onap-sdc-sdc-dcae-be-85c669ddbf-6nch5
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-7bzsj
   - onap-sdc-sdc-dcae-fe-5488b88f8c-vj9mw
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-lr287
   - onap-sdc-sdc-fe-694f4d7576-ppncx
   - onap-sdc-sdc-kb-5b48c6fd44-75lhg
   - onap-sdc-sdc-onboarding-be-58f66544b6-77c82
   - onap-sdc-sdc-onboarding-be-cassandra-init-bd944
   - onap-sdc-sdc-wfd-be-54ff7b9948-nw4z5
   - onap-sdc-sdc-wfd-be-workflow-init-nj876
   - onap-sdc-sdc-wfd-fe-647d64468f-lxpjw
   - onap-sdnc-network-name-gen-85ff6b896c-4jklv
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-648f95867c-pqkd6
   - onap-sdnc-sdnc-dbinit-job-9rjcx
   - onap-sdnc-sdnc-dgbuilder-94dcbdf77-4chgf
   - onap-sdnc-sdnc-dmaap-listener-86775f7769-8wnk4
   - onap-sdnc-sdnc-portal-6876fc8849-llxtz
   - onap-sdnc-sdnc-ueb-listener-5dd8c464f9-k9vwj
   - onap-so-so-55844c65cf-4sgzh
   - onap-so-so-bpmn-infra-6f4bf9bd69-vtzrq
   - onap-so-so-catalog-db-adapter-b7db48446-b2hpw
   - onap-so-so-openstack-adapter-558795cbb6-sfzp7
   - onap-so-so-request-db-adapter-68f6988cbd-nqcfl
   - onap-so-so-sdc-controller-59fc7d59d4-stq7k
   - onap-so-so-vfc-adapter-65f66cbbd9-lztxr
   - onap-vfc-vfc-nslcm-ccc867b6f-fftr7
   - onap-vfc-vfc-vnflcm-5f79cb477d-rp5kg
   - onap-vfc-vfc-vnfmgr-77fccd68fd-dfqcn
   - onap-vfc-vfc-vnfres-7f786df9d9-9dhrs
   - onap-vid-vid-f7cf7dbb7-gt8cv
   - onap-vnfsdk-vnfsdk-7b5746d6cd-n75zz]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-26 16:00:21,012 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc10c49090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 4