Update patch set 2
Patch Set 2:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//93750-2/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 171
 * Nb Failed Pods: 44
 * List of Failed Pods: [
   - onap-aaf-aaf-sms-vault-0
   - onap-appc-appc-0
   - onap-appc-appc-dgbuilder-856dc44bf-kgtqj
   - onap-clamp-clamp-698c75fbbc-gzs8v
   - onap-clamp-clamp-dash-es-57f88bc66-h9h29
   - onap-clamp-clamp-dash-kibana-6c7555c9b8-fscr9
   - onap-clamp-clamp-dash-logstash-659894cb9d-2nt7w
   - onap-contrib-netbox-app-f44957948-zqwh2
   - onap-dcaegen2-dcae-bootstrap-dbdb58d6b-x8774
   - onap-dmaap-dmaap-dr-node-0
   - onap-dmaap-dmaap-dr-prov-764b9d7fcd-grvkh
   - onap-dmaap-message-router-kafka-1
   - onap-modeling-modeling-genericparser-7c4d976d97-xm86r
   - onap-msb-kube2msb-795f9cb588-mdfvd
   - onap-oof-oof-75b77b669f-md2g9
   - onap-oof-oof-has-api-5bc95888bc-lfmdq
   - onap-oof-oof-has-controller-6979b4788-cftd8
   - onap-oof-oof-has-data-6c64c9bcf4-z7pvl
   - onap-oof-oof-has-reservation-69798f8dbd-ldp6l
   - onap-oof-oof-has-solver-6c9bbf9947-x8snr
   - onap-pomba-pomba-kibana-74f9c6b5cd-tv4h2
   - onap-sdnc-cds-blueprints-processor-58556f7564-wmc4d
   - onap-sdnc-cds-command-executor-5b64b96dbf-rnxgp
   - onap-sdnc-cds-controller-blueprints-7f86d8f964-cr8l8
   - onap-sdnc-cds-sdc-listener-58b7f66745-9ngsc
   - onap-sdnc-sdnc-0
   - onap-sdnc-sdnc-ansible-server-5bf89fdf68-thpc4
   - onap-sdnc-sdnc-dbinit-job-jcpj2
   - onap-sdnc-sdnc-dgbuilder-94dcbdf77-klvsw
   - onap-sdnc-sdnc-dmaap-listener-64d5867d7b-j54tz
   - onap-sdnc-sdnc-portal-8685779f6d-r2g6m
   - onap-sdnc-sdnc-ueb-listener-7bd78ccbbb-fx9tc
   - onap-so-so-5df8c9f668-d5np9
   - onap-so-so-bpmn-infra-774fbccbd4-gpv64
   - onap-so-so-catalog-db-adapter-fc8d7b6bf-nw8q6
   - onap-so-so-mariadb-config-job-xzxrf
   - onap-so-so-openstack-adapter-75b6c48c8f-rlgqw
   - onap-so-so-request-db-adapter-5f7cdd67dc-wgt2s
   - onap-so-so-sdc-controller-964bb4dc9-9jwn9
   - onap-so-so-vfc-adapter-7dc6fd959b-mk5jn
   - onap-vfc-vfc-nslcm-5855784549-xx7bp
   - onap-vfc-vfc-vnflcm-d64dc6fb4-sdmws
   - onap-vfc-vfc-vnfmgr-5974b79cd9-ldb45
   - onap-vfc-vfc-vnfres-58d55545b7-p65jr]
*********** Helm Results ***********
 * Nb Helm Charts: 31
 * Nb Failed Helm Charts: 4
 * List of Failed Helm Charts: [
   - onap-dcaegen2
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-09-25 15:43:12,103 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-onboarding-be.onap', port=8445): Max retries exceeded with url: /onboarding-api/v1.0/vendor-license-models (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fae86649050>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 2
Label: Code-Review=0