Update patch set 1
Patch Set 1:

Gitlab Azure 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//128348-1/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 22
 * Nb Failed Jobs: 0
 * Nb Deployments: 127
 * Nb Failed Deployments: 5
 * List of Failed Deployments: [
   - onap-network-name-gen
   - onap-sdnc-ansible-server
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-sdnc-web]
 * Nb StatefulSets: 23
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 50
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 35
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-sdnc]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2022-04-07 18:09:22,633 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic DCAE Microservices Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94689e23d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdnc.onap', port=8443): Max retries exceeded with url: /restconf/config/GENERIC-RESOURCE-API:services/service/GRSIdummy123 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f94689aa8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
37 critical tests, 35 passed, 2 failed
37 tests total, 35 passed, 2 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests
Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
Send registration request to VES without CMPv2 certificate :: This... | PASS |
Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
--------> DCAEMOD tests
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (01:22)
--------> CDS tests NOT executed

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | FAIL |
--------> basic_vm tests
basic_vm: FAIL (00:04)
--------> basic_network tests
basic_network: FAIL (00:00)
--------> basic_cnf tests
basic_cnf: FAIL (11:37)
--------> basic_vm_macro tests
basic_vm_macro: FAIL (00:10)
--------> basic_clamp tests NOT executed
--------> pnf_macro tests
pnf_macro: FAIL (01:19)
--------> cds_resource_resolution tests
cds_resource_resolution: PASS (01:16)
--------> basic_cnf_macro tests
basic_cnf_macro: FAIL (00:01)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (00:49)
--------> jdpw_ports tests NOT executed
--------> kube_hunter tests
kube_hunter: FAIL (00:00)
--------> root_pods tests
root_pods: FAIL (02:01)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (00:49)

____________________________________________________________

Patch-set: 1