Update patch set 8
Patch Set 8:

From: Huang, Haibin <haibin.huang@intel.com> 
Sent: Monday, March 25, 2019 1:21 PM
To: Borislav Glozman <Borislav.Glozman@amdocs.com>; Yang, Bin <Bin.Yang@windriver.com>; sylvain.desbureaux@orange.com; morgan.richomme@orange.com; Michael O'Brien <Frank.Obrien@amdocs.com>; eric.debeau@orange.com
Cc: Mike Elliott <Mike.Elliott@amdocs.com>
Subject: RE: Please review Starlingx patch again

Hi Borislav,

I tested in VIM project of Integration Lab. I got PASS.

root@mc-test-rancher:~/oom/kubernetes# grep "nodePort: 85" -nr *
msb/charts/msb-consul/values.yaml:56:  nodePort: 85
multicloud/charts/multicloud-starlingx/values.yaml:64:  nodePort: 85
root@mc-test-rancher:~/oom/kubernetes# vim msb/charts/msb-consul/values.yaml 
root@mc-test-rancher:~/oom/kubernetes# vim multicloud/charts/multicloud-starlingx/values.yaml 
root@mc-test-rancher:~/oom/kubernetes# vim multicloud/charts/multicloud-starlingx/templates/service.yaml 
root@mc-test-rancher:~/oom/kubernetes# helm deploy dev-multicloud local/onap -f /root/oom/kubernetes/onap/resources/environments/public-cloud.yaml -f /root/integration-override.yaml --namespace onap  --verbose
fetching local/onap
Release "dev-multicloud" does not exist. Installing it now.
NAME:   dev-multicloud
LAST DEPLOYED: Mon Mar 25 11:12:19 2019
NAMESPACE: onap
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME                                 DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
dev-multicloud-multicloud-azure      1        1        1           0          3s
dev-multicloud-multicloud-ocata      1        1        1           0          3s
dev-multicloud-multicloud-pike       1        1        1           0          3s
dev-multicloud-multicloud-starlingx  1        1        1           0          3s
dev-multicloud-multicloud-vio        1        1        1           0          3s
dev-multicloud-multicloud-windriver  1        1        1           0          3s
dev-multicloud-multicloud            1        1        1           0          3s

==> v1/Pod(related)
NAME                                                  READY  STATUS             RESTARTS  AGE
dev-multicloud-multicloud-azure-85548b6469-g98m6      0/2    ContainerCreating  0         3s
dev-multicloud-multicloud-ocata-cfbc7dd4b-jjjnf       0/2    ContainerCreating  0         3s
dev-multicloud-multicloud-pike-57778fb4fc-mcr66       0/2    ContainerCreating  0         3s
dev-multicloud-multicloud-starlingx-7495485966-227hw  0/2    ContainerCreating  0         3s
dev-multicloud-multicloud-vio-794f8b7d85-xrcfk        0/2    ContainerCreating  0         3s
dev-multicloud-multicloud-windriver-75b7659f96-zpqml  0/2    ContainerCreating  0         2s
dev-multicloud-multicloud-7cd96f75fb-7j29m            0/2    ContainerCreating  0         2s

==> v1/ConfigMap
NAME                                                 DATA  AGE
dev-multicloud-multicloud-azure-log-configmap        1     4s
dev-multicloud-multicloud-ocata-log-configmap        1     4s
dev-multicloud-multicloud-pike-log-configmap         1     4s
dev-multicloud-multicloud-starlingx-log-configmap    1     4s
dev-multicloud-multicloud-vio-log-configmap          1     4s
dev-multicloud-multicloud-windriver-log-configmap    1     4s
multicloud-filebeat-configmap                        1     4s
dev-multicloud-multicloud-log-configmap              1     4s
dev-multicloud-multicloud-provider-plugin-configmap  1     4s

==> v1/Service
NAME                      TYPE      CLUSTER-IP     EXTERNAL-IP  PORT(S)         AGE
multicloud-azure          NodePort  10.43.135.8    <none>       9008:30261/TCP  4s
multicloud-ocata          NodePort  10.43.130.142  <none>       9006:30293/TCP  3s
multicloud-pike           NodePort  10.43.175.83   <none>       9007:30296/TCP  3s
multicloud-starlingx      NodePort  10.43.226.188  <none>       9009:30485/TCP  3s
multicloud-vio            NodePort  10.43.182.145  <none>       9004:30292/TCP  3s
multicloud-titaniumcloud  NodePort  10.43.216.80   <none>       9005:30294/TCP  3s
multicloud-framework      NodePort  10.43.91.198   <none>       9001:30291/TCP  3s


NOTES:
# Copyright © 2018 Amdocs, AT&T, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


1. Get the application URL by running these commands:
  export NODE_PORT=$(kubectl get --namespace onap -o jsonpath="{.spec.ports[0].nodePort}" services multicloud)
  export NODE_IP=$(kubectl get nodes --namespace onap -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT

root@mc-test-rancher:~/oom/kubernetes# 
root@mc-test-rancher:~/oom/kubernetes# 
root@mc-test-rancher:~/oom/kubernetes# kubectl -n onap get pod | grep star
dev-multicloud-multicloud-starlingx-7495485966-227hw          2/2       Running             0          46s
root@mc-test-rancher:~/oom/kubernetes# kubectl -n onap get pod | grep star
dev-multicloud-multicloud-starlingx-7495485966-227hw          2/2       Running             0          48s
root@mc-test-rancher:~/oom/kubernetes# /root/oom/kubernetes/robot/ete-k8s.sh onap health
++ export NAMESPACE=onap
++ NAMESPACE=onap
+++ kubectl --namespace onap get pods
+++ sed 's/ .*//'
+++ grep robot
++ POD=dev-robot-robot-56bcbffb5d-4xnk4
++ TAGS='-i health'
++ ETEHOME=/var/opt/OpenECOMP_ETE
+++ kubectl --namespace onap exec dev-robot-robot-56bcbffb5d-4xnk4 -- bash -c 'ls -1q /share/logs/ | wc -l'
++ export GLOBAL_BUILD_NUMBER=6
++ GLOBAL_BUILD_NUMBER=6
+++ printf %04d 6
++ OUTPUT_FOLDER=0006_ete_health
++ DISPLAY_NUM=96
++ VARIABLEFILES='-V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py'
++ VARIABLES='-v GLOBAL_BUILD_NUMBER:23248'
++ kubectl --namespace onap exec dev-robot-robot-56bcbffb5d-4xnk4 -- /var/opt/OpenECOMP_ETE/runTags.sh -V /share/config/vm_properties.py -V /share/config/integration_robot_properties.py -V /share/config/integration_preload_parameters.py -v GLOBAL_BUILD_NUMBER:23248 -d /share/logs/0006_ete_health -i health --display 96
Starting Xvfb on display :96 with res 1280x1024x24
Executing robot tests at log level TRACE
==============================================================================
Testsuites                                                                    
==============================================================================
Testsuites.Health-Check :: Testing ecomp components are available via calls.  
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1525d2e510>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1525d40a50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1525d37d10>: Failed to establish a new connection: [Errno 111] Connection refused',)': /internal/fetchProv
| FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1525d0cf10>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                (DMaaP:UP)| PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | PASS |
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | PASS |
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | PASS |
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | PASS |
------------------------------------------------------------------------------
Testsuites.Health-Check :: Testing ecomp components are available ... | FAIL |
52 critical tests, 51 passed, 1 failed
52 tests total, 51 passed, 1 failed
==============================================================================
Testsuites                                                            | FAIL |
52 critical tests, 51 passed, 1 failed
52 tests total, 51 passed, 1 failed
==============================================================================
Output:  /share/logs/0006_ete_health/output.xml
Log:     /share/logs/0006_ete_health/log.html
Report:  /share/logs/0006_ete_health/report.html
command terminated with exit code 1
root@mc-test-rancher:~/oom/kubernetes# 
root@mc-test-rancher:~/oom/kubernetes# git status
On branch workarounds
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

                modified:   multicloud/charts/multicloud-starlingx/templates/service.yaml
                modified:   multicloud/charts/multicloud-starlingx/values.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

                ../0001-Add-starlingx-plugin.patch

no changes added to commit (use "git add" and/or "git commit -a")
root@mc-test-rancher:~/oom/kubernetes# git diff multicloud/charts/multicloud-starlingx/templates/service.yaml
diff --git a/kubernetes/multicloud/charts/multicloud-starlingx/templates/service.yaml b/kubernetes/multicloud/charts/multicloud-starlingx/templates/service.yaml
index 04246c5..f6925d9 100644
--- a/kubernetes/multicloud/charts/multicloud-starlingx/templates/service.yaml
+++ b/kubernetes/multicloud/charts/multicloud-starlingx/templates/service.yaml
@@ -47,7 +47,7 @@ spec:
   ports:
   {{if eq .Values.service.type "NodePort" -}}
   - port: {{ .Values.service.externalPort }}
-    nodePort: {{ .Values.global.nodePortPrefixMc | default .Values.nodePortPrefixExt }}{{ .Values.service.nodePort }}
+    nodePort: {{ .Values.global.nodePortPrefixExt | default .Values.nodePortPrefixExt }}{{ .Values.service.nodePort }}
     name: {{ .Values.service.portName }}
   {{- else -}}
   - port: {{ .Values.service.externalPort }}
root@mc-test-rancher:~/oom/kubernetes# git diff multicloud/charts/multicloud-starlingx/values.yaml
diff --git a/kubernetes/multicloud/charts/multicloud-starlingx/values.yaml b/kubernetes/multicloud/charts/multicloud-starlingx/values.yaml
index 53707f5..2ca696c 100644
--- a/kubernetes/multicloud/charts/multicloud-starlingx/values.yaml
+++ b/kubernetes/multicloud/charts/multicloud-starlingx/values.yaml
@@ -16,7 +16,7 @@
# Global configuration defaults.
#################################################################
global:
-  nodePortPrefixMc: 311
+  nodePortPrefixExt: 304

 #################################################################
# Application configuration defaults.
@@ -61,7 +61,7 @@ service:
   portName: multicloud-starlingx
   externalPort: 9009
   internalPort: 9009
-  nodePort: 20
+  nodePort: 85

 ingress:
   enabled: false

Patch-set: 8