Update patch set 2
Patch Set 2: Code-Review-1

The pods come up but the SDC controller pod at least does not reply to health check

Basic SO Health Check                                                 [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a4824cb50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a480ab090>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a4809ff90>: Failed to establish a new connection: [Errno 111] Connection refused',)': /manage/health
| FAIL |
ConnectionError: HTTPConnectionPool(host='so-sdc-controller.onap', port=8085): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a48de0f50>: Failed to establish a new connection: [Errno 111] Connection refused',))

Patch-set: 2
Label: Code-Review=-1