Update patch set 65
Patch Set 65:

Gitlab Orange 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//107976-65/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 4
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
   - onap-dmaap-bc-dmaap-provisioning
   - onap-oof-has-healthcheck
   - onap-sdc-be-config-backend]
 * Nb Deployments: 147
 * Nb Failed Deployments: 53
 * List of Failed Deployments: [
   - onap-aaf-sms
   - onap-appc-dgbuilder
   - onap-cds-sdc-listener
   - onap-clamp
   - onap-clamp-backend
   - onap-clamp-dash-es
   - onap-clamp-dash-kibana
   - onap-clamp-dash-logstash
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-config-binding-service
   - onap-dcae-dashboard
   - onap-dcae-deployment-handler
   - onap-dcae-inventory-api
   - onap-dcae-policy-handler
   - onap-dcae-servicechange-handler
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-nbi
   - onap-oof
   - onap-oof-cmso-optimizer
   - onap-oof-cmso-service
   - onap-oof-cmso-ticketmgt
   - onap-oof-cmso-topology
   - onap-oof-has-api
   - onap-oof-has-controller
   - onap-oof-has-data
   - onap-oof-has-reservation
   - onap-oof-has-solver
   - onap-portal-app
   - onap-portal-sdk
   - onap-sdc-be
   - onap-sdc-fe
   - onap-sdc-onboarding-be
   - onap-sdc-wfd-be
   - onap-sdc-wfd-fe
   - onap-sdnc-dgbuilder
   - onap-sdnc-ueb-listener
   - onap-sdnc-web
   - onap-sdnrdb-coordinating-only
   - onap-so
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-etsi-nfvo-ns-lcm
   - onap-so-monitoring
   - onap-so-nssmf-adapter
   - onap-so-oof-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-sdnc-adapter
   - onap-so-vfc-adapter
   - onap-so-vnfm-adapter]
 * Nb StatefulSets: 28
 * Nb Failed StatefulSets: 1
 * List of Failed StatefulSets: [
   - onap-dmaap-dr-node]
 * Nb Persistent Volume Claims: 76
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-11-26 15:34:21,216 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9c0d8a82d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-11-26 15:34:03,721 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
15:56:00,715: Loading (INFO)
15:56:02,320: Running (INFO)
cat: ./public/107976-65/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (00:25)
hv-ves: FAIL (00:22)
5gbulkpm: FAIL (00:15)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/107976-65/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (06:09)
kube_hunter: PASS (00:04)
root_pods: FAIL (01:43)
unlimitted_pods: PASS (00:27)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 65
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>