Update patch set 4
Patch Set 4:

@Fiachra, I was starting to say that what was puzzling me is dmaap-bc is OK __BUT__ when you look at logs (https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//101419-4/infrastructure-healthcheck/k8s/pod-onap-dmaap-bc-6bfbf489fb-24xs9-dmaap-bc-dbc-aaf-config-logs.html), you see an issue __BEFORE__ trying to retrieve the creds...
So your thought may be good.
Fyi, I tried to understand how aaf init containers works and it seems that aaf-service is also needed...


I tried to capture the logs of these services:

2020-02-20 11:05:54,331 WARN [init] 2020-02-20T11:05:54.331+0000 INIT [init] Starting Jetty Service for org.osaaf.aaf.locate, version 2.1, on https://onap-aaf-locate-5cf45bc57d-h5l7w:8095 
2020-02-20 11:05:56,928 WARN [init] 2020-02-20T11:05:56.928+0000 INIT [init] Starting Jetty Service for org.osaaf.aaf.cm, version 2.1, on https://onap-aaf-cm-5dc6f6bd85-lmwbp:8150 
2020-02-20 11:05:57,663 WARN [init] 2020-02-20T11:05:57.663+0000 INIT [init] Starting Jetty Service for org.osaaf.aaf.service, version 2.1, on https://onap-aaf-service-cfb5ff7d8-zhnl9:8100 
2020-02-20T11:06:59.692+0000 INIT [cadi] jdk.tls.client.protocols set from Default Protocols
2020-02-20T11:07:03.461+0000: Trans Info
         Read Artifact 3285.6936ms
 
org.onap.aaf.cadi.CadiException: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:135)
	at org.onap.aaf.cadi.aaf.v2_0.AAFCon.client(AAFCon.java:223)
	at org.onap.aaf.cadi.configure.Agent.readArtifact(Agent.java:542)
	at org.onap.aaf.cadi.configure.Agent.main(Agent.java:313)
Caused by: org.onap.aaf.cadi.LocatorException: No Entries found for 'https://aaf-locate.onap:8095/locate/onap.org.osaaf.aaf.cm:2.1'
	at org.onap.aaf.cadi.aaf.v2_0.AbsAAFLocator.best(AbsAAFLocator.java:240)
	at org.onap.aaf.cadi.aaf.v2_0.AAFConHttp.rclient(AAFConHttp.java:133)
	... 3 more
#### Certificate Authorization Artifact must be valid to continue

We see that DR is asking for certificates 2 min after all of them are up (again I hoped to find  something...)

I checked other AAF pods and they were up even before...

Patch-set: 4
Label: Code-Review=0