Update patch set 2
Patch Set 2:

error message: 
27-Apr-2018 16:50:25.205 SEVERE [http-nio-8702-exec-6] org.postgresql.Driver.connect Connection error:
 org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:275)
........
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: vnfsdk-postgres.onap

Seems POSTGRES_IP is not recognized.

Patch-set: 2
Label: Code-Review=0