Update patch set 1
Patch Set 1: Code-Review+2

just have a question before merge.
I see in logs:
2020-10-21T11:32:36.553Z||main|||||ERROR|500||Error reading truststore, TLS connection will fail.
java.io.FileNotFoundException: ServletContext resource [/opt/app/osaaf/local/org.onap.so.trust.jks] cannot be resolved to URL because it does not exist

and /opt/app/osaaf/local/org.onap.so.trust.jks is the place where the truststore is supposed to be (at least that's what we see in cert initializer logs)

any reason for that?

Patch-set: 1
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2