Update patch set 1
Patch Set 1:

Gitlab Orange 1: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results//97170-1/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 213
 * Nb Failed Pods: 39
 * List of Failed Pods: [
   - onap-aaf-aaf-cm-788f96b74b-vhnnw
   - onap-aaf-aaf-gui-55cb4b6ff-dsklp
   - onap-aaf-aaf-sms-74975b77f-fqjzm
   - onap-aai-aai-schema-service-55f75dd75c-7mzh4
   - onap-cds-cds-blueprints-processor-944878fb6-mq7vg
   - onap-cds-cds-command-executor-74dffcb87d-bgq7p
   - onap-cds-cds-sdc-listener-75c5fd5ffb-rk4n5
   - onap-dcaegen2-dcae-policy-handler-5c7bc7b7dd-xv9fz
   - onap-dcaegen2-dcae-servicechange-handler-579b47bcb6-dcf8h
   - onap-dmaap-message-router-0
   - onap-dmaap-message-router-kafka-2
   - onap-dmaap-message-router-mirrormaker-5bd5cbc745-kh6dl
   - onap-modeling-modeling-etsicatalog-6cd7ccc7d7-hvhsf
   - onap-msb-msb-discovery-7b85c6cbbb-vw4x6
   - onap-multicloud-multicloud-azure-59fcb9c779-9m7zj
   - onap-multicloud-multicloud-k8s-65dc448b85-jqmvq
   - onap-oof-oof-d8f7dbfbf-cw7m4
   - onap-oof-oof-has-api-7b7f4c95b9-gpbqg
   - onap-oof-oof-has-controller-7db5bf5f8b-gsx78
   - onap-oof-oof-has-data-8dc9c79dd-njhhn
   - onap-oof-oof-has-reservation-589cc655f4-4mhmc
   - onap-oof-oof-has-solver-55d9849c69-4qd5c
   - onap-pomba-pomba-contextaggregator-6d9f9bb987-twdq7
   - onap-pomba-pomba-networkdiscoveryctxbuilder-5844bcc8-hnfdx
   - onap-pomba-pomba-sdcctxbuilder-d44c85675-n7skg
   - onap-portal-portal-widget-84b4f7f448-brhht
   - onap-sdc-sdc-be-8485bc5558-bd5f5
   - onap-sdc-sdc-be-config-backend-t2qt4
   - onap-sdc-sdc-dcae-be-85c669ddbf-z4wqr
   - onap-sdc-sdc-dcae-dt-7c9ff4774d-plbdf
   - onap-sdc-sdc-dcae-fe-5488b88f8c-fb9zb
   - onap-sdc-sdc-dcae-tosca-lab-75cd495799-6gr2c
   - onap-sdc-sdc-fe-5cfcddf448-vd66b
   - onap-sdc-sdc-kb-5b48c6fd44-v5k2l
   - onap-sdc-sdc-onboarding-be-8c84cb794-8czk2
   - onap-sdc-sdc-wfd-be-54ff7b9948-d9c7x
   - onap-sdc-sdc-wfd-fe-647d64468f-zjxcx
   - onap-sdnc-sdnc-dmaap-listener-7957f5f764-tvcng
   - onap-sdnc-sdnc-ueb-listener-5d78c9c586-ll7xc]
*********** Helm Results ***********
 * Nb Helm Charts: 32
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-sdnc
   - onap-so]
******** Healthcheck Results *******
******** healthdist Results *******
2019-10-16 10:41:04,767 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f620fdd0090>: Failed to establish a new connection: [Errno -3] Try again',))

Also keyword teardown failed:
Variable '${catalog_service_id}' not found.
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
____________________________________

Patch-set: 1
Label: Verified=0