Update patch set 10
Patch Set 10:

> Patch Set 10:
> 
> https://gating-results.onap.eu/results/106586-10/
> 
> (gitlab is down but I've been able to retrieve the results)

you're "lucky"
as gitlab is down, I was able to retrieve installation logs:

Release "onap-dmaap" does not exist. Installing it now.
Error: YAML parse error on dmaap/charts/dmaap-bc/templates/deployment.yaml: error converting YAML to JSON: yaml: line 140: did not find expected key

Patch-set: 10
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>