Update patch set 9
Patch Set 9:

Gitlab Orange 3: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//117837-9/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 29
 * Nb Failed Jobs: 2
 * List of Failed Jobs: [
   - integration-onap-internal-check-certs
   - onap-dmaap-bc-dmaap-provisioning]
 * Nb Deployments: 150
 * Nb Failed Deployments: 5
 * List of Failed Deployments: [
   - onap-a1policymanagement
   - onap-dmaap-bc
   - onap-policy-pap
   - onap-so-oof-adapter
   - onap-so-openstack-adapter]
 * Nb StatefulSets: 27
 * Nb Failed StatefulSets: 1
 * List of Failed StatefulSets: [
   - onap-music-cassandra]
 * Nb Persistent Volume Claims: 74
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 0

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot full healthcheck tests
2021-02-19 19:24:31,003 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | FAIL |
ConnectionError: HTTPSConnectionPool(host='dmaap-bc.onap', port=8443): Max retries exceeded with url: /webapi/dmaap (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe732844f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
Test timeout 20 seconds exceeded.
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | FAIL |
ConnectionError: HTTPSConnectionPool(host='policy-pap.onap', port=6969): Max retries exceeded with url: /policy/pap/v1/components/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe7327be7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | FAIL |
ConnectionError: HTTPSConnectionPool(host='policy-pap.onap', port=6969): Max retries exceeded with url: /policy/pap/v1/pdps/policies (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe7327d10d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-openstack-adapter.onap', port=8087): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe732842610>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 38 passed, 5 failed
43 tests total, 38 passed, 5 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml

************************************************************
************************************************************
********************* Basic tests Results ******************
************************************************************
************************************************************
--------> healthdist (vFW onboarding and distribution)
Health-Check :: Test that ONAP components are available via basic ... | PASS |
--------> postinstall tests (dmaap and A&AI)
Post-Install-Tests :: Testing Installation                            | PASS |
--------> CMPv2 tests
Deploying PNF Simulator :: This test case deploys PNF simulator wi... | PASS |
Deploying VES collector with CMPv2 :: This test case deploys secon... | PASS |
Deploying VES collector with CMPv2 and wrong SANs :: This test cas... | PASS |
Send registration request to CMPv2 VES :: This test case triggers ... | PASS |
Send registration request to CMPv2 VES with wrong SAN-s :: This te... | PASS |
Send registration request to VES without CMPv2 certificate :: This... | PASS |
Cmpv2 :: CMPv2 Usecase functionality                                  | PASS |
--------> HV-VES tests
Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
--------> VES collector tests
Ves :: Suite for checking handling events by VES Collector            | PASS |
--------> Basic Onboard tests (SDC)
basic_onboard: PASS (02:23)
--------> CDS tests
basic_cds: PASS (00:20)

************************************************************
************************************************************
******************** End to End usecases *******************
************************************************************
************************************************************
--------> pnf-registrate tests
PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
--------> 5gbulkpm tests
Setting Global Variables :: This test case checks suite if it is w... | PASS |
5Gbulkpm :: 5G Bulk PM Usecase functionality                          | FAIL |
--------> basic_vm tests NOT executed
--------> basic_network tests NOT executed
--------> basic_cnf tests NOT executed

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
--------> cis_kubernetes tests
cis_kubernetes: PASS (00:00)
--------> nonssl_endpoints tests
nonssl_endpoints: FAIL (01:13)
--------> jdpw_ports tests
jdpw_ports: PASS (07:51)
--------> kube_hunter tests
kube_hunter: PASS (00:06)
--------> root_pods tests
root_pods: FAIL (02:43)
--------> unlimitted_pods tests
unlimitted_pods: FAIL (00:48)

____________________________________________________________

Patch-set: 9