Update patch set 27
Patch Set 27:

It's not coming up for me

2018-10-26 16:45:20,607||139849261848320|DEBUG|connectionpool|urllib3.connectionpool: [-] Starting new HTTPS connection (1): aaf-sms:10443
2018-10-26 16:45:20,625||139849261848320|ERROR|connection|urllib3.connection: [-] Certificate did not match expected hostname: aaf-sms. Certificate: {'subjectAltName': [('DNS', 'aaf-sms.api.simpledemo.onap.org'), ('DNS', 'aaf-sms.simpledemo.onap.org'), ('DNS', 'aaf-sms-db.onap'), ('DNS', 'aaf-sms.onap')], 'subject': ((('commonName', u'aaf-sms'),),)}
2018-10-26 16:45:20,627||139849261848320|CRITICAL|log|conductor: [-] Unhandled error
Traceback (most recent call last):
  File "/usr/local/bin/conductor-controller", line 10, in <module>
    sys.exit(main())
  File "/opt/has/conductor/conductor/cmd/controller.py", line 25, in main
    conf = service.prepare_service()
  File "/opt/has/conductor/conductor/service.py", line 113, in prepare_service
    sms.load_secrets()
  File "/opt/has/conductor/conductor/common/sms.py", line 104, in load_secrets
    secret_dict = retrieve_secrets()
  File "/opt/has/conductor/conductor/common/sms.py", line 94, in retrieve_secrets
    secrets = sms_client.getSecretNames(domain)
  File "/usr/local/lib/python2.7/site-packages/onapsmsclient/__init__.py", line 192, in getSecretNames
    response = self._request('get', url)
  File "/usr/local/lib/python2.7/site-packages/onapsmsclient/__init__.py", line 120, in _request
    timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='aaf-sms', port=10443): Max retries exceeded with url: /v1/sms/domain/has/secret (Caused by SSLError(CertificateError("hostname 'aaf-sms' doesn't match either of 'aaf-sms.api.simpledemo.onap.org', 'aaf-sms.simpledemo.onap.org', 'aaf-sms-db.onap', 'aaf-sms.onap'",),))

Patch-set: 27