Update patch set 5
Patch Set 5: Code-Review-1

There’s an issue with dmaap template:
Release "onap-dmaap" does not exist. Installing it now.
Error: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.VolumeMounts: []v1.VolumeMount: Resources: v1.ResourceRequirements.Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', error found in #10 byte of ...|container"}},"volume|..., bigger context ...|:"500m","memory":"1Gi# Filebeat sidecar container"}},"volumeMounts":[{"mountPath":"/opt/app/osaaf","|...

Patch-set: 5
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1