Update patch set 4
Patch Set 4: Code-Review+2 Verified+1

Fix for log health check got 1/3 passing. Another patch will be raised to fix logging.

------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       [ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /
[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /
[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /
| FAIL |
ConnectionError: HTTPConnectionPool(host='log-ls.onap', port=5044): Max retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         
| FAIL |
Test timeout 1 minute exceeded.
------------------------------------------------------------------------------

Patch-set: 4
Reviewer: Gerrit User 127 <127@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=+2
Label: Verified=+1