Update patch set 3
Patch Set 3: Verified-1

+ for subchart in '*'
+ VAR=computed_multicloud_enabled
+ COMMAND='$computed_multicloud_enabled'
+ eval 'SUBCHART_ENABLED=$computed_multicloud_enabled'
++ SUBCHART_ENABLED=true
+ [[ true == \t\r\u\e ]]
+ SUBCHART_OVERRIDES=/root/.helm/plugins/deploy/cache/onap-subcharts/multicloud/subchart-overrides.yaml
+ helm upgrade -i aaa-multicloud /root/.helm/plugins/deploy/cache/onap-subcharts/multicloud --namespace onap -f /root/global-values.yaml --set global.pullPolicy=IfNotPresent,pomba.enabled=false -f /root/.helm/plugins/deploy/cache/onap/global-overrides.yaml -f /root/.helm/plugins/deploy/cache/onap-subcharts/multicloud/subchart-overrides.yaml
Release "aaa-multicloud" does not exist. Installing it now.
Error: release aaa-multicloud failed: Service "multicloud-azure" is invalid: spec.ports[0].name: Invalid value: "http-": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')

Patch-set: 3
Label: Verified=-1