Update patch set 41
Patch Set 41:

> Patch Set 41:
> 
> Gitlab Orange 4: 
> Full results can be seen here: https://logs.onap.org/onap-integration/gating//118284-41/index.html
> ______________ Results ______________________
> 
> ************************************************************
> ************************************************************
> ************ Infrastructure-healthcheck Results ************
> ************************************************************
> ************************************************************
> --------> onap-k8s
>  * Nb Jobs: 28
>  * Nb Failed Jobs: 1
>  * List of Failed Jobs: [
>    - onap-netbox-app-provisioning]
>  * Nb Deployments: 153
>  * Nb Failed Deployments: 1
>  * List of Failed Deployments: [
>    - onap-netbox-app]
>  * Nb StatefulSets: 27
>  * Nb Failed StatefulSets: 0
>  * Nb Persistent Volume Claims: 77
>  * Nb Failed Persistent Volume Claims: 0
> --------> onap-helm
>  * Nb Helms: 36
>  * Nb Failed Helms: 0
> 
> ************************************************************
> ************************************************************
> ********************* Healthcheck Results ******************
> ************************************************************
> ************************************************************
> --------> robot full healthcheck tests
> 2021-03-31 13:20:45,567 - xtesting.core.robotframework - INFO - 
> ==============================================================================
> Health-Check :: Test that ONAP components are available via basic API calls   
> ==============================================================================
> Basic A&AI Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced A&AI Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic AAF Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic AAF SMS Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic APPC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic CLI Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic CLAMP Health Check                                              | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Basic DCAE Microservices Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Data Router Health Check                                  | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Message Router Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
> ------------------------------------------------------------------------------
> Basic External API NBI Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Microservice Bus Health Check                                   | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-pike API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-starlingx API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-titanium_cloud API Health Check                      | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-vio API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-k8s API Health Check                                 | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-Homing Health Check                                         | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-OSDF Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic OOF-CMSO Health Check                                           | PASS |
> ------------------------------------------------------------------------------
> Basic Policy Health Check                                             | FAIL |
> Test timeout 20 seconds exceeded.
> ------------------------------------------------------------------------------
> Enhanced Policy New Healthcheck                                       | FAIL |
> ConnectionError: HTTPSConnectionPool(host='policy-api.onap', port=6969): Max retries exceeded with url: /policy/api/v1/policytypes/onap.policies.controlloop.operational.common.Drools/versions/1.0.0/policies (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2436413550>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ------------------------------------------------------------------------------
> Basic Portal Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDC Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDC Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic SDNC Health Check                                               | PASS |
> ------------------------------------------------------------------------------
> Enhanced SDNC Health Check                                            | PASS |
> ------------------------------------------------------------------------------
> Basic SO Health Check                                                 | PASS |
> ------------------------------------------------------------------------------
> Basic UseCaseUI API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC gvnfmdriver API Health Check                                | PASS |
> ------------------------------------------------------------------------------
> Basic VFC huaweivnfmdriver API Health Check                           | PASS |
> ------------------------------------------------------------------------------
> Basic VFC nslcm API Health Check                                      | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnflcm API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfmgr API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC vnfres API Health Check                                     | PASS |
> ------------------------------------------------------------------------------
> Basic VFC ztevnfmdriver API Health Check                              | PASS |
> ------------------------------------------------------------------------------
> Basic VID Health Check                                                | PASS |
> ------------------------------------------------------------------------------
> Basic VNFSDK Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Basic Multicloud-fcaps API Health Check                               | PASS |
> ------------------------------------------------------------------------------
> Basic Modeling genericparser API Health Check                         | PASS |
> ------------------------------------------------------------------------------
> Enhanced CDS Health Check                                             | PASS |
> ------------------------------------------------------------------------------
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> 44 critical tests, 42 passed, 2 failed
> 44 tests total, 42 passed, 2 failed
> ==============================================================================
> Output:  /var/lib/xtesting/results/full/output.xml
> 
> ************************************************************
> ************************************************************
> ********************* Basic tests Results ******************
> ************************************************************
> ************************************************************
> --------> healthdist (vFW onboarding and distribution)
> Health-Check :: Test that ONAP components are available via basic ... | FAIL |
> --------> postinstall tests (dmaap and A&AI)
> Post-Install-Tests :: Testing Installation                            | PASS |
> --------> CMPv2 tests NOT executed
> --------> DCAEMOD tests
> Deploy DCAE Simple Application Without Config Map In Config Spec J... | PASS |
> Deploy DCAE Simple Application With Config Map In Config Spec Json... | PASS |
> Deploy DCAE Simple Application With Config Map In Config Spec Json... | PASS |
> Dcaemod                                                               | PASS |
> --------> HV-VES tests
> Hvves-Ci :: HV-VES 'Sunny Scenario' Robot Framework test - message... | PASS |
> --------> VES collector tests
> Ves :: Suite for checking handling events by VES Collector            | PASS |
> --------> Basic Onboard tests (SDC)
> basic_onboard: PASS (03:57)
> --------> CDS tests
> basic_cds: PASS (00:21)
> 
> ************************************************************
> ************************************************************
> ******************** End to End usecases *******************
> ************************************************************
> ************************************************************
> --------> pnf-registrate tests
> PNF Registration only DCAE part: AAI, VES, PRH, DMaaP :: This test... | PASS |
> Pnf-Registration :: Executes the PNF registration test cases inclu... | FAIL |
> --------> 5gbulkpm tests
> Setting Global Variables :: This test case checks suite if it is w... | PASS |
> 5Gbulkpm :: 5G Bulk PM Usecase functionality                          | PASS |
> --------> basic_vm tests
> basic_vm: PASS (11:38)
> --------> basic_network tests
> basic_network: PASS (17:51)
> --------> basic_cnf tests
> basic_cnf: PASS (09:31)
> 
> ************************************************************
> ************************************************************
> ********************** Security tests **********************
> ************************************************************
> ************************************************************
> --------> cis_kubernetes tests
> cis_kubernetes: PASS (00:00)
> --------> nonssl_endpoints tests
> nonssl_endpoints: FAIL (01:15)
> --------> jdpw_ports tests
> jdpw_ports: PASS (08:05)
> --------> kube_hunter tests
> kube_hunter: PASS (00:06)
> --------> root_pods tests
> root_pods: FAIL (02:47)
> --------> unlimitted_pods tests
> unlimitted_pods: FAIL (01:11)
> 
> ____________________________________________________________

In this run (Gitlab Orange 4), basic_vm and basic_network pass.  I don't believe SDNC is involved in the cmpv2 test that failed (cmpv2) -so we passed?

Patch-set: 41