Update patch set 2
Patch Set 2:

Gitlab Orange 1: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//117314-2/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 0
 * Nb Deployments: 146
 * Nb Failed Deployments: 2
 * List of Failed Deployments: [
   - onap-portal-cassandra
   - onap-so-vfc-adapter]
 * Nb StatefulSets: 25
 * Nb Failed StatefulSets: 0
 * Nb Persistent Volume Claims: 74
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 34
 * Nb Failed Helms: 4
 * List of Failed Helms: [
   - onap-multicloud
   - onap-aai
   - onap-so
   - onap-oof]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
2021-02-02 19:34:17,605 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced A&AI Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-OSDF Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | PASS |
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Enhanced Policy New Healthcheck                                       | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Enhanced SDC Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Enhanced SDNC Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='so-vfc-adapter.onap', port=8084): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd783dbb950>: Failed to establish a new connection: [Errno 111] Connection refused'))
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | PASS |
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | PASS |
------------------------------------------------------------------------------
Enhanced CDS Health Check                                             | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
43 critical tests, 35 passed, 8 failed
43 tests total, 35 passed, 8 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
--------> healthdist (vFW onboarding and distribution)
2021-02-02 19:37:34,945 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2021-02-02 19:31:35,644 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | PASS |
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
basic_vm: PASS (08:49)
basic_network: PASS (06:52)
pnf-registrate: FAIL (01:08)
hv-ves: PASS (00:37)
5gbulkpm: PASS (06:12)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/117314-2/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (07:38)
kube_hunter: PASS (00:06)
root_pods: FAIL (02:33)
unlimitted_pods: FAIL (01:00)

--------> FOCUS on CIS errors
cat: ./public/117314-2/security/cis_kubernetes/cis_kubernetes.log: No such file or directory

____________________________________________________________

Patch-set: 2