Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1: Code-Review-1
> > 
> > on which port are you listening?
> > How do you retrieve your certificates?
> 
> CLI expose port 32060 and on https. Currently Certificate is static one and it helps to enable the HTTPS. And I will migrate to proper certification in G release. Thank you

CLI healthcheck test failed in gating 
Basic CLI Health Check                                                | FAIL |
ConnectionError: HTTPSConnectionPool(host='cli.onap', port=8443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc328197f50>: Failed to establish a new connection: [Errno 111] Connection refused'))

and as it has been reintroduced in Master it is failing in daily master now
https://gating-results.onap.eu/results/onap_daily_pod4_master-493629129-04-01-2020_06-04/healthcheck/full/full/report.html#totals?all

In daily master I may expect that it is due to the fact that this patch is not merged..
but we can see that it is also failing in the test executing during this gating..

Are you sure that CLI is listening on https on 8443 within the cluster?

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>