Update patch set 2
Patch Set 2: Code-Review+1

OOM gating chain triggered but not really relevant regarding the nature of the patch..

the patchset triggered the deployment of a OOM solution (versions based on OOM helm chart + patchset) + some tests
all results are temporarily stored at https://gitlab.com/Orange-OpenSource/lfn/onap/xtesting-onap/-/jobs/168983086.

9 pods not in Running status
onap-appc-appc-ansible-server-598558f644-6m68z                 0/1       CrashLoopBackOff   14         1h
onap-dcaegen2-dcae-bootstrap-595d9f9594-sqc7m                  0/1       Init:0/1           4          1h
onap-dcaegen2-dcae-cloudify-manager-6dfd7f945f-ddj9j           0/1       ImagePullBackOff   0          1h
onap-dcaegen2-dcae-healthcheck-6ffbc5fdc9-vdnwz                0/1       ImagePullBackOff   0          1h
onap-dcaegen2-dcae-redis-3                                     0/1       Pending            0          1h
onap-dmaap-dmaap-bus-controller-577d694c69-m5fg6               0/1       ImagePullBackOff   0          1h
onap-dmaap-dmaap-dr-node-5c498cd687-427gs                      0/1       Init:0/1           6          1h
onap-dmaap-dmaap-dr-prov-8957666c6-c94rt                       0/1       Init:0/1           7          1h
onap-sdnc-controller-blueprints-6547954976-nwjrc               0/1       CrashLoopBackOff   15         1h

All helm charts in DEPlOYED status

Healthchecks
Basic APPC Health Check                       | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
----------------------------------------------------------------------
Basic DMAAP Data Router Health Check    | FAIL |
ConnectionError: HTTPConnectionPool(host='dmaap-dr-node.onap', port=8080): Max retries exceeded with url: /internal/fetchProv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7614c5850>: Failed to establish a new connection: [Errno 111] Connection refused',))
----------------------------------------------------------------------
Basic Holmes Rule Management API Health Check       | FAIL |
502 != 200
----------------------------------------------------------------------
Basic Holmes Engine Management API Health Check     | FAIL |
502 != 200

E2E tests not triggered

Patch-set: 2