Update patch set 9
Patch Set 9:

@Sylvain I'm wondering how that can be related with VID, Like SO (health-so) issue:
ConnectionError: HTTPConnectionPool(host='so-sdc-controller.onap', port=8085): Max retries exceeded with url: /manage/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b78398390>: Failed to establish a new connection: [Errno 111] Connection refused'))

Patch-set: 9