Update patch set 11
Patch Set 11:

Hi, looking at previous builds we got:
 Release "onap-platform" does not exist. Installing it now.
 Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CMPv2Issuer.spec): unknown field "updateEndpoint" in org.onap.certmanager.v1.CMPv2Issuer.spec

I think that the CMPv2Issuer CRD is not deleted after previous gating run. Shouldn't that be fixed? Or should we find another way to upgrade the CRD? (any hints if so?)

Patch-set: 11
Reviewer: Gerrit User 6044 <6044@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>