Update patch set 8
Patch Set 8:

Gitlab.com 3: 
Full results can be seen here: https://orange-opensource.gitlab.io/lfn/onap/xtesting-onap-view/results/94953-8/index.html
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 212
 * Nb Failed Pods: 2
 * List of Failed Pods: [
   - onap-dcaegen2-dcae-bootstrap-dbdb58d6b-cpzjm
   - onap-vfc-vfc-ems-driver-845b6dbc96-8ls7t]
*********** Helm Results ***********
 * Nb Helm Charts: 31
 * Nb Failed Helm Charts: 2
 * List of Failed Helm Charts: [
   - onap-dcaegen2
   - onap-msb]
******** Healthcheck Results *******
2019-09-09 13:56:08,932 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Basic A&AI Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
ConnectionError: HTTPSConnectionPool(host='appc.onap', port=8443): Max retries exceeded with url: /restconf/operations/SLI-API:healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb3df2446d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
ConnectionError: HTTPConnectionPool(host='dcae-healthcheck.onap', port=80): Max retries exceeded with url: /healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df271c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic DMAAP Bus Controller Health Check With Basic Auth               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /iui/microservices/default.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df1b6f10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df176710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-pike/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df103790>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-starlingx/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df271d10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-titaniumcloud/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df10f450>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-vio/v0/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df11a4d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-k8s API Health Check                                 | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-k8s/v1/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df15ffd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | PASS |
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
403 != 200
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /iui/usecaseui/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df0a7510>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/catalog/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df0e1d90>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/emsdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df0b1f10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/gvnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df2a3c10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/huaweivnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df0bd3d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/jujuvnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3df2a3b50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multivimproxy/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defbf690>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/NokiaSVNFM/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defdc710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/nslcm/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defbf690>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/resmgr/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defe7490>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/vnflcm/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3deff3590>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/vnfmgr/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defe7710>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/vnfres/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def7e410>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/workflow/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def8b290>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/ztesdncdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defdc150>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/ztevnfmdriver/v1/swagger.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def8bfd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/holmes-rule-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def9cd10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/holmes-engine-mgmt/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3defb2d50>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Multicloud-fcaps API Health Check                               | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/multicloud-fcaps/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def43bd0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Modeling genericparser API Health Check                         | FAIL |
ConnectionError: HTTPConnectionPool(host='msb-iag.onap', port=80): Max retries exceeded with url: /api/parser/v1/health_check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb3def97810>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic CDS Health Check                                                | PASS |
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
61 critical tests, 31 passed, 30 failed
61 tests total, 31 passed, 30 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 8
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=0