Update patch set 6
Patch Set 6:

Gitlab Orange 2: 
Full results can be seen here: https://logs.onap.org/onap-integration/gating//113477-6/index.html
______________ Results ______________________

************************************************************
************************************************************
************ Infrastructure-healthcheck Results ************
************************************************************
************************************************************
--------> onap-k8s
 * Nb Jobs: 27
 * Nb Failed Jobs: 6
 * List of Failed Jobs: [
   - onap-aaf-sms-preload
   - onap-aai-traversal-update-query-data
   - onap-dmaap-bc-dmaap-provisioning
   - onap-oof-has-healthcheck
   - onap-sdc-be-config-backend
   - onap-sdnc-sdnrdb-init-job]
 * Nb Deployments: 148
 * Nb Failed Deployments: 65
 * List of Failed Deployments: [
   - onap-aaf-cm
   - onap-aaf-fs
   - onap-aaf-gui
   - onap-aaf-locate
   - onap-aaf-oauth
   - onap-aaf-service
   - onap-aaf-sms
   - onap-appc-dgbuilder
   - onap-cds-sdc-listener
   - onap-clamp
   - onap-clamp-backend
   - onap-clamp-dash-es
   - onap-clamp-dash-kibana
   - onap-clamp-dash-logstash
   - onap-dcae-bootstrap
   - onap-dcae-cloudify-manager
   - onap-dcae-config-binding-service
   - onap-dcae-dashboard
   - onap-dcae-deployment-handler
   - onap-dcae-inventory-api
   - onap-dcae-policy-handler
   - onap-dcae-servicechange-handler
   - onap-dmaap-bc
   - onap-dmaap-dr-prov
   - onap-nbi
   - onap-oof
   - onap-oof-cmso-optimizer
   - onap-oof-cmso-service
   - onap-oof-cmso-ticketmgt
   - onap-oof-cmso-topology
   - onap-oof-has-api
   - onap-oof-has-controller
   - onap-oof-has-data
   - onap-oof-has-reservation
   - onap-oof-has-solver
   - onap-policy-api
   - onap-policy-distribution
   - onap-policy-pap
   - onap-policy-xacml-pdp
   - onap-portal-app
   - onap-portal-sdk
   - onap-sdc-be
   - onap-sdc-fe
   - onap-sdc-onboarding-be
   - onap-sdc-wfd-be
   - onap-sdc-wfd-fe
   - onap-sdnc-ansible-server
   - onap-sdnc-dgbuilder
   - onap-sdnc-dmaap-listener
   - onap-sdnc-ueb-listener
   - onap-sdnrdb-coordinating-only
   - onap-so
   - onap-so-appc-orchestrator
   - onap-so-bpmn-infra
   - onap-so-catalog-db-adapter
   - onap-so-etsi-nfvo-ns-lcm
   - onap-so-nssmf-adapter
   - onap-so-oof-adapter
   - onap-so-openstack-adapter
   - onap-so-request-db-adapter
   - onap-so-sdc-controller
   - onap-so-sdnc-adapter
   - onap-so-ve-vnfm-adapter
   - onap-so-vfc-adapter
   - onap-so-vnfm-adapter]
 * Nb StatefulSets: 29
 * Nb Failed StatefulSets: 5
 * List of Failed StatefulSets: [
   - onap-dmaap-dr-node
   - onap-policy-apex-pdp
   - onap-policy-drools-pdp
   - onap-sdnc
   - onap-sdnrdb-master]
 * Nb Persistent Volume Claims: 78
 * Nb Failed Persistent Volume Claims: 0
--------> onap-helm
 * Nb Helms: 33
 * Nb Failed Helms: 1
 * List of Failed Helms: [
   - onap-so]

************************************************************
************************************************************
********************* Healthcheck Results ******************
************************************************************
************************************************************
--------> robot  full healthcheck tests
--------> healthdist (vFW onboarding and distribution)
2020-10-28 16:18:10,625 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Test that ONAP components are available via basic API calls   
==============================================================================
Health Distribution Test                                              | FAIL |
Keyword teardown failed:
Several failures occurred:

1) Value of variable '@{catalog_resource_ids}' is not list or list-like.

2) ConnectionError: HTTPSConnectionPool(host='sdc-be.onap', port=8443): Max retries exceeded with url: /sdc2/rest/v1/catalog/services/None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6deb24d250>: Failed to establish a new connection: [Errno 111] Connection refused'))

3) Resolving variable '${resp.status_code}' failed: AttributeError: 'NoneType' object has no attribute 'status_code'

4) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'

5) Replacing variables from keyword return value failed: Resolving variable '${resp.json()}' failed: AttributeError: 'NoneType' object has no attribute 'json'
------------------------------------------------------------------------------
Health-Check :: Test that ONAP components are available via basic ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/healthdist/output.xml
--------> postinstall tests (dmaap and A&AI)
2020-10-28 16:18:05,611 - xtesting.core.robotframework - INFO - 
==============================================================================
Post-Install-Tests :: Testing Installation                                    
==============================================================================
Basic DMAAP Message Router ACL Update Test                            | PASS |
------------------------------------------------------------------------------
Basic AAI Service Design Models Size Test                             | FAIL |
404 != 200
------------------------------------------------------------------------------
Post-Install-Tests :: Testing Installation                            | FAIL |
2 critical tests, 1 passed, 1 failed
2 tests total, 1 passed, 1 failed
==============================================================================
Output:  /var/lib/xtesting/results/postinstall/output.xml


************************************************************
************************************************************
********************** Smoke usecases **********************
************************************************************
************************************************************
--------> End to End tests (onap-tests)
16:22:09,539: Loading (INFO)
16:22:10,192: Running (INFO)
16:21:50,213: Loading (INFO)
16:21:51,489: /usr/lib/python3.8/site-packages/onaptests/configuration/basic_network_nomulticloud_settings.py:28: (WARNING)
16:21:52,087: Running (INFO)
cat: ./public/113477-6/smoke-usecases/basic_cnf/xtesting.log: No such file or directory
pnf-registrate: FAIL (00:25)
5gbulkpm: FAIL (00:15)

************************************************************
************************************************************
********************** Security tests **********************
************************************************************
************************************************************
cis_kubernetes: PASS (00:00)
cat: ./public/113477-6/security/http_public_endpoints/xtesting.log: No such file or directory
jdpw_ports: PASS (06:55)
kube_hunter: PASS (00:13)
root_pods: PASS (01:44)
unlimitted_pods: FAIL (00:46)

--------> FOCUS on CIS errors

____________________________________________________________

Patch-set: 6