Update patch set 1
Patch Set 1:

Gitlab Orange: 
______________ Results _____________
******** Kubernetes Results ********
 * Nb Pods: 226
 * Nb Failed Pods: 54
 * List of Failed Pods: [
   - onap-aai-aai-58bf84ccd8-8j5qf
   - onap-aai-aai-champ-7f97f98976-fcszg
   - onap-aai-aai-graphadmin-c79fb7fcf-x87qs
   - onap-aai-aai-graphadmin-create-db-schema-k8ssm
   - onap-aai-aai-modelloader-7ccf55c6bf-sjx9n
   - onap-aai-aai-resources-557c6f9d78-267qh
   - onap-aai-aai-sparky-be-5ff8689c54-vm4z5
   - onap-aai-aai-spike-77ccc5bf78-q6v7r
   - onap-aai-aai-traversal-7fb5558d98-b22r6
   - onap-aai-aai-traversal-7fb5558d98-rccvm
   - onap-aai-aai-traversal-update-query-data-7txd4
   - onap-contrib-netbox-app-695fd89fd-txt4b
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-k9xns
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-2h7g5
   - onap-dcaegen2-dcae-deployment-handler-5dcd748c6-bj5j6
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-wwdh4
   - onap-dcaegen2-dcae-policy-handler-85c5b8fcb9-sp7jt
   - onap-dmaap-message-router-mirrormaker-86d74c7c57-z94dp
   - onap-multicloud-multicloud-starlingx-c68c97c68-n6rp5
   - onap-policy-nexus-669b86f554-2s7tj
   - onap-policy-nexus-669b86f554-7bvlc
   - onap-policy-nexus-669b86f554-7jwtq
   - onap-policy-nexus-669b86f554-87ttv
   - onap-policy-nexus-669b86f554-b2psk
   - onap-policy-nexus-669b86f554-blgxf
   - onap-policy-nexus-669b86f554-g6ctn
   - onap-policy-nexus-669b86f554-hdwc5
   - onap-policy-nexus-669b86f554-j4ctl
   - onap-policy-nexus-669b86f554-j5dd4
   - onap-policy-nexus-669b86f554-kbx2l
   - onap-policy-nexus-669b86f554-pmpkm
   - onap-policy-nexus-669b86f554-sw8bd
   - onap-policy-nexus-669b86f554-vltzs
   - onap-policy-nexus-669b86f554-wg6dl
   - onap-policy-nexus-669b86f554-x49vj
   - onap-policy-nexus-669b86f554-xxktw
   - onap-policy-nexus-669b86f554-zf722
   - onap-policy-policy-api-6db49d977f-lnls8
   - onap-policy-policy-pap-85845569c5-8b86x
   - onap-policy-policy-xacml-pdp-7df865f5cc-h4hcl
   - onap-pomba-pomba-networkdiscoveryctxbuilder-7f7c8d8d6b-96kd4
   - onap-so-so-f57fb6c78-8qs7k
   - onap-so-so-f57fb6c78-8x4hh
   - onap-so-so-f57fb6c78-gj26t
   - onap-so-so-f57fb6c78-gnqbr
   - onap-so-so-f57fb6c78-jqkxf
   - onap-so-so-f57fb6c78-jw4nj
   - onap-so-so-f57fb6c78-ldws6
   - onap-so-so-f57fb6c78-ndttl
   - onap-so-so-f57fb6c78-ptgxf
   - onap-so-so-f57fb6c78-q8g2p
   - onap-so-so-f57fb6c78-rbsj2
   - onap-so-so-f57fb6c78-sstwn
   - onap-so-so-f57fb6c78-vtxg2]
 * Deployment Duration Estimation (s): 900
*********** Helm Results ***********
 * Nb Helm Charts: 28
 * Nb Failed Helm Charts: 3
 * List of Failed Helm Charts: [
   - onap-dmaap
   - onap-vfc
   - onap-vnfsdk]
******** Healthcheck Results *******
2019-04-08 08:38:14,060 - xtesting.core.robotframework - INFO - 
==============================================================================
Health-Check :: Testing ecomp components are available via calls.             
==============================================================================
Basic A&AI Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic AAF Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic AAF SMS Health Check                                            | PASS |
------------------------------------------------------------------------------
Basic APPC Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic CLI Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic CLAMP Health Check                                              | PASS |
------------------------------------------------------------------------------
Basic DCAE Health Check                                               | FAIL |
Test timeout 10 seconds exceeded.
------------------------------------------------------------------------------
Basic DMAAP Data Router Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic DMAAP Message Router Health Check                               | PASS |
------------------------------------------------------------------------------
Basic External API NBI Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Log Elasticsearch Health Check                                  | PASS |
------------------------------------------------------------------------------
Basic Log Kibana Health Check                                         | PASS |
------------------------------------------------------------------------------
Basic Log Logstash Health Check                                       | PASS |
------------------------------------------------------------------------------
Basic Microservice Bus Health Check                                   | PASS |
------------------------------------------------------------------------------
Basic Multicloud API Health Check                                     | PASS |
------------------------------------------------------------------------------
Basic Multicloud-ocata API Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Multicloud-pike API Health Check                                | PASS |
------------------------------------------------------------------------------
Basic Multicloud-starlingx API Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Multicloud-titanium_cloud API Health Check                      | PASS |
------------------------------------------------------------------------------
Basic Multicloud-vio API Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic OOF-Homing Health Check                                         | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f282f3e59d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-SNIRO Health Check                                          | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f282e20fe10>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic OOF-CMSO Health Check                                           | FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f282e220610>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Policy Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic Pomba AAI-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba SDC-context-builder Health Check                          | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-discovery-context-builder Health Check            | PASS |
------------------------------------------------------------------------------
Basic Pomba Service-Decomposition Health Check                        | PASS |
------------------------------------------------------------------------------
Basic Pomba Network-Discovery-MicroService Health Check               | PASS |
------------------------------------------------------------------------------
Basic Pomba Pomba-Kibana Health Check                                 | PASS |
------------------------------------------------------------------------------
Basic Pomba Elastic-Search Health Check                               | PASS |
------------------------------------------------------------------------------
Basic Pomba Sdnc-Context-Builder Health Check                         | PASS |
------------------------------------------------------------------------------
Basic Pomba Context-Aggregator Health Check                           | PASS |
------------------------------------------------------------------------------
Basic Portal Health Check                                             | PASS |
------------------------------------------------------------------------------
Basic SDC Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic SDNC Health Check                                               | PASS |
------------------------------------------------------------------------------
Basic SO Health Check                                                 | PASS |
------------------------------------------------------------------------------
Basic UseCaseUI API Health Check                                      | PASS |
------------------------------------------------------------------------------
Basic VFC catalog API Health Check                                    | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC emsdriver API Health Check                                  | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC gvnfmdriver API Health Check                                | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC huaweivnfmdriver API Health Check                           | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC jujuvnfmdriver API Health Check                             | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC multivimproxy API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiavnfmdriver API Health Check                            | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nokiav2driver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC nslcm API Health Check                                      | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC resmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnflcm API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfmgr API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC vnfres API Health Check                                     | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC workflow API Health Check                                   | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztesdncdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VFC ztevnfmdriver API Health Check                              | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic VID Health Check                                                | PASS |
------------------------------------------------------------------------------
Basic VNFSDK Health Check                                             | FAIL |
ConnectionError: HTTPConnectionPool(host='refrepo.onap', port=8702): Max retries exceeded with url: /onapapi/vnfsdk-marketplace/v1/PackageResource/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f282e0a0950>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
------------------------------------------------------------------------------
Basic Holmes Rule Management API Health Check                         | FAIL |
502 != 200
------------------------------------------------------------------------------
Basic Holmes Engine Management API Health Check                       | FAIL |
502 != 200
------------------------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
58 critical tests, 33 passed, 25 failed
58 tests total, 33 passed, 25 failed
==============================================================================
Output:  /var/lib/xtesting/results/full/output.xml
____________________________________

Patch-set: 1
Reviewer: Gerrit User 5170 <5170@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>