Update patch set 4
Patch Set 4: Code-Review-1

oom_redeploy
I believe the HC is good now:
ConnectionError: HTTPSConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4d6b80e610>: Failed to establish a new connection: [Errno 111] Connection refused')) 	

unfortunately, we had a lot of issue and OOF pod was not running

Patch-set: 4
Reviewer: Gerrit User 2319 <2319@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Code-Review=-1