Update patch set 1
Patch Set 1: Code-Review+1

Gating results

******** Kubernetes Results ********
 * Nb Pods: 195
 * Nb Failed Pods: 10
 * List of Failed Pods: [
   - onap-appc-appc-ansible-server-598558f644-psjz7
   - onap-contrib-netbox-app-695fd89fd-9kn8t
   - onap-dcaegen2-dcae-bootstrap-d8bbc99f7-q9hq2
   - onap-dcaegen2-dcae-cloudify-manager-d7b597474-kmbjw
   - onap-dcaegen2-dcae-deployment-handler-7745994f7f-cm9ns
   - onap-dcaegen2-dcae-healthcheck-84775fddd8-nwxtt
   - onap-dcaegen2-dcae-policy-handler-dc5f7cdb6-j28rs
   - onap-sdnc-blueprints-processor-6d8c669cb-v5dmg
   - onap-sdnc-controller-blueprints-64b8cf4c7c-td9cr
   - onap-vid-vid-6b65cc7cd7-j9rln]
 * Deployment Duration Estimation (s): 3600
*********** Helm Results ***********
 * Nb Helm Charts: 26
 * Nb Failed Helm Charts: 1
 * List of Failed Helm Charts: [
   - onap-vnfsdk]

***** healthcheck (medium) **********
Basic A&AI Health Check                                    PASS |
-----------------------------------------------------------------
Basic AAF Health Check                                     PASS |
-----------------------------------------------------------------
Basic AAF SMS Health Check                                 PASS |
-----------------------------------------------------------------
Basic APPC Health Check                                    FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic CLI Health Check                                     PASS |
-----------------------------------------------------------------
Basic CLAMP Health Check                                   PASS |
-----------------------------------------------------------------
Basic DCAE Health Check                                    FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic DMAAP Message Router Health Check                    PASS |
-----------------------------------------------------------------
Basic External API NBI Health Check                        PASS |
-----------------------------------------------------------------
Basic Log Elasticsearch Health Check                       PASS |
-----------------------------------------------------------------
Basic Log Kibana Health Check                              PASS |
-----------------------------------------------------------------
Basic Log Logstash Health Check                            PASS |
-----------------------------------------------------------------
Basic Microservice Bus Health Check                        PASS |
-----------------------------------------------------------------
Basic Multicloud API Health Check                          PASS |
-----------------------------------------------------------------
Basic Multicloud-ocata API Health Check                    PASS |
-----------------------------------------------------------------
Basic Multicloud-pike API Health Check                     PASS |
-----------------------------------------------------------------
Basic OOF-Homing Health Check                              FAIL |
ConnectionError: HTTPConnectionPool(host='oof-has-api.onap', port=8091): Max retries exceeded with url: /v1/plans/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca4aa43690>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic OOF-SNIRO Health Check                               FAIL |
ConnectionError: HTTPConnectionPool(host='oof-osdf.onap', port=8698): Max retries exceeded with url: /api/oof/v1/healthcheck (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca4a8f6950>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic OOF-CMSO Health Check                                FAIL |
ConnectionError: HTTPConnectionPool(host='oof-cmso.onap', port=8080): Max retries exceeded with url: /cmso/v1/health?checkInterfaces=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca4a90a0d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
-----------------------------------------------------------------
Basic Policy Health Check                                  PASS |
-----------------------------------------------------------------
Basic Portal Health Check                                  PASS |
-----------------------------------------------------------------
Basic SDC Health Check                                     PASS |
-----------------------------------------------------------------
Basic SDNC Health Check                                    PASS |
-----------------------------------------------------------------
Basic SO Health Check                                      PASS |
-----------------------------------------------------------------
Basic UseCaseUI API Health Check                           PASS |
-----------------------------------------------------------------
Basic VID Health Check                                     FAIL |
Test timeout 10 seconds exceeded.
-----------------------------------------------------------------
Basic Holmes Rule Management API Health Check              FAIL |
502 != 200
-----------------------------------------------------------------
Basic Holmes Engine Management API Health Check            FAIL |
502 != 200
-----------------------------------------------------------------
Health-Check :: Testing ecomp components are available via calls.     | FAIL |
28 critical tests, 20 passed, 8 failed
28 tests total, 20 passed, 8 failed

Patch-set: 1
Reviewer: Gerrit User 1215 <1215@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>